<?=  $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-table.min.css'); ?>

<?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-table.js.') 
        ->appendFile($this->basePath() . '/js/bootstrap-table/locale/bootstrap-table-en-Sbt-US.min.js.'); ?>

<style>

</style>

<script>
    $(function(){
        $("html, body").animate({ scrollTop: 180 });
    });
</script>


<div class="inner">
<div class="ui-widget-header ui-corner-top ui-helper-clearfix" style="padding: 0.2em 0.6em;">&nbsp;</div>

 
<table id="sedes"
           data-toggle="table"
           data-buttons-align="right"
           data-card-visible="true"
           data-page-list="[10, 15, 30, 50, 100, All]"
           data-page-size="10"
           data-pagination="true"
           data-pagination-detail-h-align="right"
           data-pagination-h-align="left"
           data-search="false"
           data-search-align="right"
           data-show-refresh="false"
           data-show-toggle="false"
           data-smart-display="true"
           data-trim-on-search="true"
           data-undefined-text=""
           data-show-export="true"
           class="bootstrap-table ticketList table-nowrap">
        <thead>
            <tr class="ui-state-active noselect">
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="nif" data-sortable="true" data-width="6%">NIF</th>
                <th data-field="entidades" data-sortable="true" data-width="40%">Entidades</th>
                <th data-field="lote3" data-sortable="true" data-width="12%" data-align="right">LOTE 3<?= ' ['. $this->periodo .']'; ?></th>
                <th data-field="otros" data-sortable="true" data-width="12%" data-align="right">OTROS<?= ' ['. $this->periodo .']'; ?></th>
                <th data-field="lote3contiguo" data-sortable="true" data-width="12%" data-align="right">LOTE 3<?= ' ['. $this->periodocontiguo .']'; ?></th>
                <th data-field="otroscontiguo" data-sortable="true" data-width="12%" data-align="right">OTROS<?= ' ['. $this->periodocontiguo .']'; ?></th>
                <th data-field="porcentaje" data-sortable="true" data-width="6%" data-align="right">%</th>
                <!--<th data-field="operation" data-width="10%" data-align="center" data-valign="middle">ACCIONES</th>-->
            </tr>
        </thead>
        <tbody>
            <?php if(is_array($this->records)) : ?>
            <?php foreach ($this->records as $record) : ?>
                <tr class="<?php echo $this->cycle(array('oddRowColor', 'evenRowColor'))->next(); ?> bootstrap-selectableRow greyText">
                    <td></td>
                    <td class="noWrap"><?= $record['id_titular_serv']; ?></td>
                    <td class="noWrap"><?= ucwords(strtolower($record['desc_titular_serv_lote3'])); ?></td>
                    <td class="noWrap"><?= number_format($record['total_lote3'], 2, ",", "."); ?></td>
                    <td class="noWrap"><?= number_format($record['total_resto_servicios'], 2, ",", "."); ?></td>
                    <td class="noWrap"><?= number_format($record['total_lote3_continuo'], 2, ",", "."); ?></td>
                    <td class="noWrap"><?= number_format($record['total_resto_servicios_continuo'], 2, ",", "."); ?></td>
                    <td class="noWrap"><?= number_format($record['margen'], 2, ",", "."); ?></td>
                    <!--<td class="noWrap"></td>-->
                </tr>
            <?php endforeach; ?>
            <?php endif; ?>    
        </tbody>
    </table>
    <div class="clearfix">&nbsp;</div>
    <div id="result"></div>
</div>

<script>

//    var $table = $('#sedes');
//
//    $(function () {
//            $table.bootstrapTable('hideColumn', 'referenceCode');
//    });
    
</script>
 