<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }

    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }

    .form-group
    {
        margin-bottom: 2px;
    }

    .form-control
    {
        /*height: 26px;*/
        font-size: 12px;

    }

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
</style>

<script type="text/javascript">
    
    $(document).ready(function (e){

        $("#periodo").keypress(function(e){
            if(e.which === 13){
                e.preventDefault();
                filter();
                return false;
            }
        });
        
        $("#periodo").change(function(){

            var periodoSelected = $("#periodo option:selected").val();
            if(periodoSelected !== '0') {
                $("#download-summation").removeClass("disabled").addClass("active");
                $("#show-summation").removeClass("disabled").addClass("active");
            } else {
                $("#download-summation").removeClass("active").addClass("disabled");
                $("#show-summation").removeClass("active").addClass("disabled");
            }

        });
        
        
        
        
    
    });
    
    function filter() {
        
        var url = '<?= $this->url('invoice-period-getting'); ?>';
        $.ajax({
            type: "GET",
            url: url,
            data: $('#filterForm').serialize(),
            cache: false,
            beforeSend: function() {
                $("#fill-filter").html("<img style='display: block; margin:auto;' src='<?= $this->basePath() . '/img/loading.gif' ;?>' />");
            },
            success: function (json) {
                $("#fill-filter").html(json);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill-filter").html(html);
            }
        });

    }

</script>

<fieldset class="col-md-12">
    <legend>Generación del próximo período de Facturación</legend>

    <div class="panel panel-default">
        <div class="panel-body">

        <div>
            <form id="filterForm" method="get" onsubmit="return false;">
            <!--<form id="filterForm" action="<?= $this->url('invoice-period-getting'); ?>" method="post">-->
            <div class="col-lg-6">    
                
                <div class="form-group input-group">
                    <!--<input type="text" class="form-control" id="search" name="search" placeholder="Buscar..."/>-->
                    
<!--                <div class="form-group">-->
                    
                    <!--<label class="control-label" for="periodo"> Período </label>-->
                    
                    <select class="form-control" id="periodo" name="periodo" required>
                        <option disabled selected>Seleccione el período a crear</option>
                        <option value='202103'>202103</option>
                        <option value='202104'>202104</option>
                        <option value='202105'>202105</option>
                        <option value='202106'>202106</option>
                    </select>
                <!--</div>-->
                    <span class="input-group-btn">
                        &nbsp;
                    </span>
                    <span class="input-group-btn">
                        <button id="download-summation" title="Generación del próximo período" onclick="filter();" class="btn btn-danger disabled">
                            <i class="icon icon-calendar"></i>
                        </button>
                    </span>
                </div>
            </div>
            
            </form>
        </div>
        </div>
    </div>
    
</fieldset>

<div id="fill-filter">
</div>