<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }

    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }

    .form-group
    {
        margin-bottom: 2px;
    }

    .form-control
    {
        /*height: 26px;*/
        font-size: 12px;

    }

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
</style>

<script type="text/javascript">
    
    $(document).ready(function (e){

        $("#periodo").keypress(function(e){
            if(e.which === 13){
                e.preventDefault();
                filter();
                return false;
            }
        });    
    
    });
    
    function comparison() {
        
        var url = '<?= $this->url('invoice-comparison-result'); ?>';
        $.ajax({
            type: "GET",
            url: url,
            data: $('#filterForm').serialize(),
            cache: false,
            beforeSend: function() {
                $("#fill-comparison").html("<img style='display: block; margin:auto;' src='<?= $this->basePath() . '/img/loading.gif' ;?>' />");
            },
            success: function (json) {
                $("#fill-comparison").html(json);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill-comparison").html(html);
            }
        });

    }

</script>

<fieldset class="col-md-12">    	
    <legend>Comparador de facturas</legend>

    <div class="panel panel-default">
        <div class="panel-body">

        <div>
            <!--<form id="filterForm" method="get" onsubmit="return false;">-->
            <form id="filterForm" method="get">
            <div class="col-lg-6">    
                
                <div class="form-group input-group">
                    <!--<input type="text" class="form-control" id="search" name="search" placeholder="Buscar..."/>-->
                    
<!--                <div class="form-group">-->
                    
                    <!--<label class="control-label" for="periodo"> Período </label>-->
                    <div class="form-group">
                        <select class="form-control" id="percent" name="percent" required>
                            <option value='0'>Todas las variaciones respecto al mes anterior.</option>
                            <option  value='1'>Incremento  + </option>
                            <option value='-1'>Decremento - </option>
                        </select>
                    </div>
                    <select class="form-control" id="periodo" name="periodo" required>
                        <option value='0'>Elegir un período</option>
                        <option value='202012'>202012</option>
                        <option value='202011'>202011</option>
                        <option value='202010'>202010</option>
                        <option value='202009'>202009</option>
                        <option value='202008'>202008</option>
                        <option value='202007'>202007</option>
                        <option value='202006'>202006</option>
                        <option value='202005'>202005</option>
                        <option value='202004'>202004</option>
                        <option value='202003'>202003</option>
                        <option value='202002'>202002</option>
                        <option value='202001'>202001</option>
                        <option value='201912'>201912</option>
                        <option value='201911'>201911</option>
                        <option value='201910'>201910</option>
                        <option value='201909'>201909</option>
                        <option value='201908'>201908</option>
                        <option value='201907'>201907</option>
                        <option value='201906'>201906</option>
                        <option value='201905'>201905</option>
                        <option value='201904'>201904</option>
                        <option value='201903'>201903</option>
                        <option value='201902'>201902</option>
                        <option value='201901'>201901</option>
                        <option value='201812'>201812</option>
                        <option value='201811'>201811</option>
                        <option value='201810'>201810</option>
                        <option value='201809'>201809</option>
                        <option value='201808'>201808</option>
                        <option value='201807'>201807</option>
                        <option value='201806'>201806</option>
                        <option value='201805'>201805</option>
                        <option value='201804'>201804</option>
                        <option value='201803'>201803</option>
                        <option value='201802'>201802</option>
                        <option value='201801'>201801</option>
                        <option value='201712'>201712</option>
                        <option value='201711'>201711</option>
                        <option value='201710'>201710</option>
                        <option value='201709'>201709</option>
                        <option value='201708'>201708</option>
                        <option value='201707'>201707</option>
                        <option value='201706'>201706</option>
                        <option value='201705'>201705</option>
                        <option value='201704'>201704</option>
                        <option value='201703'>201703</option>
                        <option value='201702'>201702</option>
                        <option value='201701'>201701</option>
                        <option value='201612'>201612</option>
                        <option value='201611'>201611</option>
                        <option value='201610'>201610</option>
                        <option value='201609'>201609</option>
                        <option value='201608'>201608</option>
                        <option value='201607'>201607</option>
                        <option value='201606'>201606</option>
                        <option value='201605'>201605</option>
                        <option value='201604'>201604</option>
                        <option value='201603'>201603</option>
                        <option value='201602'>201602</option>
                        <option value='201601'>201601</option>
                        <option value='201512'>201512</option>
                        <option value='201511'>201511</option>
                        <option value='201510'>201510</option>
                        <option value='201509'>201509</option>
                        <option value='201508'>201508</option>
                        <option value='201507'>201507</option>
                        <option value='201506'>201506</option>
                        <option value='201505'>201505</option>
                        <option value='201504'>201504</option>
                        <option value='201503'>201503</option>
                    </select>
                <!--</div>-->
                    <span class="input-group-btn">
                        &nbsp;
                    </span>

                    <span class="input-group-btn">
                        <button class="btn btn-default" style="margin-top: 37px;" type="button" onclick="comparison();">
                            <i class="icon-search"></i>
                        </button>
                    </span>
                
                    <span class="input-group-btn">
                        &nbsp;
                    </span>
                    
                <!-- NEXT TASK TO PRINT
                    <span class="input-group-btn">
                        <button id="download-summation" title="Descarga" type="submit" class="btn btn-danger disabled" style="float: left;">
                            <i class="icon-download-alt"></i>
                        </button>
                    </span>
                !-->
                </div>
                
            </div>
            
            </form>
        </div>
        </div>
    </div>
    
</fieldset>

<div id="fill-comparison">
</div>
<!-- 
Testing Tx and Rx
-->