<?php echo $this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js');

?>
<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }
    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }
    .form-group
    {
        margin-bottom: 1px;
    }

/*    .form-control
    {
        height: 26px;
        font-size: 9px;

    }*/

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
</style>

<script type="text/javascript" style="display:none">
    
    function invoiceDelete() {

        $('#invoiceDelete').modal('hide');
        var url = '<?= $this->url('invoice-delete'); ?>';
        var id = '<?= $this->information['factura']['0']['id']; ?>';
        var data = {id: id};
    
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            cache: false,
            success: function (html) {
    //                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
    //                
                 $('.invoice-submit').addClass('disabled');
                $('.invoice-delete').addClass('disabled');

            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#result").html(html);
            }
        });
    }
    
</script>    

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('update-invoice'));
    $form->setAttribute('id', 'invoice');
    $form->setAttribute('role', 'form');
    $form->setAttribute('data-toggle', 'validator');
    $form->setAttribute('accept-charset', 'utf-8');
    #$form->setAttribute('novalidate', 'novalidate');
    $form->prepare();
?>


<?= $this->form()->openTag($form); ?>
<fieldset class="col-md-12">
    <legend> Edición de factura </legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-4">
                <div class="form-group">
                    <label for="periodo">Período</label>
                    <?php
                        $form->get('periodo')->setValue($information['factura']['0']['id_fecha_fact']);
                    ?>
                    <?= $this->formInput($form->get('periodo')); ?>                                
                </div>
                <div class="form-group">
                    <label for="cif">LCIF</label>
                    <?php
                        $form->get('idLcifCliente')->setValue($information['factura']['0']['id_lcif_cliente']);
                    ?>
                    <?= $this->formInput($form->get('idLcifCliente')); ?>
                </div>
                <div class="form-group">
                    <label for="cif">CIF</label>
                    <?php
                        $form->get('idCifCliente')->setValue($information['factura']['0']['id_cif_cliente']);
                    ?>
                    <?= $this->formInput($form->get('idCifCliente')); ?>
                </div>
                <div class="form-group">
                    <label for="entidad">Entidad</label>
                    <?php
                        $form->get('descNomEnt')->setValue($information['factura']['0']['desc_nom_ent']);
                    ?>
                    <?= $this->formInput($form->get('descNomEnt')); ?>
                </div>
                <div class="form-group">
                    <label for="servicio">Servicio</label>
                    <?php
                        $form->get('descTipoServicio')->setValue($information['factura']['0']['desc_tipo_servicio']);
                    ?>
                    <?= $this->formInput($form->get('descTipoServicio')); ?>
                </div>
                <div class="form-group">
                    <label for="multiconexion">ID Multiconexión</label>
                    <?php
                        $form->get('idMulticonexion')->setValue($information['factura']['0']['id_multiconexion']);
                    ?>
                    <?= $this->formInput($form->get('idMulticonexion')); ?>
                </div>
                <div class="form-group">
                    <label for="telefono">Número comercial</label>
                    <?php
                        $form->get('idNumeroComercial')->setValue($information['factura']['0']['id_numero_comercial']);
                    ?>
                    <?= $this->formInput($form->get('idNumeroComercial')); ?>
                </div>
                <div class="form-group">
                    <label for="codigo">Código concepto</label>
                    <?php
                        $form->get('idCodigoConcepto')->setValue($information['factura']['0']['id_codigo_concepto']);
                    ?>
                    <?= $this->formInput($form->get('idCodigoConcepto')); ?>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <label for="id_concepto_facturable">ID concepto facturable</label>
                    <?php
                        $form->get('idConceptoFacturable')->setValue($information['factura']['0']['id_concepto_facturable']);
                    ?>
                    <?= $this->formInput($form->get('idConceptoFacturable')); ?>
                </div>
                <div class="form-group">
                    <label for="concepto_facturable">Concepto facturable</label>
                    <?php
                        $form->get('descConceptoFacturable')->setValue($information['factura']['0']['desc_concepto_facturable']);
                    ?>
                    <?= $this->formInput($form->get('descConceptoFacturable')); ?>
                </div>
                <div class="form-group">
                    <label for="unidades">Unidades</label>
                    <?php
                        $form->get('unidades')->setValue($information['factura']['0']['f_unidades']);
                    ?>
                    <?= $this->formInput($form->get('unidades')); ?>
                </div>
                <div class="form-group">
                    <label for="inicio">Fecha inicio</label>
                    <?php
                        $form->get('inicioPeriodoFact')->setValue($information['factura']['0']['f_inicio_periodo_fact']);
                    ?>
                    <?= $this->formInput($form->get('inicioPeriodoFact')); ?>
                </div>
                <div class="form-group">
                    <label for="fin">Fecha fin</label>
                    <?php
                        $form->get('finPeriodoFact')->setValue($information['factura']['0']['f_fin_periodo_fact']);
                    ?>
                    <?= $this->formInput($form->get('finPeriodoFact')); ?>
                </div>
                <div class="form-group">
                    <label for="importe_total_equipo">Importe total equipo</label>
                    <?php
                        $form->get('importeTotalEquipo')->setValue($information['factura']['0']['f_importe_total_equipo']);
                    ?>
                    <?= $this->formInput($form->get('importeTotalEquipo')); ?>
                </div>

                <div class="form-group">
                    <label for="precio_mensual_lote3">Precio mensual lote3</label>
                    <?php
                        $form->get('precioMensualLote3')->setValue($information['factura']['0']['f_precio_mensual_lote3']);
                    ?>
                    <?= $this->formInput($form->get('precioMensualLote3')); ?>
                </div>

                <div class="form-group">
                    <label for="total_sin_iva">Total sin IVA</label>
                    <?php
                        $form->get('totalSinIva')->setValue($information['factura']['0']['f_total_sin_iva']);
                    ?>
                    <?= $this->formInput($form->get('totalSinIva')); ?>
                </div>

            </div>
            
            <div class="col-lg-4">
                
                <div class="form-group">
                    <label for="id_cod_cli">ID código cliente</label>
                    <?php
                        $form->get('idCodCli')->setValue($information['factura']['0']['id_cod_cli']);
                    ?>
                    <?= $this->formInput($form->get('idCodCli')); ?>
                </div>
                <div class="form-group">
                    <label for="servicio_lote3">Servicio lote 3</label>
                    <?php
                        $form->get('descServicioLote3')->setValue($information['factura']['0']['desc_servicio_lote3']);
                    ?>
                    <?= $this->formInput($form->get('descServicioLote3')); ?>
                    
                </div>

                <div class="form-group">
                    <label for="descripcion_lote">Descripción lote 3</label>
                    <?php
                        $form->get('descLote')->setValue($information['factura']['0']['desc_lote']);
                    ?>
                    <?= $this->formInput($form->get('descLote')); ?>
                    
                </div>
                
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                
                <input type="hidden" id="invoiceId" name="invoiceId" value="<?= $this->information['factura']['0']['id'] ?>">
                
                <div style="float:right;">
                    <button class="btn btn-primary invoice-submit" title="Guardar cambios" type="submit"><span class="glyphicon glyphicon-edit"></span></button>
                    <button class="btn btn-primary invoice-delete" title="Eliminar la factura" type="button" data-toggle="modal" data-target="#invoiceDelete"><span class="glyphicon glyphicon-trash"></span></button>                
                    <a class="btn btn-primary btn-primary retornar-bandeja" href="<?= $this->url('list-invoices'); ?>" role="button" title="Retornar a la bandeja de facturas">
                        <i class="glyphicon glyphicon-arrow-left"></i>
                    </a>
                </div>

            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
</fieldset>
<?= $this->form()->closeTag($form); ?>

<div class="modal fade" id="invoiceDelete" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de eliminar la factura?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="invoiceDelete();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>
