<?php echo $this->headLink()
                ->appendStylesheet('http://code.jquery.com/ui/1.10.3/themes/flick/jquery-ui.min.css')
                ->appendStylesheet($this->basePath('assets/datepicker/css/jquery-ui.theme.min.css'))
                ->appendStylesheet($this->basePath('assets/datepicker/css/custom.css'));?>



<?php echo $this->headScript()
        ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js')
        ->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js'); 
?>

<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }
    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }
    .form-group
    {
        margin-bottom: 1px;
    }

/*    .form-control
    {
        height: 26px;
        font-size: 9px;

    }*/

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
</style>                

<?php

    use Zend\Session\Container;
    $session = new Container('User');
    $userRole = $session->offsetGet('userRole');
    $firstName = $session->offsetGet('firstName');
    $lastName = $session->offsetGet('lastName');


    $form = $this->form;
    $form->setAttribute('action', $this->url('planta-update-confirm'));
    $form->setAttribute('id', 'planta');
    $form->setAttribute('role', 'form');
    $form->setAttribute('data-toggle', 'validator');
    $form->setAttribute('accept-charset', 'utf-8');
    #$form->setAttribute('novalidate', 'novalidate');
    $form->prepare();
?>
<?= $this->form()->openTag($form); ?>

<fieldset class="col-md-12">
    <legend> Edición de Planta </legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="cif">CIF</label>
                    <?php
                        $form->get('cif')->setValue($information['planta']['0']['cif_id']);
                        $form->get('cif')->setAttribute('disabled','true');
                    ?>
                    <?=   $this->formSelect($form->get('cif')); ?>                                
                </div>
            </div>

            <div class="col-lg-3"></div>
            <div class="col-lg-3"></div>
            <div class="col-lg-3">
                <label for="fecha">Fecha Alta</label>
                <div class="input-group date">
                    <input id="creacion" name="creacion" type="text" class="form-control" value="<?= $information['planta']['0']['creacion']; ?>" readonly="true"/>
                   <label for="creacion" class="input-group-addon generic_btn"><i class="glyphicon glyphicon-calendar" aria-hidden="true"></i></label>
                </div>
            </div>
            
            <div class="clearfix"></div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="sede">Sede</label>
                    <?php
                        $form->get('sede')->setValue($information['planta']['0']['sede']);
                        $form->get('sede')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('sede')); ?>
                </div>                
                
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="direccion">Dirección</label>
                    <?php
                        $form->get('direccion')->setValue($information['planta']['0']['direccion']);
                        $form->get('direccion')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('direccion')); ?>
                </div>                
                
            </div>
            
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="poblacion">Población</label>
                    <?php
                        $form->get('poblacion')->setValue($information['planta']['0']['poblacion_id']);
                        $form->get('poblacion')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formSelect($form->get('poblacion')); ?> 
                </div>
            </div>
            <div class="col-lg-3"></div>
            
            <div class="clearfix"></div>
            
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="cliente">Cliente</label>
                    <?php
                        $form->get('cliente')->setValue($information['planta']['0']['cliente_id']);
                        $form->get('cliente')->setAttribute('disabled','true');
                    ?>
                    <?=   $this->formSelect($form->get('cliente')); ?>          
                </div>
            </div>    
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="xarxa">Xarxa</label>
                    <?php
                        $form->get('xarxa')->setValue($information['planta']['0']['xarxa_id']);
                        $form->get('xarxa')->setAttribute('disabled','true');
                    ?>
                    <?=   $this->formSelect($form->get('xarxa')); ?>          
                </div>
            </div>
            <div class="col-lg-3"></div>
            <div class="col-lg-3"></div>
            
            <div class="clearfix"></div>
            
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="servicio">Servicio</label>
                    <?php
                        $form->get('servicio')->setValue($information['planta']['0']['servicio_id']);
                        $form->get('servicio')->setAttribute('disabled','true');
                    ?>
                    <?=   $this->formSelect($form->get('servicio')); ?>          
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="tipo">Tipo</label>
                    <?php
                        $form->get('tipo')->setValue($information['planta']['0']['tipo_id']);
                        $form->get('tipo')->setAttribute('disabled','true');
                    ?>
                    <?=   $this->formSelect($form->get('tipo')); ?>          
                </div>
            </div>
            <div class="col-lg-3"></div>
            <div class="col-lg-3"></div>
            
            <div class="clearfix"></div>


            <div class="col-lg-3">
                <div class="form-group">
                    <label for="caudal">Caudal</label>
                    <?php
                        $form->get('caudal')->setValue($information['planta']['0']['caudal']);
                        //$form->get('caudal')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('caudal')); ?>
                </div>                
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="velocidad">Velocidad</label>
                    <?php
                        $form->get('velocidad')->setValue($information['planta']['0']['velocidad']);
                        //$form->get('velocidad')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('velocidad')); ?>
                </div>                
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="administrativo">Administrativo</label>
                    <?php
                        $form->get('administrativo')->setValue($information['planta']['0']['administrativo']);
                        //$form->get('administrativo')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('administrativo')); ?>
                </div>                
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="backup">Administrativo Backup</label>
                    <?php
                        $form->get('backup')->setValue($information['planta']['0']['backup']);
                        //$form->get('backup')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('backup')); ?>
                </div>                
            </div>

            
            
            <div class="clearfix"></div>
            

            <div class="col-lg-3">
                <div class="form-group">
                    <label for="factura">Factura</label>
                    <?php
                        $form->get('factura')->setValue($information['planta']['0']['factura']);
                        //$form->get('backup')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('factura')); ?>
                </div>                
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="modelo">Modelo</label>
                    <?php
                        $form->get('modelo')->setValue($information['planta']['0']['modelo']);
                        //$form->get('backup')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formInput($form->get('modelo')); ?>
                </div>                
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="propiedad">propiedad</label>
                    <?php
                        $form->get('propiedad')->setValue($information['planta']['0']['propiedad']);
                    ?>
                    <?=   $this->formSelect($form->get('propiedad')); ?>          
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="ipfija">IP Fija</label>
                    <?php
                        $form->get('ipfija')->setValue($information['planta']['0']['ip_fija']);
                    ?>
                    <?=   $this->formSelect($form->get('ipfija')); ?>          
                </div>
            </div>
            
            <div class="clearfix"></div>
            
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="direccionip">Dirección IP</label>
                    <?php
                        $form->get('direccionip')->setValue($information['planta']['0']['direccion_ip']);
                    ?>
                    <?= $this->formInput($form->get('direccionip')); ?>
                </div>                
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="iplan">IP Lan</label>
                    <?php
                        $form->get('iplan')->setValue($information['planta']['0']['ip_lan']);
                    ?>
                    <?= $this->formInput($form->get('iplan')); ?>
                </div>                
            </div>
            <div class="col-lg-3"></div>
            <div class="col-lg-3"></div>
            
            <div class="clearfix"></div>
            
            <div class="col-lg-6">
                <div class="form-group">
                    <label for="observaciones">Observaciones</label>
                     <?php 
                        $form->get('observaciones')->setValue($this->information['planta']['0']['observaciones']);
                        #$form->get('observacion')->setAttribute('rows', 1);
                        //$form->get('observaciones')->setAttribute('disabled','true');
                    ?>
                    <?= $this->formTextarea($form->get('observaciones')); ?>
                </div>
            </div>
            
           
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="estado">Estado</label>
                    <?php
                        $form->get('estado')->setValue($information['planta']['0']['estado_id']);
                    ?>
                    <?=   $this->formSelect($form->get('estado')); ?>          
                </div>
                <div class="form-group" style="padding-top: 68px;">
                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" id="activo" name="activo" class="form-check-input" checked="true" value="1">
                            Activo
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <?php if('Administrador' == $userRole || 'CGP' == $userRole) : ?>
                <div class="form-group" style="float:right; padding-top: 116px;">
                    <label for="ip">&nbsp;</label>
                    <button class="btn btn-primary" title="Actualizar" type="submit"><span class="glyphicon glyphicon-saved"></span></button>
                </div>
               <?php endif; ?>
            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
</fieldset>
 <input type="hidden" id="plantaId" name="plantaId" value="<?= $this->information['planta']['0']['id'] ?>">
<?= $this->form()->closeTag($form); ?>
