<?=  $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-table.min.css'); ?>

<?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-table.js.') 
        ->appendFile($this->basePath() . '/js/bootstrap-table/locale/bootstrap-table-en-Sbt-US.min.js.'); ?>

<style>

</style>

<script>
    $(function(){
        $("html, body").animate({ scrollTop: 300 });
    });
</script>


<div class="inner">
<div class="ui-widget-header ui-corner-top ui-helper-clearfix" style="padding: 0.2em 0.6em;">&nbsp;</div>

<div id="toolbar">
    <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#exportModal">
        <i class="glyphicon glyphicon-hand-down"></i>&nbsp;Baja
    </button>
    <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#bulkCloseModal">
        <i class="glyphicon glyphicon-remove"></i>&nbsp;Eliminar
    </button>
    <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#bulkCancelModal">
        <i class="glyphicon glyphicon-export"></i>&nbsp;Exportar
    </button>
<!--    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bulkCloseModal">
        <i class="glyphicon glyphicon-th-list"></i>&nbsp;Reporte BI
    </button>-->
</div>
 
<table id="sedes"
           data-toggle="table"
           data-buttons-align="right"
           data-card-visible="true"
           data-page-list="[10, 15, 30, 50, 100, All]"
           data-page-size="10"
           <?php if($this->glanFilter||$this->apFilter) : ?>
           data-pagination="false"
           <?php else : ?>
           data-pagination="true"
           <?php endif ?>
           data-pagination-detail-h-align="right"
           data-pagination-h-align="left"
           data-search="false"
           data-search-align="right"
           data-show-refresh="false"
           data-show-toggle="false"
           data-smart-display="true"
           data-toolbar="#toolbar"
           data-trim-on-search="true"
           data-undefined-text=""
           data-show-export="true"
           class="bootstrap-table ticketList table-nowrap">
        <thead>
            <tr class="ui-state-active noselect">
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="nombre" data-sortable="true" data-width="40%">SEDE</th>
                <th data-field="direccion" data-sortable="true" data-width="60%">DIRECCIÓN</th>
                <?php if($this->glanFilter) : ?>
                <th data-field="contacto" data-sortable="true" data-width="25%">NEMÓNICO GLAN</th>
                <?php elseif ($this->apFilter) : ?>
                <th data-field="contacto" data-sortable="true" data-width="25%">ID AP</th>
                <?php endif ; ?>
                <!--<th data-field="fecha" data-sortable="true" data-width="10%">FECHA ALTA</th>-->
                <th data-field="operation" data-width="10%" data-align="center" data-valign="middle">ACCIONES</th>
                <!--<th data-field="conceptId" data-sortable="true" data-width="50%">POBLACIÓN</th>-->
            </tr>
        </thead>
        <tbody>
            <?php if(is_array($this->sedes)) : ?>
            <?php foreach ($this->sedes as $sede) : ?>
                <tr class="<?php echo $this->cycle(array('oddRowColor', 'evenRowColor'))->next(); ?> bootstrap-selectableRow greyText">
                    <td></td>
                    <td class="noWrap"><?= ucwords(strtolower($sede->nombre)); ?></td>
                    <td class="noWrap"><?= ucwords(strtolower($sede->direccion)); ?></td>
                    <?php if($this->glanFilter) : ?>
                        <td class="noWrap"><?= strtolower($sede->nemonico); ?></td>
                    <?php elseif($this->apFilter) : ?>
                        <td class="noWrap"><?= strtolower($sede->idap); ?></td>
                    <?php endif ; ?>
                    <!--<td class="noWrap"><?= date("d-m-Y", strtotime($sede->fechaAlta)); ?></td>--> 
                    <td class="noWrap">
                        <!--  href="/tabs/<?= $sede->id; ?>" -->
                        <?php if($this->glanFilter && strlen($sede->nemonico)>1) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id . '/3/4/' . $sede->nemonico . '/' . $this->glanQuery;?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->apFilter && strlen($sede->idap)>1) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id . '/4/52/' . $sede->idap . '/' . $this->apQuery;?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && $sede->isAdministrativo) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/0/1/' . $sede->administrativo . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && $sede->isTelefono) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/0/2/' . $sede->telefono . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && $sede->isIbenet) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/0/3/' . $sede->ibenet . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && $sede->isNemonico) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/1/4/' . $sede->nemonico . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && $sede->isIpGestionEquipo) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/1/5/' . $sede->ipGestion . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && ($sede->isNumeroSerieEquipo||$sede->isLocertEquipo||$sede->isObservacionEquipo)) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/1/4/' . $sede->nemonico . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && $sede->isNameSede) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/0/7/' . $sede->nombre . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter && $sede->isAddressSede) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id .'/0/8/' . $sede->direccion . '/' . $this->wanQuery; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php elseif($this->wanFilter) : ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit" style="color: red;"></i>
                            </a>
                        <?php else: ?>
                            <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id; ?>" title="Consultar">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        <?php endif ?>
                    </td>
                    <!--<td class="noWrap"></td>-->
                </tr>
            <?php endforeach; ?>
            <?php endif; ?>    
        </tbody>
    </table>
    <div class="clearfix">&nbsp;</div>
    <div id="result"></div>
</div>

<script>

//    var $table = $('#sedes');
//
//    $(function () {
//            $table.bootstrapTable('hideColumn', 'referenceCode');
//    });
    
</script>
 