<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }

    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }

    .form-group
    {
        margin-bottom: 2px;
    }

    .form-control
    {
        /*height: 26px;*/
        font-size: 12px;

    }

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
    
</style>                

<fieldset class="col-md-12">
    <legend>Filtros de Búsqueda</legend>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-lg-2">
                <fieldset class="form-group  custom-fieldset"> 
                    <legend class="custom-legend" title="Sedes">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Sedes
                    </legend>
                    <div class="col-lg-12">
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Provincia</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>                        
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Población</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>
                    </div>
                </fieldset>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div>
                    <a class="btn btn-primary btn-lg" href="#" role="button" onclick="Filtrar();" title="Filtrar">
                        <i class="glyphicon glyphicon-filter"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-3">

                <fieldset class="form-group  custom-fieldset">
                    <legend class="custom-legend" title="Circuitos">
                        <span class="glyphicon glyphicon-random" aria-hidden="true"></span> Circuitos
                    </legend>
                    <div class="col-lg-6">
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Cliente</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>                        
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Tecnología</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Velocidad</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>                        
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Criticidad</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>

                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Estados</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>
                        
                        
                        
                    </div>
                    
                    <div class="col-lg-6">

                    <fieldset class="form-group  custom-fieldset">
                        <legend class="custom-legend" title="Circuitos">Gestionado</legend>
                        <div class="form-group">
                            <div class="radio custom-radio">
                                <label>
                                    <input type="radio" name="optionsGestionado" id="optionsoptionsGestionado1" value="option1" checked="checked" /> Todos
                                </label>
                            </div>
                            <div class="radio custom-radio">
                                <label>
                                    <input type="radio" name="optionsGestionado" id="optionsoptionsGestionado2" value="option2" /> Gestionado
                                </label>
                            </div>
                            <div class="radio custom-radio">
                                <label>
                                    <input type="radio" name="optionsGestionado" id="optionsoptionsGestionado3" value="option3" /> No gestionado
                                </label>
                            </div>
                        </div>
                    </fieldset>        

                    <fieldset class="form-group  custom-fieldset">
                        <legend class="custom-legend" title="Backup">Backup</legend>
                        <div class="form-group">
                            <div class="radio custom-radio">
                                <label>
                                    <input type="radio" name="optionsBackup" id="optionsBackup1" value="option1" checked="checked" /> Todos
                                </label>
                            </div>
                            <div class="radio custom-radio">
                                <label>
                                    <input type="radio" name="optionsBackup" id="optionsBackup2" value="option2" /> Con backup
                                </label>
                            </div>
                            <div class="radio custom-radio">
                                <label>
                                    <input type="radio" name="optionsBackup" id="optionsBackup3" value="option3" /> Sin backup
                                </label>
                            </div>
                        </div>
                    </fieldset>        





                        
                        
                        
                    </div>
                    
                    
                    
                    
                    
                    
                    
                    
                    
                </fieldset>    

            </div>    

            <div class="col-lg-3">    
                <fieldset class="form-group  custom-fieldset">
                    <legend class="custom-legend" title="Equipos gestionados">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Equipos Gestionados
                    </legend>
                    
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Servicio</label>
                            <select class="form-control input-sm" id="parameters" name="parameters">
                                <option>Todos</option>
                                <option>Administrativo</option>
                                <option>Teléfono</option>
                                <option>Ibenet</option>
                                <option>Nemónico</option>
                                <option>IP de gestión</option>
                                <option>VPN</option>
                                <option>Dirección</option>
                                <option>Nombre de la sede</option>
                            </select>                    
                        </div>

                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Fabricante</label>
                            <select class="form-control input-sm" id="parameters" name="parameters">
                                <option>Todos</option>
                                <option>Administrativo</option>
                                <option>Teléfono</option>
                                <option>Ibenet</option>
                                <option>Nemónico</option>
                                <option>IP de gestión</option>
                                <option>VPN</option>
                                <option>Dirección</option>
                                <option>Nombre de la sede</option>
                            </select>                    
                        </div>

                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Modelo</label>
                            <select class="form-control input-sm" id="parameters" name="parameters">
                                <option>Todos</option>
                                <option>Administrativo</option>
                                <option>Teléfono</option>
                                <option>Ibenet</option>
                                <option>Nemónico</option>
                                <option>IP de gestión</option>
                                <option>VPN</option>
                                <option>Dirección</option>
                                <option>Nombre de la sede</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Estados</label>
                            <select class="form-control input-sm" id="parameters" name="parameters">
                                <option>Todos</option>
                                <option>Administrativo</option>
                                <option>Teléfono</option>
                                <option>Ibenet</option>
                                <option>Nemónico</option>
                                <option>IP de gestión</option>
                                <option>VPN</option>
                                <option>Dirección</option>
                                <option>Nombre de la sede</option>
                            </select>                    
                        </div>    
                        
                    </div>
                        
                    <div class="col-lg-6">

                        <fieldset class="form-group  custom-fieldset">
                            <legend class="custom-legend" title="Backup de Equipos">Backup</legend>
                            <div class="form-group">
                                <div class="radio custom-radio">
                                    <label>
                                        <input type="radio" name="optionsBackupEquipo" id="optionsBackupEquipo1" value="option1" checked="checked" /> Todos
                                    </label>
                                </div>
                                <div class="radio custom-radio">
                                    <label>
                                        <input type="radio" name="optionsBackupEquipo" id="optionsBackupEquipo2" value="option2" /> Con backup
                                    </label>
                                </div>
                                <div class="radio custom-radio">
                                    <label>
                                        <input type="radio" name="optionsBackupEquipo" id="optionsBackupEquipo3" value="option3" /> Sin backup
                                    </label>
                                </div>
                            </div>
                        </fieldset>

                    </div>
                    
                </fieldset>    
            </div>    


            <div class="col-lg-3">    
                <fieldset class="form-group  custom-fieldset">
                    <legend class="custom-legend" title="Equipos No Gestionados">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Equipos No gestionados
                    </legend>
                    <div class="col-lg-6">

                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Propiedad Router</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>                        
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Tipo IP</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Redes</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>
                    <div class="form-group">
                        <label class="custom-label" for="parameterSelect">Usos</label>
                        <select class="form-control input-sm" id="parameters" name="parameters">
                            <option>Todos</option>
                            <option>Administrativo</option>
                            <option>Teléfono</option>
                            <option>Ibenet</option>
                            <option>Nemónico</option>
                            <option>IP de gestión</option>
                            <option>VPN</option>
                            <option>Dirección</option>
                            <option>Nombre de la sede</option>
                        </select>                    
                    </div>

                    </div>

                </fieldset>
            </div>

            
            
            
            
            
<!--            <div class="col-lg-1">
                        <fieldset class="form-group">
                        <legend>Esquemas</legend>
                            <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                            <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                            <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                            <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                            <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                        </fieldset>    
                        <button type="submit" class="btn btn-primary">IMG:Upload galeria de imagenes</button>

                <div class="form-group">
                    &nbsp;        
                </div>
                <div style="float:right; ">
                    <a class="btn btn-primary btn-lg" href="#" role="button" onclick="Filtrar();" title="Filtrar">
                        <i class="glyphicon glyphicon-sort-by-attributes-alt"></i>
                    </a>
                </div>
            </div>-->
            
        </div>
    </div>

</fieldset>


