<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }

    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }

    .form-group
    {
        margin-bottom: 1px;
    }

    .form-control
    {
        /*height: 26px;*/
        font-size: 9px;

    }

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
    
</style>                

<script type="text/javascript">

    $(document).ready(function (e){

        $("#provincia").change(function(){

            var provincia = $("#provincia option:selected").val();
            var data = {provincia: provincia, custom: 1};
            var    url = '<?= $this->url('ajax-poblacion'); ?>';
            $.ajax({
                type: "POST",
                url: url,
                data: data,
                cache: false,
                success: function (html) {
                    $("#ajax-poblacion").html(html);
                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#fill").html(html);
                }
            });

        });

        $("#ctecnologia").change(function() {
            var tecnologia = $("#ctecnologia option:selected").val();
            var data = {tecnologia: tecnologia, tipo: 1, custom: 1};
            var    url = '<?= $this->url('ajax-velocidad'); ?>';
            $.ajax({
                type: "POST",
                url: url,
                data: data,
                cache: false,
                success: function (html) {
                    $("#ajax-velocidad").html(html);
                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#fill").html(html);
                }
            });
        });
        

        $("#efabricante").change(function(){
            var fabricante = $("#efabricante option:selected").val();
            var data = {fabricante: fabricante, tipo: 1, custom:1};
            var    url = '<?= $this->url('ajax-modelo'); ?>';
            $.ajax({
                type: "POST",
                url: url,
                data: data,
                cache: false,
                success: function (html) {
                    $("#ajax-modelo").html(html);
                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#fill").html(html);
                }
            });
        });
        
    });


    function filter() {
        var url = '<?= $this->url('process-filter'); ?>';
        $.ajax({
            type: "GET",
            url: url,
            data: $('#filterForm').serialize(),
            cache: false,
            beforeSend: function() {
                $("#fill-search").html("<img style='display: block; margin:auto;' src='<?= $this->basePath() . '/img/loading.gif' ;?>' />");
            },
            success: function (json) {
                $("#fill-search").html(json);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });
    }
</script>

<fieldset class="col-md-12">
    <legend>Filtros de Búsqueda</legend>
    <div class="panel panel-default">
        <div class="panel-body">
            <form id="filterForm" >    
            <div class="col-lg-2">
                <fieldset class="form-group  custom-fieldset"> 
                    <legend class="custom-legend" title="Sedes">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Sedes
                    </legend>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Provincia</label>
                            <?= $this->formSelect($form->get('provincia')); ?>
                        </div>
                        <div id="ajax-poblacion">
                            <div  class="form-group">
                                <label class="custom-label" for="poblacion">Población</label>
                                <?= $this->formSelect($form->get('poblacion')); ?>    
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                <div class="form-group">
                    &nbsp;        
                </div>
                
                <div style="float: left;">
                    <a class="btn btn-primary btn-lg" href="#" role="button" onclick="filter();" title="Filtrar">
                        <i class="glyphicon glyphicon-filter"></i>
                    </a>
                </div>
                <div style="float: right;">
                    <a class="btn btn-primary btn-lg" href="<?= $this->url('filter'); ?>" role="button" title="Refresh">
                        <i class="glyphicon glyphicon-refresh"></i>
                    </a>
                </div>
                
            </div>

            <div class="col-lg-3">

                <fieldset class="form-group  custom-fieldset">
                    <legend class="custom-legend" title="Circuitos">
                        <span class="glyphicon glyphicon-random" aria-hidden="true"></span> Circuitos
                    </legend>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="custom-label" for="client-select">Cliente</label>
                            <?= $this->formSelect($form->get('ccliente')); ?>
                        </div>
                    </div>
                    <div class="col-lg-12">    
                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Tecnología</label>
                            <?= $this->formSelect($form->get('ctecnologia')); ?>
                        </div>
                        <div id="ajax-velocidad">
                            <div class="form-group">
                                <label class="custom-label" for="velocidad">Velocidad</label>
                                <?= $this->formSelect($form->get('cvelocidad')); ?>
                            </div>
                        </div>

                    </div>
                    
                    
                    
                    <div class="col-lg-6" style="margin-top:10px;">

                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Criticidad</label>
                            <?= $this->formSelect($form->get('ccriticidad')); ?>                    
                        </div>

                        
                        
                        <div class="form-group">
                            <label class="custom-label" for="estado-circuito">Estados</label>
                            <select class="form-control input-sm" id="estado-circuito" name="estado-circuito">
                                <option value="9" selected>Todos</option>
                                <option value="1">Pre-alta</option>
                                <option value="2">Alta</option>
                                <option value="3">Pre-baja</option>
                                <option value="4">Baja</option>
                            </select>                                 
                        </div>
                    </div>    
                    <div class="col-lg-6" style="margin-top:10px;">    
                        <div class="form-group">
                            <label class="custom-label" for="gestion">Gestión</label>
                            <select class="form-control input-sm" id="gestion" name="gestion">
                                <option value="9" selected>Todos</option>
                                <option value="1">Si</option>
                                <option value="0">No</option>
                            </select>                                 
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="custom-label" for="principal-circuito">Principal&nbsp;<span title="Circuito principal/backup" style="cursor: pointer;" class="glyphicon glyphicon-question-sign"></span></label>
                            <select class="form-control input-sm" id="principal-circuito" name="principal-circuito">
                                <option value="9" selected>Todos</option>
                                <option value="1">Si</option>
                                <option value="0">No</option>
                            </select>                                 
                        </div>
                    </div>
                </fieldset>    
            </div>    
            <div class="col-lg-2">    
                <fieldset class="form-group  custom-fieldset">
                    <legend class="custom-legend" title="Equipos gestionados" style='font-size: 10px;'>
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                        Equipos Gestionados
                    </legend>
                    
                    <div class="col-lg-14">
                        
                        <div class="form-group">
                            <label class="custom-label" for="parameterSelect">Servicio</label>
                            <?= $this->formSelect($form->get('eservicio')); ?>
                        </div>

                        <div class="form-group">
                            <label class="custom-label" for="equipo-fabricante">Fabricante</label>
                            <?= $this->formSelect($form->get('efabricante')); ?>
                        </div>

                        <div id="ajax-modelo">
                            <div class="form-group">
                                <label class="custom-label" for="modelo">Modelo</label>
                                <?= $this->formSelect($form->get('emodelo')); ?>
                            </div>
                        </div>                        
                        
                    </div>
                        
                    <div class="col-lg-14">
                        <div class="form-group">
                            <label class="custom-label" for="estado-equipo">Estados</label>
                            <select class="form-control input-sm" id="estado-equipo" name="estado-equipo">
                                <option value="9" selected>Todos</option>
                                <option value="1">Pre-alta</option>
                                <option value="2">Alta</option>
                                <option value="3">Pre-baja</option>
                                <option value="4">Baja</option>
                            </select>                                 
                        </div>
                    </div>
                    
                    <div class="col-lg-14">
                        <div class="form-group">
                            <label class="custom-label" for="principal-equipo">Principal&nbsp;<span title="Equipo principal/backup" style="cursor: pointer;" class="glyphicon glyphicon-question-sign"></span></label>
                            <select class="form-control input-sm" id="principal-equipo" name="principal-equipo">
                                <option value="9" selected>Todos</option>
                                <option value="1">Si</option>
                                <option value="0">No</option>
                            </select>                                 
                        </div>
                    </div>
                    
                    
                </fieldset>    
            </div>    


            <div class="col-lg-2">    
                <fieldset class="form-group  custom-fieldset">
                    <legend class="custom-legend" title="Equipos No Gestionados" style='font-size: 10px;'>
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 
                        Equipos no gestionados
                    </legend>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="custom-label" for="propiedad-equipo">Propiedad Router</label>
                            <select class="form-control input-sm" id="propiedad-equipo" name="propiedad-equipo">
                                <option value="9" selected>Todos</option>
                                <option value="1">Teléfonica</option>
                                <option value="2">Cliente</option>
                            </select>                                 
                        </div>
                        <div class="form-group">
                            <label class="custom-label" for="tipo-ip">Tipo IP</label>
                            <select class="form-control input-sm" id="tipo-ip" name="tipo-ip">
                                <option value="9" selected>Todos</option>
                                <option value="1">Dinámico</option>
                                <option value="2">Estático</option>
                            </select>                    
                        </div>
                        
                    </div>

                </fieldset>
                
                
                
                
            </div>

                <div class="col-lg-3" style="padding: 4px; background-color: #f5f5f5;"> 
                
                    <fieldset class="form-group custom-fieldset" style='background-color: #f5f5f5;'>
                    <legend class="custom-legend" title="Equipos Glans" style='background-color: #f5f5f5;'>
                        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        Glans
                    </legend>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="custom-label" for="glan-client-select">Cliente</label>
                            <?= $this->formSelect($form->get('gcliente')); ?>
                        </div>

                        <div class="form-group">
                            <label class="custom-label" for="glan-function-select">Función</label>
                            <?= $this->formSelect($form->get('gfuncion')); ?>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="custom-label" for="glan-criticidad-select">Criticidad</label>
                            <?= $this->formSelect($form->get('gcriticidad')); ?>
                        </div>
                    </div>    
                    <div class="col-lg-6">    
                        <div class="form-group">
                            <label class="custom-label" for="estado-equipo-glan">Estados</label>
                            <select class="form-control input-sm" id="estado-equipo-glan" name="estado-equipo-glan">
                                <option value="9" selected>Todos</option>
                                <option value="1">Pre-alta</option>
                                <option value="2">Alta</option>
                                <option value="3">Pre-baja</option>
                                <option value="4">Baja</option>
                            </select>                                 
                        </div>
                    </div>

                </fieldset>
                <fieldset class="form-group  custom-fieldset"  style='margin-top:30px; background-color: #f5f5f5;'>
                    <legend class="custom-legend" title="Equipos Access Point" style='background-color: #f5f5f5;'>
                        <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                        Access Point
                    </legend>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="custom-label" for="aps-criticidad-select">Criticidad</label>
                            <?= $this->formSelect($form->get('apcriticidad')); ?>
                        </div>
                        <div class="form-group">
                            <label class="custom-label" for="estado-equipo-glan">Estados</label>
                            <select class="form-control input-sm" id="estado-equipo-ap" name="estado-equipo-ap">
                                <option value="9" selected>Todos</option>
                                <option value="1">Pre-alta</option>
                                <option value="2">Alta</option>
                                <option value="3">Pre-baja</option>
                                <option value="4">Baja</option>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </div>
            </form>
        </div>
    </div>
</fieldset>
<div id="fill-search">
</div>
