<?php echo $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

 <!-- BEGIN HEAD -->
<head>
     <meta charset="UTF-8" />
    
    <?php echo $this->headTitle($this->translate('Admin Dashboard'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
     <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>    
        
        
     <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <!-- GLOBAL STYLES -->
    
    <?php echo $this->headLink(array(
                                    'rel' => 'shortcut icon', 
                                    'type' => 'image/vnd.microsoft.icon', 
                                    'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath('assets/plugins/bootstrap/css/bootstrap.css'))
                ->appendStylesheet($this->basePath('assets/css/main.css'))
                ->appendStylesheet($this->basePath('assets/css/MoneAdmin.css'))
                ->appendStylesheet($this->basePath('assets/plugins/Font-Awesome/css/font-awesome.css'))?>

    
    
    <!--END GLOBAL STYLES -->

    <!-- PAGE LEVEL STYLES -->
    <!--<link href="assets/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />-->
    <!-- END PAGE LEVEL  STYLES -->
    
       <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- GLOBAL SCRIPTS -->
    
    <?php echo $this->headScript()
            ->appendFile($this->basePath('assets/plugins/jquery-2.0.3.min.js'))
            ->appendFile($this->basePath('assets/plugins/bootstrap/js/bootstrap.min.js'))
            ->appendFile($this->basePath('assets/plugins/modernizr-2.6.2-respond-1.1.0.min.js'))
            ->appendFile($this->basePath('assets/plugins/dataTables/jquery.dataTables.js'))         # Tabla Query
            ->appendFile($this->basePath('assets/plugins/dataTables/dataTables.bootstrap.js'))
       #     ->appendFile($this->basePath('js/bootstrap-table/bootstrap-table.js'))                  # Tabla Bootstrap 
       #     ->appendFile($this->basePath('js/bootstrap-table/locale/bootstrap-table-en-Sbt-US.min.js'))
            ; ?>
    
    
<!--    <script src="assets/plugins/jquery-2.0.3.min.js"></script>
    <script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/plugins/modernizr-2.6.2-respond-1.1.0.min.js"></script>-->
    
    
    <!-- END GLOBAL SCRIPTS -->
    
    <!-- PAGE LEVEL SCRIPTS -->
    <!--    <script src="assets/plugins/dataTables/jquery.dataTables.js"></script>
            <script src="assets/plugins/dataTables/dataTables.bootstrap.js"></script>
            <script>
                $(document).ready(function () {
                    $('#dataTables-example').dataTable();
                });
            </script>-->
     <!-- END PAGE LEVEL SCRIPTS -->

</head>
     <!-- END HEAD -->
     <!-- BEGIN BODY -->
<body class="padTop53 " >

     <!-- MAIN WRAPPER -->
    <div id="wrap">

         <!-- HEADER SECTION -->
        <div id="top">

            <nav class="navbar navbar-inverse navbar-fixed-top " style="padding-top: 10px;">
                <a data-original-title="Show/Hide Menu" data-placement="bottom" data-tooltip="tooltip" class="accordion-toggle btn btn-primary btn-sm visible-xs" data-toggle="collapse" href="#menu" id="menu-toggle">
                    <i class="icon-align-justify"></i>
                </a>
                <!-- LOGO SECTION -->
                <header class="navbar-header">

                    <a href="index.html" class="navbar-brand">
                    <!--<img src="img/logo.png" alt="" /></a>-->
                </header>
                <!-- END LOGO SECTION -->
                <ul class="nav navbar-top-links navbar-right">
                    <!--ADMIN SETTINGS SECTIONS -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="icon-user "></i>&nbsp; <i class="icon-chevron-down "></i>
                        </a>

                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="<?php echo $this->url('application') ?>"><i class="icon-user"></i> User Profile </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('application') ?>"><i class="icon-gear"></i> Settings </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="users/logout"><i class="icon-signout"></i> Logout </a>
                            </li>
                        </ul>

                    </li>
                    <!--END ADMIN SETTINGS -->
                </ul>

            </nav>

        </div>
        <!-- END HEADER SECTION -->



        <!-- MENU SECTION -->
       <div id="left">
            <div class="media user-media well-small">
                <a class="user-link" href="#">
                    <!--<img class="media-object img-thumbnail user-img" alt="User Picture" src="assets/img/user.gif" />-->
                </a>
                <br />
                <div class="media-body">
                    <h5 class="media-heading"> Euler Nuñez </h5>
                    <ul class="list-unstyled user-info">
                        <li>
                             <a class="btn btn-success btn-xs btn-circle" style="width: 10px;height: 12px;"></a> Online
                        </li>
                    </ul>
                </div>
                <br />
            </div>

            <ul id="menu" class="collapse">

                
                <li class="panel">
<!--                    <a href="index.html" >
                        <i class="icon-table"></i> Dashboard
                    </a>-->
                    
                    <a href="<?php echo $this->url('application') ?>">
                        <i class="icon-table"></i> <?php echo $this->translate('Dashboard') ?>
                    </a>
                    
                </li>



                <li class="panel ">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#component-nav">
                        <i class="icon-tasks"> </i> Administración     
	   
                        <span class="pull-right">
                          <i class="icon-angle-left"></i>
                        </span>
                       &nbsp; <span class="label label-default">6</span>&nbsp;
                    </a>
                    <ul class="collapse" id="component-nav">
                       
                        <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Generar Factura Pre. </a></li>
                         <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Carregar Factura Pro. </a></li>
                        <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Esborrar Periode Facturació </a></li>
                        <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Sumatoris per Lot </a></li>
                        <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Direcció d'Entitats </a></li>
                         <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Llistat d'Usuaris Lot3 </a></li>
                    </ul>
                </li>


                <li class="panel">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#DDL-nav">
                        <i class=" icon-sitemap"></i> Facturació
	   
                        <span class="pull-right">
                            <i class="icon-angle-left"></i>
                        </span>
                        &nbsp; <span class="label label-default">3</span>&nbsp;
                    </a>
                    <ul class="collapse" id="DDL-nav">
                        <li>
                            <a href="#" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#DDL1-nav">
                                <i class="icon-sitemap"></i>&nbsp; Diputació de Barcelona
	   
                                <span class="pull-right" style="margin-right: 20px;">
                                    <i class="icon-angle-left"></i>
                                </span>
                                
                            </a>
                            <ul class="collapse" id="DDL1-nav">
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> XIC </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> XEM </a></li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> XB </a></li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> XPN </a></li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Quadre Resum </a></li>
                                
                            </ul>
                        </li>

                    </ul>
                </li>

                <li class="panel ">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#provisio-nav">
                        <i class="icon-tasks"> </i> Provisio     
                        <span class="pull-right">
                          <i class="icon-angle-left"></i>
                        </span>
                       &nbsp; <span class="label label-default">2</span>&nbsp;
                    </a>
                    <ul class="collapse" id="provisio-nav">
                       
                        <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Seguimiento Datos </a></li>
                         <li class=""><a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> Seguimiento Moviles </a></li>
                    </ul>
                </li>


                <li class="panel ">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#inventari-nav">
                        <i class="icon-bar-chart"> </i> Inventari     
                        <span class="pull-right">
                          <i class="icon-angle-left"></i>
                        </span>
                       &nbsp; <span class="label label-default">1</span>&nbsp;
                    </a>
                    <ul class="collapse" id="inventari-nav">
                        <li class="">
                            <!--<a href="button.html"><i class="icon-angle-right"></i> Planta Instal lada </a>-->
                        <a href="<?php echo $this->url('inventario') ?>"><i class="icon-angle-right"></i> <?php echo $this->translate('Planta Instal lada') ?></a>
                        
                        </li>
                        <li class="">
                            <a href="<?php echo $this->url('tramite') ?>"><i class="icon-angle-right"></i> <?php echo $this->translate('Process') ?></a>
                        </li>
                        <li class="">
                            <a href="<?php echo $this->url('alta') ?>"><i class="icon-angle-right"></i> <?php echo $this->translate('Alta') ?></a>
                        </li>
                    </ul>
                </li>
                

                
                
                
            </ul>

        </div>
        <!--END MENU SECTION -->

        <!-- PAGE CONTENT -->
        <div id="content">
            <?php  echo $this->content; ?>
        </div>    
        <!-- END PAGE CONTENT -->

        
        
    </div>

     <!--END MAIN WRAPPER -->

   <!-- FOOTER -->
    <div id="footer">
        <p>&copy;  Diputación Barcelona &nbsp;2017 &nbsp;</p>
    </div>
    <!--END FOOTER -->

</body>
     <!-- END BODY -->
</html>
