<?php echo $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

 <!-- BEGIN HEAD -->
<head>
    <meta charset="UTF-8" />
    
    <?php echo $this->headTitle($this->translate('Admin Dashboard'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
     <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>    
        
        
     <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <!-- GLOBAL STYLES -->
    
    <?php echo $this->headLink(array(
                                    'rel' => 'shortcut icon', 
                                    'type' => 'image/vnd.microsoft.icon', 
                                    'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath('assets/plugins/bootstrap/css/bootstrap.css'))
                ->appendStylesheet($this->basePath('assets/css/main.css'))
                ->appendStylesheet($this->basePath('assets/css/MoneAdmin.css'))
                ->appendStylesheet($this->basePath('assets/plugins/Font-Awesome/css/font-awesome.css'))
            
                ->appendStylesheet($this->basePath('assets/revolution/revolution/css/layers.css'))
                ->appendStylesheet($this->basePath('assets/revolution/revolution/css/settings.css'))
                ->appendStylesheet($this->basePath('assets/revolution/revolution/css/navigation.css'))
                ->appendStylesheet($this->basePath('assets/revolution/css/style.css'));
            ?>

    
    <!--END GLOBAL STYLES -->

    <!-- PAGE LEVEL STYLES -->
    <!--<link href="assets/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />-->
    <!-- END PAGE LEVEL  STYLES -->
    
       <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- GLOBAL SCRIPTS -->
    
    <?php echo $this->headScript()
            ->appendFile($this->basePath('assets/plugins/jquery-2.0.3.min.js'))
            ->appendFile($this->basePath('assets/plugins/bootstrap/js/bootstrap.min.js'))
            ->appendFile($this->basePath('assets/plugins/modernizr-2.6.2-respond-1.1.0.min.js'))
            ->appendFile($this->basePath('assets/plugins/dataTables/jquery.dataTables.js'))         # Tabla Query
            ->appendFile($this->basePath('assets/plugins/dataTables/dataTables.bootstrap.js'))
       #     ->appendFile($this->basePath('js/bootstrap-table/bootstrap-table.js'))                  # Tabla Bootstrap 
       #     ->appendFile($this->basePath('js/bootstrap-table/locale/bootstrap-table-en-Sbt-US.min.js'))
            ->appendFile($this->basePath('assets/revolution/js/main.js'))                           # Revolution
            ->appendFile($this->basePath('assets/revolution/revolution/js/jquery.themepunch.tools.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/jquery.themepunch.revolution.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.actions.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.carousel.min.js'))
            
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.kenburn.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.layeranimation.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.migration.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.navigation.min.js'))
            
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.parallax.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.slideanims.min.js'))
            ->appendFile($this->basePath('assets/revolution/revolution/js/extensions/revolution.extension.video.min.js')); 
            
                                                                                                                    # VALIDATOR
//           appendFile('https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js'); 
           ?>
    
    
<!--    <script src="assets/plugins/jquery-2.0.3.min.js"></script>
    <script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/plugins/modernizr-2.6.2-respond-1.1.0.min.js"></script>-->
    
    
    <!-- END GLOBAL SCRIPTS -->
    
    <!-- PAGE LEVEL SCRIPTS -->
    <!--    <script src="assets/plugins/dataTables/jquery.dataTables.js"></script>
            <script src="assets/plugins/dataTables/dataTables.bootstrap.js"></script>
            <script>
                $(document).ready(function () {
                    $('#dataTables-example').dataTable();
                });
            </script>-->
     <!-- END PAGE LEVEL SCRIPTS -->

</head>
<?php
    use Zend\Session\Container;
    $session = new Container('User');
    $userRole = $session->offsetGet('userRole');
    $firstName = $session->offsetGet('firstName');
    $lastName = $session->offsetGet('lastName');
?>
     <!-- END HEAD -->
     <!-- BEGIN BODY -->
<body class="padTop53 " >

     <!-- MAIN WRAPPER -->
    <div id="wrap">

         <!-- HEADER SECTION -->
        <div id="top">

            <nav class="navbar navbar-inverse navbar-fixed-top " style="padding-top: 10px;">
                <a data-original-title="Show/Hide Menu" data-placement="bottom" data-tooltip="tooltip" class="accordion-toggle btn btn-primary btn-sm visible-xs" data-toggle="collapse" href="#menu" id="menu-toggle">
                    <i class="icon-align-justify"></i>
                </a>
                <!-- LOGO SECTION -->
                <header class="navbar-header">

                    <!--<a href="index.html" class="navbar-brand">-->
                    <!--<img src="img/logo.png" alt="" /></a>-->
                </header>
                <!-- END LOGO SECTION -->
                <ul class="nav navbar-top-links navbar-right">
                    <!--ADMIN SETTINGS SECTIONS -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="icon-user "></i>&nbsp; <i class="icon-chevron-down "></i>
                        </a>

                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="<?php echo $this->url('application') ?>"><i class="icon-user"></i> Perfil de usuario </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('application') ?>"><i class="icon-gear"></i> Configuración </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?= $this->url('logout') ?>"><i class="icon-signout"></i> Salir </a>
                            </li>
                        </ul>

                    </li>
                    <!--END ADMIN SETTINGS -->
                </ul>

            </nav>

        </div>
        <!-- END HEADER SECTION -->



        <!-- MENU SECTION -->
        <div id="left">
            <div class="media user-media well-small">
                <a class="user-link" href="#">
                    <!--<img class="media-object img-thumbnail user-img" alt="User Picture" src="assets/img/user.gif" />-->
                </a>
                <br />
                <div class="media-body">
                    <h5 class="media-heading"> <?= $firstName . ' ' . $lastName ; ?> </h5>
                    <ul class="list-unstyled user-info">
                        <li>
                             <a class="btn btn-success btn-xs btn-circle" style="width: 10px;height: 12px;"></a> Online
                        </li>
                    </ul>
                </div>
                <br />
            </div>

            <ul id="menu" class="collapse">

                <li class="panel">
                    <a href="<?php echo $this->url('application') ?>">
                        <i class="icon-table"></i> <span style="font-size: 12px;"><?php echo $this->translate('Dashboard') ?></span>
                    </a>
                    
                </li>
                


            <?php if(false) : ?>    
                <li class="panel">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#DDL-nav">
                        <i class=" icon-sitemap"></i> <span style="font-size: 12px;">Facturación</span>
                    </a>
                    <ul class="collapse" id="DDL-nav">
                        <li>
                            <a href="#" data-parent="#DDL-nav" data-toggle="collapse" class="accordion-toggle" data-target="#DDL1-nav">
                                <i class="icon-sitemap"></i><span style="font-size: 12px;">&nbsp;Diputación de Barcelona</span>  
	   
                                <span class="pull-right" style="margin-right: 6px;">
                                    <i class="icon-angle-left"></i>
                                </span>
                            </a>    
                           
                            <ul class="collapse" id="DDL1-nav">
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">XIC</span> </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">XEM</span> </a></li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">XB</span> </a></li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">XPN</span> </a></li>
                                <li>
                                    <a href="<?php echo $this->url('application') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">Quadre Resum</span> </a></li>
                                
                            </ul>
                        </li>

                    </ul>
                </li>
            <?php endif ?>    
            
            <?php if('Administrador' == $userRole) : ?>    
                <li class="panel">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#admin-nav">
                        <i class="icon-lock"> </i> <span style="font-size: 12px;">Administración</span>
	   
                    </a>
                    <ul class="collapse" id="admin-nav">
                        <li class=""><a href="<?php echo $this->url('table-maintenance') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;">Tablas maestras</span> </a></li>
                    </ul>
                </li>
            <?php endif ?>    
            
            <?php if('Administrador' == $userRole || 'Cliente' == $userRole ) : ?>    
                <li class="panel">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#billing-nav">
                        <i class="icon-credit-card"> </i> <span style="font-size: 12px;">Facturación</span>
	   
                    </a>
                    <ul class="collapse" id="billing-nav">
                        <?php if('Administrador' == $userRole) : ?>    
                        <li class=""><a href="<?php echo $this->url('billing-load') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;">Carga del documento</span> </a></li>
                        <li class=""><a href="<?php echo $this->url('list-invoices') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;">Gestión de facturas</span> </a></li>
                        <?php endif ?>    
                        <li class=""><a href="<?php echo $this->url('invoice-filter') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;">Filtro de facturas</span> </a></li>
                        <?php if('Administrador' == $userRole) : ?>    
                        <li class=""><a href="<?php echo $this->url('ui-summation') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;">Sumatoria</span> </a></li>
                        <?php endif ?>    
                        
                    </ul>
                </li>
            <?php endif ?>    
                
            <?php if('Administrador' == $userRole || 'Ventas' == $userRole || 'Ingeniero' == $userRole || 'OperadorODP' == $userRole ) : ?>    
                <li class="panel">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#provisio-nav">
                        <i class="icon-suitcase"></i> <span style="font-size: 12px;">Provisión</span>
                    </a>
                    <ul class="collapse" id="provisio-nav">
                        <li>
                            <a href="#" data-parent="#provisio-nav" data-toggle="collapse" class="accordion-toggle" data-target="#provisio-nav-sub">
                                <i class="icon-sitemap"></i><span style="font-size: 12px;">&nbsp;Trámites</span>  
	   
                                <span class="pull-right" style="margin-right: 6px;">
                                    <i class="icon-angle-left"></i>
                                </span>
                            </a>    
                           
                            <ul class="collapse" id="provisio-nav-sub">
                                <li>
                                    <a href="<?php echo $this->url('create') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">Alta</span> </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('open-supply-tracing') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">Abiertos</span> </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('close-supply-tracing') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">Cerrados</span> </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('custom-export') ?>"><i class="icon-angle-right"></i> <span style="font-size: 11px;">Exportación</span> </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </li>
             <?php endif ?>
                

            <?php if('Administrador' == $userRole || 'Operador' == $userRole || 'Cliente' == $userRole || 'Ingeniero' == $userRole) : ?>    
                <li class="panel">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#inventari-nav">
                        <i class="icon-bar-chart"> </i> <span style="font-size: 12px;">Inventario</span>     
                    </a>
                    <ul class="collapse" id="inventari-nav">
                        <li class="">
                            <a href="<?php echo $this->url('list') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;"> <?= $this->translate('Planta Instalada') ?> </span></a>
                        </li>
                        <?php if('Administrador' == $userRole || 'Operador' == $userRole || 'Ingeniero' == $userRole) : ?>
                            <li class="">
                                <a href="<?php echo $this->url('wizard') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;"> <?= $this->translate('Wizard') ?> </span></a>
                            </li>
                        <?php endIf; ?>
                    </ul>
                </li>
                
                
                <li class="panel">
                    <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#buscador-nav">
                        <i class="icon-map-marker"> </i> <span style="font-size: 12px;">Búsqueda</span>     
                    </a>
                    <ul class="collapse" id="buscador-nav">
                        <li class=""><a href="<?php echo $this->url('search') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;">Buscador</span> </a></li>
                         <li class=""><a href="<?php echo $this->url('filter') ?>"><i class="icon-angle-right"></i> <span style="font-size: 12px;">Filtrador</span> </a></li>
                    </ul>
                </li>
                <?php endIf; ?>
                
            </ul>

        </div>
        <!--END MENU SECTION -->

        <!-- PAGE CONTENT -->
        <div id="content">
            <?php  echo $this->content; ?>
        </div>    
        <!-- END PAGE CONTENT -->

        
        
    </div>

    <!-- ========== NOTIFICATION ========== -->
    <div id="notification"></div>
     <!--END MAIN WRAPPER -->

   <!-- FOOTER -->
    <div id="footer">
        <p>&copy;  Diputación Barcelona &nbsp;<?= date("Y"); ?> &nbsp;</p>
    </div>
    <!--END FOOTER -->

</body>
     <!-- END BODY -->
</html>
