<?php if(count($this->parameters)>0) : ?>
    <div class="form-group" style="margin-top: 12px;">
        <label for="parameter">Parámetros</label>
        <select class="form-control input-sm" id="parameters" name="parameters">
            <option value="0">Todos</option>
             <?php foreach ($this->parameters as $key => $value ) : ?>
                <option value="<?= $key; ?>"><?= $value; ?></option>
            <?php endforeach; ?>

        </select>                    
    </div>
<?php else: ?>
    <div class="form-group" style="margin-top: 12px;">
        <label for="parameter">Parámetros</label>
        <select class="form-control input-sm" id="parameters" name="parameters">
            <option value="0">Todos</option>
        </select>                    
    </div>
<?php endif; ?>
