<script>

$(document).ready(function (e){
});

function buscar() {

    var url = '<?= $this->url('process-searcher'); ?>';
    var value = $("#search").val();
    var s;
    var p;
    var m;
    
    $.ajax({
        type: "GET",
        url: url,
        data: $('#searchForm').serialize(),
        cache: false,
        success: function (json) {

            var isJson;
            try {
                JSON.parse(json);
                isJson = true;
            } catch (e) {
                isJson = false;
            }
            
            if(isJson) {
                var obj = jQuery.parseJSON(json);
                var sede;
                for(var key in obj){
                    //sede = parseInt(obj[key]);
                    s = parseInt(obj['section']);
                    p = parseInt(obj['parameter']);
                    m = parseInt(obj['multiple']);
                    sede = parseInt(obj['sede']);
                }
                if(sede > 0) { // http://application.localhost/tabs/
                    location.href = "<?= $this->url('tabs'); ?>"  + "/" + sede + "/" + s + "/" + p + "/" + value;
                } else if (sede === 0) {
                    json = "<div class='alert alert-danger'>¡No existe coincidencia alguna!</div>";
                    $("#fill-search").html(json);
                }
            } else { 
                $("#fill-search").html(json);
            }

        },

        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}



</script>

<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }

    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }

    .form-group
    {
        margin-bottom: 2px;
    }

    .form-control
    {
        /*height: 26px;*/
        font-size: 12px;

    }

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
</style>                





<fieldset class="col-md-12">    	
    <legend>Buscador</legend>

    <div class="panel panel-default">
        <div class="panel-body">

        <div>
            <form id="searchForm" method="get">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="section">Sección</label>
                    <select class="form-control input-sm" id="section" name="section">
                        <option value="0">Todos</option>
                        <option value="1">Sedes</option>
                        <option value="2">Circuitos</option>
                        <option value="3">Equipos gestionados</option>
                        <option value="4">Equipos no gestionados</option>
                        <option value="5">GLAN</option>
                        <option value="6">Access Points</option>
                    </select>                    
                </div>
                <div class="form-group" style="margin-top: 12px;">
                    <label for="parameter">Parámetros</label>
                    <select class="form-control input-sm" id="parameters" name="parameters">
                        <option value="0">Todos</option>
                        <option value="1">Administrativo</option>
                        <option value="2">Teléfono</option>
                        <option value="3">Ibenet</option>
                        <option value="4">Nemónico</option>
                        <option value="41">Mac</option>
                        <option value="5">IP de gestión</option>
                        <option value="51">IP gestión de cliente</option>
                        <option value="52">ID AP</option>
                        <!--<option value="6">VPN</option>-->
                        <option value="7">Nombre de la sede</option>
                        <option value="8">Dirección</option>
                    </select>                    
                </div>
            </div>
            <div class="col-lg-9">    
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                <div class="form-group">&nbsp;</div>
                
                <div class="form-group input-group">
                    <input type="text" class="form-control" id="search" name="search" placeholder="Buscar..."/>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" onclick="buscar();">
                            <i class="icon-search"></i>
                        </button>
                    </span>
                </div>
                
            </div>
            
            </form>
        </div>
        </div>
    </div>
    
</fieldset>
<div id="fill-search">
    
    
    
</div>