<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function saveMc() {
            
    var url = '<?= $this->url('save-mc'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: $('#myForm').serialize(),
        cache: false,
        success: function (json) {
            $("#grid-mc-fill").html(json);
            $('.save-mc').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}






$(function(){
    
    
    
});

</script>


<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="mcequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="redwantunelgreppal">Red Wan Tunel GRE PPAL</label>
                <?= $this->formInput($form->get('redwantunelgreppal')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="iploppbackgre">IP LoppBack GRE</label>
                <?= $this->formInput($form->get('iploppbackgre')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="ipedctunel1">IP EDC Tunel 1</label>
                <?= $this->formInput($form->get('ipedctunel1')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="ipasrppaltuneloficina">IP ASR PPAL Tunel Oficina</label>
                <?= $this->formInput($form->get('ipasrppaltuneloficina')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="interfaztunelasrppal">Interfaz Tunel ASR PPAL</label>
                <?= $this->formInput($form->get('interfaztunelasrppal')); ?>
            </div>

        </div>    

        <div class="col-lg-6">
            
            <div class="form-group">
                <label class="control-label" for="redwantunelgrebck">Red Wan Tunel GRE BCK</label>
                <?= $this->formInput($form->get('redwantunelgrebck')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="iprp">IP RP</label>
                <?= $this->formInput($form->get('iprp')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipedctunel2">IP EDC Tunel 2</label>
                <?= $this->formInput($form->get('ipedctunel2')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipasrbcktuneloficina">IP ASR BCK Tunel Oficina</label>
                <?= $this->formInput($form->get('ipasrbcktuneloficina')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="interfaztunelasrbck">Interfaz Tunel ASR BCK</label>
                <?= $this->formInput($form->get('interfaztunelasrbck')); ?>
            </div>
            
            <div class="form-group">
                &nbsp;
            </div>
            
            <div style="float:right;">
                <a class="btn btn-primary btn-sm save-mc" href="#" onclick="saveMc();" role="button" title="Guardar multicast">
                    <i class="glyphicon glyphicon-saved"></i>
                </a>
            </div>    
            
        </div>
        
    </div>
    
     <div class="clearfix"></div>
</div>