<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function saveIpwan() {

    var url = '<?= $this->url('save-ipwan'); ?>';
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                $("#grid-ipwan-fill").html(json);
                $('.save-ipwan').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}






$(function(){
    
    
    
});

</script>


<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="ipwequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwrpv">RPV</label>
                <?= $this->formSelect($form->get('ipwrpv')); ?>
            </div>
                            
            <div class="form-group">
                <label class="control-label" for="ipwrouting">Routing</label>
                <?= $this->formSelect($form->get('ipwrouting')); ?>                            
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwvlanedc">Vlan EDC</label>
                <?= $this->formInput($form->get('ipwvlanedc')); ?>
            </div>
                            
            <div class="form-group">
                <label class="control-label" for="ipwvlannacional">Vlan Nacional</label>
                <?= $this->formSelect($form->get('ipwvlannacional')); ?>                                
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwred">Red</label>
                <?= $this->formSelect($form->get('ipwred')); ?>                            
            </div>
                            
            <div class="form-group">
                <label class="control-label" for="ipwuso">Uso</label>
                <?= $this->formSelect($form->get('ipwuso')); ?>                            
            </div>

        </div>    

        <div class="col-lg-6">
                    
            <div class="form-group">
                <label class="control-label" for="ipwipwanedc">IP WAN EDC</label>
                <?= $this->formInput($form->get('ipwipwanedc')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwmascara">Máscara</label>
                <?= $this->formInput($form->get('ipwmascara')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwpeppal">PE Ppal</label>
                <?= $this->formInput($form->get('ipwpeppal')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwpebackup">PE Backup</label>
                <?= $this->formInput($form->get('ipwpebackup')); ?>
            </div>
            <div class="form-group">
                &nbsp;
            </div>        
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            
            <div style="float:right;">
                <a class="btn btn-primary btn-sm save-ipwan" href="#" onclick="saveIpwan();" role="button" title="Guardar direccionamiento Wan">
                    <i class="glyphicon glyphicon-saved"></i>
                </a>
            </div>
            
        </div>    
    </div>
</div>
