<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function saveComponent() {

    var url = '<?= $this->url('save-component'); ?>';
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                $("#save-component").html(json);
//                $('.save-ipwan').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}






$(function(){
    $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });
});

</script>

<input type="hidden" id="glanId" name="glanId" value="<?= $this->glanId ;?>">
<div class="col-lg-6">    

    <div class="form-group">
        <label class="control-label" for="componente-tipo">Componente</label>
        <?= $this->formSelect($form->get('ctipo')); ?>
    </div>

    <div class="form-group">
        <label class="control-label" for="componente">Módelo</label>
         <?= $this->formSelect($form->get('cmodelo')); ?>
    </div>

</div>

<div class="col-lg-6">    

    <div class="form-group">
        <label class="control-label" for="component-numeroserie">N/S</label>
        <?= $this->formInput($form->get('cnumeroserie')); ?>
    </div>
    
    <div style="float:right; margin-top: 21px;">
        <a class="btn btn-primary btn-sm" href="#" onclick="saveComponent();" role="button" title="Guardar componente">
            <i class="glyphicon glyphicon-saved"></i>
        </a>
    </div>
    
    

</div>
