<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function saveIplan() {
            
    var url = '/save-iplan';
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                   
                $("#grid-iplan-fill").html(json);
                $('.save-iplan').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}






$(function(){
    
    
    
});

</script>


<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="iplequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="iplrpv">RPV</label>
                <?= $this->formSelect($form->get('iplrpv')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="iplalias">Alias</label>
                <?= $this->formInput($form->get('iplalias')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="iplvlan">Vlan</label>
                <?= $this->formInput($form->get('iplvlan')); ?>
            </div>                    
                    
            <div class="form-group">
                <label class="control-label" for="ipliplan">IP Lan</label>
                <?= $this->formInput($form->get('ipliplan')); ?>
            </div>

        </div>    

        <div class="col-lg-6">
            
            <div class="form-group">
                <label class="control-label" for="iplmascara">Máscara</label>
                <?= $this->formInput($form->get('iplmascara')); ?>
            </div>
            
            
           <div class="form-group">
                <label class="control-label" for="iplnat">Nat</label>
                <?= $this->formInput($form->get('iplnat')); ?>
            </div>
            
            <div class="form-group">
                <label class="control-label" for="iplinterfaz">Interfaz</label>
                <?= $this->formInput($form->get('iplinterfaz')); ?>
            </div>            
            
            <div class="form-group">
                &nbsp;
            </div>        
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            
            <div style="float:right;">
                <a class="btn btn-primary btn-sm save-iplan" href="#" onclick="saveIplan();" role="button" title="Guardar direccionamiento Lan">
                    <i class="glyphicon glyphicon-saved"></i>
                </a>
            </div>
            
        </div>    
    </div>
</div>
