<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function saveHe() {
            
    var url = '<?= $this->url('save-he'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: $('#myForm').serialize(),
        cache: false,
        success: function (json) {
            $("#grid-he-fill").html(json);
            $('.save-he').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}






$(function(){
    
    
    
});

</script>


<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="rpvequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="rpvtarjeta">Tarjeta</label>
                <?= $this->formSelect($form->get('rpvtarjeta')); ?>
            </div>
        
            <div class="form-group">
                <label class="control-label" for="rpvfabricante">Fabricante</label>
                <?= $this->formSelect($form->get('rpvfabricante')); ?>
            </div>

        </div>    

        <div class="col-lg-6">
            
            <div class="form-group">
                <label class="control-label" for="rpvmodelo">Modelo</label>
                <?= $this->formSelect($form->get('rpvmodelo')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="rpvserie">N/S</label>
                <?= $this->formInput($form->get('rpvserie')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="rpvalias">Alias</label>
                <?= $this->formInput($form->get('rpvalias')); ?>
            </div>
                    
        </div>
        
    </div>
    
    <div class="panel-body"><!-- INICIO Direccionamiento LAN -->
        <fieldset class="col-md-12">    	
            <legend>Direccionamiento LAN</legend>
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="col-lg-6">    

                        <div class="form-group">
                            <label class="control-label" for="rpvvlan">VLAN</label>
                            <?= $this->formInput($form->get('rpvvlan')); ?>
                        </div>
                                    
                        <div class="form-group">
                            <label class="control-label" for="rpviplan1">IP Lan 1</label>
                            <?= $this->formInput($form->get('rpviplan1')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="rpviplan2">IP Lan 2</label>
                            <?= $this->formInput($form->get('rpviplan2')); ?>
                        </div>

                    </div>    

                    <div class="col-lg-6">    

                        <div class="form-group">
                            <label class="control-label" for="rpvmascara">Máscara</label>
                            <?= $this->formInput($form->get('rpvmascara')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="rpvinterfaz1">Interfaz 1</label>
                            <?= $this->formInput($form->get('rpvinterfaz1')); ?>
                        </div>
                                    
                        <div class="form-group">
                            <label class="control-label" for="rpvinterfaz2">Interfaz 2</label>
                            <?= $this->formInput($form->get('rpvinterfaz2')); ?>
                        </div>
                    </div>
                    
                </div>
            </div>
        </fieldset>				
        <div class="clearfix"></div>
    </div> <!-- FIN Direccionamiento LAN  -->    
    
    <div style="float:right; padding-right: 14px; padding-bottom: 14px;">
        <a class="btn btn-primary btn-sm save-he" href="#" onclick="saveHe();" role="button" title="Guardar hardware">
            <i class="glyphicon glyphicon-saved"></i>
        </a>
    </div>    
    
     <div class="clearfix"></div>
</div>
