<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function saveHa() {
            
    var url = '<?= $this->url('save-ha'); ?>';
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                   
                $("#grid-ha-fill").html(json);
                $('.save-ha').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}






$(function(){
    
    
    
});

</script>


<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="haequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="hatipo">Tipo</label>
                <?= $this->formSelect($form->get('hatipo')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="hafabricante">Fabricante</label>
                <?= $this->formSelect($form->get('hafabricante')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="hamodelo">Modelo</label>
                <?= $this->formSelect($form->get('hamodelo')); ?>
            </div>

        </div>    

        <div class="col-lg-6">
            
            <div class="form-group">
                <label class="control-label" for="haserie">N/S</label>
                <?= $this->formInput($form->get('haserie')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="haalias">Alias</label>
                <?= $this->formInput($form->get('haalias')); ?>
            </div>

            <div class="form-group">
                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" id="haiplan" name="haiplan" value="1" class="form-check-input">
                          ¿Es gestionado?
                        </label>
                    </div>                        
            </div>
                    
            
            <div class="form-group">
                &nbsp;
            </div>        
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            
            <div style="float:right;">
                <a class="btn btn-primary btn-sm save-ha" href="#" onclick="saveHa();" role="button" title="Guardar hardware">
                    <i class="glyphicon glyphicon-saved"></i>
                </a>
            </div>
            
        </div>    
    </div>
</div>
