<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function saveAp() {

    var url = '<?= $this->url('save-ap'); ?>';
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                $("#save-ap").html(json);
//                $('.save-ipwan').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}






$(function(){
    
    $("html, body").animate({ scrollTop: 300 });
    
});

</script>
<div id="ap-fill">
    <div class="panel panel-default">
        <div class="panel-body">
            <fieldset class="col-md-12">
                <legend>AP</legend>
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="col-lg-6">
                            
                            <div class="form-group">
                                <label class="control-label" for="switch">Switch</label>
                                <?= $this->formSelect($form->get('apswitch')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="contrato-extreme">Contrato Extreme</label>
                                <?= $this->formInput($form->get('apcontratoextreme')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ap-nombre">Nombre</label>
                                <?= $this->formInput($form->get('apnombre')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ap-ipcliente">IP Cliente</label>
                                <?= $this->formInput($form->get('apipcliente')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ap-idap">ID AP</label>
                                <?= $this->formInput($form->get('apidap')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ap-red">Red</label>
                                <table id="grid-red-ap" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width:45%;">SSID</th>
                                            <th style="width:5%;">Act.</th>
                                            <th style="width:45%;">SSID</th>
                                            <th style="width:5%;">Act.</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="row-input">
                                            <td>Internet_corporatiu</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="apinetcorp" name="apinternetcorporatiu" value="1" class="form-check-input">
                                            </td>
                                            <td>Internet_visites</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="apinternetvisites" name="apinternetvisites" value="1" class="form-check-input">
                                            </td>
                                        </tr>
                                        <tr class="row-input">
                                            <td>Diba_intern</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="apdibaintern" name="apdibaintern" value="1" class="form-check-input">
                                            </td>
                                            <td>Espai F.B</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="apespaifb" name="apespaifb" value="1" class="form-check-input">
                                            </td>
                                        </tr>
                                        <tr class="row-input">
                                            <td>PDA_PavNord</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="appdapavnord" name="appdapavnord" value="1" class="form-check-input">
                                            </td>
                                            <td>Multimedia_Escola_Dona</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="apmultimediaescoladona" name="apmultimediaescoladona" value="1" class="form-check-input">
                                            </td>
                                        </tr>
                                        <tr class="row-input">
                                            <td>PalauGuell</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="appalauguell" name="appalauguell" value="1" class="form-check-input">
                                            </td>
                                            <td>Resident_Respir</td>
                                            <td style="text-align:center;">
                                                <input type="checkbox" id="apresidentrespir" name="apresidentrespir" value="1" class="form-check-input">
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>    

                        <div class="col-lg-6">

                            <div class="form-group">
                                <label class="control-label" for="ap-actividad-tsol">Actividad TSOL</label>
                                <?= $this->formInput($form->get('apactividadtsol')); ?>
                            </div>                                    

                            <div class="form-group">
                                <label class="control-label" for="ap-modelo">Módelo</label>
                                <?= $this->formInput($form->get('apmodelo')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ap-mac">MAC</label>
                                <?= $this->formInput($form->get('apmac')); ?>
                            </div>                                                    

                            <div class="form-group">
                                <label class="control-label" for="ap-criticidad">Criticidad</label>
                                <?= $this->formSelect($form->get('apcriticidad')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ap-estado">Estado</label>
                                <?= $this->formSelect($form->get('apestado')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-observaciones">Observaciones</label>
                                <?= $this->formTextarea($form->get('apobservacion')); ?>
                            </div>
                            
                            <input type="hidden" id="apSedeId" name="apSedeId" value="<?= $this->sedeId; ?>">
                            <div style="float:right; margin-top: 21px;">
                                <a class="btn btn-primary btn-sm" href="#" onclick="saveAp();" role="button" title="Guardar equipo AP">
                                    <i class="glyphicon glyphicon-saved"></i>
                                </a>
                            </div>

                        </div>

                    </div>
                </div>
            </fieldset>				
            <div class="clearfix"></div>
        </div>
    </div>
</div>