<div class="form-group">
    <label class="control-label" for="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>">Velocidad</label>
    <select name="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>" id="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>" class="form-control input-sm">
        <?php foreach ($this->velocidades as $key => $value ) : ?>
            <option value="<?= $key; ?>"><?= $value; ?></option>
        <?php endforeach; ?>
    </select>
</div>