<?php if(count($this->poblaciones)>0) : ?>
<div class="form-group">
    <label class="<?= ($this->custom==1)?'custom-label':'control-label'; ?>" for="poblacion">Población</label>
    <select name="poblacion" id="poblacion" class="form-control input-sm">
        <?php if(1== $this->custom) : ?>
            <option value="-1">Todos</option>
        <?php endif; ?>
        <?php foreach ($this->poblaciones as $key => $value ) : ?>
            <option value="<?= $key; ?>"><?= $value; ?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php else: ?>
<div class="form-group">
    <label class="<?= ($this->custom==1)?'custom-label':'control-label'; ?>" for="poblacion">Población</label>
    <select name="poblacion" id="poblacion" class="form-control input-sm">
            <option value="">Seleccione una opción</option>
    </select>
</div>
<?php endif; ?>
