<?php if(count($this->velocidades)>0) : ?>
<div class="form-group">
    <label class="<?= ($this->custom==1)?'custom-label':'control-label'; ?>" for="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>">Velocidad</label>
    <select name="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>" id="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>" class="form-control input-sm">
        <?php if(1== $this->custom) : ?>
            <option value="-1">Todos</option>
        <?php endif; ?>
        <?php foreach ($this->velocidades as $key => $value ) : ?>
            <option value="<?= $key; ?>"><?= $value; ?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php else: ?>
<div class="form-group">
    <label class="<?= ($this->custom==1)?'custom-label':'control-label'; ?>" for="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>">Velocidad</label>
    <select name="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>" id="<?= ($this->tipo==1)?'cvelocidad':'bcvelocidad'; ?>" class="form-control input-sm">
        <option value="">Seleccione una opción</option>
    </select>
</div>
<?php endif; ?>
