<?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/jquery-smart-wizard/jquery.smartWizard.js.') 
        ; ?>



<style>

.x_panel {
    position: relative;
    width: 100%;
    margin-bottom: 10px;
    padding: 10px 17px;
    display: inline-block;
    background: #fff;
    border: 1px solid #E6E9ED;
    -webkit-column-break-inside: avoid;
    -moz-column-break-inside: avoid;
    column-break-inside: avoid;
    opacity: 1;
    transition: all .2s ease
}

.x_content {
    padding: 0 5px 6px;
    position: relative;
    width: 100%;
    float: left;
    clear: both;
    margin-top: 5px
}
.x_content h4 {
    font-size: 16px;
    font-weight: 500
}

/*a:focus {
    outline: none
}*/
a:hover,
a:focus {
    text-decoration: none;
    outline: none
}


@media (max-width: 1200px) {
    .x_title h2 {
        width: 62%;
        font-size: 17px
    }
    .tile,
    .graph {
        zoom: 85%;
        height: inherit
    }
}
@media (max-width: 1270px) and (min-width: 192px) {
    .x_title h2 small {
        display: none
    }
}

.x_title {
    border-bottom: 2px solid #E6E9ED;
    padding: 1px 5px 6px;
    margin-bottom: 10px
}
.x_title .filter {
    width: 40%;
    float: right
}
.x_title h2 {
    margin: 5px 0 6px;
    float: left;
    display: block;
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap
}
.x_title h2 small {
    margin-left: 10px
}
.x_title span {
    color: #BDBDBD
}

.dashboard_graph .x_title {
    padding: 5px 5px 7px
}
.dashboard_graph .x_title h3 {
    margin: 0;
    font-weight: normal
}

.clearfix:after,
form:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden
}

.form_wizard .stepContainer {
    display: block;
    position: relative;
    margin: 0;
    padding: 0;
    border: 0 solid #CCC;
    overflow-x: hidden
}
.wizard_horizontal ul.wizard_steps {
    display: table;
    list-style: none;
    position: relative;
    width: 100%;
    margin: 0 0 20px
}
.wizard_horizontal ul.wizard_steps li {
    display: table-cell;
    text-align: center
}
.wizard_horizontal ul.wizard_steps li a,
.wizard_horizontal ul.wizard_steps li:hover {
    display: block;
    position: relative;
    -moz-opacity: 1;
    filter: alpha(opacity=100);
    opacity: 1;
    color: #666
}
.wizard_horizontal ul.wizard_steps li a:before {
    content: "";
    position: absolute;
    height: 4px;
    background: #ccc;
    top: 20px;
    width: 100%;
    z-index: 4;
    left: 0
}
.wizard_horizontal ul.wizard_steps li a.disabled .step_no {
    background: #ccc
}
.wizard_horizontal ul.wizard_steps li a .step_no {
    width: 40px;
    height: 40px;
    line-height: 40px;
    border-radius: 100px;
    display: block;
    margin: 0 auto 5px;
    font-size: 16px;
    text-align: center;
    position: relative;
    z-index: 5
}
.wizard_horizontal ul.wizard_steps li a.selected:before,
.step_no {
    background: #34495E;
    color: #fff
}
.wizard_horizontal ul.wizard_steps li a.done:before,
.wizard_horizontal ul.wizard_steps li a.done .step_no {
    background: #1ABB9C;
    color: #fff
}
.wizard_horizontal ul.wizard_steps li:first-child a:before {
    left: 50%
}
.wizard_horizontal ul.wizard_steps li:last-child a:before {
    right: 50%;
    width: 50%;
    left: auto
}
.wizard_verticle .stepContainer {
    width: 80%;
    float: left;
    padding: 0 10px
}
.actionBar {
    width: 100%;
    border-top: 1px solid #ddd;
    padding: 10px 5px;
    text-align: right;
    margin-top: 10px
}
.actionBar .buttonDisabled {
    cursor: not-allowed;
    pointer-events: none;
    opacity: .65;
    filter: alpha(opacity=65);
    box-shadow: none
}
.actionBar a {
    margin: 0 3px
}
.wizard_verticle .wizard_content {
    width: 80%;
    float: left;
    padding-left: 20px
}
.wizard_verticle ul.wizard_steps {
    display: table;
    list-style: none;
    position: relative;
    width: 20%;
    float: left;
    margin: 0 0 20px
}
.wizard_verticle ul.wizard_steps li {
    display: list-item;
    text-align: center
}
.wizard_verticle ul.wizard_steps li a {
    height: 80px
}
.wizard_verticle ul.wizard_steps li a:first-child {
    margin-top: 20px
}
.wizard_verticle ul.wizard_steps li a,
.wizard_verticle ul.wizard_steps li:hover {
    display: block;
    position: relative;
    -moz-opacity: 1;
    filter: alpha(opacity=100);
    opacity: 1;
    color: #666
}
.wizard_verticle ul.wizard_steps li a:before {
    content: "";
    position: absolute;
    height: 100%;
    background: #ccc;
    top: 20px;
    width: 4px;
    z-index: 4;
    left: 49%
}
.wizard_verticle ul.wizard_steps li a.disabled .step_no {
    background: #ccc
}
.wizard_verticle ul.wizard_steps li a .step_no {
    width: 40px;
    height: 40px;
    line-height: 40px;
    border-radius: 100px;
    display: block;
    margin: 0 auto 5px;
    font-size: 16px;
    text-align: center;
    position: relative;
    z-index: 5
}
.wizard_verticle ul.wizard_steps li a.selected:before,
.step_no {
    background: #34495E;
    color: #fff
}
.wizard_verticle ul.wizard_steps li a.done:before,
.wizard_verticle ul.wizard_steps li a.done .step_no {
    background: #1ABB9C;
    color: #fff
}
.wizard_verticle ul.wizard_steps li:first-child a:before {
    left: 49%
}
.wizard_verticle ul.wizard_steps li:last-child a:before {
    left: 49%;
    left: auto;
    width: 0
}
.form_wizard .loader {
    display: none
}
.form_wizard .msgBox {
    display: none
}

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}




</style>

<script>


function init_SmartWizard() {
	
	if( typeof ($.fn.smartWizard) === 'undefined'){ return; }
	console.log('init_SmartWizard');
	
	$('#wizard').smartWizard();

	$('#wizard_verticle').smartWizard({
	  transitionEffect: 'slide',
          autoAdjustHeight:true,
          toolbarSettings: {
                toolbarPosition: 'top', // none, top, bottom, both
                toolbarButtonPosition: 'right', // left, right
                showNextButton: true, // show/hide a Next button
                showPreviousButton: true, // show/hide a Previous button
                toolbarExtraButtons: [
			$('<button></button>').text('Finish')
					      .addClass('btn btn-info')
					      .on('click', function(){ 
						alert('Finsih button click');                            
					      }),
			$('<button></button>').text('Cancel')
					      .addClass('btn btn-danger')
					      .on('click', function(){ 
						alert('Cancel button click');                            
					      })
                      ]
            }, 
          
	});

//	$('.buttonNext').addClass('btn btn-success');
//	$('.buttonPrevious').addClass('btn btn-primary');
//	$('.buttonFinish').addClass('btn btn-default');
	
};
	   
$(document).ready(function() {
			
	init_SmartWizard();
        
        $('#gestionado').click(function(){
            if (this.checked) {
              $('.grid-caudal').css('display','block');
            }
            else {
               $('.grid-caudal').css('display','none');
            }
            });
            $('#is-backup').click(function(){
            if (this.checked) {
              $('#circuit-backup').css('display','block');
            }
            else {
               $('#circuit-backup').css('display','none');
            }
            });
            $('#gestionado-backup').click(function(){
            if (this.checked) {
              $('.grid-caudal-backup').css('display','block');  
//              $('.stepContainer').css('height','1200px');
              $('.stepContainer').css('color','red');
            }
            else {
               $('.grid-caudal-backup').css('display','none');
            }
        });
});	
</script>


<div class="inner">
    
    <div class="x_panel">
        <div class="x_title">
            <h2> Alta de Planta<small> :: </small></h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <!-- Smart Wizard -->
            <div id="wizard" class="form_wizard wizard_horizontal">
                <ul class="wizard_steps">
                    <li>
                        <a href="#step-1">
                            <span class="step_no">1</span>
                            <span class="step_descr">
                                
                                <small>Sede&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#step-2">
                            <span class="step_no">2</span>
                            <span class="step_descr">
                                
                                <small>Circuito&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#step-3">
                            <span class="step_no">3</span>
                            <span class="step_descr">
                                Equipo <br/>
                                <small>Gestionado</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#step-4">
                            <span class="step_no">4</span>
                            <span class="step_descr">
                                Equipo <br/>
                                <small>No Gestionado</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#step-5">
                            <span class="step_no">5</span>
                            <span class="step_descr">
                                Direccionamiento <br/>
                                <small>WAN</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#step-6">
                            <span class="step_no">6</span>
                            <span class="step_descr">
                                Direccionamiento <br/>
                                <small>LAN</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#step-7">
                            <span class="step_no">7</span>
                            <span class="step_descr">
                                Hardware <br/>
                                <small>Adicional</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#step-8">
                            <span class="step_no">8</span>
                            <span class="step_descr">
                                Hardware <br/>
                                <small>RPV 13918</small>
                            </span>
                        </a>
                    </li>
                    
                </ul>
                <div id="step-1">


<div class="panel panel-default">
    <!--<div class="panel-heading">Fieldset Example</div>-->
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>SEDE</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                <div class="col-lg-6">    
                    
                    <form> 
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nombre</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingresa el nombre de la sede">
                        </div>
                        
                        <div class="form-group">
                            <label for="exampleInputEmail1">Idescat</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                            <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
                        </div>

                        <div class="form-group">
                            <label for="exampleTextarea">Dirección</label>
                            <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
                        </div>
                        
                        
<!--                        <div class="form-group">
                          <label for="exampleInputPassword1">Password</label>
                          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>-->
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Población</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Badalona</option>
                                <option>Rubi</option>
                                <option>Terrassa</option>
                                <option>Sabadell</option>
                                <option>Granollers</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Provincia</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Barcelona</option>
                                <option>Tarragona</option>
                                <option>Lérida</option>
                                <option>Gerona</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Horario</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>


<!--                        <div class="form-group">
                          <label for="exampleSelect2">Example multiple select</label>
                          <select multiple class="form-control" id="exampleSelect2">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                          </select>
                        </div>-->
                        
                    
                </div>    
                    
                <div class="col-lg-6">    
                        
<!--                        <div class="form-group">
                          <label for="exampleInputFile">File input</label>
                          <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                          <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
                        </div>-->

                        <div class="form-group">
                            <label for="exampleInputEmail1">Contacto</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Teléfono</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>

                        <div class="form-group">
                            <label for="exampleTextarea">Observaciones</label>
                            <textarea class="form-control" id="exampleTextarea" rows="6"></textarea>
                        </div>

                        <fieldset class="form-group">
                          <legend>Mapa de Red</legend>
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                
                        </fieldset>    



                        <!--<div class="clearfix"></div>-->

<!--                        <fieldset class="form-group">
                          <legend>Radio buttons</legend>
                          <div class="form-check">
                            <label class="form-check-label">
                              <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                              Option one is this and that&mdash;be sure to include why it's great
                            </label>
                          </div>
                          <div class="form-check">
                          <label class="form-check-label">
                              <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                              Option two can be something else and selecting it will deselect option one
                            </label>
                          </div>
                          <div class="form-check disabled">
                          <label class="form-check-label">
                              <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios3" value="option3" disabled>
                              Option three is disabled
                            </label>
                          </div>
                        </fieldset>
                        <div class="form-check">
                            <label class="form-check-label">
                              <input type="checkbox" class="form-check-input">
                              Check me out
                            </label>
                        </div>-->

                        <button type="submit" class="btn btn-primary">IMG:Upload images</button>
                        
                    </form>
                    
                </div>    
                
                </div>
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>

                    
<!--                    <form class="form-horizontal form-label-left">
                        <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nombre <span class="required"></span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Idescat <span class="required"></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Contacto</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="middle-name" class="form-control col-md-7 col-xs-12" type="text" name="middle-name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Teléfono</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="middle-name" class="form-control col-md-7 col-xs-12" type="text" name="middle-name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Date Of Birth <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="birthday" class="date-picker form-control col-md-7 col-xs-12" required="required" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">GLAN?</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="gender" class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input type="radio" name="gender" value="male"> &nbsp; Si &nbsp;
                                    </label>
                                    <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input type="radio" name="gender" value="female"> No
                                    </label>
                                </div>
                            </div>
                        </div>
                    </form>-->

                </div>
                <div id="step-2">
                    
                    
<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>CIRCUITO</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        <form> 
                            <div class="form-group">
                                <label for="exampleInputEmail1">Administrativo</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Teléfono</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Cliente</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>Ajuntament de Baga</option>
                                    <option>Ajuntament de El Brull</option>
                                    <option>Ajuntament de Calonge de Segarra</option>
                                    <option>Diputacion de Barcelona</option>
                                    <option>Serveis Municipal de Montseny S.L.</option>
                                    <option>Xarxa Audiovisual Local</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Tecnología</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>FO</option>
                                    <option>FTTH</option>
                                    <option>xDSL</option>
                                    <option>UMTS</option>
                                    <option>LTE</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Velocidad</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>10MB</option>
                                    <option>100MB</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Criticidad</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>Crítica</option>
                                    <option>Normal</option>
                                </select>
                            </div>

                            <div class="form-check">
                                <label class="form-check-label">
                                  <input id="is-backup" type="checkbox" class="form-check-input">
                                  ¿Tiene Backup?
                                </label>
                            </div>                        

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Factura</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>AB-526389</option>
                                <option>HB-958777</option>
                                <option>GG-956857</option>
                                <option>KJ-525689</option>
                                <option>PL-955577</option>
                                <option>XC-922877</option>    
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Estado</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Pre-Alta</option>
                                <option>Alta</option>
                            </select>
                        </div>
                    
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                  <input type="checkbox" id="gestionado" class="form-check-input">
                                  ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal" style="display: none;">
                            <button type="submit" class="btn btn-primary" style="float: right; margin-left: 2px; margin-right: 14px;">IMG:Delete</button>
                            <button type="submit" class="btn btn-primary" style="float: right;">IMG:Add</button>
                            <div class="panel-body">

                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th><input type="checkbox" id="" class="form-check-input"></th>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Unidad</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><input type="checkbox" id="" class="form-check-input"></td>
                                            <td>Oro</td>
                                            <td>60</td>
                                            <td>
                                                <select class="form-control" id="exampleSelect1">
                                                    <option selected="">Mb</option>
                                                    <option>%</option>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><input type="checkbox" id="" class="form-check-input"></td>
                                            <td>Plata</td>
                                            <td>30</td>
                                            <td>
                                                <select class="form-control" id="exampleSelect1">
                                                    <option selected="">Mb</option>
                                                    <option>%</option>
                                                </select>
                                            </td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                        
                        
                    </div>    
                
                </div>
                
                <!-- SET CIRCUIT BACKUP -->
                
<!--<div class="panel panel-default">-->
    <div id="circuit-backup" class="panel-body" style="display:none;">
        <fieldset class="col-md-12">    	
            <legend>CIRCUITO BACKUP</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        <form> 
                            <div class="form-group">
                                <label for="exampleInputEmail1">Administrativo</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Teléfono</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Cliente</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>Ajuntament de Baga</option>
                                    <option>Ajuntament de El Brull</option>
                                    <option>Ajuntament de Calonge de Segarra</option>
                                    <option>Diputacion de Barcelona</option>
                                    <option>Serveis Municipal de Montseny S.L.</option>
                                    <option>Xarxa Audiovisual Local</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Tecnología</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>FO</option>
                                    <option>FTTH</option>
                                    <option>xDSL</option>
                                    <option>UMTS</option>
                                    <option>LTE</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Velocidad</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>10MB</option>
                                    <option>100MB</option>
                                </select>
                            </div>

                            <div class="form-group">
                            <label for="exampleSelect1">Estado</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Pre-Alta</option>
                                <option>Alta</option>
                            </select>
                        </div>    
                            
                                  

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        
                    
                    
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                  <input type="checkbox" id="gestionado-backup" class="form-check-input">
                                  ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal-backup" style="display: none;">
                            <button type="submit" class="btn btn-primary" style="float: right; margin-left: 2px; margin-right: 14px;">IMG:Delete</button>
                            <button type="submit" class="btn btn-primary" style="float: right;">IMG:Add</button>
                            <div class="panel-body">

                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th><input type="checkbox" id="" class="form-check-input"></th>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Unidad</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><input type="checkbox" id="" class="form-check-input"></td>
                                            <td>Bronce</td>
                                            <td>60</td>
                                            <td>
                                                <select class="form-control" id="exampleSelect1">
                                                    <option>Mb</option>
                                                    <option selected="">%</option>
                                                </select>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                        
                        
                    </div>    
                
                </div>
                
                <!-- Set -->
                
                
                
                
                
                
                
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
<!--</div>-->                
                
                
                
                
                
                <!-- SET -->
                
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>                
                
                
                
                
                
                </div>
                <div id="step-3">
                    <h2 class="StepTitle">Step 3 Content</h2>
                    <p>
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
                        eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                <div id="step-4">
                    <h2 class="StepTitle">Step 4 Content</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                <div id="step-5">
                    <h2 class="StepTitle">Step 5 Content</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                
                <div id="step-6">
                    <h2 class="StepTitle">Step 6 Content</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                
                <div id="step-7">
                    <h2 class="StepTitle">Step 7 Content</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                
                <div id="step-8">
                    <h2 class="StepTitle">Step 8 Content</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                
                
                
                
                
                
            </div>
            <!-- End SmartWizard Content -->
        </div>
    </div>

</div>