<?php
    use Zend\Session\Container;
    $session = new Container('User');
    $userRole = $session->offsetGet('userRole');
?>
<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function deleteHa() {
    
    $('#deleteHa').modal('hide');
    var url = '<?= $this->url('delete-ha'); ?>';
    var id = $('#deleteHaId').val();
    
    var equipoId = $('#equipoId').val();
    var equipoBckId = $('#equipoBckId').val();
    var data = {id: id, equipoId: equipoId, equipoBckId:equipoBckId};

    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            $("#ipwan-fill").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}
    



function updateHa() {

    var url = '<?= $this->url('save-ha'); ?>'; 
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                $("#grid-ha-fill").html(json);
                $('.update-ha').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}




function addHa() {

    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();

    var data = {id: id, idbck: idbck};
    var url = '<?= $this->url('add-ha'); ?>';
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (json) {
            $("#ipwanone-fill").html(json);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}

//function updateAP() {
//
//    var url = '<?= $this->url('update-ap'); ?>';
//    $.ajax({
//       type: "POST",
//       url: url,
//       data: $('#myForm').serialize(),
//       cache: false,
//       success: function (json) {
//                $("#save-ap").html(json);
////                $('.save-ipwan').addClass('disabled');
//        },
//        error: function (xhr, status) {
//            html = "<div class='alert alert-danger'>Error!</div>"
//            $("#box").html(html);
//        }
//    });
//
//}


    

function haoneFill(id) {
    
    var data = {id: id, view: 1};
    var    url = '<?= $this->url('haone-fill'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwanone-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}







$(function(){
    
    $('#grid-ha tbody tr').click(function(){
        
        $("#grid-ha tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

    $('#deleteHa').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        $('#deleteHaId').val(id);
    })

    $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });

});

</script>
<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">
            <legend>AP</legend>
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="col-lg-6">
                        <input type="hidden" id="apEquipoId" name="apEquipoId" value="<?= $this->information['aps']['0']['id']; ?>">
                        <div class="form-group">
                            <label class="control-label" for="switch">Switch</label>
                            <?php $form->get('apswitch')->setValue($this->information['aps']['0']['switchId']); ?>
                            <?= $this->formSelect($form->get('apswitch')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="contrato-extreme">Contrato Extreme</label>
                            <?php $form->get('apcontratoextreme')->setValue($this->information['aps']['0']['contrato_extreme']); ?>
                            <?= $this->formInput($form->get('apcontratoextreme')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ap-nombre">Nombre</label>
                            <?php $form->get('apnombre')->setValue($this->information['aps']['0']['nombre']); ?>
                            <?= $this->formInput($form->get('apnombre')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ap-ipcliente">IP Cliente</label>
                            <?php $form->get('apipcliente')->setValue($this->information['aps']['0']['ip_cliente']); ?>
                            <?= $this->formInput($form->get('apipcliente')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ap-idap">ID AP</label>
                            <?php $form->get('apidap')->setValue($this->information['aps']['0']['id_ap']); ?>
                            <?= $this->formInput($form->get('apidap')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ap-red">Red</label>
                            <table id="grid-red-ap" class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width:45%;">SSID</th>
                                        <th style="width:5%;">Act.</th>
                                        <th style="width:45%;">SSID</th>
                                        <th style="width:5%;">Act.</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                        $esIntCorp = (int)$this->information['aps']['0']['es_internet_corporatiu'];
                                        $esIntVisi = (int)$this->information['aps']['0']['es_internet_visites'];
                                        $esDibaInt = (int)$this->information['aps']['0']['es_diba_intern'];
                                        $esEspai = (int)$this->information['aps']['0']['es_espai_f_b'];
                                        $esPda = (int)$this->information['aps']['0']['es_pda_pavnord'];
                                        $esEscDona = (int)$this->information['aps']['0']['es_multimedia_escola_dona'];
                                        $esPalauguell = (int)$this->information['aps']['0']['es_palauguell'];
                                        $esResResp = (int)$this->information['aps']['0']['es_resident_respir'];
                                     ?>
                                    <tr class="row-input">
                                        <td>Internet_corporatiu</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="apinetcorp" name="apinternetcorporatiu" value="1" class="form-check-input" <?= ($esIntCorp)?'checked':''; ?>>
                                        </td>
                                        <td>Internet_visites</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="apinternetvisites" name="apinternetvisites" value="1" class="form-check-input" <?= ($esIntVisi)?'checked':''; ?>>
                                        </td>
                                    </tr>
                                    <tr class="row-input">
                                        <td>Diba_intern</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="apdibaintern" name="apdibaintern" value="1" class="form-check-input" <?= ($esDibaInt)?'checked':''; ?>>
                                        </td>
                                        <td>Espai F.B</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="apespaifb" name="apespaifb" value="1" class="form-check-input" <?= ($esEspai)?'checked':''; ?>>
                                        </td>
                                    </tr>
                                    <tr class="row-input">
                                        <td>PDA_PavNord</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="appdapavnord" name="appdapavnord" value="1" class="form-check-input" <?= ($esPda)?'checked':''; ?>>
                                        </td>
                                        <td>Multimedia_Escola_Dona</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="apmultimediaescoladona" name="apmultimediaescoladona" value="1" class="form-check-input" <?= ($esEscDona)?'checked':''; ?>>
                                        </td>
                                    </tr>
                                    <tr class="row-input">
                                        <td>PalauGuell</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="appalauguell" name="appalauguell" value="1" class="form-check-input" <?= ($esPalauguell)?'checked':''; ?>>
                                        </td>
                                        <td>Resident_Respir</td>
                                        <td style="text-align:center;">
                                            <input type="checkbox" id="apresidentrespir" name="apresidentrespir" value="1" class="form-check-input" <?= ($esResResp)?'checked':''; ?>>
                                        </td>
                                    </tr>


                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-lg-6">    

                        <div class="form-group">
                            <label class="control-label" for="ap-actividad-tsol">Actividad TSOL</label>
                            <?php $form->get('apactividadtsol')->setValue($this->information['aps']['0']['actividad_tsol']); ?>
                            <?= $this->formInput($form->get('apactividadtsol')); ?>
                        </div>                                    

                        <div class="form-group">
                            <label class="control-label" for="ap-modelo">Módelo</label>
                            <?php $form->get('apmodelo')->setValue($this->information['aps']['0']['modelo']); ?>
                            <?= $this->formInput($form->get('apmodelo')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ap-mac">MAC</label>
                            <?php $form->get('apmac')->setValue($this->information['aps']['0']['mac']); ?>
                            <?= $this->formInput($form->get('apmac')); ?>
                        </div>                                                    

                        <div class="form-group">
                            <label class="control-label" for="ap-criticidad">Criticidad</label>
                            <?php $form->get('apcriticidad')->setValue($this->information['aps']['0']['criticidadId']) ?>
                            <?= $this->formSelect($form->get('apcriticidad')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ap-estado">Estado</label>
                            <?php $form->get('apestado')->setValue($this->information['aps']['0']['estadoId']) ?>
                            <?= $this->formSelect($form->get('apestado')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="glan-observaciones">Observaciones</label>
                            <?php $form->get('apobservacion')->setValue($this->information['aps']['0']['observaciones']) ?>    
                            <?= $this->formTextarea($form->get('apobservacion')); ?>
                        </div>

                        <div style="float:right; margin-top: 20px;">
                            <?php if('Administrador' == $userRole || 'Operador' == $userRole || 'Ingeniero' == $userRole) : ?>
                            <a class="btn btn-primary btn-sm update-sede" href="#" role="button" onclick="updateAp();" title="Update AP">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                            <?php endIf; ?>
                        </div>
                    </div>    
                </div>
            </div>
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>            
