<?php
    use Zend\Session\Container;
    $session = new Container('User');
    $userRole = $session->offsetGet('userRole');
?>
<script>
$(function(){

   $('#grid-equipos tbody tr').click(function(){
        
        $("#grid-equipos tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

});
</script>

<input type="hidden" id="deleteEquipoNotManagementId" name="deleteEquipoNotManagementId" value="">
<input type="hidden" id="deleteEquipoNotManagementSedeId" name="deleteEquipoNotManagementSedeId" value="<?= $this->information['sede']['id'] ;?>">
<?php
    $equiposNoGestionadosNumber = 0;
    if(isset($this->information['notequiposall'])) {
        $equiposNoGestionadosNumber = count($this->information['notequiposall']);
    }
?>
<div style="float:left;">
    <button type="button" class="btn btn-primary" title="Número de equipos no gestionados"><?= '# ' . $equiposNoGestionadosNumber; ?></button>
</div>                    
<div style="float:right;">
    <?php if('Administrador' == $userRole || 'Operador' == $userRole || 'Ingeniero' == $userRole) : ?>
    <a class="btn btn-primary btn-sm" href="<?= $this->url('wizard') . '/'. $sedeId; ?>/3" role="button" title="Agregar equipo no gestionado">
        <i class="glyphicon glyphicon-plus"></i>
    </a>
    <?php endIf; ?>
</div>
<div style="clear: both;"></div>

<div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
                 
                <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Propiedad Router</th>
                            <th>Tipo IP</th>
                            <th>IP Cliente</th>
                            <th>Red</th>
                            <th>Usos</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $row = 1; ?>
                        <?php foreach($this->information['notequiposall'] as $notequipo) : ?> 
                        <tr id="<?= $notequipo['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                            <td><?= $notequipo['propiedad'] ?></td>
                            <td><?= $notequipo['tipo'] ?></td>
                            <td><?= $notequipo['ip'] ?></td>
                            <td><?= $notequipo['red'] ?></td>
                            <td><?= $notequipo['uso'] ?></td>
                            <td> 
                                <a class="btn btn-primary btn-xs" href="#" onclick="notequipoFill('<?= $this->sedeId; ?>', '<?= $notequipo['id'] ?>');" title="Consultar equipo">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                                <?php if('Administrador' == $userRole || 'Operador' == $userRole || 'Ingeniero' == $userRole) : ?>
                                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo no gestionado" data-toggle="modal" data-id="<?= $notequipo['id']; ?>" data-target="#deleteEquipoNotManagement">    
                                    <i class="glyphicon glyphicon-minus"></i>
                                </a>
                                <?php endIf; ?>
                            </td>  
                        </tr>
                        <?php $row++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div style="clear: both;"></div>

    <?php if(isset($this->information['notequipos']['0'])) : ?>        
              
        <div id="equipo-not-fill">
        
        <div class="panel panel-default">
            <div class="panel-body">        
        
                <fieldset class="col-md-12">    	
                <legend>EQUIPO NO GESTIONADO</legend>
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="col-lg-6">    
                            <div id="form-step-3" role="form" data-toggle="validator">
                                
                                <div class="form-group">
                                    <label class="control-label" for="circuito">Circuito</label>
                                    <?= $this->information['htmlcombobox2']['0']; ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="engservicio">Servicio</label>
                                    <?php $form->get('engservicio')->setValue($this->information['notequipos']['0']['servicio_id']) ?>
                                    <?= $this->formSelect($form->get('engservicio')); ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="engpropiedad">Propiedad Router</label>
                                    <?php $form->get('engpropiedad')->setValue($this->information['notequipos']['0']['propiedad_id']) ?>
                                    <?= $this->formSelect($form->get('engpropiedad')); ?>
                                </div>                        

                                <div class="form-group">
                                    <label class="control-label" for="tipo-ip">Tipo IP</label>
                                    <?php $form->get('engtipoip')->setValue($this->information['notequipos']['0']['tipo_ip']) ?>
                                    <?= $this->formSelect($form->get('engtipoip')); ?>                            
                                </div>                        

                                <div class="form-group">
                                    <label class="control-label" for="ip-no-gestionado">IP</label>
                                    <?php $form->get('engip')->setValue($this->information['notequipos']['0']['ip']) ?>
                                    <?= $this->formInput($form->get('engip')); ?>
                                </div>
                        
                                <div class="form-group">
                                    <label class="control-label" for="red">Red</label>
                                    <?php $form->get('engred')->setValue($this->information['notequipos']['0']['red_id']) ?>
                                    <?= $this->formSelect($form->get('engred')); ?>                                
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="usos">Usos</label>
                                    <?php $form->get('enguso')->setValue($this->information['notequipos']['0']['uso_id']) ?>    
                                    <?= $this->formSelect($form->get('enguso')); ?>                            
                                </div>
                            
                            </div>
                        </div>    
                    
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-no-gestionado">Contacto</label>
                            <?php $form->get('engcontacto')->setValue($this->information['notequipos']['0']['contacto']) ?>
                            <?= $this->formInput($form->get('engcontacto')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="telefono-no-gestionado">Teléfono</label>
                            <?php $form->get('engtelefono')->setValue($this->information['notequipos']['0']['telefono']) ?>
                            <?= $this->formInput($form->get('engtelefono')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="horario-no-gestionado">Horario</label>
                            <?php $form->get('enghorario')->setValue($this->information['notequipos']['0']['horario']) ?>
                            <?= $this->formInput($form->get('enghorario')); ?>
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="observacion-no-gestionado">Observaciones</label>
                            <?php $form->get('engobservacion')->setValue($this->information['notequipos']['0']['observacion']) ?>    
                            <?= $this->formTextarea($form->get('engobservacion')); ?>
                        </div>
                        
                    </div>    
                
                </div>

            </div>

            <div class="clearfix"></div>

            <div style="float:right; padding-top: 14px; padding-bottom: 14px;">
                <?php if('Administrador' == $userRole || 'Operador' == $userRole || 'Ingeniero' == $userRole) : ?>
                <a class="btn btn-primary btn-sm update-notequipo" href="#" role="button" onclick="updateNotEquipos();" title="Update equipo no gestionado">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
                <?php endIf; ?>
            </div>     

        </fieldset>				

    </div>
    </div>        
            
        <input type="hidden" id="notEquipoId" name="notEquipoId" value="<?=  $this->information['notequipos']['0']['id']; ?>">
        <input type="hidden" id="notEquipoContactoId" name="notEquipoContactoId" value="<?=  $this->information['notequipos']['0']['contacto_id']; ?>">
          
    </div>        
            
            
    <?php endif; ?>        
            

            
            
