<script>
$(function(){

//    $(".btn-pref .btn").click(function () {
//        $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
//        // $(".tab").addClass("active"); // instead of this do the below 
//        $(this).removeClass("btn-default").addClass("btn-primary");   
//    });
//

    if($('#cgestionado').prop('checked')) {
        $('.grid-caudal').css('display','block');
    }
    
    $('#cgestionado').click(function(){

      if (this.checked) {
          $('.grid-caudal').css('display','block');
      }
      else {
          
           $('.grid-caudal').css('display','none');
      }

    });
    
    if($('#cbackup').prop('checked')) {
        $('#circuit-backup').css('display','block');
    }
    
    $('#cbackup').click(function(){

      if (this.checked) {
          $('#circuit-backup').css('display','block');
      }
      else {
          
           $('#circuit-backup').css('display','none');
      }

    });

    if($('#bcgestionado').prop('checked')) {
        $('.grid-caudal-backup').css('display','block');
    }

    
    $('#bcgestionado').click(function(){

      if (this.checked) {
          $('.grid-caudal-backup').css('display','block');
      }
      else {
          
           $('.grid-caudal-backup').css('display','none');
      }

    });

});
</script>


<input type="hidden" id="circuitoId" name="circuitoId" value="<?= $this->information['circuitos']['0']['id']; ?>">
<?php if(isset($this->information['circuitos']['1']['id'])) : ?>
    <input type="hidden" id="circuitoBackupId" name="circuitoBackupId" value="<?= $this->information['circuitos']['1']['id']; ?>">
<?php endif ; ?>


<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>CIRCUITO</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-lg-6">    
                        <div class="form-group">
                            <label for="exampleInputEmail1">Administrativo</label>
                            <?php $form->get('cadministrativo')->setValue($this->information['circuitos']['0']['administrativo']) ?>
                            <?= $this->formInput($form->get('cadministrativo')); ?>

                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Teléfono</label>
                            <?php $form->get('ctelefono')->setValue($this->information['circuitos']['0']['telefono']) ?>
                            <?= $this->formInput($form->get('ctelefono')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Cliente</label>
                            <?php $form->get('ccliente')->setValue($this->information['circuitos']['0']['clienteId']) ?>
                            <?= $this->formSelect($form->get('ccliente')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Tecnología</label>
                            <?php $form->get('ctecnologia')->setValue($this->information['circuitos']['0']['tecnologiaId']) ?>
                            <?= $this->formSelect($form->get('ctecnologia')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Velocidad</label>
                            <?php $form->get('cvelocidad')->setValue($this->information['circuitos']['0']['velocidadId']) ?>
                            <?= $this->formSelect($form->get('cvelocidad')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Criticidad</label>
                            <?php $form->get('ccriticidad')->setValue($this->information['circuitos']['0']['criticidadId']) ?>
                            <?= $this->formSelect($form->get('ccriticidad')); ?>
                        </div>

                        <div class="form-check">
                            <label class="form-check-label"> 
                                <?php $backup = $this->information['circuitos']['0']['tiene_backup']; ?>
                              <input id="cbackup" name="cbackup" type="checkbox" value="1" class="form-check-input" <?= ($backup)?'checked':'' ?>>
                              ¿Tiene Backup?
                            </label>
                        </div>                        

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Factura</label>
                            <?php $form->get('cfactura')->setValue($this->information['circuitos']['0']['facturaId']) ?>
                            <?= $this->formSelect($form->get('cfactura')); ?>                        
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Estado</label>
                            <?php $form->get('cestado')->setValue($this->information['circuitos']['0']['estadoId']) ?>
                            <?= $this->formSelect($form->get('cestado')); ?>
                        </div>
                    
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <?php $esGestionado = $this->information['circuitos']['0']['es_gestionado']; ?>
                                    <input type="checkbox" id="cgestionado" value="1" name="cgestionado" class="form-check-input" <?= ($esGestionado)?'checked':'' ?>>
                                    ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal" style="display: none;">
                            
                            <button id="add" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right;  margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                            
                            <div style="clear:both;"></div>
                            <div class="panel-body">

                                <table id="grid-caudal" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Unidad</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->information['caudales']['principal'])) : ?>
                                            <?php $cont = 1; ?>
                                            <?php foreach($this->information['caudales']['principal'] as $item) : ?>

                                                <tr class="row-input">
                                                    <td><input name="caudal-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['caudal']  ?>" /></td>
                                                    <td><input name="cantidad-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['cantidad']  ?>" /></td>
                                                    <td><select name="unidad-<?= $cont?>" class="col-xs-20" id="exampleSelect1">
                                                            <option value="1" <?= ('1'==$item['unidad'])?'selected':'' ?>>Mb</option>
                                                            <option value="2" <?= ('2'==$item['unidad'])?'selected':'' ?>>%</option></select></td>
                                                    <td>
                                                        <!--<input type="button" class="borrar" value="Eliminar" />-->
                                                        <a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar">
                                                            <i class="glyphicon glyphicon-minus"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                                <?php $cont++; ?>
                                            <?php endforeach; ?>
                                        <?php endif; ?>            
                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                    </div>    
                </div>
                
                <!-- SET CIRCUIT BACKUP -->
                
        <!--<div class="panel panel-default">-->
    <div id="circuit-backup" class="panel-body" style="display:none;">
        <fieldset class="col-md-12">    	
            <legend>CIRCUITO BACKUP</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        
                            <div class="form-group">
                                <label for="exampleInputEmail1">Administrativo</label>
                                <?php   if(isset($this->information['circuitos']['1']['administrativo'])) { 
                                            $form->get('bcadministrativo')->setValue($this->information['circuitos']['1']['administrativo']);
                                        }
                                ?>
                                <?= $this->formInput($form->get('bcadministrativo')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Teléfono</label>
                                <?php   if(isset($this->information['circuitos']['1']['telefono'])) { 
                                            $form->get('bctelefono')->setValue($this->information['circuitos']['1']['telefono']);
                                        }
                                ?>
                                <?= $this->formInput($form->get('bctelefono')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Cliente</label>
                                <?php   if(isset($this->information['circuitos']['1']['clienteId'])) { 
                                            $form->get('bccliente')->setValue($this->information['circuitos']['1']['clienteId']);
                                        }
                                ?>
                                <?= $this->formSelect($form->get('bccliente')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Tecnología</label>
                                <?php   if(isset($this->information['circuitos']['1']['tecnologiaId'])) { 
                                            $form->get('bctecnologia')->setValue($this->information['circuitos']['1']['tecnologiaId']);
                                        }
                                ?>
                                
                                <?= $this->formSelect($form->get('bctecnologia')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Velocidad</label>
                                <?php   if(isset($this->information['circuitos']['1']['velocidadId'])) { 
                                            $form->get('bcvelocidad')->setValue($this->information['circuitos']['1']['velocidadId']);
                                        }
                                ?>
                                
                                <?= $this->formSelect($form->get('bcvelocidad')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Estado</label>
                                <?php   if(isset($this->information['circuitos']['1']['estadoId'])) { 
                                            $form->get('bcestado')->setValue($this->information['circuitos']['1']['estadoId']);
                                        }
                                ?>
                                
                                <?= $this->formSelect($form->get('bcestado')); ?>
                            </div>    
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <?php $esBGestionado = 0;  
                                        if(isset($this->information['circuitos']['1']['es_gestionado'])) {
                                            $esBGestionado = $this->information['circuitos']['1']['es_gestionado'];
                                        }
                                    ?>
                                    <input type="checkbox" id="bcgestionado" name="bcgestionado" value="1" class="form-check-input" <?= ($esBGestionado)?'checked':'' ?>>
                                  ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal-backup" style="display: none;">
                            <!--<button id="add-backup" type="button" class="btn btn-primary btn-sm" style="float: right;">IMG:Add</button>-->
                            <button id="add-backup" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right; margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                            <div style="clear:both;"></div>
                            <div class="panel-body">

                                <table id="backup" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Unidad</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $cont = 1; ?>
                                        <?php foreach($this->information['caudales']['backup'] as $item) : ?>
.                                            <tr class="row-input">
                                                <td><input name="caudalbck-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['caudal']  ?>" /></td>
                                                <td><input name="cantidadbck-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['cantidad']  ?>" /></td>
                                                <td><select name="unidadbck-<?= $cont?>" class="col-xs-20" id="exampleSelect1">
                                                        <option value="1" <?= ('1'==$item['unidad'])?'selected':'' ?>>Mb</option>
                                                        <option value="2" <?= ('2'==$item['unidad'])?'selected':'' ?>>%</option></select></td>
                                                <td>
                                                    <!--<input type="button" class="borrar" value="Eliminar" />-->
                                                    <a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar">
                                                        <i class="glyphicon glyphicon-minus"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php $cont++; ?>
                                        <?php endforeach; ?>                                    
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                    </div>    
                </div>
                
                <!-- Set -->
                
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
<!--</div>-->                
                
                
                
                
                
                <!-- SET -->
                
            </div>
            
            
            
            <div class="clearfix"></div>                
                        
            <div style="float:right; padding-top: 14px; padding-bottom: 14px;">
                <a class="btn btn-primary btn-sm update-circuito" href="#" role="button" onclick="updateCircuitos();" title="Update circuito">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>     
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>          
