<style>
fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>                

<script>

$(function(){

    
    
    
    
    
});

</script>

<div class="panel panel-default">
    <div class="panel-body">
        
        <fieldset class="col-md-12">    	
            <legend>EQUIPO NO GESTIONADO</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                            <div class="form-group">
                                <label class="control-label" for="servicio-no-gestionado">Servicio</label>
                                <select class="form-control input-sm" id="servicio-no-gestionado" name="servicio-no-gestionado" required>
                                    <option value="">Seleccione una opción</option>
                                    <option value="1" selected>Navegación</option>
                                </select>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="propiedad">Propiedad Router</label>
                                <select class="form-control input-sm" id="propiedad" name="propiedad" required>
                                    <option value="">Seleccione una opción</option>
                                    <option value="1">Telefónica</option>
                                    <option value="2">Cliente</option>
                                </select>
                            </div>                        
                            
                            <div class="form-group">
                                <label class="control-label" for="tipo-ip">Tipo IP</label>
                                <select class="form-control input-sm" id="tipo-ip" name="tipo-ip" required>
                                    <option value="">Seleccione una opción</option>
                                    <option value="1">Dinámico</option>
                                    <option value="2">Estático</option>
                                </select>
                            </div>                        

                            <div class="form-group">
                                <label class="control-label" for="ip-no-gestionado">IP</label>
                                <input type="text" class="form-control input-sm" id="ip-no-gestionado" name="ip-no-gestionado" aria-describedby="ip-no-gestionadoHelp" required>
                            </div>
                        
                            <div class="form-group">
                                <label class="control-label" for="red">Red</label>
                                <select class="form-control input-sm" id="red" name="red" required>
                                    <option value="">Seleccione una opción</option>
                                    <option value="1">Xic</option>
                                    <option value="2">Xem</option>
                                    <option value="3">Xal</option>
                                </select>
                                
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="usos">Usos</label>
                                <select class="form-control input-sm" id="usos" name="usos" required>
                                    <option value="">Seleccione una opción</option>
                                    <option value="1">Corporativo</option>
                                    <option value="2">Usuarios</option>
                                    <option value="3">parques</option>
                                </select>
                            </div>
                            
                          

                                          

                    </div>    
                    
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-no-gestionado">Contacto</label>
                            <input type="text" class="form-control input-sm" id="contacto-no-gestionado" name="contacto-no-gestionado">
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="telefono-no-gestionado">Teléfono</label>
                            <input type="text" class="form-control input-sm" id="telefono-no-gestionado" name="telefono-no-gestionado">
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="horario-no-gestionado">Horario</label>
                            <input type="text" class="form-control input-sm" id="horario-no-gestionado" name="horario-no-gestionado">
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="observacion-no-gestionado">Observaciones</label>
                            <textarea class="form-control input-sm" id="observacion-no-gestionado" name="observacion-no-gestionado" rows="5"></textarea>
                        </div>
                        
                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>