<style>
fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 4px;       
    position: relative;
    border-radius:2px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 2px; 
    padding: 2px 2px 2px 4px; 
    background-color: #ffffff;
}
                
</style>                

<script>

$(function(){

    $('#gestionado').click(function(){

      if (this.checked) {
          $('.grid-caudal').css('display','block');
      }
      else {
          
           $('.grid-caudal').css('display','none');
      }

    });
    
    $('#is-backup').click(function(){

      if (this.checked) {
          $('#circuit-backup').css('display','block');
      }
      else {
          
           $('#circuit-backup').css('display','none');
      }

    });

    
    $('#gestionado-backup').click(function(){

      if (this.checked) {
          $('.multicast').css('display','block');
      }
      else {
          
           $('.multicast').css('display','none');
      }

    });
    
    
        
//    $("#boton").on("click",function(){
//	    $("#parrafo").css("color", "#000000");
//    });
    
    

});

</script>

<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">  	
            <legend>Hardware RPV 13918</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Equipo</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>diba-caco</option>
                                <option>diba-saco</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Tarjeta</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>codec</option>
                                <option>decodec</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Fabricante</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Cisco</option>
                                <option>HP</option>
                            </select>
                        </div>

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Modelo</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>AB-526389</option>
                                <option>HB-958777</option>
                                <option>GG-956857</option>
                                <option>KJ-525689</option>
                                <option>PL-955577</option>
                                <option>XC-922877</option>    
                            </select>
                        </div>

                        <div class="form-group">
                                <label for="exampleInputEmail1">N/S</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>                    
                        
                        <div class="form-group">
                                <label for="exampleInputEmail1">Alias</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>                    
                        
                    </div>    
                
                </div>

               
                <div class="panel-body"><!-- INICIO Direccionamiento LAN -->
                    <fieldset class="col-md-12">    	
                        <legend>Direccionamiento LAN</legend>
                        <div class="panel panel-default">
                            <div class="panel-body">

                                <div class="col-lg-6">    

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">VLAN</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP Lan 1</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP Lan 2</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                </div>    

                                <div class="col-lg-6">    

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Máscara</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Interfaz 1</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Interfaz 2</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                </div>    

                            </div>



                        </div>



                    </fieldset>				
                    <div class="clearfix"></div>
                </div> <!-- FIN Direccionamiento LAN  -->
    
                <div class="form-group" style="padding: 14px;">
                    <div class="form-check">
                        <label class="form-check-label">
                          <input type="checkbox" id="gestionado-backup" class="form-check-input">
                          ¿Tiene configuración Multicast?
                        </label>
                    </div>                        
                </div>


                <div class="panel-body multicast" style="display:none;"><!-- INICIO Multicast -->
                    <fieldset class="col-md-12">    	
                        <legend>Multicast</legend>
                        <div class="panel panel-default">
                            <div class="panel-body">

                                <div class="col-lg-6">    

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Red Wan Tunel GRE PPAL </label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP LoppBack GRE</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP EDC Tunel 1</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP ASR PPAL Tunel Oficina</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>                                    
                                    
                                                                        
                                    
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Interfaz Tunel ASR PPAL</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>                        
                                    
                                </div>    

                                <div class="col-lg-6">    

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Red Wan Tunel GRE BCK</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP RP</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP EDC Tunel 2</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">IP ASR BCK Tunel Oficina</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Interfaz Tunel ASR BCK</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la sede">
                                    </div>

                                </div>    

                            </div>



                        </div>



                    </fieldset>				
                    <div class="clearfix"></div>
                </div> <!-- FIN Multicast  -->
    
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>