<style>
fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>                

<script>

$(function(){

    
    
    
    
    
});

</script>

<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>GLAN</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        <div class="form-group">
                            <label class="control-label" for="servicio">Cliente</label>
                            <select class="form-control input-sm" id="servicio" name="servicio" required>
                                <option>Seleccione una opción</option>
                                <option>Macrolan</option>
                                <option>DataInternet</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="nemonico">Actividad TSOL</label>
                            <input type="text" class="form-control" id="nemonico" name="nemonico" aria-describedby="nemonicoHelp" required>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="servicio">Familia Fabricante</label>
                            <select class="form-control input-sm" id="servicio" name="servicio" required>
                                <option>Seleccione una opción</option>
                                <option>Macrolan</option>
                                <option>DataInternet</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="servicio">Modelo Equipo</label>
                            <select class="form-control input-sm" id="servicio" name="servicio" required>
                                <option>Seleccione una opción</option>
                                <option>Macrolan</option>
                                <option>DataInternet</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="nemonico">Nemónico</label>
                            <input type="text" class="form-control" id="nemonico" name="nemonico" aria-describedby="nemonicoHelp" required>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ip-gestion">IP Gestión Cliente</label>
                            <input type="text" class="form-control" id="ip-gestion" name="ip-gestion" aria-describedby="ip-gestionHelp" required>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="ip-gestion">IP Gestión</label>
                            <input type="text" class="form-control" id="ip-gestion" name="ip-gestion" aria-describedby="ip-gestionHelp" required>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="logos-alta">Firmware</label>
                            <input type="text" class="form-control input-sm" id="logos-alta" name="logos-alta" aria-describedby="logos-altaHelp" required>
                        </div>    

                        <div class="form-group">
                            <label class="control-label" for="ubicacion">MAC</label>
                            <input type="text" class="form-control input-sm" id="ubicacion" name="ubicacion" aria-describedby="ubicacionHelp" required>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ubicacion">S/N</label>
                            <input type="text" class="form-control input-sm" id="ubicacion" name="ubicacion" aria-describedby="ubicacionHelp" required>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="ubicacion">Stack</label>
                            <input type="text" class="form-control input-sm" id="ubicacion" name="ubicacion" aria-describedby="ubicacionHelp" required>
                        </div>

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="fabricante">EDC WAN</label>
                            <select class="form-control input-sm" id="fabricante" name="fabricante">
                                <option></option>
                                <option>CISCO</option>
                                <option>Alcatel-Lucent</option>
                                <option>Juniper</option>
                                <option>Huawei</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo">Ubicación</label>
                            <input type="text" class="form-control input-sm" id="contacto-equipo" name="contacto-equipo" aria-describedby="contacto-equipoHelp">
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="estado-equipo">Función</label>
                            <select class="form-control input-sm" id="estado-equipo" name="estado-equipo">
                                <option selected>Pre-Alta</option>
                                <option>Alta</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="estado-equipo">Criticidad</label>
                            <select class="form-control input-sm" id="estado-equipo" name="estado-equipo">
                                <option selected>Pre-Alta</option>
                                <option>Alta</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="estado-equipo">Estado</label>
                            <select class="form-control input-sm" id="estado-equipo" name="estado-equipo">
                                <option selected>Pre-Alta</option>
                                <option>Alta</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo">Contacto</label>
                            <input type="text" class="form-control input-sm" id="contacto-equipo" name="contacto-equipo" aria-describedby="contacto-equipoHelp">
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo">Teléfono</label>
                            <input type="text" class="form-control input-sm" id="contacto-equipo" name="contacto-equipo" aria-describedby="contacto-equipoHelp">
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="observacion-equipo">Observaciones</label>
                            <textarea class="form-control input-sm" id="observacion-equipo" name="observacion-equipo" rows="5"></textarea>
                        </div>
                        
                    </div>    
                
                </div>
                
                <div id="equipo-backup" class="panel-body">
                    <fieldset class="col-md-12">    	
                        <legend>MODULO ADICIONALES</legend>
                        <div class="panel panel-default">
                            <div class="panel-body">

                                <div class="col-lg-6">    

                                    <div class="form-group">
                                        <label class="control-label" for="servicio">Tipo</label>
                                        <select class="form-control input-sm" id="servicio" name="servicio" required>
                                            <option>Seleccione una opción</option>
                                            <option>Macrolan</option>
                                            <option>DataInternet</option>
                                        </select>
                                    </div>
                            
                                    <div class="form-group">
                                        <label class="control-label" for="nemonico">Componente</label>
                                        <input type="text" class="form-control" id="nemonico" name="nemonico" aria-describedby="nemonicoHelp" required>
                                    </div>

                                </div>    
                    
                                <div class="col-lg-6">    

                                    <div class="form-group">
                                        <label class="control-label" for="contacto-equipo">N/S</label>
                                        <input type="text" class="form-control input-sm" id="contacto-equipo" name="contacto-equipo" aria-describedby="contacto-equipoHelp">
                                    </div>

                                </div>    

                            </div> 

                        </div>

                    </fieldset>				
                    <div class="clearfix"></div>
                </div>

            </div>
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>