<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>








$(function(){
    
    
    
});

</script>

<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="haequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="hatipo">Tipo</label>
                <?php $form->get('hatipo')->setValue($this->information['has']['0']['tipo_id']) ?>
                <?= $this->formSelect($form->get('hatipo')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="hafabricante">Fabricante</label>
                <?php $form->get('hafabricante')->setValue($this->information['has']['0']['fabricante_id']) ?>
                <?= $this->formSelect($form->get('hafabricante')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="hamodelo">Modelo</label>
                <?php $form->get('hamodelo')->setValue($this->information['has']['0']['modelo_id']) ?>
                <?= $this->formSelect($form->get('hamodelo')); ?>
            </div>
        </div>    

        <div class="col-lg-6">
                    
                    <div class="form-group">
                        <label class="control-label" for="haserie">N/S</label>
                        <?php $form->get('haserie')->setValue($this->information['has']['0']['serie']) ?>
                        <?= $this->formInput($form->get('haserie')); ?>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="haalias">Alias</label>
                        <?php $form->get('haalias')->setValue($this->information['has']['0']['alias']) ?>
                        <?= $this->formInput($form->get('haalias')); ?>
                    </div>
                    
                     <div class="form-group">
                        &nbsp;
                    </div>  

                    <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <?php $tieneIplan = 0;  
                                        if(isset($this->information['has']['0']['tiene_iplan'])) {
                                            $tieneIplan = $this->information['has']['0']['tiene_iplan'];
                                        }
                                    ?>
                                    <input type="checkbox" id="haiplan" name="haiplan" value="1" class="form-check-input" <?= ($tieneIplan)?'checked':'' ?>>
                                  ¿Tiene IP Lan?
                                </label>
                            </div>                        
                    </div>
                    
                         
                    <div class="form-group">
                        &nbsp;
                    </div>
                    <div class="form-group">
                        &nbsp;
                    </div>
                    
                    <?php if(isset($this->information['has']['0']['id'])) : ?>
                        <input type="hidden" id="haId" name="haId" value="<?=  $this->information['has']['0']['id']; ?>">
                    <?php  endif; ?>
                    
                    <div style="float:right;">
                        <a class="btn btn-primary btn-sm update-ha" href="#" onclick="updateHa();" role="button" title="Update Hardware">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                    </div>
            
                    
        </div>    
    </div>
</div>
   