<style>
fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>                

<script>

$(function(){
});

</script>

<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>HARDWARE ADICIONAL</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        <div class="form-group">
                            <label class="control-label" for="haequipo">Equipo</label>
                            <select class="form-control input-sm" id="haequipo" name="haequipo" required>
                                <option>diba-caco</option>
                                <option>dipb-saco</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="hatipo">Tipo</label>
                            <select class="form-control input-sm" id="hatipo" name="hatipo" required>
                                <option>Seleccione una opción</option>
                                <option>Tarjeta</option>
                                <option>Cable</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="hafabricante">Fabricante</label>
                            <select class="form-control input-sm" id="hafabricante" name="hafabricante" required>
                                <option>Seleccione una opción</option>
                                <option>CISCO</option>
                                <option>Belden</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="hamodelo">Modelo</label>
                            <select class="form-control input-sm" id="hamodelo" name="hamodelo" required>
                                <option>Seleccione una opción</option>
                                <option>RJ 45</option>
                                <option>7845OKM</option>
                            </select>
                        </div>
                        
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="hanumeroserie">N/S</label>
                            <input type="text" class="form-control input-sm" id="hanumeroserie" name="hanumeroserie" aria-describedby="hanumeroserieHelp">
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="haalias">Alias</label>
                            <input type="text" class="form-control input-sm" id="haalias" name="haalias" aria-describedby="haaliasHelp">
                        </div>

                        <div class="form-check">
                            <label class="form-check-label">
                                <input id="haiplan" name="haiplan" type="checkbox" class="form-check-input" value="1">
                              ¿Tiene IP Lan?
                            </label>
                        </div> 

                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>