<style>
fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>                

<script>

$(function(){
});

</script>

<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>DIRECCIONAMIENTO LAN</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        

                            <div class="form-group">
                                <label class="control-label" for="iplrpv">RPV</label>
                                <select class="form-control input-sm" id="ipwrpv" name="ipwrpv" required>
                                    <option>Seleccione una opción</option>
                                    <option>686</option>
                                    <option>544</option>
                                </select>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="iplalias">Alias</label>
                                <input type="text" class="form-control" id="iplalias" name="iplalias" aria-describedby="iplaliasHelp" required>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="iplvlan">Vlan</label>
                                <input type="text" class="form-control" id="iplvlan" name="iplvlan" aria-describedby="iplvlanHelp" required>
                            </div>    
                        
                            <div class="form-group">
                                <label class="control-label" for="ipliplan">IP Lan</label>
                                <input type="text" class="form-control" id="ipliplan" name="ipliplan" aria-describedby="ipliplanHelp" required>
                            </div>    
                        
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="iplmascara">Máscara</label>
                            <input type="text" class="form-control input-sm" id="iplmascara" name="iplmascara" aria-describedby="iplmascaraHelp">
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="iplnat">Nat</label>
                            <input type="text" class="form-control input-sm" id="iplnat" name="iplnat" aria-describedby="iplnatHelp">
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="iplinterfaz">Interfaz</label>
                            <input type="text" class="form-control input-sm" id="iplinterfaz" name="iplinterfaz" aria-describedby="iplinterfazHelp">
                        </div>

                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>