<style>
fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>                

<script>

$(function(){
});

</script>

<div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>DIRECCIONAMIENTO WAN</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        <form> 

                            <div class="form-group">
                                <label class="control-label" for="ipwrpv">RPV</label>
                                <select class="form-control input-sm" id="ipwrpv" name="ipwrpv" required>
                                    <option>Seleccione una opción</option>
                                    <option>686</option>
                                    <option>544</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="ipwrouting">Routing</label>
                                <select class="form-control input-sm" id="ipwrouting" name="ipwrouting" required>
                                    <option>Seleccione una opción</option>
                                    <option>RIP</option>
                                    <option>BGP</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ipwvlanedc">Vlan EDC</label>
                                <input type="text" class="form-control" id="ipwvlanedc" name="ipwvlanedc" aria-describedby="ipwvlanedcHelp" required>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="ipwvlannacional">Vlan Nacional</label>
                                <select class="form-control input-sm" id="ipwvlannacional" name="ipwvlannacional" required>
                                    
                                    <option>205</option>
                                    <option>350</option>
                                    <option>748</option>
                                </select>
                                
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ipwred">Red</label>
                                <select class="form-control input-sm" id="ipwred" name="ipwred" required>
                                    <option>XEM</option>
                                    <option>XIC</option>
                                </select>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="ipwuso">Uso</label>
                                <select class="form-control input-sm" id="ipwuso" name="ipwuso" required>
                                    <option>Usuarios</option>
                                    <option>Jardin</option>
                                </select>
                            </div>
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="ipwipwanedc">IP WAN EDC</label>
                            <input type="text" class="form-control input-sm" id="ipwipwanedc" name="ipwipwanedc" aria-describedby="ipwipwanedcHelp">
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ipwmascara">Máscara</label>
                            <input type="text" class="form-control input-sm" id="ipwmascara" name="ipwmascara" aria-describedby="ipwmascaraHelp">
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="ipwpeppal">PE Ppal</label>
                            <input type="text" class="form-control input-sm" id="ipwpeppal" name="ipwpeppal" aria-describedby="ipwpeppalHelp">
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ipwpebackup">PE Backup</label>
                            <input type="text" class="form-control input-sm" id="ipwpebackup" name="ipwpebackup" aria-describedby="ipwpebackupHelp">
                        </div>

                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>