<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>








$(function(){
    
    
    
});

</script>

<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="iplequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="iplrpv">RPV</label>
                <?php $form->get('iplrpv')->setValue($this->information['iplans']['0']['rpv_id']) ?>
                <?= $this->formSelect($form->get('iplrpv')); ?>
            </div>
                    
                    
            <div class="form-group">
                <label class="control-label" for="iplalias">Alias</label>
                <?php $form->get('iplalias')->setValue($this->information['iplans']['0']['alias']) ?>
                <?= $this->formInput($form->get('iplalias')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="iplvlan">Vlan</label>
                <?php $form->get('iplvlan')->setValue($this->information['iplans']['0']['vlan']) ?>
                <?= $this->formInput($form->get('iplvlan')); ?>
            </div>                    
                    
            <div class="form-group">
                <label class="control-label" for="ipliplan">IP Lan</label>
                <?php $form->get('ipliplan')->setValue($this->information['iplans']['0']['ip_lan']) ?>
                <?= $this->formInput($form->get('ipliplan')); ?>
            </div>

        </div>    

        <div class="col-lg-6">
                    
            <div class="form-group">
                <label class="control-label" for="iplmascara">Máscara</label>
                <?php $form->get('iplmascara')->setValue($this->information['iplans']['0']['mascara']) ?>
                <?= $this->formInput($form->get('iplmascara')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="iplnat">Nat</label>
                <?php $form->get('iplnat')->setValue($this->information['iplans']['0']['nat']) ?>
                <?= $this->formInput($form->get('iplnat')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="iplinterfaz">Interfaz</label>
                <?php $form->get('iplinterfaz')->setValue($this->information['iplans']['0']['interfaz']) ?>
                <?= $this->formInput($form->get('iplinterfaz')); ?>
            </div>

            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <?php if(isset($this->information['iplans']['0']['id'])) : ?>
                <input type="hidden" id="iplanId" name="iplanId" value="<?=  $this->information['iplans']['0']['id']; ?>">
            <?php  endif; ?>

            <div style="float:right;">
                <a class="btn btn-primary btn-sm update-iplan" href="#" onclick="updateIplan();" role="button" title="Update direccionamiento Lan">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>
            
                    
        </div>    
    </div>
</div>
   