<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>








$(function(){
    
    $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });
    
});

</script>

<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="ipwequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwrpv">RPV</label>
                <?php $form->get('ipwrpv')->setValue($this->information['ipwans']['0']['rpv_id']) ?>
                <?= $this->formSelect($form->get('ipwrpv')); ?>
            </div>
                            
            <div class="form-group">
                <label class="control-label" for="ipwrouting">Routing</label>
                <?php $form->get('ipwrouting')->setValue($this->information['ipwans']['0']['routing_id']) ?>
                <?= $this->formSelect($form->get('ipwrouting')); ?>                            
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwvlanedc">Vlan EDC</label>
                <?php $form->get('ipwvlanedc')->setValue($this->information['ipwans']['0']['vlan_edc']) ?>
                <?= $this->formInput($form->get('ipwvlanedc')); ?>
            </div>
                            
            <div class="form-group">
                <label class="control-label" for="ipwvlannacional">Vlan Nacional</label>
                <?php $form->get('ipwvlannacional')->setValue($this->information['ipwans']['0']['vlan_nacional_id']) ?>
                <?= $this->formSelect($form->get('ipwvlannacional')); ?>                                
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwred">Red</label>
                <?php $form->get('ipwred')->setValue($this->information['ipwans']['0']['red_id']) ?>
                <?= $this->formSelect($form->get('ipwred')); ?>                            
            </div>
                            
            <div class="form-group">
                <label class="control-label" for="ipwuso">Uso</label>
                <?php $form->get('ipwuso')->setValue($this->information['ipwans']['0']['uso_id']) ?>
                <?= $this->formSelect($form->get('ipwuso')); ?>                            
            </div>

        </div>    

        <div class="col-lg-6">
                    
            <div class="form-group">
                <label class="control-label" for="ipwipwanedc">IP WAN EDC</label>
                <?php $form->get('ipwipwanedc')->setValue($this->information['ipwans']['0']['ip_wan_edc']) ?>
                <?= $this->formInput($form->get('ipwipwanedc')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwmascara">Máscara</label>
                <?php $form->get('ipwmascara')->setValue($this->information['ipwans']['0']['mascara']) ?>
                <?= $this->formInput($form->get('ipwmascara')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwpeppal">PE Ppal</label>
                <?php $form->get('ipwpeppal')->setValue($this->information['ipwans']['0']['pe_ppal']) ?>
                <?= $this->formInput($form->get('ipwpeppal')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipwpebackup">PE Backup</label>
                <?php $form->get('ipwpebackup')->setValue($this->information['ipwans']['0']['pe_backup']) ?>
                <?= $this->formInput($form->get('ipwpebackup')); ?>
            </div>
            
            <div class="form-group">
                <label class="control-label" for="ipwintpeppal">Interfaz PE Ppal</label>
                <?php $form->get('ipwintpeppal')->setValue($this->information['ipwans']['0']['int_pe_ppal']) ?>
                <?= $this->formInput($form->get('ipwintpeppal')); ?>
            </div>
            
            <div class="form-group">
                <label class="control-label" for="ipwintpebackup">Interfaz PE Backup</label>
                <?php $form->get('ipwintpebackup')->setValue($this->information['ipwans']['0']['int_pe_backup']) ?>
                <?= $this->formInput($form->get('ipwintpebackup')); ?>
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            <div class="form-group">
                &nbsp;
            </div>
            
            <?php if(isset($this->information['ipwans']['0']['id'])) : ?>
                <input type="hidden" id="ipwanId" name="ipwanId" value="<?=  $this->information['ipwans']['0']['id']; ?>">
            <?php  endif; ?>
            
            <div style="float:right;">
                <a class="btn btn-primary btn-sm update-ipwan" href="#" onclick="updateIpwan();" role="button" title="Update direccionamiento Wan">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>
            
                    
        </div>    
    </div>
</div>
   