<?=  $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-table.min.css'); ?>

<?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-table.js.') 
        ->appendFile($this->basePath() . '/js/bootstrap-table/locale/bootstrap-table-en-Sbt-US.min.js.'); ?>

<style>
    
    .btn-primary {
        width: 110px;
    }
    
    .form-control {
        width: 350px;
    }
    
</style>


<div class="inner">
<div class="ui-widget-header ui-corner-top ui-helper-clearfix" style="padding: 0.2em 0.6em;">&nbsp;</div>

<div id="toolbar">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exportModal">
        <i class="glyphicon glyphicon-hand-down"></i>&nbsp;Baja
    </button>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bulkCloseModal">
        <i class="glyphicon glyphicon-remove"></i>&nbsp;Eliminar
    </button>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bulkCancelModal">
        <i class="glyphicon glyphicon-export"></i>&nbsp;Exportar
    </button>
<!--    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bulkCloseModal">
        <i class="glyphicon glyphicon-th-list"></i>&nbsp;Reporte BI
    </button>-->
</div>
 
<table id="sedes"
           data-toggle="table"
           data-buttons-align="right"
           data-card-visible="true"
           data-page-list="[10, 15, 30, 50, 100, All]"
           data-page-size="10"
           data-pagination="true"
           data-pagination-detail-h-align="right"
           data-pagination-h-align="left"
           data-search="true"
           data-search-align="right"
           data-show-refresh="true"
           data-show-toggle="false"
           data-smart-display="true"
           data-toolbar="#toolbar"
           data-trim-on-search="true"
           data-undefined-text=""
           data-show-export="true"
           class="bootstrap-table ticketList table-nowrap">
        <thead>
            <tr class="ui-state-active noselect">
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="nombre" data-sortable="true" data-width="40%">SEDE</th>
                <th data-field="direccion" data-sortable="true" data-width="60%">DIRECCIÓN</th>
                <!--<th data-field="contacto" data-sortable="true" data-width="25%">CONTACTO</th>-->
                <!--<th data-field="fecha" data-sortable="true" data-width="10%">FECHA ALTA</th>-->
                <th data-field="operation" data-width="10%" data-align="center" data-valign="middle">ACCIONES</th>
                <!--<th data-field="conceptId" data-sortable="true" data-width="50%">POBLACIÓN</th>-->
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->sedes as $sede) : ?>
            
                
        
                <tr class="<?php echo $this->cycle(array('oddRowColor', 'evenRowColor'))->next(); ?> bootstrap-selectableRow greyText">
                    <td></td>
                    <td class="noWrap"><?= ucwords(strtolower($sede->nombre)); ?></td>
                    <td class="noWrap"><?= ucwords(strtolower($sede->direccion)); ?></td>
                    <!--<td class="noWrap"><?php # ucwords(strtolower($sede->contacto)); ?></td>-->
                    <!--<td class="noWrap"><?= date("d-m-Y", strtotime($sede->fechaAlta)); ?></td>--> 
                    <td class="noWrap">
                        <!--  href="/tabs/<?= $sede->id; ?>" -->
                        <a class="update" href="<?php echo $this->url('tabs') . '/' . $sede->id; ?>" title="Consultar">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>

                    </td>
                    <!--<td class="noWrap"></td>-->
                </tr>
          
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="clearfix">&nbsp;</div>
    <div id="result"></div>
</div>

<script>

//    var $table = $('#sedes');
//
//    $(function () {
//            $table.bootstrapTable('hideColumn', 'referenceCode');
//    });
    
</script>
