<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function deleteMc() {
    
    $('#deleteMc').modal('hide');
    var url = '<?= $this->url('delete-mc'); ?>';
    var id = $('#deleteMcId').val();
    
    var equipoId = $('#equipoId').val();
    var equipoBckId = $('#equipoBckId').val();
    var data = {id: id, equipoId: equipoId, equipoBckId:equipoBckId};

    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            $("#ipwan-fill").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}


function updateMc() {

    var url = '<?= $this->url('save-mc'); ?>'; 
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                $("#grid-mc-fill").html(json);
                $('.update-mc').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}




function addMc() {

    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();

    var data = {id: id, idbck: idbck};
    var url = '<?= $this->url('add-mc'); ?>';

    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (json) {
            $("#ipwanone-fill").html(json);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}
    
    

function mconeFill(id) {
    
    var data = {id: id, view: 1};
    var    url = '<?= $this->url('mcone-fill'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwanone-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
    
}







$(function(){

    $('#grid-mc tbody tr').click(function(){

        $("#grid-mc tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

    $('#deleteMc').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        $('#deleteMcId').val(id);
    })

});

</script>


<div class="panel panel-default">
    <div class="panel-body">
        <input type="hidden" id="deleteMcId" name="deleteMcId" value="">
        <?php
            $multicastNumber = 0;
            if(isset($this->information['mcs'])) {
                $multicastNumber = count($this->information['mcs']);
            }
        ?>
        <div style="float:left;">
            <button type="button" class="btn btn-primary" title="Número de configuraciones multicast"><?= '# ' . $multicastNumber; ?></button>
        </div>
        <div style="float:right;">
            <a class="btn btn-primary btn-sm" href="#" onclick="addMc();" role="button" title="Agregar multicast">
                <i class="glyphicon glyphicon-plus"></i>
            </a>
        </div>    
        <div style="clear: both;"></div>

        <div id="grid-mc-fill">
        <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 109px;">
            <table id="grid-mc" class="table table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th>Red Wan Tunel Gre Ppal</th>
                        <th>IP Lopp Back Gre</th>
                        <th>IP Edc Tunel 1</th>
                        <th>IP Asr Ppal Tunel Oficina</th>
                        <th>Interfaz Tunel Asr Ppal</th>
                        <th>Red Wan Tunel Gre Bck</th>
                        <th>IP RP</th>
                        <th>IP Edc Tunel 2</th>
                        <th>IP Asr Bck Tunel Oficina</th>
                        <th>Interfaz Tunel Asr Bck</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $row = 1; ?>
                    <?php foreach($this->information['mcs'] as $mc) : ?> 
                    <tr class="fila-grid <?= (1==$row)?'success':'' ?>">                    
                        <td><?= $mc['red_wan_tunel_gre_ppal'] ?></td>
                        <td><?= $mc['ip_lopp_back_gre'] ?></td>
                        <td><?= $mc['ip_edc_tunel_1'] ?></td>
                        <td><?= $mc['ip_asr_ppal_tunel_oficina'] ?></td>
                        <td><?= $mc['interfaz_tunel_asr_ppal'] ?></td>
                        <td><?= $mc['red_wan_tunel_gre_bck'] ?></td>
                        <td><?= $mc['ip_rp'] ?></td>
                        <td><?= $mc['ip_edc_tunel_2'] ?></td>
                        <td><?= $mc['ip_asr_bck_tunel_oficina'] ?></td>
                        <td><?= $mc['interfaz_tunel_asr_bck'] ?></td>
                        <td> 
                            <a class="btn btn-primary btn-xs" href="#" onclick="mconeFill('<?= $mc['id'] ?>');" title="Consultar configuración">
                                <i class="glyphicon glyphicon-eye-open"></i>
                            </a>
                            <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar multicast" data-toggle="modal" data-id="<?= $mc['id']; ?>" data-target="#deleteMc">
                                <i class="glyphicon glyphicon-minus"></i>
                            </a>
                        </td>
                    </tr>
                    <?php $row++; ?>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
        <div id="ipwanone-fill">
        <?php if(isset($this->information['mcs']['0'])) : ?>    
        <div class="panel panel-default">
            <div class="panel-body">

                <div class="col-lg-6">
                    
                    <div class="form-group">
                        <label class="control-label" for="mcequipo">Equipo</label>
                        <?= $this->information['htmlcombobox']['0']; ?>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="redwantunelgreppal">Red Wan Tunel GRE PPAL</label>
                        <?php $form->get('redwantunelgreppal')->setValue($this->information['mcs']['0']['red_wan_tunel_gre_ppal']) ?>
                        <?= $this->formInput($form->get('redwantunelgreppal')); ?>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label" for="iploppbackgre">IP LoppBack GRE</label>
                        <?php $form->get('iploppbackgre')->setValue($this->information['mcs']['0']['ip_lopp_back_gre']) ?>
                        <?= $this->formInput($form->get('iploppbackgre')); ?>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label" for="ipedctunel1">IP EDC Tunel 1</label>
                        <?php $form->get('ipedctunel1')->setValue($this->information['mcs']['0']['ip_edc_tunel_1']) ?>
                        <?= $this->formInput($form->get('ipedctunel1')); ?>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label" for="ipasrppaltuneloficina">IP ASR PPAL Tunel Oficina</label>
                        <?php $form->get('ipasrppaltuneloficina')->setValue($this->information['mcs']['0']['ip_asr_ppal_tunel_oficina']) ?>
                        <?= $this->formInput($form->get('ipasrppaltuneloficina')); ?>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="interfaztunelasrppal">Interfaz Tunel ASR PPAL</label>
                        <?php $form->get('interfaztunelasrppal')->setValue($this->information['mcs']['0']['interfaz_tunel_asr_ppal']) ?>
                        <?= $this->formInput($form->get('interfaztunelasrppal')); ?>
                    </div>
                    
                </div>    

                <div class="col-lg-6">
                    
                    <div class="form-group">
                        <label class="control-label" for="redwantunelgrebck">Red Wan Tunel GRE BCK</label>
                        <?php $form->get('redwantunelgrebck')->setValue($this->information['mcs']['0']['red_wan_tunel_gre_bck']) ?>
                        <?= $this->formInput($form->get('redwantunelgrebck')); ?>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label" for="iprp">IP RP</label>
                        <?php $form->get('iprp')->setValue($this->information['mcs']['0']['ip_rp']) ?>
                        <?= $this->formInput($form->get('iprp')); ?>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="ipedctunel2">IP EDC Tunel 2</label>
                        <?php $form->get('ipedctunel2')->setValue($this->information['mcs']['0']['ip_edc_tunel_2']) ?>
                        <?= $this->formInput($form->get('ipedctunel2')); ?>
                    </div>
                
                    <div class="form-group">
                        <label class="control-label" for="ipasrbcktuneloficina">IP ASR BCK Tunel Oficina</label>
                        <?php $form->get('ipasrbcktuneloficina')->setValue($this->information['mcs']['0']['ip_asr_bck_tunel_oficina']) ?>
                        <?= $this->formInput($form->get('ipasrbcktuneloficina')); ?>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label" for="interfaztunelasrbck">Interfaz Tunel ASR BCK</label>
                        <?php $form->get('interfaztunelasrbck')->setValue($this->information['mcs']['0']['interfaz_tunel_asr_bck']) ?>
                        <?= $this->formInput($form->get('interfaztunelasrbck')); ?>
                    </div>
                    
                
                    <?php if(isset($this->information['mcs']['0']['id'])) : ?>
                        <input type="hidden" id="mcId" name="mcId" value="<?=  $this->information['mcs']['0']['id']; ?>">
                    <?php  endif; ?>
                    
                    <div class="form-group">
                        &nbsp;
                    </div>

                    <div style="float:right;">
                        <a class="btn btn-primary btn-sm update-mc" href="#" onclick="updateMc();" role="button" title="Update multicast">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                    </div>


                </div>
            </div>

        </div>
        <?php endif; ?>    
        </div>
        
        
        <div class="clearfix"></div>
    </div>
</div>