<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

$(function(){
    
    
    
});

</script>

<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-lg-6">

            <div class="form-group">
                <label class="control-label" for="mcequipo">Equipo</label>
                <?= $this->information['htmlcombobox']['0']; ?>
            </div>
            
            
            <div class="form-group">
                <label class="control-label" for="redwantunelgreppal">Red Wan Tunel GRE PPAL</label>
                <?php $form->get('redwantunelgreppal')->setValue($this->information['mcs']['0']['red_wan_tunel_gre_ppal']) ?>
                <?= $this->formInput($form->get('redwantunelgreppal')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="iploppbackgre">IP LoppBack GRE</label>
                <?php $form->get('iploppbackgre')->setValue($this->information['mcs']['0']['ip_lopp_back_gre']) ?>
                <?= $this->formInput($form->get('iploppbackgre')); ?>
            </div>
                    
            <div class="form-group">
                <label class="control-label" for="ipedctunel1">IP EDC Tunel 1</label>
                <?php $form->get('ipedctunel1')->setValue($this->information['mcs']['0']['ip_edc_tunel_1']) ?>
                <?= $this->formInput($form->get('ipedctunel1')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipasrppaltuneloficina">IP ASR PPAL Tunel Oficina</label>
                <?php $form->get('ipasrppaltuneloficina')->setValue($this->information['mcs']['0']['ip_asr_ppal_tunel_oficina']) ?>
                <?= $this->formInput($form->get('ipasrppaltuneloficina')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="interfaztunelasrppal">Interfaz Tunel ASR PPAL</label>
                <?php $form->get('interfaztunelasrppal')->setValue($this->information['mcs']['0']['interfaz_tunel_asr_ppal']) ?>
                <?= $this->formInput($form->get('interfaztunelasrppal')); ?>
            </div>
            
        </div>    

        <div class="col-lg-6">
                    
            <div class="form-group">
                <label class="control-label" for="redwantunelgrebck">Red Wan Tunel GRE BCK</label>
                <?php $form->get('redwantunelgrebck')->setValue($this->information['mcs']['0']['red_wan_tunel_gre_bck']) ?>
                <?= $this->formInput($form->get('redwantunelgrebck')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="iprp">IP RP</label>
                <?php $form->get('iprp')->setValue($this->information['mcs']['0']['ip_rp']) ?>
                <?= $this->formInput($form->get('iprp')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="ipedctunel2">IP EDC Tunel 2</label>
                <?php $form->get('ipedctunel2')->setValue($this->information['mcs']['0']['ip_edc_tunel_2']) ?>
                <?= $this->formInput($form->get('ipedctunel2')); ?>
            </div>
                
            <div class="form-group">
                <label class="control-label" for="ipasrbcktuneloficina">IP ASR BCK Tunel Oficina</label>
                <?php $form->get('ipasrbcktuneloficina')->setValue($this->information['mcs']['0']['ip_asr_bck_tunel_oficina']) ?>
                <?= $this->formInput($form->get('ipasrbcktuneloficina')); ?>
            </div>

            <div class="form-group">
                <label class="control-label" for="interfaztunelasrbck">Interfaz Tunel ASR BCK</label>
                <?php $form->get('interfaztunelasrbck')->setValue($this->information['mcs']['0']['interfaz_tunel_asr_bck']) ?>
                <?= $this->formInput($form->get('interfaztunelasrbck')); ?>
            </div>
                    
            <div class="form-group">
                &nbsp;
            </div>
                
            <?php if(isset($this->information['mcs']['0']['id'])) : ?>
                <input type="hidden" id="mcId" name="mcId" value="<?=  $this->information['mcs']['0']['id']; ?>">
            <?php  endif; ?>

            <div style="float:right;">
                <a class="btn btn-primary btn-sm update-mc" href="#" onclick="updateMc();" role="button" title="Update multicast">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>                    
                    
        </div>    
    </div>
    
</div>
   