<script>

$(function() {

    $('#grid-he tbody tr').click(function(){
        $("#grid-he tbody tr").each(function () {
            $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

});

</script>

<div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 109px;">
    <table id="grid-he" class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Tarjeta</th>
                <th>Alias</th>
                <th>Vlan</th>
                <th>Máscara</th>
                <th>IP Lan 1</th>
                <th>Int Lan 1</th>
                <th>IP Lan 2</th>
                <th>Int Lan 2</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        <?php   
            $total = count($this->information['hes']);
            $row = 1; 
        ?>
        <?php foreach($this->information['hes'] as $he) : ?> 
        <?php if(0==$this->select) : ?>    
        <tr class="fila-grid <?= ($total==$row)?'success':'' ?>">
        <?php else: ?>
        <tr class="fila-grid <?= ($he['id']==$this->select)?'success':'' ?>">
        <?php endif; ?>     
            
            <td><?= $he['tarjeta'] ?></td>
            <td><?= $he['alias'] ?></td>
            <td><?= $he['vlan'] ?></td>
            <td><?= $he['mascara'] ?></td>
            <td><?= $he['ip_lan_1'] ?></td>
            <td><?= $he['interfaz_1'] ?></td>
            <td><?= $he['ip_lan_2'] ?></td>
            <td><?= $he['interfaz_2'] ?></td>
            <td> 
                <a class="btn btn-primary btn-xs" href="#" onclick="heoneFill('<?= $he['id'] ?>');" title="Consultar configuración">
                    <i class="glyphicon glyphicon-eye-open"></i>
                </a>
                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar configuración">
                    <i class="glyphicon glyphicon-minus"></i>
                </a>
            </td>  
        </tr>
        <?php $row++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>   