<script>

$(function() {

    $('#grid-mc tbody tr').click(function(){
        $("#grid-mc tbody tr").each(function () {
            $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

});

</script>

<div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 109px;">
    <table id="grid-mc" class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Red Wan Tunel Gre Ppal</th>
                <th>IP Lopp Back Gre</th>
                <th>IP Edc Tunel 1</th>
                <th>IP Asr Ppal Tunel Oficina</th>
                <th>Interfaz Tunel Asr Ppal</th>
                <th>Red Wan Tunel Gre Bck</th>
                <th>IP RP</th>
                <th>IP Edc Tunel 2</th>
                <th>IP Asr Bck Tunel Oficina</th>
                <th>Interfaz Tunel Asr Bck</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        <?php   
            $total = count($this->information['mcs']);
            $row = 1; 
        ?>
        <?php foreach($this->information['mcs'] as $mc) : ?>
         <?php if(0==$this->select) : ?>    
        <tr class="fila-grid <?= ($total==$row)?'success':'' ?>">
        <?php else: ?>
        <tr class="fila-grid <?= ($mc['id']==$this->select)?'success':'' ?>">
        <?php endif; ?>     
            <td><?= $mc['red_wan_tunel_gre_ppal'] ?></td>
            <td><?= $mc['ip_lopp_back_gre'] ?></td>
            <td><?= $mc['ip_edc_tunel_1'] ?></td>
            <td><?= $mc['ip_asr_ppal_tunel_oficina'] ?></td>
            <td><?= $mc['interfaz_tunel_asr_ppal'] ?></td>
            <td><?= $mc['red_wan_tunel_gre_bck'] ?></td>
            <td><?= $mc['ip_rp'] ?></td>
            <td><?= $mc['ip_edc_tunel_2'] ?></td>
            <td><?= $mc['ip_asr_bck_tunel_oficina'] ?></td>
            <td><?= $mc['interfaz_tunel_asr_bck'] ?></td>
            <td> 
                <a class="btn btn-primary btn-xs" href="#" onclick="mconeFill('<?= $mc['id'] ?>');" title="Consultar configuración">
                    <i class="glyphicon glyphicon-eye-open"></i>
                </a>
                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar configuración">
                    <i class="glyphicon glyphicon-minus"></i>
                </a>
            </td>  
        </tr>
        <?php $row++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>   