<script>

$(function() {

    $('#grid-ha tbody tr').click(function(){

        $("#grid-ha tbody tr").each(function () {
            $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

});

</script>

<div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 109px;">
    <table id="grid-ha" class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Fabricante</th>
                <th>Modelo</th>
                <th>N/S</th>
                <th>Alias</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        <?php   
            $total = count($this->information['has']);
            $row = 1; 
        ?>
        <?php foreach($this->information['has'] as $ha) : ?>
        <?php if(0==$this->select) : ?>    
        <tr class="fila-grid <?= ($total==$row)?'success':'' ?>">
        <?php else: ?>
        <tr class="fila-grid <?= ($ha['id']==$this->select)?'success':'' ?>">
        <?php endif; ?>     
            
            <td><?= $ha['tipo'] ?></td>
            <td><?= $ha['fabricante'] ?></td>
            <td><?= $ha['modelo'] ?></td>
            <td><?= $ha['serie'] ?></td>
            <td><?= $ha['alias'] ?></td>
            <td> 
                <a class="btn btn-primary btn-xs" href="#" onclick="haoneFill('<?= $ha['id'] ?>');" title="Consultar configuración">
                    <i class="glyphicon glyphicon-eye-open"></i>
                </a>
                <a class="btn btn-primary btn-xs" href="#" role="button" onclick="alert('Delete');"  title="Eliminar configuración">
                    <i class="glyphicon glyphicon-minus"></i>
                </a>
            </td>  
        </tr>
        <?php $row++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>   