<script>

$(function() {

    $('#grid-iplan tbody tr').click(function(){

        $("#grid-iplan tbody tr").each(function () {
            $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

});

</script>

<div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 109px;">
    <table id="grid-iplan" class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Alias</th>
                <th>Vlan Lan</th>
                <th>IP Lan</th>
                <th>Mask Lan</th>
                <th>Nat</th>
                <th>Int Lan</th>
                <th>RPV</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        <?php   
            $total = count($this->information['iplans']);
            $row = 1; 
        ?>
        <?php foreach($this->information['iplans'] as $configuration) : ?> 
        <tr class="fila-grid <?= ($total==$row)?'success':'' ?>">                    
           <td><?= $configuration['alias'] ?></td>
            <td><?= $configuration['vlan'] ?></td>
            <td><?= $configuration['ip_lan'] ?></td>
            <td><?= $configuration['mascara'] ?></td>
            <td><?= $configuration['nat'] ?></td>
            <td><?= $configuration['interfaz'] ?></td>
            <td><?= $configuration['rpv'] ?></td>
            <td> 
                <a class="btn btn-primary btn-xs" href="#" onclick="iplanoneFill('<?= $configuration['id'] ?>');" title="Consultar configuración">
                    <i class="glyphicon glyphicon-eye-open"></i>
                </a>
                <a class="btn btn-primary btn-xs" href="#" role="button" onclick="alert('Delete');"  title="Eliminar configuración">
                    <i class="glyphicon glyphicon-minus"></i>
                </a>
            </td>  
        </tr>
        <?php $row++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>   