<style>
fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>                

<!--<div class="container">-->

<div class="panel panel-default">
    <!--<div class="panel-heading">Fieldset Example</div>-->
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>SEDE</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                <div class="col-lg-6">    
                    
                    <form> 
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nombre</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingresa el nombre de la sede">
                        </div>
                        
                        <div class="form-group">
                            <label for="exampleInputEmail1">Idescat</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                            <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
                        </div>

                        <div class="form-group">
                            <label for="exampleTextarea">Dirección</label>
                            <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
                        </div>
                        
                        
<!--                        <div class="form-group">
                          <label for="exampleInputPassword1">Password</label>
                          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>-->
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Población</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Badalona</option>
                                <option>Rubi</option>
                                <option>Terrassa</option>
                                <option>Sabadell</option>
                                <option>Granollers</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Provincia</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Barcelona</option>
                                <option>Tarragona</option>
                                <option>Lérida</option>
                                <option>Gerona</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Horario</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>


<!--                        <div class="form-group">
                          <label for="exampleSelect2">Example multiple select</label>
                          <select multiple class="form-control" id="exampleSelect2">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                          </select>
                        </div>-->
                        
                    
                </div>    
                    
                <div class="col-lg-6">    
                        
<!--                        <div class="form-group">
                          <label for="exampleInputFile">File input</label>
                          <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                          <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
                        </div>-->

                        <div class="form-group">
                            <label for="exampleInputEmail1">Contacto</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Teléfono</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>

                        <div class="form-group">
                            <label for="exampleTextarea">Observación</label>
                            <textarea class="form-control" id="exampleTextarea" rows="6"></textarea>
                        </div>

                        <fieldset class="form-group">
                          <legend>Mapa de Red</legend>
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                
                        </fieldset>    



                        <!--<div class="clearfix"></div>-->

<!--                        <fieldset class="form-group">
                          <legend>Radio buttons</legend>
                          <div class="form-check">
                            <label class="form-check-label">
                              <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                              Option one is this and that&mdash;be sure to include why it's great
                            </label>
                          </div>
                          <div class="form-check">
                          <label class="form-check-label">
                              <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                              Option two can be something else and selecting it will deselect option one
                            </label>
                          </div>
                          <div class="form-check disabled">
                          <label class="form-check-label">
                              <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios3" value="option3" disabled>
                              Option three is disabled
                            </label>
                          </div>
                        </fieldset>
                        <div class="form-check">
                            <label class="form-check-label">
                              <input type="checkbox" class="form-check-input">
                              Check me out
                            </label>
                        </div>-->

                        <button type="submit" class="btn btn-primary">IMG:Upload galeria de imagenes</button>
                        
                    </form>
                    
                </div>    
                
                </div>
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>
<!--</div>-->