<style>

.btn-pref .btn {
    -webkit-border-radius:0 !important;
}





fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 4px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 2px 2px 2px 4px; 
    background-color: #ffffff;
}
                
.form-group {
    margin-bottom: 2px;
}

.form-control {
    height: 26px;
    font-size: 12px;
    
}

.panel {
    margin-bottom: 2px;
}

.tab-content {
    padding: 0px;
}

.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    padding: 4px;
}




</style>                

<script>

function updateEquipos() {
    
    var url = '/equipo-fill';
        $.ajax({
           type: "POST",
           url: url,
           data: $('#myForm').serialize(),
           cache: false,
           success: function (json) {
                    $("#equipo-fill").html(json);
                    $('.update-equipo').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });
    
}

function updateCircuitos() {

    var url = '/circuito-fill';
        $.ajax({
           type: "POST",
           url: url,
           data: $('#myForm').serialize(),
           cache: false,
           success: function (json) {
                    $("#circuito-fill").html(json);
                    $('.update-circuito').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });

}





function updateSede() {
    
    var url = '/sede-fill';
       $.ajax({
           type: "POST",
           url: url,
           data: $('#myForm').serialize(),
           cache: false,
           success: function (json) {
                    $("#sede-fill").html(json);
                    $('.update-sede').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });

}




function circuitoFill(id) {
    var data = {id: id, view: 1};
    var    url = '/circuito-fill';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#circuito-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}
    
function equipoFill(sede, id) {
    var data = {id: id, sede: sede, view: 1};
    var    url = '/equipo-fill';
    
    $('#ipwan').removeClass('disabled');
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#equipo-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}

function ipwanFill() {
    
    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();
    
    $('#ipwan').addClass('disabled');
    
    var data = {id: id, idbck: idbck, view: 1};
    var    url = '/ipwan-fill';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}

function iplanFill() {
    
    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();
    
    $('#iplan').addClass('disabled');
    
    var data = {id: id, idbck: idbck, view: 1};
    var    url = '<?= $this->url('iplan-fill') ?>'; 
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}




$(function(){

    $(".btn-pref .btn").click(function () {
        $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
        // $(".tab").addClass("active"); // instead of this do the below 
        $(this).removeClass("btn-default").addClass("btn-primary");   
    });

    if($('#cgestionado').prop('checked')) {
        $('.grid-caudal').css('display','block');} 
    
    $('#cgestionado').click(function(){
        if (this.checked) {
            $('.grid-caudal').css('display','block');
        } else {
             $('.grid-caudal').css('display','none');
        } });

    if($('#bcgestionado').prop('checked')) {
        $('.grid-caudal-backup').css('display','block');
    }

    $('#bcgestionado').click(function(){
        if (this.checked) {
            $('.grid-caudal-backup').css('display','block');
        } else {
             $('.grid-caudal-backup').css('display','none');
        } });
    
    
    if($('#cbackup').prop('checked')) {
        $('#circuit-backup').css('display','block');
    }
    
    $('#cbackup').click(function(){
      if (this.checked) {
          $('#circuit-backup').css('display','block');
      } else {
           $('#circuit-backup').css('display','none');
      } });


    if($('#ebackup').prop('checked')) {
        $('#equipo-backup').css('display','block');
    }
    
    $('#ebackup').click(function(){
      if (this.checked) {
          $('#equipo-backup').css('display','block');
      } else {
           $('#equipo-backup').css('display','none');
      } });



    $('#add').click(function() {

        var row;
        var id = $('.row-input').length + 1;
        var caudal = 'caudal-' + id;
        var cantidad = 'cantidad-' + id;
        var unidad = 'unidad-' + id;

        row =   '<tr class="row-input">\n\
                    <td><input name="' + caudal + '" class="col-xs-12" type="text" value="" /></td>\n\
                    <td><input name="' + cantidad + '" class="col-xs-12" type="text" value="" /></td>\n\
                    <td><select name="' + unidad + '" class="col-xs-20" id="exampleSelect1"><option value="1" selected="selected">Mb</option><option value="2">%</option></select></td>\n\
                    <td><a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar"><i class="glyphicon glyphicon-minus"></i></a></td>\n\
                </tr>';
        $('#grid-caudal tr:last').after(row);

    });    
    
    
    $('#add-backup').click(function(){

        var row;
        var id = $('.row-input-backup').length + 1;
        var caudalbck = 'caudalbck-' + id;
        var cantidadbck = 'cantidadbck-' + id;
        var unidadbck = 'unidadbck-' + id;

        row =   '<tr class="row-input-backup">\n\
                    <td><input name="' + caudalbck + '" class="col-xs-12" type="text" value="" /></td>\n\
                    <td><input name="' + cantidadbck + '"  class="col-xs-12" type="text" value="" /></td>\n\
                    <td><select name="' + unidadbck + '"  class="col-xs-20" id="exampleSelect1"><option value="1" selected="selected">Mb</option><option value="2">%</option></select></td>\n\
                    <td><input type="button" class="borrar" value="Eliminar" /></td>\n\
                </tr>';
        $('#backup tr:last').after(row);

    });
            
    $(document).on('click', '.borrar', function (event) {
        event.preventDefault();
        $(this).closest('tr').remove();
    });
    
    

                    
    $('#grid-circuitos tbody tr').click(function(){
        
        $("#grid-circuitos tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });
    
    $('#grid-equipos tbody tr').click(function(){
        
        $("#grid-equipos tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });
    
   
    
    
    
    
});

</script>

<?php
    $form = $this->form;
    #$form->setAttribute('action', $this->url('wizard'));
    $form->setAttribute('id', 'myForm');
    $form->setAttribute('role', 'form');
    $form->setAttribute('data-toggle', 'validator');
    $form->setAttribute('accept-charset', 'utf-8');
    #$form->setAttribute('novalidate', 'novalidate');
    $form->prepare();
?>

<div>
    
    <?= $this->form()->openTag($form); ?>

    
        <fieldset class="col-md-12">    	
            <legend>SEDE</legend>
            
            <div class="panel panel-default">
                <div class="panel-body">
                    
                <div id="sede-fill">    
                    <div class="col-lg-3">    
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nombre</label>
                            <?php $form->get('nombre')->setValue($information['sede']['nombre']) ?>
                            <?= $this->formInput($form->get('nombre')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Idescat</label>
                            <?php $form->get('idescat')->setValue($this->information['sede']['idescat']) ?>
                            <?= $this->formInput($form->get('idescat')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleTextarea">Dirección</label>
                            <?php $form->get('direccion')->setValue($this->information['sede']['direccion']);
                                  $form->get('direccion')->setAttribute('rows', 1); ?>
                            <?= $this->formTextarea($form->get('direccion')); ?>
                        </div>
                    </div>    
                    
                    <div class="col-lg-3">    
                    
                        <div class="form-group">
                            <label for="exampleSelect1">Población</label>
                            <?php $form->get('poblacion')->setValue($this->information['sede']['poblacionId']) ?>
                            <?= $this->formSelect($form->get('poblacion')); ?>
                        </div>
                            
                        <div class="form-group">
                            <label for="exampleSelect1">Provincia</label>
                            <?php $form->get('provincia')->setValue($this->information['sede']['provinciaId']) ?>
                            <?= $this->formSelect($form->get('provincia')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Horario</label>
                            <?php $form->get('horario')->setValue($this->information['sede']['horario']) ?>
                            <?= $this->formInput($form->get('horario')); ?>
                        </div>

                    </div>    
                    
                    <div class="col-lg-3">    
                        
                        <div class="form-group">
                            <label for="exampleInputEmail1">Contacto</label>
                            <?php $form->get('contacto')->setValue($this->information['sede']['contacto']) ?>
                            <?= $this->formInput($form->get('contacto')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Teléfono</label>
                            <?php $form->get('telefono')->setValue($this->information['sede']['telefono']) ?>
                            <?= $this->formInput($form->get('telefono')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleTextarea">Observación</label>
                            <?php $form->get('observacion')->setValue($this->information['sede']['observacion']);
                                  $form->get('observacion')->setAttribute('rows', 1);  ?>
                            <?= $this->formTextarea($form->get('observacion')); ?>
                        </div>
                    
                    </div>    
                </div>
                    <div class="col-lg-3">
                        
<!--                        <fieldset class="form-group">
                            <legend>Esquemas</legend>
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                        </fieldset>    
                        <button type="submit" class="btn btn-primary">IMG:Upload galeria de imagenes</button>-->
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div style="float:right; ">
                            <a class="btn btn-primary btn-sm update-sede" href="#" role="button" onclick="updateSede();" title="Update sede">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        </div>                
                    </div>
                </div>
            </div>
            <input type="hidden" id="sedeId" name="sedeId" value="<?= $this->information['sede']['id']; ?>">
            <input type="hidden" id="sedeContactoId" name="sedeContactoId" value="<?= $this->information['sede']['contactoId']; ?>">
        </fieldset>
        
        
    
    <div style="padding: 4px;" class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
        
        <div class="btn-group" role="group">
            <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-random" aria-hidden="true"></span>
                <div class="hidden-xs">&nbsp;&nbsp;&nbsp;Circuitos&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div class="hidden-xs">&nbsp;</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                <div class="hidden-xs">Equipos</div>
                <div class="hidden-xs">Gestionados</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <div class="hidden-xs">Equipos</div>
                <div class="hidden-xs">No&nbsp;&nbsp;Gestionados</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="glan" class="btn btn-default" href="#tab4" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                <div class="hidden-xs">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GLAN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div class="hidden-xs">&nbsp;</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="accesspoint" class="btn btn-default" href="#tab5" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                <div class="hidden-xs">&nbsp;&nbsp;&nbsp;&nbsp;Access&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div class="hidden-xs">Point</div>
            </button>
        </div>
    
        
    </div>
    

    
    
    
    <div class="tab-content" style="margin: 2px; padding: 2px;">
        <div class="tab-pane fade in active" id="tab1">

            
            <div style="float:right;">
                <?php $sedeId = $this->information['sede']['id'] ;?>
                <a class="btn btn-primary btn-sm" href="/wizard/<?= $sedeId; ?>/1" role="button" title="Agregar circuito">
                    <i class="glyphicon glyphicon-plus"></i>
                </a>
            </div>    
            <div style="clear: both;"></div>
            
            <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
                <table id="grid-circuitos" class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Administrativo</th>
                            <th>Tecnología</th>
                            <th>Velocidad</th>
                            <th>Criticidad</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $row = 1; ?>
                        <?php foreach($this->information['circuitosall'] as $circuito) : ?> 
                        <tr class="fila-grid <?= (1==$row)?'success':'' ?>">
                            <td><?= ($circuito['parent_id']==0)?'PRINCIPAL':'BACKUP' ?></td>
                            <td><?= $circuito['administrativo'] ?></td>
                            <td><?= $circuito['tecnologia'] ?></td>
                            <td><?= $circuito['velocidad'] ?></td>
                            <td><?= $circuito['criticidad'] ?></td>
                            <td> 
                                <?php if(0==$circuito['parent_id']) : ?>
                                <a class="btn btn-primary btn-xs" href="#" onclick="circuitoFill('<?= $circuito['id'] ?>');" title="Consultar circuito">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                                <?php else : ?>
                                <span style="margin-left: 20px;">&nbsp;</span>
                                <?php endif; ?>
                                <a class="btn btn-primary btn-xs" href="#" role="button" onclick="alert('Delete');"  title="Eliminar circuito">
                                    <i class="glyphicon glyphicon-minus"></i>
                                </a>
                                

                                
                                
                            </td>  
                        </tr>
                        <?php $row++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div style="clear: both;"></div>

            <div id="circuito-fill">

            <?php if(isset($this->information['circuitos']['0']['id'])) : ?>    
            <input type="hidden" id="circuitoId" name="circuitoId" value="<?= $this->information['circuitos']['0']['id']; ?>">
            <?php if(isset($this->information['circuitos']['1']['id'])) : ?>
                <input type="hidden" id="circuitoBackupId" name="circuitoBackupId" value="<?= $this->information['circuitos']['1']['id']; ?>">
            <?php endif ; ?>
    
            <div class="panel panel-default">
                <div class="panel-body">
                    <fieldset class="col-md-12">    	
                        <legend>CIRCUITO</legend>
                        <div class="panel panel-default">
                            <div class="panel-body">
                    
                    <div class="col-lg-6">    

                            <div class="form-group">
                                <label for="exampleInputEmail1">Administrativo</label>
                                <?php $form->get('cadministrativo')->setValue($this->information['circuitos']['0']['administrativo']) ?>
                                <?= $this->formInput($form->get('cadministrativo')); ?>
                                
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Teléfono</label>
                                <?php $form->get('ctelefono')->setValue($this->information['circuitos']['0']['telefono']) ?>
                                <?= $this->formInput($form->get('ctelefono')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Cliente</label>
                                <?php $form->get('ccliente')->setValue($this->information['circuitos']['0']['clienteId']) ?>
                                <?= $this->formSelect($form->get('ccliente')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Tecnología</label>
                                <?php $form->get('ctecnologia')->setValue($this->information['circuitos']['0']['tecnologiaId']) ?>
                                <?= $this->formSelect($form->get('ctecnologia')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Velocidad</label>
                                <?php $form->get('cvelocidad')->setValue($this->information['circuitos']['0']['velocidadId']) ?>
                                <?= $this->formSelect($form->get('cvelocidad')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Criticidad</label>
                                <?php $form->get('ccriticidad')->setValue($this->information['circuitos']['0']['criticidadId']) ?>
                                <?= $this->formSelect($form->get('ccriticidad')); ?>
                            </div>

                            <div class="form-check">
                                <label class="form-check-label"> 
                                    <?php $backup = $this->information['circuitos']['0']['tiene_backup']; ?>
                                    <input id="cbackup" name="cbackup" type="checkbox" value="1" class="form-check-input" <?= ($backup)?'checked':'' ?>>
                                  ¿Tiene Backup?
                                </label>
                            </div>                        

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Factura</label>
                            <?php $form->get('cfactura')->setValue($this->information['circuitos']['0']['facturaId']) ?>
                            <?= $this->formSelect($form->get('cfactura')); ?>                        
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Estado</label>
                            <?php $form->get('cestado')->setValue($this->information['circuitos']['0']['estadoId']) ?>
                            <?= $this->formSelect($form->get('cestado')); ?>
                        </div>
                    
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <?php $esGestionado = $this->information['circuitos']['0']['es_gestionado']; ?>
                                    <input type="checkbox" id="cgestionado" name="cgestionado" value="1" class="form-check-input" <?= ($esGestionado)?'checked':'' ?>>
                                    ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal" style="display: none;">
                            
                            <button id="add" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right;  margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                            
                            <div style="clear:both;"></div>
                            <div class="panel-body">

                                <table id="grid-caudal" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Unidad</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php $cont = 1; ?>     
                                        <?php foreach($this->information['caudales']['principal'] as $item) : ?>
                                            <tr class="row-input">
                                                <td><input name="caudal-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['caudal']  ?>" /></td>
                                                <td><input name="cantidad-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['cantidad']  ?>" /></td>
                                                <td><select name="unidad-<?= $cont?>" class="col-xs-20" id="exampleSelect1">
                                                        <option value="1" <?= ('1'==$item['unidad'])?'selected':'' ?>>Mb</option>
                                                        <option value="2" <?= ('2'==$item['unidad'])?'selected':'' ?>>%</option></select></td>
                                                <td>
                                                    <!--<input type="button" class="borrar" value="Eliminar" />-->
                                                    <a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar">
                                                        <i class="glyphicon glyphicon-minus"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php $cont++; ?>
                                        <?php endforeach; ?>

                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                        
                        
                    </div>    
                
                </div>
                
                <!-- SET CIRCUIT BACKUP -->
                
<!--<div class="panel panel-default">-->
    <div id="circuit-backup" class="panel-body" style="display:none;">
        <fieldset class="col-md-12">    	
            <legend>CIRCUITO BACKUP</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                         
                            <div class="form-group">
                                <label for="exampleInputEmail1">Administrativo</label>
                                <?php $form->get('bcadministrativo')->setValue($this->information['circuitos']['1']['administrativo']) ?>
                                <?= $this->formInput($form->get('bcadministrativo')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Teléfono</label>
                                <?php $form->get('bctelefono')->setValue($this->information['circuitos']['1']['telefono']) ?>
                                <?= $this->formInput($form->get('bctelefono')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Cliente</label>
                                <?php $form->get('bccliente')->setValue($this->information['circuitos']['1']['clienteId']) ?>
                                <?= $this->formSelect($form->get('bccliente')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Tecnología</label>
                                <?php $form->get('bctecnologia')->setValue($this->information['circuitos']['1']['tecnologiaId']) ?>
                                <?= $this->formSelect($form->get('bctecnologia')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Velocidad</label>
                                <?php $form->get('bcvelocidad')->setValue($this->information['circuitos']['1']['velocidadId']) ?>
                                <?= $this->formSelect($form->get('bcvelocidad')); ?>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Estado</label>
                                <?php $form->get('bcestado')->setValue($this->information['circuitos']['1']['estadoId']) ?>
                                <?= $this->formSelect($form->get('bcestado')); ?>
                            </div>    
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                     <?php $esBGestionado = $this->information['circuitos']['1']['es_gestionado']; ?>
                                    <input type="checkbox" id="bcgestionado" name="bcgestionado" value="1" class="form-check-input" <?= ($esBGestionado)?'checked':'' ?>>
                                  ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal-backup" style="display: none;">
                            <!--<button id="add-backup" type="button" class="btn btn-primary btn-sm" style="float: right;">IMG:Add</button>-->
                            <button id="add-backup" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right; margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                            <div style="clear:both;"></div>
                            <div class="panel-body">

                                <table id="backup" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Unidad</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $cont = 1; ?>
                                        <?php foreach($this->information['caudales']['backup'] as $item) : ?>
                                                 
                                            <tr class="row-input">
                                                <td><input name="caudalbck-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['caudal']  ?>" /></td>
                                                <td><input name="cantidadbck-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['cantidad']  ?>" /></td>
                                                <td><select name="unidadbck-<?= $cont?>" class="col-xs-20" id="exampleSelect1">
                                                        <option value="1" <?= ('1'==$item['unidad'])?'selected':'' ?>>Mb</option>
                                                        <option value="2" <?= ('2'==$item['unidad'])?'selected':'' ?>>%</option></select></td>
                                                <td>
                                                    <!--<input type="button" class="borrar" value="Eliminar" />-->
                                                    <a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar">
                                                        <i class="glyphicon glyphicon-minus"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php $cont++; ?>
                                        <?php endforeach; ?>                                    
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                    </div>    
                </div>
                
                
                
                
                
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
<!--</div>-->                
                
                
                
                
                
                <!-- SET -->
                
            </div>
                            
        </fieldset>				
        <div class="clearfix"></div>
        
        
    </div>
</div>       
                
                <div style="float:right;">
                    <a class="btn btn-primary btn-sm update-circuito" href="#" role="button" onclick="updateCircuitos();" title="Update circuito">
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                </div>     
                 
            <?php endIf; ?>    
                
                
            </div>
            
            

        </div>
        <div class="tab-pane fade in" id="tab2">
            
            <div style="float:right;">
                
                <a class="btn btn-primary btn-sm" href="/wizard/<?= $sedeId; ?>/2" role="button" title="Agregar equipo">
                    <i class="glyphicon glyphicon-plus"></i>
                </a>
            </div>    
            <div style="clear: both;"></div>

            
            
        
        <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
                 
                <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Nivel</th>
                            <th>Servicio</th>
                            <th>Nemónico</th>
                            <th>IP Gestión</th>
                            <th>Modelo</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $row = 1; ?>
                        <?php foreach($this->information['equiposall'] as $equipo) : ?> 
                        <tr id="<?= $equipo['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                            <td><?= ($equipo['parent_id']==0)?'PRINCIPAL':'BACKUP' ?></td>
                            <td><?= $equipo['nemonico_nivel1'] ?></td>
                            <td><?= $equipo['servicio'] ?></td>
                            <td><?= $equipo['nemonico'] ?></td>
                            <td><?= $equipo['ip_gestion'] ?></td>
                            <td><?= $equipo['modelo'] ?></td>
                            <td> 
                                <?php if(0==$equipo['parent_id']) : ?>
                                <a class="btn btn-primary btn-xs" href="#" onclick="equipoFill('<?= $this->sedeId; ?>', '<?= $equipo['id'] ?>');" title="Consultar equipo">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                                <?php else : ?>
                                <span style="margin-left: 20px;">&nbsp;</span>
                                <?php endif; ?>
                                
                                <a class="btn btn-primary btn-xs" href="#" role="button" onclick="alert('Delete');"  title="Eliminar equipo">
                                    <i class="glyphicon glyphicon-minus"></i>
                                </a>
                            </td>  
                        </tr>
                        <?php $row++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div style="clear: both;"></div>

    <?php if(isset($this->information['equipos']['0'])) : ?>        
            <div>
                <button id="ipwan" type="button" class="btn btn-primary" onclick="ipwanFill();">Direccionamiento WAN</button>
                <button id="iplan" type="button" class="btn btn-primary" onclick="iplanFill();">Direccionamiento LAN</button>
                <button type="button" class="btn btn-primary">Hardware Adicional</button>
                <button type="button" class="btn btn-primary">Hardware RPV 13918</button>
            </div>
        
    <div id="equipo-fill">
        <div id="ipwan-fill">
    <div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>EQUIPO GESTIONADO</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                            <div class="form-group">
                                <label class="control-label" for="circuito">Circuito</label>
                                <?= $this->information['htmlcombobox']['0']; ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="servicio">Servicio</label>
                                <?php $form->get('eservicio')->setValue($this->information['equipos']['0']['servicioId']) ?>
                                <?= $this->formSelect($form->get('eservicio')); ?>
                            </div>
                            
                            
                            <div class="form-group">
                                <label class="control-label" for="nemonico">Nemónico</label>
                                <?php $form->get('enemonico')->setValue($this->information['equipos']['0']['nemonico']) ?>
                                <?= $this->formInput($form->get('enemonico')); ?>
                                
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ip-gestion">IP Gestión</label>
                                <?php $form->get('eipgestion')->setValue($this->information['equipos']['0']['ip_gestion']) ?>
                                <?= $this->formInput($form->get('eipgestion')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="nivel">Nivel</label>
                                <?php $form->get('enivel')->setValue($this->information['equipos']['0']['nivel']) ?>
                                <?= $this->formSelect($form->get('enivel')); ?>
                                
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="nemonico-n1">Nemónico N1</label>
                                <?php $form->get('enemonicon1')->setValue($this->information['equipos']['0']['nemonico_nivel1']) ?>
                                <?= $this->formSelect($form->get('enemonicon1')); ?>
                                
                            </div>
                        
                            <div class="form-group">
                                <label class="control-label" for="fabricante">Fabricante</label>
                                <?php $form->get('efabricante')->setValue($this->information['equipos']['0']['fabricanteId']) ?>
                                <?= $this->formSelect($form->get('efabricante')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="exampleSelect1">Modelo</label>
                                <?php $form->get('emodelo')->setValue($this->information['equipos']['0']['modeloId']) ?>
                                <?= $this->formSelect($form->get('emodelo')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="serie">N/S</label>
                                <?php $form->get('eserie')->setValue($this->information['equipos']['0']['numero_serie']) ?>
                               <?= $this->formInput($form->get('eserie')); ?>
                            </div>

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="ubicacion">Ubicación</label>
                            <?php $form->get('eubicacion')->setValue($this->information['equipos']['0']['ubicacion']) ?>
                            <?= $this->formInput($form->get('eubicacion')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="logos-alta">Pedido LOGOS Alta</label>
                            <?php $form->get('elogosalta')->setValue($this->information['equipos']['0']['pedido_logos_alta']) ?>
                            <?= $this->formInput($form->get('elogosalta')); ?>
                        </div>    
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo">Contacto</label>
                            <?php $form->get('econtacto')->setValue($this->information['equipos']['0']['contacto']) ?>
                            <?= $this->formInput($form->get('econtacto')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="telefono-equipo">Teléfono</label>
                            <?php $form->get('etelefono')->setValue($this->information['equipos']['0']['telefono']) ?>
                            <?= $this->formInput($form->get('etelefono')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo-horario">Horario</label>
                            <?php $form->get('ehorario')->setValue($this->information['equipos']['0']['horario']) ?>
                            <?= $this->formInput($form->get('ehorario')); ?>
                        </div>
                                                
                         <div class="form-group">
                            <label class="control-label" for="estado-equipo">Estado</label>
                            <?php $form->get('eestado')->setValue($this->information['equipos']['0']['estadoId']) ?>
                            <?= $this->formSelect($form->get('eestado')); ?>
                        </div>
                        
                         <div class="form-group">
                            <label class="control-label" for="observacion-equipo">Observaciones</label>
                            <?php $form->get('eobservacion')->setValue($this->information['equipos']['0']['observacion']);
                            #$form->get('observacion')->setAttribute('rows', 1);  ?>
                            <?= $this->formTextarea($form->get('eobservacion')); ?>
                        </div>
                        
                        <div class="form-check">
                            <label class="form-check-label"> 
                                <?php $ebackup = $this->information['equipos']['0']['tiene_backup']; ?>
                                <input id="ebackup" name="ebackup" type="checkbox" value="1" class="form-check-input" <?= ($ebackup)?'checked':'' ?>>
                              ¿Tiene Backup?
                            </label>
                        </div>
                        
                    </div>    
                
                </div>
                
                <!-- EQUIPO BACKUP -->
                    <div id="equipo-backup" class="panel-body" style="display:none;">
        <fieldset class="col-md-12">    	
            <legend>EQUIPO GESTIONADO BCK</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">
                        
                            <div class="form-group">
                                <label class="control-label" for="circuito-equipo-backup">Circuito</label>
                                <?php if(isset($this->information['htmlcombobox']['1'])) : ?>
                                    <?= $this->information['htmlcombobox']['1']; ?>
                                <?php else: ?>
                                    <?= $this->comboBoxCircuitoBck; ?>
                                <?php endif; ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="servicio">Servicio</label>
                                <?php if(isset($this->information['equipos']['1']['servicioId'])) {
                                    $form->get('beservicio')->setValue($this->information['equipos']['1']['servicioId']);
                                }
                                ?>
                                <?= $this->formSelect($form->get('beservicio')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="nemonico">Nemónico</label>
                                <?php if(isset($this->information['equipos']['1']['nemonico'])) {
                                    $form->get('benemonico')->setValue($this->information['equipos']['1']['nemonico']);
                                }
                                ?>
                                <?= $this->formInput($form->get('benemonico')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ip-gestion">IP Gestión</label>
                                <?php if(isset($this->information['equipos']['1']['ip_gestion'])) {
                                    $form->get('beipgestion')->setValue($this->information['equipos']['1']['ip_gestion']);
                                }
                                ?>
                                <?= $this->formInput($form->get('beipgestion')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="nivel">Nivel</label>
                                <?php if(isset($this->information['equipos']['1']['nivel'])) {
                                    $form->get('benivel')->setValue($this->information['equipos']['1']['nivel']);
                                }
                                ?>                                
                                <?= $this->formSelect($form->get('benivel')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="nemonico-n1">Nemónico N1</label>
                                <?php if(isset($this->information['equipos']['1']['nemonico_nivel1'])) {
                                    $form->get('benemonicon1')->setValue($this->information['equipos']['1']['nemonico_nivel1']);
                                }
                                ?>                                
                                
                                <?= $this->formSelect($form->get('benemonicon1')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="fabricante">Fabricante</label>
                                <?php if(isset($this->information['equipos']['1']['fabricanteId'])) {
                                    $form->get('befabricante')->setValue($this->information['equipos']['1']['fabricanteId']);
                                }
                                ?>
                                <?= $this->formSelect($form->get('befabricante')); ?>
                            </div>
                        
                            <div class="form-group">
                                <label class="control-label" for="modelo">Modelo</label>
                                <?php if(isset($this->information['equipos']['1']['modeloId'])) {
                                    $form->get('bemodelo')->setValue($this->information['equipos']['1']['modeloId']);
                                }
                                ?>
                                <?= $this->formSelect($form->get('bemodelo')); ?>
                            </div>
                        
                            <div class="form-group">
                                <label class="control-label" for="numero-serie">S/N</label>
                                <?php if(isset($this->information['equipos']['1']['numero_serie'])) {
                                    $form->get('beserie')->setValue($this->information['equipos']['1']['numero_serie']);
                                }
                                ?>
                                <?= $this->formInput($form->get('beserie')); ?>
                            </div>

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="ubicacion">Ubicación</label>
                            <?php if(isset($this->information['equipos']['1']['ubicacion'])) {
                                $form->get('beubicacion')->setValue($this->information['equipos']['1']['ubicacion']);
                            }
                            ?>
                            <?= $this->formInput($form->get('beubicacion')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="logos-alta">Pedido LOGOS Alta</label>
                            <?php if(isset($this->information['equipos']['1']['pedido_logos_alta'])) {
                                $form->get('belogosalta')->setValue($this->information['equipos']['1']['pedido_logos_alta']);
                            }
                            ?>
                            <?= $this->formInput($form->get('belogosalta')); ?>
                        </div>    
                        
                        <div class="form-group">
                            <label class="control-label" for="observacion-equipo">Observaciones</label>
                            <?php if(isset($this->information['equipos']['1']['observacion'])) {
                                $form->get('beobservacion')->setValue($this->information['equipos']['1']['observacion']);
                            }
                            ?>
                            
                            <?= $this->formTextarea($form->get('beobservacion')); ?>
                        </div>
                    </div>    
                </div>
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>

            <!-- EQUIPOS BACKUP -->
                
            </div>
        
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>        
        </div>
        <input type="hidden" id="equipoId" name="equipoId" value="<?=  $this->information['equipos']['0']['id']; ?>">
        <?php if(isset($this->information['equipos']['1']['id'])) : ?>
        <input type="hidden" id="equipoBckId" name="equipoBckId" value="<?=  $this->information['equipos']['1']['id']; ?>">
        <?php  endif; ?>
        <input type="hidden" id="equipoContactoId" name="equipoContactoId" value="<?=  $this->information['equipos']['0']['contactoId']; ?>">
          
            </div>
          <!-- FIN -->
            <div style="float:right;">
                <a class="btn btn-primary btn-sm update-equipo" href="#" role="button" onclick="updateEquipos();" title="Update equipo">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>
    <?php endIf; ?>      
        </div>
        <div class="tab-pane fade in" id="tab3">
          <h3>This is tab 3</h3>
        </div>
        <div class="tab-pane fade in" id="tab4">
          <h3>This is tab 4</h3>
        </div>
        <div class="tab-pane fade in" id="tab5">
          <h3>This is tab 5</h3>
        </div>
        
        
        
    </div>

    <?= $this->form()->closeTag($form); ?>
</div>
