<?php
    use Zend\Session\Container;
    $session = new Container('User');
    $userRole = $session->offsetGet('userRole');
?>




<style>

.btn-pref .btn {
    -webkit-border-radius:0 !important;
}


.item-selected {
    font-weight: bold;
    color: white;
}



fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 4px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}	
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 2px 2px 2px 4px; 
    background-color: #ffffff;
}
                
.form-group {
    margin-bottom: 2px;
}

.form-control {
    height: 26px;
    font-size: 12px;
    
}

.panel {
    margin-bottom: 2px;
}

.tab-content {
    padding: 0px;
}

.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    padding: 4px;
}


textarea[name=direccion] {
    resize: none;
}


</style>                

<script>

$(document).ready(function (e){

    $('#deleteCircuito').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        var parentId = $(e.relatedTarget).data().parent;
        var administrativo = $(e.relatedTarget).data().administrativo;
        var nif = $(e.relatedTarget).data().nif;
        var html = '<p><b>Administrativo:</b><br/>' +  administrativo + '</p><p><b>Cliente:</b><br/>' +  nif + '</p>';
        $('#deleteCircuitoId').val(id);
        $('#msgModalDeleteCircuito').html(html);
        $('#deleteCircuitoParentId').val(parentId);
    })

    $('#deleteEquipo').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        var parentId = $(e.relatedTarget).data().parent;
        var nemonico = $(e.relatedTarget).data().nemonico;
        var ip = $(e.relatedTarget).data().ip;
        var servicio = $(e.relatedTarget).data().servicio;
        var html = '<p><b>Nemónico:</b><br/>' +  nemonico + '</p><p><b>IP Gestión:</b><br/>' +  ip + '</p><p><b>Servicio:</b><br/>' +  servicio + '</p>';
        $('#msgModalDeleteEquipo').html(html);
        $('#deleteEquipoId').val(id);
        $('#deleteEquipoParentId').val(parentId);
    })

    $('#deleteEquipoNotManagement').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        $('#deleteEquipoNotManagementId').val(id);
    })

    $('#deleteGlanEquipo').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        $('#deleteGlanId').val(id);
    })

    $('#deleteApEquipo').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        $('#deleteApId').val(id);
    })

    $("#provincia").change(function(){
        
        var provincia = $("#provincia option:selected").val();
        var data = {provincia: provincia};
        var    url = '<?= $this->url('ajax-poblacion'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            cache: false,
            success: function (html) {
                $("#ajax-poblacion").html(html);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill").html(html);
            }
        });
        
    });

    $("#ctecnologia").change(function(){
        var tecnologia = $("#ctecnologia option:selected").val();
        var data = {tecnologia: tecnologia, tipo: 1};
        var    url = '<?= $this->url('ajax-velocidad'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            cache: false,
            success: function (html) {
                $("#ajax-velocidad").html(html);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill").html(html);
            }
        });
    });

    $("#bctecnologia").change(function(){
        var tecnologia = $("#bctecnologia option:selected").val();
        var data = {tecnologia: tecnologia, tipo: 2};
        var    url = '<?= $this->url('ajax-velocidad'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            cache: false,
            success: function (html) {
                $("#ajax-velocidad-backup").html(html);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill").html(html);
            }
        });
    });


    $("#efabricante").change(function(){
        var fabricante = $("#efabricante option:selected").val();
        var data = {fabricante: fabricante, tipo: 1};
        var    url = '<?= $this->url('ajax-modelo'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            cache: false,
            success: function (html) {
                $("#ajax-modelo").html(html);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill").html(html);
            }
        });
    });

    $("#befabricante").change(function(){
        var fabricante = $("#befabricante option:selected").val();
        var data = {fabricante: fabricante, tipo: 2};
        var    url = '<?= $this->url('ajax-modelo'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            cache: false,
            success: function (html) {
                $("#ajax-modelo-backup").html(html);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill").html(html);
            }
        });
    });

    $("#engred").change(function(){
        var red = $("#engred option:selected").val();
        var data = {red: red};
        var url = '<?= $this->url('ajax-usos'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            cache: false,
            success: function (html) {
                $("#ajax-usos").html(html);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#fill").html(html);
            }
        });
    });





});

function addComponent(id)
{

    var data = {id: id};
    var url = '<?= $this->url('add-component'); ?>';

    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (json) {
            $("#component-fill").html(json);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}




function addGlan() {

    var id = $('#sedeId').val();
    var data = {id: id};
    var url = '<?= $this->url('add-glan'); ?>';
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (json) {
            $("#glan-fill").html(json);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });
    
}

function addAp() {

    var id = $('#sedeId').val();
    var data = {id: id};
    var url = '<?= $this->url('add-ap'); ?>';
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (json) {
            $("#ap-fill").html(json);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });
    
}



function deleteEquipoNotManagement() {

    $('#deleteEquipoNotManagement').modal('hide');
    var url = '<?= $this->url('delete-equipo-not-management'); ?>';
    var id = $('#deleteEquipoNotManagementId').val();
    var sedeId = $('#deleteEquipoNotManagementSedeId').val();
    var data = {id: id, sedeId: sedeId};

    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            $("#delete-equipo-not-management").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });

}




function deleteEquipo() {
    
    $('#deleteEquipo').modal('hide');
    var url = '<?= $this->url('delete-equipo'); ?>';
    var id = $('#deleteEquipoId').val();
    var parentId = $('#deleteEquipoParentId').val();
    var sedeId = $('#deleteEquipoSedeId').val();
    var data = {id: id, parentId: parentId, sedeId: sedeId};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
             $("#delete-equipo").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}

function deleteGlanEquipo() {
    
    $('#deleteGlanEquipo').modal('hide');
    var url = '<?= $this->url('delete-glan'); ?>';
    var id = $('#deleteGlanId').val();
    var sedeId = $('#deleteGlanSedeId').val();
    var data = {id: id, sedeId: sedeId};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
             $("#delete-glan").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}



function deleteApEquipo() {
    
    $('#deleteApEquipo').modal('hide');
    var url = '<?= $this->url('delete-ap'); ?>';
    var id = $('#deleteApId').val();
    var sedeId = $('#deleteApSedeId').val();
    var data = {id: id, sedeId: sedeId};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
             $("#delete-ap").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}

function deleteCircuito() {
    $('#deleteCircuito').modal('hide');
    var url = '<?= $this->url('delete-circuito'); ?>';
    var id = $('#deleteCircuitoId').val();
    var parentId = $('#deleteCircuitoParentId').val();
    var sedeId = $('#deleteCircuitoSedeId').val();
    var data = {id: id, parentId: parentId, sedeId: sedeId};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
             $("#delete-circuito").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}



function updateNotEquipos() {
    
    var url = '<?= $this->url('notequipo-update'); ?>';
        $.ajax({
           type: "POST",
           url: url,
           data: $('#myForm').serialize(),
           cache: false,
           success: function (json) {
                    $("#equipo-not-update").html(json);
                    $('.update-notequipo').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });

}

function updateGlan() {
    var url = '<?= $this->url('update-glan'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: $('#myForm').serialize(),
            cache: false,
            success: function (json) {
            $("#save-glan").html(json);
//                 $('.update-equipo').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });
}

function updateAp() {
    var url = '<?= $this->url('update-ap'); ?>';
        $.ajax({
            type: "POST",
            url: url,
            data: $('#myForm').serialize(),
            cache: false,
            success: function (json) {
            $("#save-ap").html(json);
//                 $('.update-equipo').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });
}



function updateEquipos() {
    
    var url = '<?= $this->url('equipo-update'); ?>';
        $.ajax({
           type: "POST",
           url: url,
           data: $('#myForm').serialize(),
           cache: false,
           success: function (json) {
                    $("#equipo-update").html(json);
                    $('.update-equipo').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });
    
}

function updateCircuitos() {

    var url = '<?= $this->url('circuito-update'); ?>';
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                $("#circuito-update").html(json);
                $('.update-circuito').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}





function updateSede() {
    
    var url = '<?= $this->url('sede-fill');?>';
       $.ajax({
           type: "POST",
           url: url,
           data: $('#myForm').serialize(),
           cache: false,
           success: function (json) {
                    $("#sede-fill").html(json);
                    $('.update-sede').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });

}

function glanFill(id) {
    var sede = $('#sedeId').val();
    var data = {sede: sede, id: id};
    var url = '<?= $this->url('glan-fill'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#glan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
    
}


function apFill(id) {
    var sede = $('#sedeId').val();
    var data = {sede: sede, id: id};
    var url = '<?= $this->url('ap-fill'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ap-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
    
}



function circuitoFill(id) {
    var data = {id: id, view: 1};
    var    url = '<?= $this->url('circuito-fill'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#circuito-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}

function notequipoFill(sede, id) {
    var data = {id: id, sede: sede, view: 1};
    var    url = '<?= $this->url('notequipo-fill'); ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#equipo-not-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}


 
 
function equipoFill(sede, id) {
    var data = {id: id, sede: sede, view: 1};
    var    url = '<?= $this->url('equipo-fill'); ?>';
    
    $('#ipwan').removeClass('disabled');
    $('#iplan').removeClass('disabled');
    $('#ha').removeClass('disabled');
    $('#he').removeClass('disabled');
    $('#mc').removeClass('disabled');

   
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#equipo-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}

function ipwanFill() {
    
    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();

    $('#ipwan').addClass('disabled');
    $('#iplan').removeClass('disabled');
    $('#ha').removeClass('disabled');
    $('#he').removeClass('disabled');
    $('#mc').removeClass('disabled');
    
    
    var data = {id: id, idbck: idbck, view: 1};
    var    url = '<?= $this->url('ipwan-fill') ?>';
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}

function iplanFill() {
    
    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();
    
    $('#iplan').addClass('disabled');
    $('#ipwan').removeClass('disabled');
    $('#ha').removeClass('disabled');
    $('#he').removeClass('disabled');
    $('#mc').removeClass('disabled');    
    
    var data = {id: id, idbck: idbck, view: 1};
    var    url = '<?= $this->url('iplan-fill') ?>'; 
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}

function haFill() {
    
    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();
    
    $('#ha').addClass('disabled');
    $('#ipwan').removeClass('disabled');
    $('#iplan').removeClass('disabled');
    $('#he').removeClass('disabled');
    $('#mc').removeClass('disabled');    

    
    
    
    var data = {id: id, idbck: idbck, view: 1};
    var    url = '<?= $this->url('ha-fill') ?>'; 
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}

function heFill() {
    
    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();
    
    $('#he').addClass('disabled');
    $('#ipwan').removeClass('disabled');
    $('#iplan').removeClass('disabled');
    $('#ha').removeClass('disabled');
    $('#mc').removeClass('disabled');    

    
    
    var data = {id: id, idbck: idbck, view: 1};
    var    url = '<?= $this->url('he-fill') ?>'; 
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}


function mcFill() {
    
    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();
    
    $('#mc').addClass('disabled');
    $('#ipwan').removeClass('disabled');
    $('#iplan').removeClass('disabled');
    $('#ha').removeClass('disabled');
    $('#he').removeClass('disabled');    
    
    var data = {id: id, idbck: idbck, view: 1};
    var    url = '<?= $this->url('mc-fill') ?>'; 
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            //html = "<div class='alert alert-success'>" + html + "</div>";
            $("#ipwan-fill").html(html);
//                $('.btn').hide();
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#fill").html(html);
        }
    });
}





$(function(){

    $(".btn-pref .btn").click(function () {
        $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
        // $(".tab").addClass("active"); // instead of this do the below 
        $(this).removeClass("btn-default").addClass("btn-primary");   
    });

    if($('#cgestionado').prop('checked')) {
        $('.grid-caudal').css('display','block');} 
    
    $('#cgestionado').click(function(){
        if (this.checked) {
            $('.grid-caudal').css('display','block');
        } else {
             $('.grid-caudal').css('display','none');
        } });

    if($('#bcgestionado').prop('checked')) {
        $('.grid-caudal-backup').css('display','block');
    }

    $('#bcgestionado').click(function(){
        if (this.checked) {
            $('.grid-caudal-backup').css('display','block');
        } else {
             $('.grid-caudal-backup').css('display','none');
        } });
    
    
    if($('#cbackup').prop('checked')) {
        $('#circuit-backup').css('display','block');
    }
    
    $('#cbackup').click(function(){
      if (this.checked) {
          $('#circuit-backup').css('display','block');
      } else {
           $('#circuit-backup').css('display','none');
      } });


    if($('#ebackup').prop('checked')) {
        $('#equipo-backup').css('display','block');
    }
    
    $('#ebackup').click(function(){
      if (this.checked) {
          $('#equipo-backup').css('display','block');
      } else {
           $('#equipo-backup').css('display','none');
      } });



    $('#add').click(function() {

        var row;
        var id = $('.row-input').length + 1;
        var caudal = 'caudal-' + id;
        var cantidad = 'cantidad-' + id;
        var unidad = 'unidad-' + id;

        row =   '<tr class="row-input">\n\
                    <td><input name="' + caudal + '" class="col-xs-12" type="text" value="" /></td>\n\
                    <td><input name="' + cantidad + '" class="col-xs-12" type="text" value="" /></td>\n\
                    <td><select name="' + unidad + '" class="col-xs-20" id="exampleSelect1"><option value="1" selected="selected">Mb</option><option value="2">%</option></select></td>\n\
                    <td><a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar"><i class="glyphicon glyphicon-minus"></i></a></td>\n\
                </tr>';
        $('#grid-caudal tr:last').after(row);

    });    
    
    
    $('#add-backup').click(function(){

        var row;
        var id = $('.row-input-backup').length + 1;
        var caudalbck = 'caudalbck-' + id;
        var cantidadbck = 'cantidadbck-' + id;
        var unidadbck = 'unidadbck-' + id;

        row =   '<tr class="row-input-backup">\n\
                    <td><input name="' + caudalbck + '" class="col-xs-12" type="text" value="" /></td>\n\
                    <td><input name="' + cantidadbck + '"  class="col-xs-12" type="text" value="" /></td>\n\
                    <td><select name="' + unidadbck + '"  class="col-xs-20" id="exampleSelect1"><option value="1" selected="selected">Mb</option><option value="2">%</option></select></td>\n\
                    <td><a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar"><i class="glyphicon glyphicon-minus"></i></a></td>\n\
                </tr>';
        $('#backup tr:last').after(row);

    });
            
    $(document).on('click', '.borrar', function (event) {
        event.preventDefault();
        $(this).closest('tr').remove();
    });
    
    

                    
    $('#grid-circuitos tbody tr').click(function(){
        
        $("#grid-circuitos tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

    $('#grid-equipos tbody tr').click(function(){
        
        $("#grid-equipos tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });
    
   
    
    
    
    
});

</script>

<?php
    $form = $this->form;
    #$form->setAttribute('action', $this->url('wizard'));
    $form->setAttribute('id', 'myForm');
    $form->setAttribute('role', 'form');
    $form->setAttribute('data-toggle', 'validator');
    $form->setAttribute('accept-charset', 'utf-8');
    #$form->setAttribute('novalidate', 'novalidate');
    $form->prepare();
?>

<?php if(is_array($this->information)) : ?>
<div>

    <?= $this->form()->openTag($form); ?>


        <fieldset class="col-md-12">    	
            <legend>SEDE</legend>
            
            <div class="panel panel-default">
                <div class="panel-body">
    
                <div id="sede-fill">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nombre</label>
                            <?php   $form->get('nombre')->setValue($information['sede']['nombre']);
                                    if('7' == $this->item) {
                                        $form->get('nombre')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                        $form->get('nombre')->setAttribute('title','Dato encontrado');
                                    }
                            ?>
                            <?= $this->formInput($form->get('nombre')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Idescat</label>
                            <?php $form->get('idescat')->setValue($this->information['sede']['idescat']) ?>
                            <?= $this->formInput($form->get('idescat')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleTextarea">Dirección</label>
                            <?php   $form->get('direccion')->setValue($this->information['sede']['direccion']);
                                    $form->get('direccion')->setAttribute('rows', 2); 
                                    if('8' == $this->item) {
                                        $form->get('direccion')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                        $form->get('direccion')->setAttribute('title','Dato encontrado');
                                    }
                            ?>
                            <?= $this->formTextarea($form->get('direccion')); ?>
                        </div>
                    </div>    
                    
                    <div class="col-lg-3">

                            
                        <div class="form-group">
                            <label for="exampleSelect1">Provincia</label>
                            <?php $form->get('provincia')->setValue($this->information['sede']['provinciaId']) ?>
                            <?= $this->formSelect($form->get('provincia')); ?>
                        </div>
                        
                        <div id="ajax-poblacion">
                            <div class="form-group">
                                <label for="exampleSelect1">Población</label>
                                <?php 
                                    $form->get('poblacion')->setValue($this->information['sede']['poblacionId']) 
                                ?>
                                <?= $this->formSelect($form->get('poblacion')); ?>
                            </div>
                        </div>    
                        <div class="form-group">
                            <label for="exampleInputEmail1">Horario</label>
                            <?php $form->get('horario')->setValue($this->information['sede']['horario']) ?>
                            <?= $this->formInput($form->get('horario')); ?>
                        </div>

                    </div>    
                    
                    <div class="col-lg-3">    
                        
                        <div class="form-group">
                            <label for="exampleInputEmail1">Contacto</label>
                            <?php $form->get('contacto')->setValue($this->information['sede']['contacto']) ?>
                            <?= $this->formInput($form->get('contacto')); ?>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Teléfono</label>
                            <?php $form->get('telefono')->setValue($this->information['sede']['telefono']) ?>
                            <?= $this->formInput($form->get('telefono')); ?>
                        </div>

                        <?php if('Cliente' != $userRole) : ?>
                        <div class="form-group">
                            <label for="exampleTextarea">Observación</label>
                            <?php $form->get('observacion')->setValue($this->information['sede']['observacion']);
                                  $form->get('observacion')->setAttribute('rows', 3);  ?>
                            <?= $this->formTextarea($form->get('observacion')); ?>
                        </div>
                        <?php endIf; ?>
                    </div>    
                </div>
                    <div class="col-lg-3">
                        
<!--                        <fieldset class="form-group">
                            <legend>Esquemas</legend>
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="32" width="32" style="border:1px solid black;">
                        </fieldset>    
                        <button type="submit" class="btn btn-primary">IMG:Upload galeria de imagenes</button>-->
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div class="form-group">
                            &nbsp;        
                        </div>
                        <div style="float:right; ">
                            <a class="btn btn-primary btn-sm update-sede" href="#" role="button" onclick="updateSede();" title="Update sede">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        </div>                
                    </div>
                </div>
            </div>
            <input type="hidden" id="sedeId" name="sedeId" value="<?= $this->information['sede']['id']; ?>">
            <input type="hidden" id="sedeContactoId" name="sedeContactoId" value="<?= $this->information['sede']['contactoId']; ?>">
        </fieldset>
        
        
    
    <div style="padding: 4px;" class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">

        <div class="btn-group" role="group">
            <button type="button" id="stars" class="btn <?= ($this->tab == 0)?'btn-primary':'btn-default'; ?>" href="#tab1" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-random" aria-hidden="true"></span>
                <div class="hidden-xs">&nbsp;&nbsp;&nbsp;Circuitos&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div class="hidden-xs">&nbsp;</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="favorites" class="btn <?= ($this->tab == 1)?'btn-primary':'btn-default' ?>" href="#tab2" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                <div class="hidden-xs">Equipos</div>
                <div class="hidden-xs">Gestionados</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="following" class="btn <?= ($this->tab == 2)?'btn-primary':'btn-default' ?>" href="#tab3" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <div class="hidden-xs">Equipos</div>
                <div class="hidden-xs">No&nbsp;&nbsp;Gestionados</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="glan" class="btn <?= ($this->tab == 3)?'btn-primary':'btn-default' ?>" href="#tab4" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                <div class="hidden-xs">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GLAN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div class="hidden-xs">&nbsp;</div>
            </button>
        </div>

        <div class="btn-group" role="group">
            <button type="button" id="accesspoint" class="btn <?= ($this->tab == 4)?'btn-primary':'btn-default' ?>" href="#tab5" data-toggle="tab" style="width:100%;">
                <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                <div class="hidden-xs">&nbsp;&nbsp;&nbsp;&nbsp;Access&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div class="hidden-xs">Point</div>
            </button>
        </div>
    
        
    </div>
    

    
    
    
    <div class="tab-content" style="margin: 2px; padding: 2px;">
        
        <div class="tab-pane fade in <?= ($this->tab == 0)?'active':''; ?>" id="tab1">
            <div id="delete-circuito">
            <input type="hidden" id="deleteCircuitoId" name="deleteCircuitoId" value="">
            <input type="hidden" id="deleteCircuitoParentId" name="deleteCircuitoParentId" value="">
            <input type="hidden" id="deleteCircuitoSedeId" name="deleteCircuitoSedeId" value="<?= $this->information['sede']['id'] ;?>">
            
            <div id="circuito-update">
            <?php
                $circuitosNumber = 0;
                if(isset($this->information['circuitosall'])) {
                    $circuitosNumber = count($this->information['circuitosall']);
                }
            ?>
            <div style="float:left;">
                <button type="button" class="btn btn-primary" title="Número de circuitos"><?= '# ' . $circuitosNumber; ?></button>
            </div>
            
            <div style="float:right;">
                <?php $sedeId = $this->information['sede']['id'] ;?>
                <a class="btn btn-primary btn-sm" href="<?= $this->url('wizard') . '/'. $sedeId; ?>/1" role="button" title="Agregar circuito">
                    <i class="glyphicon glyphicon-plus"></i>
                </a>
            </div>
            <div style="clear: both;"></div>
            
            <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
                <table id="grid-circuitos" class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Cliente</th>
                            <th>Administrativo</th>
                            <th>Tecnología</th>
                            <th>Velocidad</th>
                            <th>Criticidad</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php $row = false; ?>
                    <?php foreach($this->information['circuitosall'] as $circuito) : ?> 
                        <?php
                            if(isset($this->information['circuitos']['0']['id'])) {
                                $row = true;  
                            }
                        ?>
                        <?php if($row) : ?>
                        <tr class="fila-grid <?= ($this->information['circuitos']['0']['id']==$circuito['id'])?'success':'' ?>">
                        <?php else : ?>
                        <tr class="fila-grid">    
                        <?php endif; ?>    
                            <td><?= ($circuito['parent_id']==0)?'PRINCIPAL':'BACKUP' ?></td>
                            <td><?= $circuito['nif'] ?></td>
                            
                                <?php if($circuito['administrativo'] == $this->value) : ?> 
                                <td class="<?= ($this->item == 1)?'item-selected':''; ?>" style="<?= ($this->item == 1)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $circuito['administrativo']; ?></td>
                                <?php else : ?>
                                <td>
                                    <?php if(preg_match("/^00000/", $circuito['administrativo'])) : ?> 
                                    <span style="color: red; font-weight: bold;" title="pseudo-administrativo" ><?= $circuito['administrativo'] ?></span>
                                    <?php else : ?>
                                    <?= $circuito['administrativo'] ?>
                                    <?php endif ; ?>
                                </td>
                                <?php endif ; ?>    
                            
                            
                            <td><?= $circuito['tecnologia'] ?></td>
                            <td><?= $circuito['velocidad'] ?></td>
                            <td><?= $circuito['criticidad'] ?></td>
                            <td> 
                                <?php if(0==$circuito['parent_id']) : ?>
                                <a class="btn btn-primary btn-xs" href="#" onclick="circuitoFill('<?= $circuito['id'] ?>');" title="Consultar circuito">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                                <?php else : ?>
                                <span style="margin-left: 20px;">&nbsp;</span>
                                <?php endif; ?>
                                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar circuito" data-toggle="modal" data-administrativo="<?= $circuito['administrativo']; ?>" data-nif="<?= $circuito['nif']; ?>" data-id="<?= $circuito['id']; ?>" data-parent="<?= $circuito['parent_id']; ?>" data-target="#deleteCircuito">
                                    <i class="glyphicon glyphicon-minus"></i>
                                </a>
                                
                            </td>  
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div style="clear: both;"></div>

            <div id="circuito-fill">
                   
            <?php if(isset($this->information['circuitos']['0']['id'])) : ?>
    
            <input type="hidden" id="circuitoId" name="circuitoId" value="<?= $this->information['circuitos']['0']['id']; ?>">
            <?php if(isset($this->information['circuitos']['1']['id'])) : ?>
                <input type="hidden" id="circuitoBackupId" name="circuitoBackupId" value="<?= $this->information['circuitos']['1']['id']; ?>">
            <?php endif ; ?>
     
            <div class="panel panel-default">
                <div class="panel-body">
                    <fieldset class="col-md-12">    	
                        <legend>CIRCUITO</legend>
                        <div class="panel panel-default">
                            <div class="panel-body">
                    
                    <div class="col-lg-6">

                            <div class="form-group">
                                <label class="control-label" for="exampleInputEmail1">Administrativo</label>
                                <?php
                                    $form->get('cadministrativo')->setValue($this->information['circuitos']['0']['administrativo']); 
                                    $form->get('cadministrativo')->setAttribute('readonly','readonly');
                                    
                                    if($this->information['circuitos']['0']['administrativo'] === $this->value) {
                                        $form->get('cadministrativo')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                        $form->get('cadministrativo')->setAttribute('title','Dato encontrado');
                                    } else {
                                        if(preg_match("/^00000/", $this->information['circuitos']['0']['administrativo'])) {
                                            $form->get('cadministrativo')->setAttribute('title','Pseudo-administrativo');
                                            $form->get('cadministrativo')->setAttribute('style','color:red; font-weight: bold;');
                                        }
                                    }
                                ?>
                                                                
                                
                                <?= $this->formInput($form->get('cadministrativo')); ?>
                            </div>

<!--                            <div class="form-group">
                                <label class="control-label" for="exampleInputEmail1">Administrativo</label>
                                <?php //$form->get('xcadministrativo')->setValue($this->information['circuitos']['0']['xadministrativo']) ?>
                                <?php // $this->formInput($form->get('xcadministrativo')); ?>
                                
                            </div>-->
                        
                            <div class="form-group">
                                <label class="control-label" for="exampleInputEmail1">Teléfono</label>
                                <?php 
                                    $form->get('ctelefono')->setValue($this->information['circuitos']['0']['telefono']);
                                    if($this->information['circuitos']['0']['telefono'] === $this->value && !empty($this->value)) {
                                        $form->get('ctelefono')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                        $form->get('ctelefono')->setAttribute('title','Dato encontrado');
                                    }
                                ?>
                                <?= $this->formInput($form->get('ctelefono')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="exampleInputEmail1">Ibenet</label>
                                <?php
                                    $form->get('cibenet')->setValue($this->information['circuitos']['0']['ibenet']);
                                    if($this->information['circuitos']['0']['ibenet'] === $this->value && !empty($this->value)) {
                                        $form->get('cibenet')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                        $form->get('cibenet')->setAttribute('title','Dato encontrado');
                                    }
                                ?>
                                <?= $this->formInput($form->get('cibenet')); ?>
                            </div>
                        
                            <div class="form-group">
                                <label class="control-label" for="exampleSelect1">Cliente</label>
                                <?php $form->get('ccliente')->setValue($this->information['circuitos']['0']['clienteId']) ?>
                                <?= $this->formSelect($form->get('ccliente')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="exampleSelect1">Tecnología</label>
                                <?php $form->get('ctecnologia')->setValue($this->information['circuitos']['0']['tecnologiaId']) ?>
                                <?= $this->formSelect($form->get('ctecnologia')); ?>
                            </div>
                            <div id="ajax-velocidad">
                                <div class="form-group">
                                    <label class="control-label" for="velocidad">Velocidad</label>
                                    <?php $form->get('cvelocidad')->setValue($this->information['circuitos']['0']['velocidadId']) ?>
                                    <?= $this->formSelect($form->get('cvelocidad')); ?>
                                </div>
                            </div>    
                            <div class="form-group">
                                <label class="control-label" for="exampleSelect1">Criticidad</label>
                                <?php $form->get('ccriticidad')->setValue($this->information['circuitos']['0']['criticidadId']) ?>
                                <?= $this->formSelect($form->get('ccriticidad')); ?>
                            </div>

                             <?php $esGestionado = $this->information['circuitos']['0']['es_gestionado']; ?>
                        
                            <div style="display: <?= ($esGestionado)?'block':'none' ?>;" class="form-check">
                                <label class="control-label" class="form-check-label"> 
                                    <?php $backup = $this->information['circuitos']['0']['tiene_backup']; ?>
                                    <input id="cbackup" name="cbackup" type="checkbox" value="1" class="form-check-input" <?= ($backup)?'checked':'' ?> <?= ($backup)?'readonly':'' ?>>
                                  ¿Tiene Backup?
                                </label>
                            </div>                        

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="exampleSelect1">Factura</label>
                            <?php $form->get('cfactura')->setValue($this->information['circuitos']['0']['facturaId']) ?>
                            <?= $this->formSelect($form->get('cfactura')); ?>                        
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="exampleSelect1">Estado</label>
                            <?php $form->get('cestado')->setValue($this->information['circuitos']['0']['estadoId']) ?>
                            <?= $this->formSelect($form->get('cestado')); ?>
                        </div>
                    
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                   
                                    <input type="checkbox" id="cgestionado" name="cgestionado" value="1" class="form-check-input" <?= ($esGestionado)?'checked':'' ?> disabled>
                                    ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal" style="display: none;">
                            
                            <button id="add" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right;  margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                            
                            <div style="clear:both;"></div>
                            <div class="panel-body">

                                <table id="grid-caudal" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Calidad</th>
                                            <th>Caudal</th>
                                            <th>Unidad</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(isset($this->information['caudales']['principal'])) : ?>    
                                        <?php $cont = 1; ?>     
                                        <?php foreach($this->information['caudales']['principal'] as $item) : ?>
                                            <tr class="row-input">
                                                <td><input name="caudal-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['caudal']  ?>" /></td>
                                                <td><input name="cantidad-<?= $cont?>" class="col-xs-12" type="text" value="<?= number_format($item['cantidad'],0)  ?>" /></td>
                                                <td><select name="unidad-<?= $cont?>" class="col-xs-20" id="exampleSelect1">
                                                        <option value="1" <?= ('1'==$item['unidad'])?'selected':'' ?>>Mb</option>
                                                        <option value="2" <?= ('2'==$item['unidad'])?'selected':'' ?>>%</option></select></td>
                                                <td>
                                                    <!--<input type="button" class="borrar" value="Eliminar" />-->
                                                    <a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar">
                                                        <i class="glyphicon glyphicon-minus"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php $cont++; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                        
                        
                    </div>    
                
                </div>
                
                <!-- SET CIRCUIT BACKUP -->
                
<!--<div class="panel panel-default">-->
    <div id="circuit-backup" class="panel-body" style="display:none;">
        <fieldset class="col-md-12">    	
            <legend>CIRCUITO BACKUP</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                         
                            <div class="form-group">
                                <label class="control-label" for="bcadministrativo">Administrativo</label>
                                <?php if(isset($this->information['circuitos']['1']['administrativo'])) {
                                    $form->get('bcadministrativo')->setValue($this->information['circuitos']['1']['administrativo']);
                                    $form->get('bcadministrativo')->setAttribute('readonly','readonly');
                                    if(preg_match("/^00000/", $this->information['circuitos']['1']['administrativo'])) {
                                        $form->get('bcadministrativo')->setAttribute('title','Pseudo-administrativo');
                                        $form->get('bcadministrativo')->setAttribute('style','color:red; font-weight: bold;');                                        
                                    }
                                } ?>
                                <?= $this->formInput($form->get('bcadministrativo')); ?>
                            </div>

<!--                            <div class="form-group">
                                <label class="control-label" for="xbcadministrativo">Administrativo</label>
                                <?php
//                                if(isset($this->information['circuitos']['1']['administrativo'])) {
//                                    $form->get('xbcadministrativo')->setValue($this->information['circuitos']['1']['xadministrativo']);
//                                } ?>
                                <?php // $this->formInput($form->get('xbcadministrativo')); ?>
                            </div>-->
                        
                        
                            <div class="form-group">
                                <label class="control-label" for="bctelefono">Teléfono</label>
                                <?php
                                
                                if(isset($this->information['circuitos']['1']['telefono'])) {
                                    $form->get('bctelefono')->setValue($this->information['circuitos']['1']['telefono']);
                                    if($this->information['circuitos']['1']['telefono'] === $this->value) {
                                        $form->get('bctelefono')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                    }
                                } 
                                ?>
                                <?= $this->formInput($form->get('bctelefono')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="bcibenet">Ibenet</label>
                                <?php if(isset($this->information['circuitos']['1']['ibenet'])) {
                                    $form->get('bcibenet')->setValue($this->information['circuitos']['1']['ibenet']);
                                } ?>
                                <?= $this->formInput($form->get('bcibenet')); ?>
                            </div>
                        
<!--                            <div class="form-group">
                                <label class="control-label" for="bccliente">Cliente</label>
                                <?php
//                                if(isset($this->information['circuitos']['1']['clienteId'])) {
//                                    $form->get('bccliente')->setValue($this->information['circuitos']['1']['clienteId']);
//                                } 
                                ?>
                                <?php #$this->formSelect($form->get('bccliente')); ?>
                            </div>-->

                            <div class="form-group">
                                <label class="control-label" for="bctecnologia">Tecnología</label>
                                <?php if(isset($this->information['circuitos']['1']['tecnologiaId'])) {
                                    $form->get('bctecnologia')->setValue($this->information['circuitos']['1']['tecnologiaId']);
                                } ?>
                                <?= $this->formSelect($form->get('bctecnologia')); ?>
                            </div>
                            
                            <div id="ajax-velocidad-backup">
                                <div class="form-group">
                                    <label class="control-label" for="bcvelocidad">Velocidad</label>
                                    <?php if(isset($this->information['circuitos']['1']['velocidadId'])) {
                                        $form->get('bcvelocidad')->setValue($this->information['circuitos']['1']['velocidadId']);
                                    } ?>
                                    <?= $this->formSelect($form->get('bcvelocidad')); ?>
                                </div>
                            </div>    
                            <div class="form-group">
                                <label class="control-label" for="exampleSelect1">Estado</label>
                                <?php if(isset($this->information['circuitos']['1']['estadoId'])) {
                                    $form->get('bcestado')->setValue($this->information['circuitos']['1']['estadoId']);
                                } ?>
                                <?= $this->formSelect($form->get('bcestado')); ?>
                            </div>    
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <?php
                                        $esBGestionado = 0;
                                        $existBGestionado = 0;
                                        if(isset($this->information['circuitos']['1']['es_gestionado'])) {
                                        $esBGestionado = $this->information['circuitos']['1']['es_gestionado'];
                                        $existBGestionado = 1;
                                        } ?>
                                    
                                    <input type="checkbox" id="bcgestionado" name="bcgestionado" value="1" class="form-check-input" <?= ($esBGestionado)?'checked':'' ?> <?= ($existBGestionado)?'disabled':'' ?>>
                                    ¿Es gestionado?
                                </label>
                            </div>                        
                        </div>
                        
                        <div class="grid-caudal-backup" style="display: none;">
                            <!--<button id="add-backup" type="button" class="btn btn-primary btn-sm" style="float: right;">IMG:Add</button>-->
                            <button id="add-backup" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right; margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                            <div style="clear:both;"></div>
                            <div class="panel-body">

                                <table id="backup" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Calidad</th>
                                            <th>Caudal</th>
                                            <th>Unidad</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <?php if(isset($this->information['caudales']['backup'])) : ?>
                                    <tbody>
                                        <?php $cont = 1; ?>
                                        <?php foreach($this->information['caudales']['backup'] as $item) : ?>
                                                 
                                            <tr class="row-input-backup">
                                                <td><input name="caudalbck-<?= $cont?>" class="col-xs-12" type="text" value="<?= $item['caudal']  ?>" /></td>
                                                <td><input name="cantidadbck-<?= $cont?>" class="col-xs-12" type="text" value="<?= number_format($item['cantidad'],0)  ?>" /></td>
                                                <td><select name="unidadbck-<?= $cont?>" class="col-xs-20" id="exampleSelect1">
                                                        <option value="1" <?= ('1'==$item['unidad'])?'selected':'' ?>>Mb</option>
                                                        <option value="2" <?= ('2'==$item['unidad'])?'selected':'' ?>>%</option></select></td>
                                                <td>
                                                    <!--<input type="button" class="borrar" value="Eliminar" />-->
                                                    <a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar">
                                                        <i class="glyphicon glyphicon-minus"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            <?php $cont++; ?>
                                        <?php endforeach; ?>                                    
                                    
                                    </tbody>
                                    <?php endif; ?>
                                </table>
                            </div>
                        </div>                        
                    </div>    
                </div>
                
                
                
                
                
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
<!--</div>-->                
                
                
                
                
                
                <!-- SET -->
                
            </div>
                            
        <div class="clearfix"></div>                
                        
        <div style="float:right; padding-top: 14px; padding-bottom: 14px;">
            <a class="btn btn-primary btn-sm update-circuito" href="#" role="button" onclick="updateCircuitos();" title="Update circuito">
                <i class="glyphicon glyphicon-edit"></i>
            </a>
        </div>     
        
          
                        
                    
        </fieldset>				
        <div class="clearfix"></div>
        
        
        
    </div>
</div>       
                
                 
            <?php endIf; ?>    
                
                </div>
            </div>
            
            </div>
        </div>
            <div class="tab-pane fade in <?= ($this->tab == 1)?'active':''; ?>" id="tab2">
                <div id="delete-equipo">
                    <input type="hidden" id="deleteEquipoId" name="deleteEquipoId" value="">
                    <input type="hidden" id="deleteEquipoParentId" name="deleteEquipoParentId" value="">
                    <input type="hidden" id="deleteEquipoSedeId" name="deleteEquipoSedeId" value="<?= $this->information['sede']['id'] ;?>">

                <div id="equipo-update">
                    <div style="float:right;">

                        <a class="btn btn-primary btn-sm" href="<?= $this->url('wizard') . '/'. $sedeId; ?>/2" role="button" title="Agregar equipo">
                            <i class="glyphicon glyphicon-plus"></i>
                        </a>
                    </div>    
                    <div style="clear: both;"></div>
            
        
        <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
                 
                <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>Nivel</th>
                            <th>Servicio</th>
                            <?php if('Cliente' != $userRole) : ?>
                                <th>Nemónico</th>
                                <th>IP Gestión</th>
                            <?php endIf; ?>
                            <th>Modelo</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $row = 1; ?>
                        <?php foreach($this->information['equiposall'] as $equipo) : ?> 
                        <tr id="<?= $equipo['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                            <td><?= ($equipo['parent_id']==0)?'PRINCIPAL':'BACKUP' ?></td>
                            <td><?= $equipo['nivel'] ?></td>
                            <td><?= $equipo['servicio'] ?></td>
                            <?php if('Cliente' != $userRole) : ?>
                                <?php if($equipo['nemonico'] == $this->value ) : ?>
                                    <td class="<?= ($this->item == 4)?'item-selected':''; ?>" style="<?= ($this->item == 4)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $equipo['nemonico']; ?></td>
                                <?php else: ?>
                                    <td><?= $equipo['nemonico']; ?></td>
                                <?php endif; ?>
                            
                               <?php if($equipo['ip_gestion'] == $this->value ) : ?>     
                                    <td class="<?= ($this->item == 5)?'item-selected':''; ?>" style="<?= ($this->item == 5)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $equipo['ip_gestion']; ?></td>                                    
                                <?php else: ?>    
                                    <td><?= $equipo['ip_gestion'] ?></td>
                                <?php endif; ?>
                                
                            <?php endIf; ?>
                            <td><?= $equipo['modelo'] ?></td>
                            <td> 
                                <?php if(0==$equipo['parent_id']) : ?>
                                <a class="btn btn-primary btn-xs" href="#" onclick="equipoFill('<?= $this->sedeId; ?>', '<?= $equipo['id'] ?>');" title="Consultar equipo">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                                <?php else : ?>
                                <span style="margin-left: 20px;">&nbsp;</span>
                                <?php endif; ?>
                                
                                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo" data-toggle="modal" data-nemonico="<?= $equipo['nemonico']; ?>" data-ip="<?= $equipo['ip_gestion']; ?>" data-servicio="<?= $equipo['servicio']; ?>" data-id="<?= $equipo['id']; ?>" data-parent="<?= $equipo['parent_id']; ?>" data-target="#deleteEquipo">    
                                    <i class="glyphicon glyphicon-minus"></i>
                                </a>
                            </td>  
                        </tr>
                        <?php $row++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div style="clear: both;"></div>

    <?php if(isset($this->information['equipos']['0'])) : ?>        
            <div>
                <button id="ipwan" type="button" title="Direccionamiento Wan" class="btn btn-primary" onclick="ipwanFill();">Direccionamiento WAN</button>
                <button id="iplan" type="button" title="Direccionamiento Lan" class="btn btn-primary" onclick="iplanFill();">Direccionamiento LAN</button>
                <button id="ha"    type="button" title="Hardware Adicional" class="btn btn-primary" onclick="haFill();">Hardware Adicional</button>
                <button id="he"    type="button" title="Hardware Especial" class="btn btn-primary" onclick="heFill();">Hardware RPV 13918</button>
                <button id="mc"    type="button" title="Configuración Multicast" class="btn btn-primary" onclick="mcFill();">Configuración Multicast</button>
            </div> 
        
            <div id="equipo-fill">
        <div id="ipwan-fill">
    <div class="panel panel-default">
    <div class="panel-body">
        <fieldset class="col-md-12">    	
            <legend>EQUIPO GESTIONADO</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                            <div class="form-group">
                                <label class="control-label" for="circuito">Administrativo</label>
                                <?= $this->information['htmlcombobox']['0']; ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="servicio">Servicio</label>
                                <?php $form->get('eservicio')->setValue($this->information['equipos']['0']['servicioId']) ?>
                                <?= $this->formSelect($form->get('eservicio')); ?>
                            </div>
                            
                            <?php if('Cliente' != $userRole) : ?>
                                <div class="form-group">
                                    <label class="control-label" for="nemonico">Nemónico</label>
                                    <?php 
                                        $form->get('enemonico')->setValue($this->information['equipos']['0']['nemonico']);
                                        if($this->information['equipos']['0']['nemonico'] == $this->value) {
                                            $form->get('enemonico')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                            $form->get('enemonico')->setAttribute('title','Dato encontrado');
                                        }
                                    ?>
                                    <?= $this->formInput($form->get('enemonico')); ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="ip-gestion">IP Gestión</label>
                                    <?php 
                                        $form->get('eipgestion')->setValue($this->information['equipos']['0']['ip_gestion']);
                                        if($this->information['equipos']['0']['ip_gestion'] == $this->value) {
                                            $form->get('eipgestion')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                            $form->get('eipgestion')->setAttribute('title','Dato encontrado');
                                        }
                                    ?>
                                    <?= $this->formInput($form->get('eipgestion')); ?>
                                </div>
                            <?php endIf; ?>
                        
                            <div class="form-group">
                                <label class="control-label" for="nivel">Nivel</label>
                                <?php $form->get('enivel')->setValue($this->information['equipos']['0']['nivel']) ?>
                                <?= $this->formSelect($form->get('enivel')); ?>
                                
                            </div>
                            <?php if('Cliente' != $userRole) : ?>
                            <div class="form-group">
                                <label class="control-label" for="nemonico-n1">Nemónico N1</label>
                                <?php # $form->get('enemonicon1')->setValue($this->information['equipos']['0']['nemonico_nivel1']) ?>
                                <?php # $this->formSelect($form->get('enemonicon1')); ?>
                                <?= $this->information['htmlcombobox3']['0']; ?>
                            </div>
                            <?php endIf; ?>
                            <div class="form-group">
                                <label class="control-label" for="fabricante">Fabricante</label>
                                <?php $form->get('efabricante')->setValue($this->information['equipos']['0']['fabricanteId']) ?>
                                <?= $this->formSelect($form->get('efabricante')); ?>
                            </div>
                            <div id="ajax-modelo">
                                <div class="form-group">
                                    <label class="control-label" for="exampleSelect1">Modelo</label>
                                    <?php $form->get('emodelo')->setValue($this->information['equipos']['0']['modeloId']) ?>
                                    <?= $this->formSelect($form->get('emodelo')); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="serie">N/S</label>
                                <?php $form->get('eserie')->setValue($this->information['equipos']['0']['numero_serie']) ?>
                               <?= $this->formInput($form->get('eserie')); ?>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="locert">Locert</label>
                                <?php $form->get('elocert')->setValue($this->information['equipos']['0']['locert']) ?>
                               <?= $this->formInput($form->get('elocert')); ?>
                            </div>

                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="ubicacion">Ubicación</label>
                            <?php $form->get('eubicacion')->setValue($this->information['equipos']['0']['ubicacion']) ?>
                            <?= $this->formInput($form->get('eubicacion')); ?>
                        </div>
                        <?php if('Cliente' != $userRole) : ?>
                        <div class="form-group">
                            <label class="control-label" for="logos-alta">Pedido LOGOS Alta</label>
                            <?php $form->get('elogosalta')->setValue($this->information['equipos']['0']['pedido_logos_alta']) ?>
                            <?= $this->formInput($form->get('elogosalta')); ?>
                        </div>    
                        <?php endIf; ?>
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo">Contacto</label>
                            <?php $form->get('econtacto')->setValue($this->information['equipos']['0']['contacto']) ?>
                            <?= $this->formInput($form->get('econtacto')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="telefono-equipo">Teléfono</label>
                            <?php $form->get('etelefono')->setValue($this->information['equipos']['0']['telefono']) ?>
                            <?= $this->formInput($form->get('etelefono')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo-horario">Horario</label>
                            <?php $form->get('ehorario')->setValue($this->information['equipos']['0']['horario']) ?>
                            <?= $this->formInput($form->get('ehorario')); ?>
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="estado-equipo">Estado</label>
                            <?php $form->get('eestado')->setValue($this->information['equipos']['0']['estadoId']) ?>
                            <?= $this->formSelect($form->get('eestado')); ?>
                        </div>
                        <?php if('Cliente' != $userRole) : ?>
                         <div class="form-group">
                            <label class="control-label" for="observacion-equipo">Observaciones</label>
                            <?php $form->get('eobservacion')->setValue($this->information['equipos']['0']['observacion']);
                            #$form->get('observacion')->setAttribute('rows', 1);  ?>
                            <?= $this->formTextarea($form->get('eobservacion')); ?>
                        </div>
                        <?php endIf; ?>
                        <div class="form-check">
                            <label class="form-check-label"> 
                                <?php $ebackup = $this->information['equipos']['0']['tiene_backup']; ?>
                                <input id="ebackup" name="ebackup" type="checkbox" value="1" class="form-check-input" <?= ($ebackup)?'checked':'' ?>>
                              ¿Tiene Backup?
                            </label>
                        </div>
                        
                    </div>    
                
                </div>
                
                <!-- EQUIPO BACKUP -->
                    <div id="equipo-backup" class="panel-body" style="display:none;">
        <fieldset class="col-md-12">    	
            <legend>EQUIPO GESTIONADO BCK</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label class="control-label" for="circuito-equipo-backup">Administrativo</label>
                            <?php if(isset($this->information['htmlcombobox']['1'])) : ?>
                                <?= $this->information['htmlcombobox']['1']; ?>
                            <?php else: ?>
                                <?= $this->comboBoxCircuitoBck; ?>
                            <?php endif; ?>
                        </div>

                            <div class="form-group">
                                <label class="control-label" for="servicio">Servicio</label>
                                <?php if(isset($this->information['equipos']['1']['servicioId'])) {
                                    $form->get('beservicio')->setValue($this->information['equipos']['1']['servicioId']);
                                }
                                ?>
                                <?= $this->formSelect($form->get('beservicio')); ?>
                            </div>
                            <?php if('Cliente' != $userRole) : ?>
                            <div class="form-group">
                                <label class="control-label" for="nemonico">Nemónico</label>
                                <?php if(isset($this->information['equipos']['1']['nemonico'])) {
                                    $form->get('benemonico')->setValue($this->information['equipos']['1']['nemonico']);
                                    if($this->information['equipos']['1']['nemonico'] == $this->value) {
                                        $form->get('benemonico')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                    }
                                    }
                                ?>
                                <?= $this->formInput($form->get('benemonico')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ip-gestion">IP Gestión</label>
                                <?php if(isset($this->information['equipos']['1']['ip_gestion'])) {
                                    $form->get('beipgestion')->setValue($this->information['equipos']['1']['ip_gestion']);
                                    if($this->information['equipos']['1']['ip_gestion'] == $this->value) {
                                        $form->get('beipgestion')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                    }
                                }
                                ?>
                                <?= $this->formInput($form->get('beipgestion')); ?>
                            </div>
                            <?php endIf; ?>
                            <div class="form-group">
                                <label class="control-label" for="nivel">Nivel</label>
                                <?php if(isset($this->information['equipos']['1']['nivel'])) {
                                    $form->get('benivel')->setValue($this->information['equipos']['1']['nivel']);
                                }
                                ?>                                
                                <?= $this->formSelect($form->get('benivel')); ?>
                            </div>
                            <?php if('Cliente' != $userRole) : ?>
                            <div class="form-group">
                                <label class="control-label" for="nemonico-n1">Nemónico N1</label>
                                <?php
//                                if(isset($this->information['equipos']['1']['nemonico_nivel1'])) {
//                                    $form->get('benemonicon1')->setValue($this->information['equipos']['1']['nemonico_nivel1']);
//                                }
                                ?>                                
                                
                                <?php # $this->formSelect($form->get('benemonicon1')); ?>
                                
                                <?php   
                                    if (isset($this->information['htmlcombobox3']['1'])) {
                                        echo $this->information['htmlcombobox3']['1'];
                                    } else {
                                        echo $this->information['htmlcombobox3']['0'];
                                    }
                                ?>
                            </div>
                            <?php endIf; ?>
                            <div class="form-group">
                                <label class="control-label" for="fabricante">Fabricante</label>
                                <?php if(isset($this->information['equipos']['1']['fabricanteId'])) {
                                    $form->get('befabricante')->setValue($this->information['equipos']['1']['fabricanteId']);
                                }
                                ?>
                                <?= $this->formSelect($form->get('befabricante')); ?>
                            </div>
                            <div id="ajax-modelo-backup">
                                <div class="form-group">
                                    <label class="control-label" for="modelo">Modelo</label>
                                    <?php if(isset($this->information['equipos']['1']['modeloId'])) {
                                        $form->get('bemodelo')->setValue($this->information['equipos']['1']['modeloId']);
                                    }
                                    ?>
                                    <?= $this->formSelect($form->get('bemodelo')); ?>
                                </div>
                            </div>    
                            <div class="form-group">
                                <label class="control-label" for="numero-serie">S/N</label>
                                <?php if(isset($this->information['equipos']['1']['numero_serie'])) {
                                    $form->get('beserie')->setValue($this->information['equipos']['1']['numero_serie']);
                                }
                                ?>
                                <?= $this->formInput($form->get('beserie')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="locert">Locert</label>
                                <?php if(isset($this->information['equipos']['1']['locert'])) {
                                    $form->get('belocert')->setValue($this->information['equipos']['1']['locert']);
                                }
                                ?>
                                <?= $this->formInput($form->get('belocert')); ?>
                            </div>
                        
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="ubicacion">Ubicación</label>
                            <?php if(isset($this->information['equipos']['1']['ubicacion'])) {
                                $form->get('beubicacion')->setValue($this->information['equipos']['1']['ubicacion']);
                            }
                            ?>
                            <?= $this->formInput($form->get('beubicacion')); ?>
                        </div>
                        <?php if('Cliente' != $userRole) : ?>
                        <div class="form-group">
                            <label class="control-label" for="logos-alta">Pedido LOGOS Alta</label>
                            <?php if(isset($this->information['equipos']['1']['pedido_logos_alta'])) {
                                $form->get('belogosalta')->setValue($this->information['equipos']['1']['pedido_logos_alta']);
                            }
                            ?>
                            <?= $this->formInput($form->get('belogosalta')); ?>
                        </div>    
                        
                        <div class="form-group">
                            <label class="control-label" for="observacion-equipo">Observaciones</label>
                            <?php if(isset($this->information['equipos']['1']['observacion'])) {
                                $form->get('beobservacion')->setValue($this->information['equipos']['1']['observacion']);
                            }
                            ?>
                            
                            <?= $this->formTextarea($form->get('beobservacion')); ?>
                        </div>
                        <?php endIf; ?>
                    </div>    
                </div>
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>

            <!-- EQUIPOS BACKUP -->
                
            </div>
        
            <div class="clearfix"></div>
            <div style="float:right; padding-top: 14px; padding-bottom: 14px;">
                <a class="btn btn-primary btn-sm update-equipo" href="#" role="button" onclick="updateEquipos();" title="Update equipo">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>
            
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
</div>        
        </div>
        <input type="hidden" id="equipoId" name="equipoId" value="<?=  $this->information['equipos']['0']['id']; ?>">
        <?php if(isset($this->information['equipos']['1']['id'])) : ?>
        <input type="hidden" id="equipoBckId" name="equipoBckId" value="<?=  $this->information['equipos']['1']['id']; ?>">
        <?php  endif; ?>
        <input type="hidden" id="equipoContactoId" name="equipoContactoId" value="<?=  $this->information['equipos']['0']['contactoId']; ?>">
          <!-- FIN -->
            
                </div>      
    
          
          
    <?php endIf; ?>
    </div> <!-- UPDATE -->      
          <!-- POZOR!!!! -->

          
            </div>
        </div>
        <div class="tab-pane fade in <?= ($this->tab == 2)?'active':''; ?>" id="tab3">
            <div id="delete-equipo-not-management">
                    <input type="hidden" id="deleteEquipoNotManagementId" name="deleteEquipoNotManagementId" value="">
                    <input type="hidden" id="deleteEquipoNotManagementSedeId" name="deleteEquipoNotManagementSedeId" value="<?= $this->information['sede']['id'] ;?>">
                <div id="equipo-not-update">        
                    <div style="float:right;">

                        <a class="btn btn-primary btn-sm" href="<?= $this->url('wizard') . '/'. $sedeId; ?>/3" role="button" title="Agregar equipo no gestionado">
                            <i class="glyphicon glyphicon-plus"></i>
                        </a>

                    </div>
            <div style="clear: both;"></div>

            <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
                 
                <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Propiedad Router</th>
                            <th>Tipo IP</th>
                            <th>IP Cliente</th>
                            <th>Red</th>
                            <th>Usos</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $row = 1; ?>
                        <?php foreach($this->information['notequiposall'] as $notequipo) : ?> 
                        <tr id="<?= $notequipo['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                            <td><?= $notequipo['propiedad'] ?></td>
                            <td><?= $notequipo['tipo'] ?></td>
                            <?php if($notequipo['ip'] == $this->value ) : ?>     
                                    <td class="<?= ($this->item == 5)?'item-selected':''; ?>" style="<?= ($this->item == 5)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $notequipo['ip']; ?></td>                                    
                            <?php else: ?>    
                                    <td><?= $notequipo['ip'] ?></td>
                            <?php endif; ?>
                            <td><?= $notequipo['red'] ?></td>
                            <td><?= $notequipo['uso'] ?></td>
                            <td> 
                                <a class="btn btn-primary btn-xs" href="#" onclick="notequipoFill('<?= $this->sedeId; ?>', '<?= $notequipo['id'] ?>');" title="Consultar equipo">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo no gestionado" data-toggle="modal" data-id="<?= $notequipo['id']; ?>" data-target="#deleteEquipoNotManagement">    
                                    <i class="glyphicon glyphicon-minus"></i>
                                </a>
                            </td>  
                        </tr>
                        <?php $row++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div style="clear: both;"></div>

    <?php if(isset($this->information['notequipos']['0'])) : ?>        
              
        <div id="equipo-not-fill">
        
        <div class="panel panel-default">
            <div class="panel-body">        
        
                <fieldset class="col-md-12">    	
                <legend>EQUIPO NO GESTIONADO</legend>
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="col-lg-6">    
                            <div id="form-step-3" role="form" data-toggle="validator">
                                
                                <div class="form-group">
                                    <label class="control-label" for="circuito">Administrativo</label>
                                    <?= $this->information['htmlcombobox2']['0']; ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="engservicio">Servicio</label>
                                    <?php $form->get('engservicio')->setValue($this->information['notequipos']['0']['servicio_id']) ?>
                                    <?= $this->formSelect($form->get('engservicio')); ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="engpropiedad">Propiedad Router</label>
                                    <?php $form->get('engpropiedad')->setValue($this->information['notequipos']['0']['propiedad_id']) ?>
                                    <?= $this->formSelect($form->get('engpropiedad')); ?>
                                </div>                        

                                <div class="form-group">
                                    <label class="control-label" for="tipo-ip">Tipo IP</label>
                                    <?php $form->get('engtipoip')->setValue($this->information['notequipos']['0']['tipo_ip']); ?>
                                    <?= $this->formSelect($form->get('engtipoip')); ?>                            
                                </div>                        

                                <div class="form-group">
                                    <label class="control-label" for="ip-no-gestionado">IP</label>
                                    <?php 
                                        $form->get('engip')->setValue($this->information['notequipos']['0']['ip']);
                                        if($this->information['notequipos']['0']['ip'] == $this->value) {
                                            $form->get('engip')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                            $form->get('engip')->setAttribute('title','Dato encontrado');
                                        }
                                    ?>
                                    <?= $this->formInput($form->get('engip')); ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="red">Red</label>
                                    <?php $form->get('engred')->setValue($this->information['notequipos']['0']['red_id']) ?>
                                    <?= $this->formSelect($form->get('engred')); ?>                                
                                </div>
                                <div id="ajax-usos">
                                    <div class="form-group">
                                        <label class="control-label" for="usos">Usos</label>
                                        <?php $form->get('enguso')->setValue($this->information['notequipos']['0']['uso_id']) ?>    
                                        <?= $this->formSelect($form->get('enguso')); ?>                            
                                    </div>
                                </div>    
                            </div>
                        </div>    
                    
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-no-gestionado">Contacto</label>
                            <?php $form->get('engcontacto')->setValue($this->information['notequipos']['0']['contacto']) ?>
                            <?= $this->formInput($form->get('engcontacto')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="telefono-no-gestionado">Teléfono</label>
                            <?php $form->get('engtelefono')->setValue($this->information['notequipos']['0']['telefono']) ?>
                            <?= $this->formInput($form->get('engtelefono')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="horario-no-gestionado">Horario</label>
                            <?php $form->get('enghorario')->setValue($this->information['notequipos']['0']['horario']) ?>
                            <?= $this->formInput($form->get('enghorario')); ?>
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="observacion-no-gestionado">Observaciones</label>
                            <?php $form->get('engobservacion')->setValue($this->information['notequipos']['0']['observacion']) ?>    
                            <?= $this->formTextarea($form->get('engobservacion')); ?>
                        </div>
                        
                    </div>    
                
                </div>

            </div>
            
            <div class="clearfix"></div>                
                        
            <div style="float:right; padding-top: 14px; padding-bottom: 14px;">
                <a class="btn btn-primary btn-sm update-notequipo" href="#" role="button" onclick="updateNotEquipos();" title="Update equipo no gestionado">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>     

        </fieldset>				

    </div>
    </div>        
            
        <input type="hidden" id="notEquipoId" name="notEquipoId" value="<?=  $this->information['notequipos']['0']['id']; ?>">
        <input type="hidden" id="notEquipoContactoId" name="notEquipoContactoId" value="<?=  $this->information['notequipos']['0']['contacto_id']; ?>">
          
    </div>        
            
            
    <?php endif; ?>        
            

            
            </div>
            
            <!-- HASTA AQUIIIIIIIIIIIIIIIIIII -->    
        
            </div>
        </div>
        <div class="tab-pane fade in <?= ($this->tab == 3)?'active':''; ?>" id="tab4">
          

            <div style="float:right;">

                <a class="btn btn-primary btn-sm" href="#" onclick="addGlan();" role="button" title="Agregar equipo glan">
                    <i class="glyphicon glyphicon-plus"></i>
                </a>

            </div>
            <div style="clear: both;"></div>

            <div id="delete-glan">
                <input type="hidden" id="deleteGlanId" name="deleteGlanId" value="">
                <input type="hidden" id="deleteGlanSedeId" name="deleteGlanSedeId" value="<?= $this->information['sede']['id'] ;?>">
            
                    <div id="save-glan">
                        <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">

                            <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                                <thead>
                                    <tr>
                                        <th>Cliente</th>
                                        <th>Función</th>
                                        <th>Nemónico</th>
                                        <th>Modelo</th>
                                        <th>S/N</th>
                                        <th>IP Gestión</th>
                                        <th>Criticidad</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $row = 1; ?>
                                    <?php foreach($this->information['glansall'] as $glan) : ?> 
                                    <tr id="<?= $glan['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                                        <td><?= $glan['cliente'] ?></td>
                                        <td><?= $glan['funcion'] ?></td>
                                        <?php if($glan['nemonico'] == $this->value ) : ?>     
                                                <td class="<?= ($this->item == 4)?'item-selected':''; ?>" style="<?= ($this->item == 4)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $glan['nemonico']; ?></td>                                    
                                        <?php else: ?>    
                                                <td><?= $glan['nemonico'] ?></td>
                                        <?php endif; ?>
                                        <td><?= $glan['modelo_equipo'] ?></td>
                                        <td><?= $glan['numero_serie'] ?></td>
                                        <?php if($glan['ip_gestion'] == $this->value ) : ?>     
                                                <td class="<?= ($this->item == 5)?'item-selected':''; ?>" style="<?= ($this->item == 5)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $glan['ip_gestion']; ?></td>                                    
                                        <?php else: ?>    
                                                <td><?= $glan['ip_gestion'] ?></td>
                                        <?php endif; ?>
                                        <td><?= $glan['criticidad'] ?></td>
                                        <td> 
                                            <a class="btn btn-primary btn-xs" href="#" onclick="glanFill('<?= $glan['id'] ?>');" title="Consultar equipo glan">
                                                <i class="glyphicon glyphicon-eye-open"></i>
                                            </a>
                                            <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo glan" data-toggle="modal" data-id="<?= $glan['id']; ?>" data-target="#deleteGlanEquipo">
                                                <i class="glyphicon glyphicon-minus"></i>
                                            </a>
                                        </td>  
                                    </tr>
                                    <?php $row++; ?>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>

                        <div style="clear: both;"></div>

            
              
                        <div id="glan-fill">
                            <?php if(isset($this->information['glans']['0'])) : ?>
                            <!-- INICIO GLAN -->
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <fieldset class="col-md-12">
                                        <legend>GLAN</legend>
                                        <div class="panel panel-default">
                                            <div class="panel-body">

                                                <div class="col-lg-6">
                                                    <input type="hidden" id="glanEquipoId" name="glanEquipoId" value="<?= $this->information['glans']['0']['id']; ?>">
                                                    <input type="hidden" id="glanContactoId" name="glanContactoId" value="<?= $this->information['glans']['0']['contactoId']; ?>">
                                                    <div class="form-group">
                                                        <label class="control-label" for="contrato-fabricante">Contrato Fabricante</label>
                                                        <?php $form->get('gconfab')->setValue($this->information['glans']['0']['contrato_fabricante']); ?>
                                                        <?= $this->formInput($form->get('gconfab')); ?>
                                                    </div>
                                                    
                                                    <div class="form-group">
                                                        <label class="control-label" for="actividad-tsol">Actividad TSOL</label>
                                                        <?php $form->get('gactsol')->setValue($this->information['glans']['0']['actividad_tsol']); ?>
                                                        <?= $this->formInput($form->get('gactsol')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="modelo-equipo">Modelo Equipo</label>
                                                        <?php $form->get('gmodeloequipo')->setValue($this->information['glans']['0']['modelo_equipo']); ?>
                                                        <?= $this->formInput($form->get('gmodeloequipo')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="familia-fabricante">Familia Fabricante</label>
                                                        <?php $form->get('gfamfab')->setValue($this->information['glans']['0']['familia_fabricante']); ?>
                                                        <?= $this->formInput($form->get('gfamfab')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-nemonico">Nemónico</label>
                                                        <?php
                                                            $form->get('gnemonico')->setValue($this->information['glans']['0']['nemonico']);
                                                            if($this->information['glans']['0']['nemonico'] == $this->value) {
                                                                $form->get('gnemonico')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                                                $form->get('gnemonico')->setAttribute('title','Dato encontrado');
                                                            }
                                                        ?>
                                                        <?= $this->formInput($form->get('gnemonico')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="ip-gestion">IP Gestión</label>
                                                        <?php 
                                                            $form->get('gipgestion')->setValue($this->information['glans']['0']['ip_gestion']); 
                                                            if($this->information['glans']['0']['ip_gestion'] == $this->value) {
                                                                $form->get('gipgestion')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                                                $form->get('gipgestion')->setAttribute('title','Dato encontrado');
                                                            }
                                                        ?>
                                                        <?= $this->formInput($form->get('gipgestion')); ?>
                                                    </div>
                                                    
                                                    <div class="form-group">
                                                        <label class="control-label" for="ip-gestion-cliente">IP Gestión Cliente</label>
                                                        <?php
                                                            $form->get('gipgestioncliente')->setValue($this->information['glans']['0']['ip_gestion_cliente']);
                                                            if($this->information['glans']['0']['ip_gestion_cliente'] == $this->value) {
                                                                $form->get('gipgestioncliente')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                                                $form->get('gipgestioncliente')->setAttribute('title','Dato encontrado');
                                                            }
                                                        ?>
                                                        <?= $this->formInput($form->get('gipgestioncliente')); ?>
                                                    </div>


                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-firmware">Firmware</label>
                                                        <?php $form->get('gfirmware')->setValue($this->information['glans']['0']['firmware']); ?>
                                                        <?= $this->formInput($form->get('gfirmware')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-mac">MAC</label>
                                                        <?php 
                                                            $form->get('gmac')->setValue($this->information['glans']['0']['mac']); 
                                                            if($this->information['glans']['0']['mac'] == $this->value) {
                                                                $form->get('gmac')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                                                $form->get('gmac')->setAttribute('title','Dato encontrado');
                                                            }
                                                        
                                                        ?>
                                                        <?= $this->formInput($form->get('gmac')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-numeroserie">Número Serie</label>
                                                        <?php $form->get('gnumeroserie')->setValue($this->information['glans']['0']['numero_serie']); ?>
                                                        <?= $this->formInput($form->get('gnumeroserie')); ?>
                                                    </div>

                                                    
                                                    <div class="form-group">
                                                        <label class="control-label" class="form-check-label">
                                                            <?php $isStack = $this->information['glans']['0']['tiene_stack']; ?>
                                                            <input id="gisstack" name="gisstack" type="checkbox" value="1" class="form-check-input" <?= ($isStack)?'checked':''; ?>>
                                                            ¿Tiene stack?
                                                        </label>
                                                        <!--<label class="control-label" for="glan-stack">Stack</label>-->
                                                         <?php $form->get('gstack')->setValue($this->information['glans']['0']['stack']); ?>
                                                        <?= $this->formInput($form->get('gstack')); ?>
                                                    </div>

                                                </div>    

                                                <div class="col-lg-6">    

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-cliente">Cliente</label>
                                                        <?php $form->get('gcliente')->setValue($this->information['glans']['0']['clienteId']); ?>
                                                        <?= $this->formSelect($form->get('gcliente')); ?>
                                                    </div>
                                                    
                                                    <div class="form-group">
                                                        <label class="control-label" for="equipo-edc-wan">EDC WAN</label>
                                                        <?php # $this->information['htmlcomboboxglannemonico']['0']; ?>
                                                        <?php $form->get('gnemonicoequipo')->setValue($this->information['glans']['0']['equipoId']); ?>
                                                        <?= $this->formSelect($form->get('gnemonicoequipo')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-ubicacion">Ubicación</label>
                                                        <?php $form->get('gubicacion')->setValue($this->information['glans']['0']['ubicacion']); ?>
                                                        <?= $this->formInput($form->get('gubicacion')); ?>
                                                    </div>                                    

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-funcion">Función</label>
                                                        <?php $form->get('gfuncion')->setValue($this->information['glans']['0']['funcionId']); ?>
                                                        <?= $this->formSelect($form->get('gfuncion')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-criticidad">Criticidad</label>
                                                        <?php $form->get('gcriticidad')->setValue($this->information['glans']['0']['criticidadId']) ?>
                                                        <?= $this->formSelect($form->get('gcriticidad')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-estado">Estado</label>
                                                        <?php $form->get('gestado')->setValue($this->information['glans']['0']['estadoId']) ?>
                                                        <?= $this->formSelect($form->get('gestado')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="contacto-glan">Contacto</label>
                                                        <?php $form->get('gcontacto')->setValue($this->information['glans']['0']['contacto']) ?>
                                                        <?= $this->formInput($form->get('gcontacto')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="telefono-glan">Teléfono</label>
                                                        <?php $form->get('gtelefono')->setValue($this->information['glans']['0']['telefono']) ?>
                                                        <?= $this->formInput($form->get('gtelefono')); ?>
                                                    </div>

                                                    <div class="form-group">
                                                        <label class="control-label" for="glan-observaciones">Observaciones</label>
                                                        <?php $form->get('gobservacion')->setValue($this->information['glans']['0']['observaciones']) ?>    
                                                        <?= $this->formTextarea($form->get('gobservacion')); ?>
                                                    </div>
                                                    
                                                    <div style="float:right; margin-top: 20px;">
                                                        <a class="btn btn-primary btn-sm update-sede" href="#" role="button" onclick="updateGlan();" title="Update Glan">
                                                            <i class="glyphicon glyphicon-edit"></i>
                                                        </a>
                                                    </div>                
                                                    
                                                </div>    

                                            </div>

                                            <!-- Inicio -->
                                            <div id="modulo-glan" class="panel-body">
                                                <fieldset class="col-md-12">    	
                                                    <legend>MÓDULO ADICIONALES</legend>
                                                    <div class="panel panel-default">
                                                        <div class="panel-body">
                                                            <div Id="save-component">    
                                                            <div style="float:right;">

                                                                <a class="btn btn-primary btn-sm" href="#" role="button" onclick="addComponent('<?= $this->information['glans']['0']['id']; ?>');" title="Agregar módulo(tab)">
                                                                    <i class="glyphicon glyphicon-plus"></i>
                                                                </a>

                                                            </div>
                                                            <div style="clear: both;"></div>                            

                                                            <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">

                                                                <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                                                                    <thead>
                                                                        <tr>
                                                                            <th style="width:30%;">Componente</th>
                                                                            <th style="width:30%;">Módelo</th>
                                                                            <th style="width:30%;">S/N</th>
                                                                            <th style="width:10%;">Acciones</th>
                                                                        </tr>
                                                                    </thead>
                                                                    <tbody>
                                                                        <?php $row = 1; ?>
                                                                        <?php foreach($this->information['componentesall'] as $component) : ?> 
                                                                        <tr id="<?= $component['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                                                                            <td><?= $component['tipo'] ?></td>
                                                                            <td><?= $component['modelo'] ?></td>
                                                                            <td><?= $component['numero_serie'] ?></td>
                                                                            <td> 
                                                                                <a class="btn btn-primary btn-xs" href="#" onclick="componentFill('<?= $this->sedeId; ?>', '<?= $glan['id'] ?>');" title="Consultar equipo">
                                                                                    <i class="glyphicon glyphicon-eye-open"></i>
                                                                                </a>
                                                                                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo">
                                                                                    <i class="glyphicon glyphicon-minus"></i>
                                                                                </a>
                                                                            </td>  
                                                                        </tr>
                                                                        <?php $row++; ?>
                                                                        <?php endforeach; ?>
                                                                    </tbody>
                                                                </table>
                                                            </div>
                                                           
                                                            <div id="component-fill">
                                                                <?php if(isset($this->information['componentes']['0'])) : ?> 
                                                                <div class="col-lg-6">    

                                                                    <div class="form-group">
                                                                        <label class="control-label" for="componente-tipo">Componente</label>
                                                                        <?php $form->get('ctipo')->setValue($this->information['componentes']['0']['tipoId']) ?>
                                                                        <?= $this->formSelect($form->get('ctipo')); ?>
                                                                    </div>

                                                                    <div class="form-group">
                                                                        <label class="control-label" for="componente">Módelo</label>
                                                                        <?php $form->get('cmodelo')->setValue($this->information['componentes']['0']['modeloId']); ?>
                                                                         <?= $this->formSelect($form->get('cmodelo')); ?>
                                                                    </div>

                                                                </div>

                                                                <div class="col-lg-6">    

                                                                    <div class="form-group">
                                                                        <label class="control-label" for="component-numeroserie">N/S</label>
                                                                        <?php $form->get('cnumeroserie')->setValue($this->information['componentes']['0']['numero_serie']); ?>
                                                                        <?= $this->formInput($form->get('cnumeroserie')); ?>
                                                                    </div>

                                                                </div>
                                                                <?php endif ?>
                                                            </div>
                                                            </div>    
                                                        </div> 

                                                    </div>

                                                    </fieldset>				
                                                    <div class="clearfix"></div>
                                                </div>
                                                <!-- Fin -->
                                            </div>
                                        </fieldset>				
                                        <div class="clearfix"></div>
                                    </div>
                                </div>            

                        <!-- FIN GLAN-->
                        <?php endif; ?>    
                    </div>


                </div>  
            </div>
        </div>
        <div class="tab-pane fade in <?= ($this->tab == 4)?'active':''; ?>" id="tab5">

            <div style="float:right;">

                <a class="btn btn-primary btn-sm" href="#" role="button" onclick="addAp();" title="Agregar APs">
                    <i class="glyphicon glyphicon-plus"></i>
                </a>

            </div>
            <div style="clear: both;"></div>
        <div id="delete-ap">
            <input type="hidden" id="deleteApId" name="deleteApId" value="">
            <input type="hidden" id="deleteApSedeId" name="deleteApSedeId" value="<?= $this->information['sede']['id'] ;?>">
            
            <div id="save-ap">
            <!-- AP -->    
            <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
                 
                <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>IP Cliente</th>
                            <th>ID AP</th>
                            <th>Modelo</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $row = 1; ?>
                        <?php foreach($this->information['apsall'] as $ap) : ?> 
                        <tr id="<?= $ap['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                            <td><?= $ap['nombre'] ?></td>
                        
                            <?php if($ap['ip_cliente'] == $this->value ) : ?>     
                                <td class="<?= ($this->item == 51)?'item-selected':''; ?>" style="<?= ($this->item == 51)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $ap['ip_cliente']; ?></td>                                    
                            <?php else: ?>    
                                <td><?= $ap['ip_cliente'] ?></td>
                            <?php endif; ?>
                            <?php if($ap['id_ap'] == $this->value ) : ?>     
                                <td class="<?= ($this->item == 52)?'item-selected':''; ?>" style="<?= ($this->item == 52)?'background-color: red; cursor:pointer;':''; ?>" title="Dato encontrado"><?= $ap['id_ap']; ?></td>                                    
                            <?php else: ?>    
                                <td><?= $ap['id_ap'] ?></td>
                            <?php endif; ?>
                            <td><?= $ap['modelo'] ?></td>
                            <td> 
                                <a class="btn btn-primary btn-xs" href="#" onclick="apFill('<?= $ap['id'] ?>');" title="Consultar AP">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                                </a>
                                <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo AP" data-toggle="modal" data-id="<?= $ap['id']; ?>" data-target="#deleteApEquipo">
                                    <i class="glyphicon glyphicon-minus"></i>
                                </a>
                            </td>  
                        </tr>
                        <?php $row++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            
            <div style="clear: both;"></div>
            <div id="ap-fill">
                <?php if(isset($this->information['aps']['0'])) : ?>
                    <!-- INICIO AP -->
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <fieldset class="col-md-12">
                                <legend>AP</legend>
                                <div class="panel panel-default">
                                    <div class="panel-body">

                                        <div class="col-lg-6">
                                            <input type="hidden" id="glanEquipoId" name="apEquipoId" value="<?= $this->information['aps']['0']['id']; ?>">
                                            <div class="form-group">
                                                <label class="control-label" for="switch">Switch</label>
                                                <?php $form->get('apswitch')->setValue($this->information['aps']['0']['switchId']); ?>
                                                <?= $this->formSelect($form->get('apswitch')); ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="contrato-extreme">Contrato Extreme</label>
                                                <?php $form->get('apcontratoextreme')->setValue($this->information['aps']['0']['contrato_extreme']); ?>
                                                <?= $this->formInput($form->get('apcontratoextreme')); ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="ap-nombre">Nombre</label>
                                                <?php $form->get('apnombre')->setValue($this->information['aps']['0']['nombre']); ?>
                                                <?= $this->formInput($form->get('apnombre')); ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="ap-ipcliente">IP Cliente</label>
                                                <?php 
                                                    $form->get('apipcliente')->setValue($this->information['aps']['0']['ip_cliente']);
                                                    if($this->information['aps']['0']['ip_cliente'] == $this->value) {
                                                        $form->get('apipcliente')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                                        $form->get('apipcliente')->setAttribute('title','Dato encontrado');
                                                    }
                                                ?>
                                                <?= $this->formInput($form->get('apipcliente')); ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="ap-idap">ID AP</label>
                                                <?php 
                                                    $form->get('apidap')->setValue($this->information['aps']['0']['id_ap']);
                                                    if($this->information['aps']['0']['id_ap'] == $this->value) {
                                                        $form->get('apidap')->setAttribute('style','color:white; font-weight: bold; background-color: red; cursor:pointer;');
                                                        $form->get('apidap')->setAttribute('title','Dato encontrado');
                                                    }
                                                ?>
                                                <?= $this->formInput($form->get('apidap')); ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="ap-red">Red</label>
                                                <table id="grid-red-ap" class="table table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th style="width:45%;">SSID</th>
                                                            <th style="width:5%;">Act.</th>
                                                            <th style="width:45%;">SSID</th>
                                                            <th style="width:5%;">Act.</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php
                                                            $esIntCorp = (int)$this->information['aps']['0']['es_internet_corporatiu'];
                                                            $esIntVisi = (int)$this->information['aps']['0']['es_internet_visites'];
                                                            $esDibaInt = (int)$this->information['aps']['0']['es_diba_intern'];
                                                            $esEspai = (int)$this->information['aps']['0']['es_espai_f_b'];
                                                            $esPda = (int)$this->information['aps']['0']['es_pda_pavnord'];
                                                            $esEscDona = (int)$this->information['aps']['0']['es_multimedia_escola_dona'];
                                                            $esPalauguell = (int)$this->information['aps']['0']['es_palauguell'];
                                                            $esResResp = (int)$this->information['aps']['0']['es_resident_respir'];
                                                         ?>
                                                        <tr class="row-input">
                                                            <td>Internet_corporatiu</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="apinetcorp" name="apinternetcorporatiu" value="1" class="form-check-input" <?= ($esIntCorp)?'checked':''; ?>>
                                                            </td>
                                                            <td>Internet_visites</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="apinternetvisites" name="apinternetvisites" value="1" class="form-check-input" <?= ($esIntVisi)?'checked':''; ?>>
                                                            </td>
                                                        </tr>
                                                        <tr class="row-input">
                                                            <td>Diba_intern</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="apdibaintern" name="apdibaintern" value="1" class="form-check-input" <?= ($esDibaInt)?'checked':''; ?>>
                                                            </td>
                                                            <td>Espai F.B</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="apespaifb" name="apespaifb" value="1" class="form-check-input" <?= ($esEspai)?'checked':''; ?>>
                                                            </td>
                                                        </tr>
                                                        <tr class="row-input">
                                                            <td>PDA_PavNord</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="appdapavnord" name="appdapavnord" value="1" class="form-check-input" <?= ($esPda)?'checked':''; ?>>
                                                            </td>
                                                            <td>Multimedia_Escola_Dona</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="apmultimediaescoladona" name="apmultimediaescoladona" value="1" class="form-check-input" <?= ($esEscDona)?'checked':''; ?>>
                                                            </td>
                                                        </tr>
                                                        <tr class="row-input">
                                                            <td>PalauGuell</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="appalauguell" name="appalauguell" value="1" class="form-check-input" <?= ($esPalauguell)?'checked':''; ?>>
                                                            </td>
                                                            <td>Resident_Respir</td>
                                                            <td style="text-align:center;">
                                                                <input type="checkbox" id="apresidentrespir" name="apresidentrespir" value="1" class="form-check-input" <?= ($esResResp)?'checked':''; ?>>
                                                            </td>
                                                        </tr>
                                                        
                                                        
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">    

                                            <div class="form-group">
                                                <label class="control-label" for="ap-actividad-tsol">Actividad TSOL</label>
                                                <?php $form->get('apactividadtsol')->setValue($this->information['aps']['0']['actividad_tsol']); ?>
                                                <?= $this->formInput($form->get('apactividadtsol')); ?>
                                            </div>                                    

                                            <div class="form-group">
                                                <label class="control-label" for="ap-modelo">Módelo</label>
                                                <?php $form->get('apmodelo')->setValue($this->information['aps']['0']['modelo']); ?>
                                                <?= $this->formInput($form->get('apmodelo')); ?>
                                            </div>
                                                    
                                            <div class="form-group">
                                                <label class="control-label" for="ap-mac">MAC</label>
                                                <?php $form->get('apmac')->setValue($this->information['aps']['0']['mac']); ?>
                                                <?= $this->formInput($form->get('apmac')); ?>
                                            </div>                                                    

                                            <div class="form-group">
                                                <label class="control-label" for="ap-criticidad">Criticidad</label>
                                                <?php $form->get('apcriticidad')->setValue($this->information['aps']['0']['criticidadId']) ?>
                                                <?= $this->formSelect($form->get('apcriticidad')); ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="ap-estado">Estado</label>
                                                <?php $form->get('apestado')->setValue($this->information['aps']['0']['estadoId']) ?>
                                                <?= $this->formSelect($form->get('apestado')); ?>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label" for="glan-observaciones">Observaciones</label>
                                                <?php $form->get('apobservacion')->setValue($this->information['aps']['0']['observaciones']) ?>    
                                                <?= $this->formTextarea($form->get('apobservacion')); ?>
                                            </div>

                                            <div style="float:right; margin-top: 20px;">
                                                <a class="btn btn-primary btn-sm update-sede" href="#" role="button" onclick="updateAp();" title="Update AP">
                                                    <i class="glyphicon glyphicon-edit"></i>
                                                </a>
                                            </div>

                                        </div>    

                                    </div>
                                            
                                </div>
                            </fieldset>				
                        <div class="clearfix"></div>
                    </div>
                </div>            
                <!-- FIN AP -->
            <?php endif; ?>
            </div>
            <!-- FIN save AP -->
            </div>
        </div>
</div>
</div>

<?= $this->form()->closeTag($form); ?>
</div>
<?php endif; ?>

<!-- Modal Delete Circulo -->
<div class="modal fade" id="deleteCircuito" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar circuito</h4>
            </div>
            <div class="modal-body">
                <div id="msgModalDeleteCircuito"></div>
                <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de continuar con la eliminación?</p>
<!--                 <input type="text" id="modalCircuitoId" name="modalCircuitoId" value="" readonly> -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteCircuito();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete Equipo -->
<div class="modal fade" id="deleteEquipo" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar equipo</h4>
            </div>
            <div class="modal-body">
                <div id="msgModalDeleteEquipo"></div>
                 <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteEquipo();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete EquipoNotManagement -->
<div class="modal fade" id="deleteEquipoNotManagement" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar equipo no gestionado</h4>
            </div>
            <div class="modal-body">
                 <p>¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteEquipoNotManagement();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete IpWan -->
<div class="modal fade" id="deleteIpWan" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar configuración IP Wan</h4>
            </div>
            <div class="modal-body">
                 <p>¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteIpWan();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal Delete IpLan -->
<div class="modal fade" id="deleteIpLan" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar configuración IP Lan</h4>
            </div>
            <div class="modal-body">
                 <p>¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteIpLan();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal Delete Ha -->
<div class="modal fade" id="deleteHa" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar hardware</h4>
            </div>
            <div class="modal-body">
                 <p>¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteHa();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete He -->
<div class="modal fade" id="deleteHe" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar hardware</h4>
            </div>
            <div class="modal-body">
                 <p>¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteHe();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete Mc -->
<div class="modal fade" id="deleteMc" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar multicast</h4>
            </div>
            <div class="modal-body">
                 <p>¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteMc();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete AP -->
<div class="modal fade" id="deleteApEquipo" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar equipo AP</h4>
            </div>
            <div class="modal-body">
                <div id="msgModalDeleteEquipo"></div>
                 <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteApEquipo();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete Glan -->
<div class="modal fade" id="deleteGlanEquipo" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar equipo glan</h4>
            </div>
            <div class="modal-body">
                <div id="msgModalDeleteEquipo"></div>
                 <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de continuar con la eliminación?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="deleteGlanEquipo();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>
