<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

    function updateGlan() {

        var url = '<?= $this->url('save-glan'); ?>';
        $.ajax({
           type: "POST",
           url: url,
           data: $('#myForm').serialize(),
           cache: false,
           success: function (json) {
                    $("#save-glan").html(json);
    //                $('.save-ipwan').addClass('disabled');
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });

    }


    $(function(){
        $("html, body").animate({ scrollTop: 300 });
    });

</script>
            
<div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">
    <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Cliente</th>
                <th>Función</th>
                <th>Nemónico</th>
                <th>Modelo</th>
                <th>S/N</th>
                <th>IP Gestión</th>
                <th>Criticidad</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php $row = 1; ?>
            <?php foreach($this->information['glansall'] as $glan) : ?> 
            <tr id="<?= $glan['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                <td><?= $glan['cliente'] ?></td>
                <td><?= $glan['funcion'] ?></td>
                <td><?= $glan['nemonico'] ?></td>
                <td><?= $glan['modelo_equipo'] ?></td>
                <td><?= $glan['numero_serie'] ?></td>
                <td><?= $glan['ip_gestion'] ?></td>
                <td><?= $glan['criticidad'] ?></td>
                <td> 
                    <a class="btn btn-primary btn-xs" href="#" onclick="glanFill('<?= $this->sedeId; ?>', '<?= $glan['id'] ?>');" title="Consultar equipo">
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </a>
                    <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo">
                        <i class="glyphicon glyphicon-minus"></i>
                    </a>
                </td>  
            </tr>
            <?php $row++; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div style="clear: both;"></div>

<div id="glan-fill">
    <?php if(isset($this->information['glans']['0'])) : ?>
    <!-- INICIO GLAN -->
    <div class="panel panel-default">
        <div class="panel-body">
            <fieldset class="col-md-12">
                <legend>GLAN</legend>
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="col-lg-6">    

                            <div class="form-group">
                                <label class="control-label" for="contrato-fabricante">Contrato Fabricante</label>
                                <?php $form->get('gconfab')->setValue($this->information['glans']['0']['contrato_fabricante']); ?>
                                <?= $this->formInput($form->get('gconfab')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="actividad-tsol">Actividad TSOL</label>
                                <?php $form->get('gactsol')->setValue($this->information['glans']['0']['actividad_tsol']); ?>
                                <?= $this->formInput($form->get('gactsol')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="modelo-equipo">Modelo Equipo</label>
                                <?php $form->get('gmodeloequipo')->setValue($this->information['glans']['0']['modelo_equipo']); ?>
                                <?= $this->formInput($form->get('gmodeloequipo')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="familia-fabricante">Familia Fabricante</label>
                                <?php $form->get('gfamfab')->setValue($this->information['glans']['0']['familia_fabricante']); ?>
                                <?= $this->formInput($form->get('gfamfab')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-nemonico">Nemónico</label>
                                <?php $form->get('gnemonico')->setValue($this->information['glans']['0']['nemonico']); ?>
                                <?= $this->formInput($form->get('gnemonico')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ip-gestion-cliente">IP Gestión Cliente</label>
                                <?php $form->get('gipgestioncliente')->setValue($this->information['glans']['0']['ip_gestion_cliente']); ?>
                                <?= $this->formInput($form->get('gipgestioncliente')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ip-gestion">IP Gestión</label>
                                <?php $form->get('gipgestion')->setValue($this->information['glans']['0']['ip_gestion']); ?>
                                <?= $this->formInput($form->get('gipgestion')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-firmware">Firmware</label>
                                <?php $form->get('gfirmware')->setValue($this->information['glans']['0']['firmware']); ?>
                                <?= $this->formInput($form->get('gfirmware')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-mac">MAC</label>
                                <?php $form->get('gmac')->setValue($this->information['glans']['0']['mac']); ?>
                                <?= $this->formInput($form->get('gmac')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-numeroserie">Número Serie</label>
                                <?php $form->get('gnumeroserie')->setValue($this->information['glans']['0']['numero_serie']); ?>
                                <?= $this->formInput($form->get('gnumeroserie')); ?>
                            </div>

                            <div class="form-group">
                                    <label class="control-label" class="form-check-label">
                                        <?php $isStack = $this->information['glans']['0']['tiene_stack']; ?>
                                        <input id="gisstack" name="gisstack" type="checkbox" value="1" class="form-check-input" <?= ($isStack)?'checked':''; ?>>
                                        ¿Tiene stack?
                                    </label>
                                    <!--<label class="control-label" for="glan-stack">Stack</label>-->
                                     <?php $form->get('gstack')->setValue($this->information['glans']['0']['stack']); ?>
                                    <?= $this->formInput($form->get('gstack')); ?>

                                </div>
                        </div>    

                        <div class="col-lg-6">    

                            <div class="form-group">
                                <label class="control-label" for="glan-cliente">Cliente</label>
                                <?php $form->get('gcliente')->setValue($this->information['glans']['0']['clienteId']); ?>
                                <?= $this->formSelect($form->get('gcliente')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="equipo-edc-wan">EDC WAN</label>
                                <?= $this->information['htmlcomboboxglannemonico']['0']; ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-ubicacion">Ubicación</label>
                                <?php $form->get('gubicacion')->setValue($this->information['glans']['0']['ubicacion']); ?>
                                <?= $this->formInput($form->get('gubicacion')); ?>
                            </div>                                    

                            <div class="form-group">
                                <label class="control-label" for="glan-funcion">Función</label>
                                <?php $form->get('gfuncion')->setValue($this->information['glans']['0']['funcionId']); ?>
                                <?= $this->formSelect($form->get('gfuncion')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-criticidad">Criticidad</label>
                                <?php $form->get('gcriticidad')->setValue($this->information['glans']['0']['criticidadId']) ?>
                                <?= $this->formSelect($form->get('gcriticidad')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-estado">Estado</label>
                                <?php $form->get('gestado')->setValue($this->information['glans']['0']['estadoId']) ?>
                                <?= $this->formSelect($form->get('gestado')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="contacto-glan">Contacto</label>
                                <?php $form->get('gcontacto')->setValue($this->information['glans']['0']['contacto']) ?>
                                <?= $this->formInput($form->get('gcontacto')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="telefono-glan">Teléfono</label>
                                <?php $form->get('gtelefono')->setValue($this->information['glans']['0']['telefono']) ?>
                                <?= $this->formInput($form->get('gtelefono')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="glan-observaciones">Observaciones</label>
                                <?php $form->get('gobservacion')->setValue($this->information['glans']['0']['observaciones']) ?>    
                                <?= $this->formTextarea($form->get('gobservacion')); ?>
                            </div>

                        </div>    

                    </div>

                    <div id="modulo-glan" class="panel-body">
                        <fieldset class="col-md-12">    	
                            <legend>MÓDULO ADICIONALES</legend>
                            <div class="panel panel-default">
                                <div class="panel-body">

                                    <div style="float:right;">

                                        <a class="btn btn-primary btn-sm" href="#" role="button" title="Agregar módulo">
                                            <i class="glyphicon glyphicon-plus"></i>
                                        </a>

                                    </div>
                                    <div style="clear: both;"></div>                            

                                    <div class="panel panel-default" style="padding: 2px; overflow: scroll; height: 112px;">

                                        <table id="grid-equipos" class="table table-bordered table-hover table-condensed">
                                            <thead>
                                                <tr>
                                                    <th style="width:30%;">Componente</th>
                                                    <th style="width:30%;">Módelo</th>
                                                    <th style="width:30%;">S/N</th>
                                                    <th style="width:10%;">Acciones</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php $row = 1; ?>
                                                <?php foreach($this->information['componentesall'] as $component) : ?> 
                                                <tr id="<?= $component['id'] ?>" class="fila-grid <?= (1==$row)?'success':'' ?>">
                                                    <td><?= $component['tipo'] ?></td>
                                                    <td><?= $component['modelo'] ?></td>
                                                    <td><?= $component['numero_serie'] ?></td>
                                                    <td> 
                                                        <a class="btn btn-primary btn-xs" href="#" onclick="glanFill('<?= $this->sedeId; ?>', '<?= $glan['id'] ?>');" title="Consultar equipo">
                                                            <i class="glyphicon glyphicon-eye-open"></i>
                                                        </a>
                                                        <a class="btn btn-primary btn-xs" href="#" role="button" title="Eliminar equipo">
                                                            <i class="glyphicon glyphicon-minus"></i>
                                                        </a>
                                                    </td>  
                                                </tr>
                                                <?php $row++; ?>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>

<!--                                    <div class="col-lg-6">    
                                        <div class="form-group">
                                            <label class="control-label" for="componente-tipo">Tipo</label>
                                            <?php # $form->get('ctipo')->setValue($this->information['componentes']['0']['tipoId']) ?>
                                            <?php # $this->formSelect($form->get('ctipo')); ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="componente">Componente</label>
                                            <?php # $form->get('ccomponente')->setValue($this->information['componentes']['0']['componente']); ?>
                                            <?php # $this->formInput($form->get('ccomponente')); ?>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">    
                                        <div class="form-group">
                                            <label class="control-label" for="component-numeroserie">N/S</label>
                                            <?php # $form->get('cnumeroserie')->setValue($this->information['componentes']['0']['numero_serie']); ?>
                                            <?php # $this->formInput($form->get('cnumeroserie')); ?>
                                        </div>
                                    </div>    -->

                            </div> 

                        </div>

                    </fieldset>				
                    <div class="clearfix"></div>
                </div>

                </div>
            </fieldset>				
            <div class="clearfix"></div>
        </div>
    </div>            

    <!-- FIN GLAN-->
    <?php endif; ?>    
</div>