<?php
    use Zend\Session\Container;
    $session = new Container('User');
    $userRole = $session->offsetGet('userRole');
?>
<style>

fieldset 
{
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
}
	
legend
{
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
}
                
</style>

<script>

function deleteHa() {
    
    $('#deleteHa').modal('hide');
    var url = '<?= $this->url('delete-ha'); ?>';
    var id = $('#deleteHaId').val();
    
    var equipoId = $('#equipoId').val();
    var equipoBckId = $('#equipoBckId').val();
    var data = {id: id, equipoId: equipoId, equipoBckId:equipoBckId};

    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
            $("#ipwan-fill").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}
    



function updateHa() {

    var url = '<?= $this->url('save-ha'); ?>'; 
    $.ajax({
       type: "POST",
       url: url,
       data: $('#myForm').serialize(),
       cache: false,
       success: function (json) {
                $("#grid-ha-fill").html(json);
                $('.update-ha').addClass('disabled');
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}




function addHa() {

    var id = $('#equipoId').val();
    var idbck = $('#equipoBckId').val();

    var data = {id: id, idbck: idbck};
    var url = '<?= $this->url('add-ha'); ?>';
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (json) {
            $("#ipwanone-fill").html(json);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#box").html(html);
        }
    });

}



    








$(function(){
    
    $('#grid-ha tbody tr').click(function(){
        
        $("#grid-ha tbody tr").each(function () {
                $(this).removeClass('success');
        });
        $(this).addClass('success');
    });

    $('#deleteHa').on('show.bs.modal',function(e){
        var id = $(e.relatedTarget).data().id;
        $('#deleteHaId').val(id);
    })

    $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });


    $("#update-vozip").on("click", function(e){
        e.preventDefault();
        var output;
        if($(".form-group").hasClass("has-error")){
            output = '<div class="notification error"><span class="notification-icon"><i class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></i></span><span class="notification-text">' + 'Falta completar con los datos requeridos' + '</span></div>';
        } else {
                var url = '<?= $this->url('save-vozip'); ?>';
                $.ajax({
                    type: "POST",
                    url: url,
                     data: $('#myForm').serialize(),
                    cache: false,
                    success: function (html) {
                        $("#save-vozip").html(html);

                    },
                    error: function (xhr, status) {
                        html = "<div class='alert alert-danger'>Error!</div>"
                        $("#box").html(html);
                    }
                });
            output = '<div class="notification success"><span class="notification-icon"><i class="glyphicon glyphicon-ok" aria-hidden="true"></i></span><span class="notification-text">' + 'Se ha guardado satisfactoriamente!' + '</span></div>';    
        }

        $("#notification").html(output);
        $(".notification").delay(8000).queue(function (next) {
            $(this).addClass("scale-out");
            next();
        });
        $(".notification").on("click", function(){ 
            $(this).addClass("scale-out");
        });

    });





});

</script>

    <div class="panel panel-default">
        <div class="panel-body">
            <fieldset class="col-md-12">
                <legend>Voz IP</legend>
                <div class="panel panel-default">
                    <div class="panel-body" data-toggle="validator">
                        <div class="col-lg-6">
                            <input type="hidden" id="vozipId" name="vozipId" value="<?= $this->information['vozips']['0']['id']; ?>">
                            <div class="form-group">
                                <label class="control-label" for="vipextension">Nº de Extensión</label>
                                <?php $form->get('vipextension')->setValue($this->information['vozips']['0']['numero_extension']); ?>
                                <?= $this->formInput($form->get('vipextension')); ?>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="viptipo">Tipo</label>
                                <?php $form->get('viptipo')->setValue($this->information['vozips']['0']['tipoId']); ?>
                                <?= $this->formSelect($form->get('viptipo')); ?>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="vipmodelo">Modelo</label>
                                <?php $form->get('vipmodelo')->setValue($this->information['vozips']['0']['modeloId']); ?>
                                <?= $this->formSelect($form->get('vipmodelo')); ?>
                            </div>

<!--                                            <div class="form-group">&nbsp;</div>-->
                            <?php $isDdi = $this->information['vozips']['0']['ddi']; ?>
                            <div class="form-check" style="margin-top: 14px;">
                                <label class="control-label" class="form-check-label">
                                    <input id="vipddi" name="vipddi" type="checkbox" value="1" class="form-check-input" <?= ($isDdi)?'checked':''; ?>>
                                    ¿DDI?
                                </label>
                            </div>



                        </div>
                        <div class="col-lg-6">

                            <div class="form-group">
                                <label class="control-label" for="vipgrupocaptura">Grupo de captura</label>
                                <?php $form->get('vipgrupocaptura')->setValue($this->information['vozips']['0']['grupo_captura']); ?>
                                <?= $this->formInput($form->get('vipgrupocaptura')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vipgruposalto">Grupo de salto</label>
                                <?php $form->get('vipgruposalto')->setValue($this->information['vozips']['0']['grupo_salto']); ?>
                                <?= $this->formInput($form->get('vipgruposalto')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vipperfil">Perfil</label>
                                <?php $form->get('vipperfil')->setValue($this->information['vozips']['0']['perfil']); ?>
                                <?= $this->formSelect($form->get('vipperfil')); ?>
                            </div>



<!--                                            <div style="float:right;">
                                <button class="btn btn-primary enabled" title="Guardar" type="submit"><span class="glyphicon glyphicon-edit"></span></button>

                                onclick="updateVozip();" 

                            </div>-->
                            <div style="float:right; margin-top: 8px;">
                                <a id="update-vozip" class="btn btn-primary btn-sm update-vozip" href="#" role="button" title="Update Voz IP">
                                    <i class="glyphicon glyphicon-edit"></i>
                                </a>
                            </div>    
                        </div>

                    </div>

                </div>
            </fieldset>
        <div class="clearfix"></div>
    </div>
</div>
                    
