<?=  $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/wizard/smart_wizard.css')
        ->appendStylesheet($this->basePath() . '/css/wizard/smart_wizard_theme_dots.css')
        ->appendStylesheet($this->basePath() . '/css/wizard/smart_wizard_theme_arrows.css'); ?>

<?php echo $this->headScript()
        ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js') 
        ->appendFile($this->basePath() . '/js/wizard/jquery.smartWizard.js'); ?>

<style>

    fieldset 
    {
    border: 1px solid #ddd !important;
    margin: 0;
    xmin-width: 0;
    padding: 10px;       
    position: relative;
    border-radius:4px;
    background-color:#f5f5f5;
    padding-left:10px!important;
    }	
	
    legend
    {
    font-size:14px;
    font-weight:bold;
    margin-bottom: 0px; 
    width: 35%; 
    border: 1px solid #ddd;
    border-radius: 4px; 
    padding: 5px 5px 5px 10px; 
    background-color: #ffffff;
    }
    
    .form-group
    {
     margin-bottom:5px;   
    }
    
    .inner
    {
        /*padding: 2px;*/
       
    }

    #smartwizard {
        padding: 8px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
        padding: 4px;
       
        
    }
    
    
    
</style>
<?php

$form = $this->form;
#$form->setAttribute('action', $this->url('wizard'));
$form->setAttribute('id', 'myForm');
$form->setAttribute('role', 'form');
$form->setAttribute('data-toggle', 'validator');
$form->setAttribute('accept-charset', 'utf-8');
#$form->setAttribute('novalidate', 'novalidate');

$form->prepare();

?>
<div class="inner">
 
    
    <?= $this->form()->openTag($form); ?>
    <!--<form action="/wizard" id="myForm" role="form" data-toggle="validator" method="post" accept-charset="utf-8">-->

    <!-- SmartWizard html -->
    <?php
    
        if(isset($this->tab) && $this->tab==2) {
            $property = 'block';
            $hiddenButtons = 1;
        } else {
            $property = 'none';
            $hiddenButtons = 0;
        }
        if(isset($this->tab) && $this->tab==3) {
            $property2 = 'block';
            $hiddenButtons2 = 1;
        } else {
            $property2 = 'none';
            $hiddenButtons2 = 0;
        }
        
        $hiddenButtons3 = 0;
        if(isset($this->tab) && $this->tab==1) {
            $hiddenButtons3 = 1;
        }
    ?>
    <div id="box"></div>
    <div id="smartwizard" >
        <ul>
            <li><a href="#step-1">SEDE&nbsp;&nbsp;&nbsp;&nbsp;<br /><small>1er Paso</small></a></li>
            <li><a href="#step-2">CIRCUITO<br /><small>2do Paso</small></a></li>
            <li class="step-equipo" style="display:<?= $property; ?>;"><a href="#step-3">&nbsp;&nbsp;EQUIPO&nbsp;&nbsp;GESTIONADO&nbsp;&nbsp;<br /><small>3er Paso (a)</small></a></li>
            <li class="step-equipo-no-gestionado" style="display:<?= $property2; ?>;"><a href="#step-4">EQUIPO NO GESTIONADO<br /><small>3er Paso(b)</small></a></li>
            <li class="step-equipo-comodin"><a href="#step-5">EQUIPO&nbsp;&nbsp;&nbsp;&nbsp;<br /><small>3er Paso</small></a></li>
            <li><a href="#step-6">FINAL&nbsp;&nbsp;&nbsp;&nbsp;<br /><small>&nbsp;</small></a></li>
        </ul>

        <div style="border-style: none;">
            <div id="step-1">
                <fieldset class="col-md-12">    	
                <legend>SEDE</legend>
                <div class="panel panel-default">
                    <div class="panel-body">
                    
                <div class="col-lg-6">    
                <div id="form-step-0" role="form" data-toggle="validator">

                        <div class="form-group">
                            <label class="control-label" for="nombre">Nombre</label>
                            <?= $this->formInput($form->get('nombre')); ?>
                            <!--<input type="text" class="form-control input-sm" id="nombre" name="nombre" aria-describedby="nombreHelp" placeholder="Ingresa el nombre de la sede" required>-->
                            <!--<div class="help-block with-errors"></div>-->
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="idescat">Idescat</label>
                            <?= $this->formInput($form->get('idescat')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="direccion">Dirección</label>
                            <?= $this->formTextarea($form->get('direccion')); ?>
                            <!--<textarea class="form-control input-sm" id="direccion" name="direccion" rows="3" placeholder="Ingresa la dirección de la sede ..." required></textarea>-->
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="poblacion">Población</label>
                            <?= $this->formSelect($form->get('poblacion')); ?>    
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="provincia">Provincia</label>
                            <?= $this->formSelect($form->get('provincia')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="horario">Horario</label>
                            <?= $this->formInput($form->get('horario')); ?>
                        </div>
                    
                </div>    
                </div>    
                <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label for="contacto">Contacto</label>
                            <?= $this->formInput($form->get('contacto')); ?>
                        </div>

                        <div class="form-group">
                            <label for="telefono">Teléfono</label>
                            <?= $this->formInput($form->get('telefono')); ?>
                        </div>

                        <div class="form-group">
                            <label for="observaciones">Observaciones</label>
                            <?= $this->formTextarea($form->get('observacion')); ?>
                        </div>
<!--
                        <fieldset class="form-group">
                          <legend>Mapa de Red</legend>
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                <img src="http://www.huawei.com/ucmf/groups/public/documents/webasset/ar1200.jpg" alt="Smiley face" height="42" width="42" style="border:1px solid black;">
                                
                        </fieldset>   

                        <button type="submit" class="btn btn-primary">IMG:Upload galeria de imagenes</button>
                     -->
                </div>    
                
                </div>
            </div>
        </fieldset>    
    
                </div>
                

            <div id="step-2">
<!--                    <h2>Your Name</h2>
                    <div id="form-step-1" role="form" data-toggle="validator">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" class="form-control" name="name" id="email" placeholder="Write your name" required>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>-->
                
                
                <fieldset class="col-md-12">    	
                    <legend>CIRCUITO</legend>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="col-lg-6">
                                <div id="form-step-1" role="form" data-toggle="validator">    

                                    <div class="form-group">
                                        <label class="control-label" for="administrativo">Administrativo</label>
                                        <?= $this->formInput($form->get('cadministrativo')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="telefono-circuito">Teléfono</label>
                                        <?= $this->formInput($form->get('ctelefono')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="cliente">Cliente</label>
                                        <?= $this->formSelect($form->get('ccliente')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="tecnologia">Tecnología</label>
                                        <?= $this->formSelect($form->get('ctecnologia')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="velocidad">Velocidad</label>
                                        <?= $this->formSelect($form->get('cvelocidad')); ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="criticidad">Criticidad</label>
                                        <?= $this->formSelect($form->get('ccriticidad')); ?>
                                    </div>

                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input id="cbackup" name="cbackup" type="checkbox" class="form-check-input" value="1">
                                          ¿Tiene Backup?
                                        </label>
                                    </div>                        
                                </div>    
                            </div>
                            <div class="col-lg-6">    
                        
                                <div class="form-group">
                                    <label class="control-label" for="factura">Factura</label>
                                    <?= $this->formSelect($form->get('cfactura')); ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="estado">Estado</label>
                                    <?= $this->formSelect($form->get('cestado')); ?>
                                </div>

                                <div class="form-group">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="checkbox" id="cgestionado" name="cgestionado" class="form-check-input" value="1">
                                          ¿Es gestionado?
                                        </label>
                                    </div>                        
                                </div>
                        
                                <div class="grid-caudal" style="display: none;">
                                    <button id="add" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right;  margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                                    <div style="clear:both;"></div>
                                    <div class="panel-body">

                                        <table id="grid-caudal" class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Nombre</th>
                                                    <th>Cantidad</th>
                                                    <th>Unidad</th>
                                                    <th>Acciones</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                
<!--                                                <tr>
                                                    <td>Oro</td>
                                                    <td>60</td>
                                                    <td>
                                                        <select class="form-control" id="exampleSelect1">
                                                            <option selected="">Mb</option>
                                                            <option>%</option>
                                                        </select>
                                                    </td>
                                                    <td><input type="button" class="borrar" value="Eliminar" /></td>
                                                </tr>
                                                <tr>
                                                    <td>Plata</td>
                                                    <td>30</td>
                                                    <td>
                                                        <select class="form-control" id="exampleSelect1">
                                                            <option selected="">Mb</option>
                                                            <option>%</option>
                                                        </select>
                                                    </td>
                                                    <td><input type="button" class="borrar" value="Eliminar" /></td>
                                                </tr>-->
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>                        
                            </div>    
                        </div>
                        <div id="circuit-backup" class="panel-body" style="display:none;">
                            <fieldset class="col-md-12">    	
                                <legend>CIRCUITO BACKUP</legend>
                                <div class="panel panel-default">
                                    <div class="panel-body">

                                        <div class="col-lg-6">    

                                                <div class="form-group">
                                                    <label class="control-label" for="administrativo-backup">Administrativo</label>
                                                    <?= $this->formInput($form->get('bcadministrativo')); ?>
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label" for="telefono-circuito-backup">Teléfono</label>
                                                    <?= $this->formInput($form->get('bctelefono')); ?>
                                                </div>

                            <div class="form-group">
                                <label class="control-label" for="cliente-backup">Cliente</label>
                                <?= $this->formSelect($form->get('bccliente')); ?>                            
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="tecnologia-backup">Tecnología</label>
                                <?= $this->formSelect($form->get('bctecnologia')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="velocidad-backup">Velocidad</label>
                                <?= $this->formSelect($form->get('bcvelocidad')); ?>
                            </div>


                    </div>    
                    
                    <div class="col-lg-6">    
                        
                            <div class="form-group">
                                <label class="control-label" for="estado-backup">Estado</label>
                                <?= $this->formSelect($form->get('bcestado')); ?>
                            </div>   
                    
                    
                            <div class="form-group">
                                <div class="form-check">
                                    <label class="form-check-label">
                                      <input type="checkbox" id="bcgestionado" name="bcgestionado" class="form-check-input" value="1">
                                      ¿Es gestionado?
                                    </label>
                                </div>                        
                            </div>
                        
                        <div class="grid-caudal-backup" style="display: none;">
                            <button id="add-backup" type="button" title="Agregar caudal" class="btn btn-primary btn-xs" style="float: right; margin-right: 18px;"><i class="glyphicon glyphicon-plus"></i></button>
                            <div style="clear:both;"></div>
                            <div class="panel-body">
                                <table id="backup" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Unidad</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
<!--                                        <tr>
                                            <td><input type="checkbox" id="" class="form-check-input"></td>
                                            <td>Bronce</td>
                                            <td>60</td>
                                            <td>
                                                <select class="form-control" id="exampleSelect1">
                                                    <option>Mb</option>
                                                    <option selected="">%</option>
                                                </select>
                                            </td>
                                        </tr>-->
                                    </tbody>
                                </table>
                            </div>
                        </div>                        
                        
                        
                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				
        <div class="clearfix"></div>
    </div>
                
            </div>
            
            
            
        </fieldset>				
        <div class="clearfix"></div>                
                







                
            </div>
            <div class="step-equipo" style="display:<?= $property; ?>;">   
            <div id="step-3">
<!--    
<h2>Your Address</h2>
<div id="form-step-2" role="form" data-toggle="validator">
    <div class="form-group">
        <label for="address">Address</label>
        <textarea class="form-control" name="address" id="address" rows="3" placeholder="Write your address..." required></textarea>
        <div class="help-block with-errors"></div>
    </div>
</div>
-->


        <fieldset class="col-md-12">    	
            <legend>EQUIPO GESTIONADO</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    
                        <div id="form-step-2" role="form" data-toggle="validator">
                         
                            <?php if(2==$this->tab) : ?>
                            <div class="form-group">
                                <label class="control-label" for="servicio">Circuito</label>
                                <?= $this->comboBoxCircuito; ?>
                            </div>
                            
                            <?php endif; ?>
                            
                            <div class="form-group">
                                <label class="control-label" for="servicio">Servicio</label>
                                <?= $this->formSelect($form->get('eservicio')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="nemonico">Nemónico</label>
                                <?= $this->formInput($form->get('enemonico')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ip-gestion">IP Gestión</label>
                                <?= $this->formInput($form->get('eipgestion')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="nivel">Nivel</label>
                                <?= $this->formSelect($form->get('enivel')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="nemonico-n1">Nemónico N1</label>
                                <?= $this->formSelect($form->get('enemonicon1')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="fabricante">Fabricante</label>
                                <?= $this->formSelect($form->get('efabricante')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="exampleSelect1">Modelo</label>
                                <?= $this->formSelect($form->get('emodelo')); ?>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="serie">N/S</label>
                                <?= $this->formInput($form->get('eserie')); ?>
                            </div>
                            
                    </div>
                </div>    
                    
                    <div class="col-lg-6">    

                        <div class="form-group">
                            <label class="control-label" for="ubicacion">Ubicación</label>
                            <?= $this->formInput($form->get('eubicacion')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="logos-alta">Pedido LOGOS Alta</label>
                            <?= $this->formInput($form->get('elogosalta')); ?>
                        </div>    

                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo">Contacto</label>
                            <?= $this->formInput($form->get('econtacto')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo-horario">Teléfono</label>
                            <?= $this->formInput($form->get('etelefono')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-equipo-horario">Horario</label>
                            <?= $this->formInput($form->get('ehorario')); ?>
                        </div>
                                                
                         <div class="form-group">
                            <label class="control-label" for="estado-equipo">Estado</label>
                            <?= $this->formSelect($form->get('eestado')); ?>                        
                         </div>
                        
                         <div class="form-group">
                            <label class="control-label" for="observacion-equipo">Observaciones</label>
                            <?= $this->formTextarea($form->get('eobservacion')); ?>
                        </div>
                        
                        
                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				

            </div>
        </div>    
        <div class="step-equipo-no-gestionado" style="display: <?= $property2; ?>;">
            <div id="step-4" class="">
                    
            <fieldset class="col-md-12">    	
                <legend>EQUIPO NO GESTIONADO</legend>
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="col-lg-6">    
                            <div id="form-step-3" role="form" data-toggle="validator">
                                
                                <?php if(3==$this->tab) : ?>
                                    <div class="form-group">
                                        <label class="control-label" for="servicio">Circuito</label>
                                        <?= $this->comboBoxCircuito; ?>
                                    </div>
                                <?php endif; ?>
                                
                                <div class="form-group">
                                    <label class="control-label" for="servicio-no-gestionado">Servicio</label>
                                    <?= $this->formSelect($form->get('engservicio')); ?>
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="propiedad">Propiedad Router</label>
                                    <?= $this->formSelect($form->get('engpropiedad')); ?>
                                </div>                        

                            <div class="form-group">
                                <label class="control-label" for="tipo-ip">Tipo IP</label>
                                <?= $this->formSelect($form->get('engtipoip')); ?>                            
                            </div>                        

                            <div class="form-group">
                                <label class="control-label" for="ip-no-gestionado">IP</label>
                                <?= $this->formInput($form->get('engip')); ?>
                            </div>
                        
                            <div class="form-group">
                                <label class="control-label" for="red">Red</label>
                                <?= $this->formSelect($form->get('engred')); ?>                                
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="usos">Usos</label>
                                <?= $this->formSelect($form->get('enguso')); ?>                            
                            </div>
                            
                        </div>
                    </div>    
                    
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label class="control-label" for="contacto-no-gestionado">Contacto</label>
                            <?= $this->formInput($form->get('engcontacto')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="telefono-no-gestionado">Teléfono</label>
                            <?= $this->formInput($form->get('engtelefono')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label" for="horario-no-gestionado">Horario</label>
                            <?= $this->formInput($form->get('enghorario')); ?>
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="observacion-no-gestionado">Observaciones</label>
                            <?= $this->formTextarea($form->get('engobservacion')); ?>
                        </div>
                        
                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				
                    
            </div>
        </div>

            <div id="step-5" class="">
<!--                <h2>Final</h2>
                <p>Keep your smile :) </p>
                <div id="form-step-4" role="form" data-toggle="validator">
                    <div class="form-group">
                        <label for="terms">I agree with this prototype.</label>
                        <input type="checkbox" id="terms" name="terms" data-error="Please accept the Terms and Conditions" required>  
                        <div class="help-block with-errors"></div>
                    </div>
                </div>  -->
                
        <fieldset class="col-md-12">    	
            <legend>DIRECCIONAMIENTO WAN</legend>
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    <div class="col-lg-6">    

                        <div id="form-step-4" role="form" data-toggle="validator">


                            <div class="form-group">
                                <label class="control-label" for="ipwrpv">RPV</label>
                                <?= $this->formSelect($form->get('ipwrpv')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="ipwrouting">Routing</label>
                                <?= $this->formSelect($form->get('ipwrouting')); ?>                            
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ipwvlanedc">Vlan EDC</label>
                                <?= $this->formInput($form->get('ipwvlanedc')); ?>
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="ipwvlannacional">Vlan Nacional</label>
                                <?= $this->formSelect($form->get('ipwvlannacional')); ?>                                
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="ipwred">Red</label>
                                <?= $this->formSelect($form->get('ipwred')); ?>                            
                            </div>
                            
                            <div class="form-group">
                                <label class="control-label" for="ipwuso">Uso</label>
                                <?= $this->formSelect($form->get('ipwuso')); ?>                            
                            </div>
                            
                        </div>    
                    </div>    
                    
                    <div class="col-lg-6">    
                        
                        <div class="form-group">
                            <label class="control-label" for="ipwipwanedc">IP WAN EDC</label>
                            <?= $this->formInput($form->get('ipwipwanedc')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ipwmascara">Máscara</label>
                            <?= $this->formInput($form->get('ipwmascara')); ?>
                        </div>
                                                
                        <div class="form-group">
                            <label class="control-label" for="ipwpeppal">PE Ppal</label>
                            <?= $this->formInput($form->get('ipwpeppal')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ipwpebackup">PE Backup</label>
                            <?= $this->formInput($form->get('ipwpebackup')); ?>
                        </div>

                    </div>    
                
                </div>
                
            </div>
            
        </fieldset>				
                
                
            </div>
                
            <!-- SET -->
            
            <div id="step-6" class="">
                <h2>Final</h2>
                <div id="form-step-5" role="form" data-toggle="validator">
                    <div class="form-group">
                        <label for="terms">I agree with this development.</label>
                        <input type="checkbox" id="terms" name="terms" data-error="Please accept the Terms and Conditions" required>  
                        <div class="help-block with-errors"></div>
                    </div>
                </div>  
            </div>
            
            
            
            
            <!-- SET -->
            
        </div>
    </div>
    
    <input type="hidden" id="stepwizard" name="stepwizard" value="0">
    <input type="hidden" id="tab" name="tab" value="<?= $this->tab; ?>">
    <input type="hidden" id="sedeId" name="sedeId" value="<?= $this->sedeId; ?>">
    <!--<input type="hidden" id="circuitoId" name="circuitoId" value="<?php # $this->circuitoId; ?>">-->
    
    <!--</form>-->
    <?= $this->form()->closeTag($form); ?>
    <div id="boxXXX" style="border:1px solid #ccc;"></div>
</div>

<script type="text/javascript">

function sleep(delay) {
        var start = new Date().getTime();
        while (new Date().getTime() < start + delay);
}


$(document).ready(function(){
            
    // Toolbar extra buttons 
    var btnFinish = $('<button></button>').text('Finish')
                    .addClass('btn btn-info')
                    .on('click', function(){
                        if( !$(this).hasClass('disabled')){ 
                            var elmForm = $("#myForm");
                            if(elmForm){
                                elmForm.validator('validate'); 
                                var elmErr = elmForm.find('.has-error');
                                if(elmErr && elmErr.length > 0){
                                    alert('Oops we still have error in the form');
                                    return false;    
                                }else{
                                    alert('Great! we are ready to submit form');
                                    elmForm.submit();
                                    return false;
                                }
                            }
                        }
                    });
                                                
    var btnCancel = $('<button></button>').text('Cancel')
                    .addClass('btn btn-danger')
                    .on('click', function(){ 
                           $('#smartwizard').smartWizard("reset"); 
                           $('#myForm').find("input, textarea, select").val(""); 
                    });                         
            
            
            
            
    var btnSaveAndOut = $('<button></button>').text('Grabar')
                        .addClass('btn btn-success save')
                        .on('click', function(){

                            var url = '<?= $this->url('com'); ?>';
                               $.ajax({
                                   type: "POST",
                                   url: url,
                                   data: $('#myForm').serialize(),
                                   cache: false,
                                   success: function (html) {
//                                        var obj = jQuery.parseJSON(json);
//                                        var results;
//                                        for(var key in obj){
//                                            console.log(' name= ' + key + ' value= ' + obj[key]);
//                                            results = parseInt(obj[key]);
//                                            console.log('Resultado='+results);
//                                       }
//                                       if(results>0) {
                                            
                                            //html = "<div class='alert alert-success' style='text-align: center; font-family: 20px; font-weight: bold;'>¡Se proceso satisfactoriamente!</div>";
                                            $("#box").html(html);
                                            $('.save').hide();
                                            $('.sw-btn-group-extra').hide();
//-                                            $('.sw-btn-prev').addClass('disabled');
//-                                            $('.sw-btn-next').addClass('disabled');
                                            $('.sw-btn-prev').hide();
                                            $('.sw-btn-next').hide();
//+                                            Para direccionar a la nueva página. 
//+                                            document.location.href = '<?php # $this->url('tabs') . '1447' ; ?>';
                                            
//                                        } else {
//                                            html = "<div class='alert alert-danger'>Error!</div>";
//                                            $("#box").html(html);
//                                        }
                                        
                                    },
                                    error: function (xhr, status) {
                                        html = "<div class='alert alert-danger'>Error!</div>"
                                        $("#box").html(html);
                                    }
                                });

                        });                         
 
 
            // Smart Wizard   btnFinish, btnCancel, 
            $('#smartwizard').smartWizard({ 
                selected: <?= $this->tab; ?>, 
                theme: 'arrows',
                keyNavigation: false,
                transitionEffect:'fade',
                
                <?php if('1'== $this->tab) : ?>
                hiddenSteps: ['0', '2', '3', '4', '5'],
                <?php elseif('2'== $this->tab) : ?>
                hiddenSteps: ['0', '1', '3', '4', '5'],
                <?php elseif('3'== $this->tab) : ?>
                hiddenSteps: ['0', '1', '2', '4', '5'],    
                <?php else : ?>
                hiddenSteps: ['5'],        
                <?php endif ; ?>
                toolbarSettings: {toolbarPosition: 'top',
                                  toolbarExtraButtons: [btnSaveAndOut]
                },
                anchorSettings: {
                    markDoneStep: true, // add done css
                    markAllPreviousStepsAsDone: true, // When a step selected by url hash, all previous steps are marked done
                    removeDoneStepOnNavigateBack: true, // While navigate back done step after active step will be cleared
                    enableAnchorOnDoneStep: true // Enable/Disable the done steps navigation
                },
                lang: {  // Language variables
                    next: 'Siguiente', 
                    previous: 'Anterior'
                },                        
            });
            
            
            $("#smartwizard").on("leaveStep", function(e, anchorObject, stepNumber, stepDirection) {
                
                if(stepNumber==1 && stepDirection === 'forward') {
                    if($('#cgestionado').prop('checked')) {
                        $('.step-equipo').css('display','block');
                        $('.step-equipo-comodin').css('display','none');
                    } else {
                        stepNumber = stepNumber + 1;
                        $('.step-equipo-no-gestionado').css('display','block');
                        $('.step-equipo-comodin').css('display','none');
                    }
                }
                var elmForm = $("#form-step-" + stepNumber);
                
//                alert('TEST: ' + elmForm);
                
                // stepDirection === 'forward' :- this condition allows to do the form validation 
                // only on forward navigation, that makes easy navigation on backwards still do the validation when going next
                if(stepDirection === 'forward' && elmForm){
                    elmForm.validator('validate');
                    
                    var elmErr = elmForm.children('.has-error');
                    
//                    alert('LONGITUD: ' + elmErr.length);
                    
                    if(elmErr && elmErr.length > 0) {
                        // Form validation failed
                        return false;    
                    }
                }
                
                $('#stepwizard').val(stepNumber+1);
                
                return true;

            });
            
            $("#smartwizard").on("showStep", function(e, anchorObject, stepNumber, stepDirection) {
                // Enable finish button only on last step
                if(stepNumber == 4){ 
                    $('.btn-finish').removeClass('disabled');  
                }else{
                    $('.btn-finish').addClass('disabled');
                }
                
                if(stepNumber == 2){
                    $('.sw-btn-next').addClass('disabled');
                } else {
                    $('.sw-btn-next').removeClass('disabled');
                }
                
            });                               

            
            $('#add').click(function() {

                var row;
                var id = $('.row-input').length + 1;
                var caudal = 'caudal-' + id;
                var cantidad = 'cantidad-' + id;
                var unidad = 'unidad-' + id;

                row =   '<tr class="row-input">\n\
                            <td><input name="' + caudal + '" class="col-xs-12" type="text" value="" /></td>\n\
                            <td><input name="' + cantidad + '" class="col-xs-12" type="text" value="" /></td>\n\
                            <td><select name="' + unidad + '" class="col-xs-20" id="exampleSelect1"><option value="1" selected="selected">Mb</option><option value="2">%</option></select></td>\n\
                            <td><a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar"><i class="glyphicon glyphicon-minus"></i></a></td>\n\
                        </tr>';
                $('#grid-caudal tr:last').after(row);

            });
            
            
            $('#add-backup').click(function(){

                var row;
                var id = $('.row-input-backup').length + 1;
                var caudalbck = 'caudalbck-' + id;
                var cantidadbck = 'cantidadbck-' + id;
                var unidadbck = 'unidadbck-' + id;
                
                row =   '<tr class="row-input-backup">\n\
                            <td><input name="' + caudalbck + '" class="col-xs-12" type="text" value="" /></td>\n\
                            <td><input name="' + cantidadbck + '"  class="col-xs-12" type="text" value="" /></td>\n\
                            <td><select name="' + unidadbck + '"  class="col-xs-20" id="exampleSelect1"><option value="1" selected="selected">Mb</option><option value="2">%</option></select></td>\n\
                            <td><a class="btn btn-primary btn-xs borrar" href="#" title="Eliminar"><i class="glyphicon glyphicon-minus"></i></a></td>\n\
                        </tr>';
                $('#backup tr:last').after(row);
                
            });
            
            
            
            $(document).on('click', '.borrar', function (event) {
                event.preventDefault();
                $(this).closest('tr').remove();
            });
            
            
            <?php if($hiddenButtons==1||$hiddenButtons2==1||$hiddenButtons3==1) : ?>
                $('.sw-btn-prev').hide();
                $('.sw-btn-next').hide();
            <?php endif; ?>                

            
            
            
    }); 



// Step 2
    $('#cgestionado').click(function(){
        if (this.checked) {
            $('.grid-caudal').css('display','block');
            
            $('#eservicio').attr('required','required');
            $('#enemonico').attr('required','required');
            $('#eipgestion').attr('required','required');
            $('#efabricante').attr('required','required');
            $('#emodelo').attr('required','required');
           
            $('#engservicio').removeAttr('required');
            $('#engpropiedad').removeAttr('required');
            $('#engtipoip').removeAttr('required');
            $('#engip').removeAttr('required');
            $('#engred').removeAttr('required');
            $('#enguso').removeAttr('required');
            
            $('#ipwrpv').attr('required','required');
            $('#ipwrouting').attr('required','required');
            $('#ipwvlanedc').attr('required','required');
            $('#ipwvlannacional').attr('required','required');
            $('#ipwred').attr('required','required');            
            $('#ipwuso').attr('required','required');
            
        }
        else {
            $('.grid-caudal').css('display','none');

            $('.step-equipo').css('display','none');
            $('.step-equipo-no-gestionado').css('display','block');

            $('#eservicio').removeAttr('required');
            $('#enemonico').removeAttr('required');
            $('#eipgestion').removeAttr('required');
            $('#efabricante').removeAttr('required');
            $('#emodelo').removeAttr('required');
             
            $('#engservicio').attr('required','required');
            $('#engpropiedad').attr('required','required');
            $('#engtipoip').attr('required','required');
            $('#engip').attr('required','required');
            $('#engred').attr('required','required');
            $('#enguso').attr('required','required');
            
            $('#ipwrpv').removeAttr('required');
            $('#ipwrouting').removeAttr('required');
            $('#ipwvlanedc').removeAttr('required');
            $('#ipwvlannacional').removeAttr('required');
            $('#ipwred').removeAttr('required');
            $('#ipwuso').removeAttr('required');
            
        }    
    });
    
    $('#cbackup').click(function(){
        if (this.checked) {
            $('#circuit-backup').css('display','block');
        }
        else {
             $('#circuit-backup').css('display','none');
        }
    });

    
    $('#bcgestionado').click(function(){
        if (this.checked) {
            $('.grid-caudal-backup').css('display','block');
        }
        else {

             $('.grid-caudal-backup').css('display','none');
        }
    });

//    var $table = $('#sedes');
//    $(function () {
//            $table.bootstrapTable('hideColumn', 'referenceCode');
//    });
    
</script>
