<?=  $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-table.min.css'); ?>

<?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-table.js.') 
        ->appendFile($this->basePath() . '/js/bootstrap-table/locale/bootstrap-table-en-Sbt-US.min.js.'); ?>

<script type="text/javascript" style="display:none">
<!--

    $(function(){
//        $("html, body").animate({ scrollTop: 300 });
//        $("#mask").css('display','none');

        $("#search").keypress(function(e){
            if(e.which == 13){
                e.preventDefault();
                supplySearcher();
                return false;
            }
        });




    });

    function supplySearcher() {
        
        var url = '<?= $this->url('process-supply-search'); ?>';
        
        $.ajax({
            type: "GET",
            url: url,
            data: $('#supplySearcherForm').serialize(),
            cache: false,
            beforeSend: function() {
//                $("#mask").css('display','block');
                $("#fill-supply-search").html("<img style='display: block; margin:auto;' src='<?= $this->basePath() . '/img/loading.gif' ;?>' />");
            },
            success: function (json) {
                $("#fill-supply-search").html(json);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });
    }

//-->
</script>




<div class="ui-widget-header ui-corner-top ui-helper-clearfix" style="padding: 0.2em 0.6em;">&nbsp;</div>

<div id="toolbar">
    <div class="col-lg-6" style="padding-left: 0px;">
        <form id="supplySearcherForm">
            <div class="form-group input-group" >
                <input type="text" class="form-control" id="search" name="search" placeholder="Buscar ..." value="<?= $this->search; ?>"/>
                <input type="hidden" id="visible" name="visible" value="<?= $this->visible; ?>" />
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" onclick="supplySearcher();">
                        <i class="icon-search"></i>
                    </button>
                </span>
            </div>
        </form>    
    </div>
    <!--    <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#exportModal">
                <i class="glyphicon glyphicon-hand-down"></i>&nbsp;Baja
            </button>
            <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#bulkCloseModal">
                <i class="glyphicon glyphicon-remove"></i>&nbsp;Eliminar
            </button>-->
    <!--        <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#bulkCancelModal">
                <i class="glyphicon glyphicon-export"></i>&nbsp;Exportar
            </button>-->
    <!--    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bulkCloseModal">
                <i class="glyphicon glyphicon-th-list"></i>&nbsp;Reporte BI
            </button>-->
</div>

    <table id="sedes"
           data-toggle="table"
           data-buttons-align="right"
           data-card-visible="true"
           data-page-list="[10, 15, 30, 50, 100, All]"
           data-page-size="10"
           data-pagination="true"
           data-pagination-detail-h-align="right"
           data-pagination-h-align="left"
           data-search="false"
           data-search-align="right"
           data-show-refresh="false"
           data-show-toggle="false"
           data-smart-display="true"
           data-toolbar="#toolbar"
           data-trim-on-search="true"
           data-undefined-text=""
           data-show-export="true"
           class="bootstrap-table ticketList table-nowrap">
        <thead style="font-size: 10px;">
            <tr class="ui-state-active noselect">
                <!--<th data-field="state" data-checkbox="true"></th>-->
                <th data-field="cif" data-sortable="true" data-width="5%">NIF</th>
                <th data-field="entitat" data-sortable="true" data-width="15%">ENTITAT</th>
                <th data-field="servicio" data-sortable="true" data-width="12%">SERVICIO</th>
                <!--<th data-field="lote" data-sortable="true" data-width="5%">LOTE</th>-->
                <th data-field="solicitante" data-sortable="true" data-width="5%">SOLICITANTE</th>
                <!--<th data-field="midas" data-sortable="true" data-width="5%">MIDAS</th>-->
                <th data-field="inicio" data-sortable="true" data-width="5%">PETICIÓN</th>
                <th data-field="linea" data-sortable="true" data-width="5%">ADM/Tel/Ext</th>
                <th data-field="peticion" data-sortable="true" data-width="5%">TIPO</th>
                <th data-field="tramitador" data-sortable="true" data-width="5%">TRAMITADOR</th>
                <th data-field="sede" data-sortable="true" data-width="15%">SEDE</th>
                <!--<th data-field="descripcion" data-sortable="true" data-width="5%">DESCRIPCIÓN</th>-->
                <th data-field="estado" data-sortable="true" data-width="5%">ESTADO</th>
                <th data-field="operation" data-width="10%" data-align="center" data-valign="middle">ACCIONES</th>
            </tr>
        </thead>
        <tbody style="font-size: 10px;">
            <?php foreach ($this->tramites as $item) : ?>
                <tr class="<?php echo $this->cycle(array('oddRowColor', 'evenRowColor'))->next(); ?> bootstrap-selectableRow greyText">
                    <!--<td></td>-->
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $item->nif); ?></td>
                    <?php $clienteName = ucwords(strtolower($item->cliente)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $clienteName); ?></td>
                    <?php $servicioName = ucwords(strtolower($item->servicio)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $servicioName); ?></td>
                    <!--<td class="noWrap"><?= ucwords(strtolower($item->lote)); ?></td>-->
                    <?php $solicitante = ucwords(strtolower($item->solicitante)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $solicitante); ?></td>
                    <!--<td class="noWrap"><?= ucwords(strtolower($item->midas)); ?></td>-->
                    <?php $inicio = date("Y-m-d", strtotime($item->inicio)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $inicio) ; ?></td>
                    <?php $linea = ucwords(strtolower($item->linea)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $linea); ?></td>
                    <?php $peticionName = ucwords(strtolower($item->peticion)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $peticionName); ?></td>
                    <?php $tramitador = ucwords(strtolower($item->tramitador)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $tramitador); ?></td>
                    <?php $sedeName = ucwords(strtolower($item->nombre)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $sedeName); ?></td>
                    <!--<td class="noWrap"><?= ucwords(strtolower($item->descripcion)); ?></td>-->
                    <?php $estadoName = ucwords(strtolower($item->estados)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $estadoName); ?></td>
                    <td class="noWrap">
                        <?php if('1' == $this->visible) : ?>
                        <a class="update" href="<?php echo $this->url('supply') . '/' . $item->id; ?>" title="Consultar">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        <?php elseif ('2' == $this->visible)  : ?>
                        <a class="update" href="<?php echo $this->url('supply') . '/' . $item->id . '/2'; ?>" title="Consultar">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
    </div>
</fieldset>
</div>

