<?=  $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/bootstrap-table/bootstrap-table.min.css'); ?>

<?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/bootstrap-table/bootstrap-table.js.') 
        ->appendFile($this->basePath() . '/js/bootstrap-table/locale/bootstrap-table-en-Sbt-US.min.js.'); ?>

<script type="text/javascript" style="display:none">
<!--

    $(function(){
//        $("html, body").animate({ scrollTop: 300 });
//        $("#mask").css('display','none');

        $("#search").keypress(function(e){
            if(e.which == 13){
                e.preventDefault();
                supplySearcher();
                return false;
            }
        });

        var $table = $('#supplies');
        var $exportData = $('#export-data');
        $table.on('check.bs.table uncheck.bs.table ' +
                    'check-all.bs.table uncheck-all.bs.table', () => {
            $exportData.prop('disabled', !$table.bootstrapTable('getSelections').length);

            // save your data, here just save the current page
            //selections = getIdSelections();
            // push or splice the selections if you want to save all data selections
            var data = JSON.stringify($table.bootstrapTable('getSelections'));
            $('#data').val(data);
        });






    });

    function esconder() {
        $('#exportDataModal').modal('hide');
    }


    function supplySearcher() {
        
        var url = '<?= $this->url('process-supply-search'); ?>';
        
        $.ajax({
            type: "GET",
            url: url,
            data: $('#supplySearcherForm').serialize(),
            cache: false,
            beforeSend: function() {
//                $("#mask").css('display','block');
                $("#fill-supply-search").html("<img style='display: block; margin:auto;' src='<?= $this->basePath() . '/img/loading.gif' ;?>' />");
            },
            success: function (json) {
                $("#fill-supply-search").html(json);
            },
            error: function (xhr, status) {
                html = "<div class='alert alert-danger'>Error!</div>"
                $("#box").html(html);
            }
        });
    }

//-->
</script>




<div class="ui-widget-header ui-corner-top ui-helper-clearfix" style="padding: 0.2em 0.6em;">&nbsp;</div>

<div id="toolbar">
    <div class="col-lg-6" style="padding-left: 0px;">
        <form id="supplySearcherForm">
            <div class="form-group input-group" >
                <input type="text" class="form-control" id="search" name="search" placeholder="Buscar ..." value="<?= $this->search; ?>"/>
                <input type="hidden" id="visible" name="visible" value="<?= $this->visible; ?>" />
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" onclick="supplySearcher();">
                        <i class="icon-search"></i>
                    </button>
                </span>
            </div>
        </form>    
    </div>
    <div class="col-lg-6" style="padding-right: 0px;">
        <button id='export-data' type="button" class="btn btn-primary" title="Exportación de datos" style="width: 98px; float: right;" data-toggle="modal" data-target="#exportDataModal" disabled>
            <i class="glyphicon glyphicon-export"></i>
        </button>
    </div>


    <!--    <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#exportModal">
                <i class="glyphicon glyphicon-hand-down"></i>&nbsp;Baja
            </button>
            <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#bulkCloseModal">
                <i class="glyphicon glyphicon-remove"></i>&nbsp;Eliminar
            </button>-->
    <!--        <button type="button" class="btn btn-primary" style="width: 110px;" data-toggle="modal" data-target="#bulkCancelModal">
                <i class="glyphicon glyphicon-export"></i>&nbsp;Exportar
            </button>-->
    <!--    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bulkCloseModal">
                <i class="glyphicon glyphicon-th-list"></i>&nbsp;Reporte BI
            </button>-->
</div>

    <table id="supplies"
           data-toggle="table"
           data-buttons-align="right"
           data-card-visible="true"
           data-page-list="[10, 15, 30, 50, 100, All]"
           data-page-size="10"
           data-pagination="true"
           data-pagination-detail-h-align="right"
           data-pagination-h-align="left"
           data-search="false"
           data-search-align="right"
           data-show-refresh="false"
           data-show-toggle="false"
           data-smart-display="true"
           data-toolbar="#toolbar"
           data-trim-on-search="true"
           data-undefined-text=""
           data-show-export="true"
           class="bootstrap-table ticketList table-nowrap">
        <thead style="font-size: 11px;">
            <tr class="ui-state-active noselect">
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="id" data-sortable="true" data-width="5%" class="hidden">ID</th>
                <th data-field="cif" data-sortable="true" data-width="5%">NIF</th>
                <th data-field="entitat" data-sortable="true" data-width="15%">ENTITAT</th>
                <th data-field="servicio" data-sortable="true" data-width="12%">SERVICIO</th>
                <th data-field="solicitante" data-sortable="true" data-width="5%">SOLICITANTE</th>
                <th data-field="inicio" data-sortable="true" data-width="5%">PETICIÓN</th>
                <th data-field="datecreated" data-sortable="true" data-width="5%" class="hidden">DATECREATED</th>
                <th data-field="fin" data-sortable="true" data-width="5%" class="hidden">DATEFINISH</th>
                <th data-field="currentdate" data-sortable="true" data-width="5%" class="hidden">CURRENTDATE</th>
                <th data-field="d" data-sortable="true" data-width="5%" class="hidden">DAYS</th>
                <th data-field="h" data-sortable="true" data-width="5%" class="hidden">HOURS</th>
                <th data-field="m" data-sortable="true" data-width="5%" class="hidden">MINUTES</th>
                <th data-field="s" data-sortable="true" data-width="5%" class="hidden">SECONDS</th>
                <th data-field="linea" data-sortable="true" data-width="5%">ADM/Tel/Ext</th>
                <th data-field="peticion" data-sortable="true" data-width="5%">TIPO</th>
                <th data-field="tramitador" data-sortable="true" data-width="5%">TRAMITADOR</th>
                <th data-field="asunto" data-sortable="true" data-width="15%">ASUNTO</th>
                <th data-field="sede" data-sortable="true" data-width="15%" class="hidden">SEDE</th>
                <th data-field="estado" data-sortable="true" data-width="5%">ESTADO</th>
                <th data-field="operation" data-width="10%" data-align="center" data-valign="middle">ACCIONES</th>
            </tr>
        </thead>
        <tbody style="font-size: 12px;">
            <?php foreach ($this->tramites as $item) : ?>
                <tr class="<?php echo $this->cycle(array('oddRowColor', 'evenRowColor'))->next(); ?> bootstrap-selectableRow greyText">
                    <td></td>
                    <td class="noWrap hidden"><?= $item->id; ?></td>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $item->nif); ?></td>
                    <?php $clienteName = ucwords(strtolower($item->cliente)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $clienteName); ?></td>
                    <?php $servicioName = ucwords(strtolower($item->servicio)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $servicioName); ?></td>
                    <!--<td class="noWrap"><?= ucwords(strtolower($item->lote)); ?></td>-->
                    <?php $solicitante = ucwords(strtolower($item->solicitante)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $solicitante); ?></td>
                    <!--<td class="noWrap"><?= ucwords(strtolower($item->midas)); ?></td>-->
                    <?php $inicio = date("Y-m-d", strtotime($item->inicio)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $inicio) ; ?></td>
                    <td class="noWrap hidden"><?= $item->inicio; ?></td>
                    <td class="noWrap hidden"><?= $item->fin; ?></td>
                    <td class="noWrap hidden"><?= $item->currentdate; ?></td>
                    <?php
                            $seconds = (int)$item->datetime;
                            $minutes = floor($seconds/60);
                            $hours =  floor($minutes/60);  	
                            $days = floor($hours/24);
                            $h = $hours-($days*24);
                            $m = $minutes-($hours*60);
                            $s = $seconds-($minutes*60);
                            $d = $days;
                    ?>
                    <td class="noWrap hidden"><?= $d; ?></td>
                    <td class="noWrap hidden"><?= $h; ?></td>
                    <td class="noWrap hidden"><?= $m; ?></td>
                    <td class="noWrap hidden"><?= $s; ?></td>
                    <?php $linea = ucwords(strtolower($item->linea)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $linea); ?></td>
                    <?php $peticionName = ucwords(strtolower($item->peticion)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $peticionName); ?></td>
                    <?php $tramitador = ucwords(strtolower($item->tramitador)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $tramitador); ?></td>
                    <?php $asunto = ucwords(strtolower($item->asunto)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $asunto); ?></td>
                    <td class="noWrap hidden"><?= ucwords(strtolower($item->nombre)); ?></td>
                    <?php $estadoName = ucwords(strtolower($item->estados)); ?>
                    <td class="noWrap"><?= str_ireplace($this->search, '<span style="background-color:red;color:white;font-weight:bold;">' . $this->search . '</span>', $estadoName); ?></td>
                    <td class="noWrap">
                        <?php if('1' == $this->visible) : ?>
                        <a class="update" href="<?php echo $this->url('supply') . '/' . $item->id; ?>" title="Consultar">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        <?php elseif ('2' == $this->visible)  : ?>
                        <a class="update" href="<?php echo $this->url('supply') . '/' . $item->id . '/2'; ?>" title="Consultar">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<!--    </div>
    <div class="clearfix">&nbsp;</div>
</div>
    </div>
</fieldset>
</div>-->

<div class="modal fade" id="exportDataModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="<?= $this->url('export-data'); ?>" method="post" onsubmit="esconder();">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"> Exportación de datos </h4>
                </div>
                <div class="modal-body">
                    Va a exportar los registros seleccionados.
                    <input type="hidden" id="data" name="data" value="1" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;"> Cancel </button>
                    <button type="submit" class="btn btn-danger" style="float: left;"> Exportar </button>
                </div>
            </form>    
        </div>
    </div>
</div>
