<?php echo $this->headLink()
                ->appendStylesheet($this->basePath('assets/select/css/bootstrap-select.min.css'));?>



<?php echo $this->headScript()
        ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js')
        ->appendFile($this->basePath('assets/select/js/bootstrap-select.min.js'));
?>

<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }
    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }
    .form-group
    {
        margin-bottom: 1px;
    }

/*    .form-control
    {
        height: 26px;
        font-size: 9px;

    }*/

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
    
  
  /* Notification */  
  .notification {
  position: fixed;
  padding: 8px;
  bottom: 15px;
  right: 15px;
  width: 55px;
  height: 55px;
  border-radius: 3px;
  color: white;
  opacity: 0;
  overflow: hidden;
  -webkit-animation: scale-in .3s ease-out forwards, expand .3s 1.5s ease-out forwards;
  animation: scale-in .3s ease-out forwards, expand .3s 1.5s ease-out forwards;
  z-index: 99;
}

.notification:hover {
    cursor: pointer;
}

.notification.success {
    background: #a7d155;
}

.notification.error {
    background: #E34F4F;
}

.notification .notification-icon {
    margin-right: 10px;
    float: left;
    width: 40px;
    height: 40px;
    border-radius: 25px;
    background: #ce4848;
    text-align: center;
}

.notification.error .notification-icon {
    background: #ce4848;
}

.notification.success .notification-icon {
    background: #97bd4f;
}

.notification .notification-icon i {
    font-size: 22px;
    line-height: 40px;
    color: #f5f5f5;
}

.notification-text {
  opacity: 0;
  font-size: .9em;
  text-align: left;
  color: #f5f5f5;
  letter-spacing: .5px;
  -webkit-animation: fade-in 1s 1s ease-in forwards;
  animation: fade-in 1s 1s ease-in forwards;
}
@-webkit-keyframes scale-in {

    0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 0;
    }
    
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}
@keyframes scale-in {

    0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 0;
    }
      
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}

@-webkit-keyframes expand {

   0% {
       width: 55px;
   } 

  100% {
    width: 330px;
  }
}

@keyframes expand {

   0% {
       width: 55px;
   } 

  100% {
    width: 330px;
  }
}

@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  
  100% {
    opacity: 1;
  }
}

.notification.scale-out {
    opacity: 1; 
  -webkit-animation: collapse .3s ease-in forwards, scale-out .3s 1.5s ease-out forwards;
  animation: collapse .3s ease-in forwards, scale-out .3s 1.5s ease-out forwards;
    
}
.notification.scale-out .notification-text {
  -webkit-animation: fade-out 1s  ease-in forwards;
  animation: fade-out 1s ease-in forwards;
}

@-webkit-keyframes collapse {
     0% {
       width: 330px;
   } 

  100% {
    width: 55px;
  }
}

@keyframes collapse {
     0% {
       width: 330px;
   } 

  100% {
    width: 55px;
  }
}

@-webkit-keyframes scale-out {

    0% { 
     -webkit-transform: scale(1);
    transform: scale(1);

    }
    
  100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  
}

@keyframes scale-out {

    0% { 
     -webkit-transform: scale(1);
    transform: scale(1);

    }
    
  100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  
}

@-webkit-keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

@keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

    
    
    
    
    
</style>                

<script type="text/javascript" style="display:none">

    $(document).ready(function(e){
        /* This code is executed after the DOM has been completely loaded */
        $('select').selectpicker({
            style: 'btn-select',
            size: 'auto',
            container: 'body',
        });

        if (/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)) {
            $('select').selectpicker('mobile');
        }

        $("#table-id").change(function() {

            var formulario = this.value;
            if('4' === formulario) {
                $('#form-tramitador').css('display','block');
            } else {
                $('#form-tramitador').css('display','none');
            }

        });
        
        $("#save-form-master").on("click", function(e){
            e.preventDefault();
            
            var url = '<?= $this->url('save-tables'); ?>';
            $.ajax({
                type: "POST",
                url: url,
                data: $('#Tramitador').serialize(),
                cache: false,
                success: function (html) {
                    $("#result").html(html);

                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#box").html(html);
                }
            });            
            
            //Response server message
            var output = '<div class="notification success"><span class="notification-icon"><i class="glyphicon glyphicon-ok" aria-hidden="true"></i></span><span class="notification-text">' + 'Se ha guardado satisfactoriamente!' + '</span></div>';
            //If success clear inputs
            $("#tramitador").val('');
            $("#backup").prop('checked',false);
            $("#save-form-master").addClass('disabled');

            $("#notification").html(output);
            $(".notification").delay(8000).queue(function (next) {
                $(this).addClass("scale-out");
                next();
            });
            $(".notification").on("click", function(){ 
                $(this).addClass("scale-out");
            });


        });
        
        
    });

</script>

<?php
    $form = $this->form;
//    $form->setAttribute('action', $this->url('save-tables'));
//    $form->setAttribute('id', 'formTramitador');
//    $form->setAttribute('role', 'form');
    $form->setAttribute('data-toggle', 'validator');
    $form->setAttribute('accept-charset', 'utf-8');
    #$form->setAttribute('novalidate', 'novalidate');
    $form->prepare();
?>



<fieldset class="col-md-6">
    <legend>Tablas maestras</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-12">
                <div class="form-group">
                    <label>Tablas</label>
                    <div class="form_select">
                        <select id="table-id" name="table-id" class="form-control" title="Selecciona la tabla maestra" data-header="Selecciona la tabla maestra" data-live-search="true" data-size="5">
                            <option value="1">Cliente</option>
                            <option value="2">Estados de trámites</option>
                            <option value="3">Tipos de trámites</option>
                            <option value="4">Tramitadores</option>
                            <option value="5">Servicios</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</fieldset>

<?= $this->form()->openTag($form); ?>
<fieldset id="form-tramitador" class="col-md-12" style="display: none;">
    <legend>Alta de tramitadores</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-6">
                
                <div class="form-group">
                    <label for="tramitador">Tramitador</label>
                    <?= $this->formInput($form->get('tramitador')); ?>
                </div>
                
                <div class="form-group">&nbsp;</div>
                
                <div class="form-group">
                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" id="backup" value="1" name="backup" class="form-check-input">
                            ¿Es backup?
                        </label>
                    </div>                        
                </div>

                <input type="hidden" id="entity" name="entity" value="\Tramitador" />
                <input type="hidden" id="activo" name="activo" value="1" />

                <div class="form-group">&nbsp;</div>

                <div style="float:right;">
                    <button id="save-form-master" class="btn btn-primary" title="Guardar" type="submit"  ><span class="glyphicon glyphicon-saved"></span></button>
                </div>
                
            </div>
            <div class="col-lg-6">

                <div class="form-group">&nbsp;</div>

            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
</fieldset>
<?= $this->form()->closeTag($form); ?>
<div id="result"></div>