<?php echo $this->headLink()
                ->appendStylesheet($this->basePath('assets/select/css/bootstrap-select.min.css'));?>



<?php echo $this->headScript()
        ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js')
        ->appendFile($this->basePath('assets/select/js/bootstrap-select.min.js'));
?>

<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }
    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }
    .form-group
    {
        margin-bottom: 1px;
    }

/*    .form-control
    {
        height: 26px;
        font-size: 9px;

    }*/

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
    
  
  /* Notification */  
  .notification {
  position: fixed;
  padding: 8px;
  bottom: 15px;
  right: 15px;
  width: 55px;
  height: 55px;
  border-radius: 3px;
  color: white;
  opacity: 0;
  overflow: hidden;
  -webkit-animation: scale-in .3s ease-out forwards, expand .3s 1.5s ease-out forwards;
  animation: scale-in .3s ease-out forwards, expand .3s 1.5s ease-out forwards;
  z-index: 99;
}

.notification:hover {
    cursor: pointer;
}

.notification.success {
    background: #a7d155;
}

.notification.error {
    background: #E34F4F;
}

.notification .notification-icon {
    margin-right: 10px;
    float: left;
    width: 40px;
    height: 40px;
    border-radius: 25px;
    background: #ce4848;
    text-align: center;
}

.notification.error .notification-icon {
    background: #ce4848;
}

.notification.success .notification-icon {
    background: #97bd4f;
}

.notification .notification-icon i {
    font-size: 22px;
    line-height: 40px;
    color: #f5f5f5;
}

.notification-text {
  opacity: 0;
  font-size: .9em;
  text-align: left;
  color: #f5f5f5;
  letter-spacing: .5px;
  -webkit-animation: fade-in 1s 1s ease-in forwards;
  animation: fade-in 1s 1s ease-in forwards;
}
@-webkit-keyframes scale-in {

    0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 0;
    }
    
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}
@keyframes scale-in {

    0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 0;
    }
      
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}

@-webkit-keyframes expand {

   0% {
       width: 55px;
   } 

  100% {
    width: 330px;
  }
}

@keyframes expand {

   0% {
       width: 55px;
   } 

  100% {
    width: 330px;
  }
}

@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  
  100% {
    opacity: 1;
  }
}

.notification.scale-out {
    opacity: 1; 
  -webkit-animation: collapse .3s ease-in forwards, scale-out .3s 1.5s ease-out forwards;
  animation: collapse .3s ease-in forwards, scale-out .3s 1.5s ease-out forwards;
    
}
.notification.scale-out .notification-text {
  -webkit-animation: fade-out 1s  ease-in forwards;
  animation: fade-out 1s ease-in forwards;
}

@-webkit-keyframes collapse {
     0% {
       width: 330px;
   } 

  100% {
    width: 55px;
  }
}

@keyframes collapse {
     0% {
       width: 330px;
   } 

  100% {
    width: 55px;
  }
}

@-webkit-keyframes scale-out {

    0% { 
     -webkit-transform: scale(1);
    transform: scale(1);

    }
    
  100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  
}

@keyframes scale-out {

    0% { 
     -webkit-transform: scale(1);
    transform: scale(1);

    }
    
  100% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  }
  
}

@-webkit-keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

@keyframes fade-out {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

    
    
    
    
    
</style>                

<script type="text/javascript" style="display:none">

    $(document).ready(function(e){
        /* This code is executed after the DOM has been completely loaded */
        $('#table-id').selectpicker({
            style: 'btn-select',
            size: 'auto',
            container: 'body',
        });

        if (/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)) {
            $('#table-id').selectpicker('mobile');
        }

        $("#table-id").change(function() {

            var formulario = this.value;
            $('#formName').val(formulario);
            if('Tramitador' === formulario) {
                $('#form-tramitador').css('display','block');
                $('#form-cliente').css('display','none');
                $('#form-servicio').css('display','none');
                $('#form-peticion').css('display','none');
                $('#form-estado').css('display','none');                
            } else if('Cliente' === formulario) {
                $('#form-tramitador').css('display','none');
                $('#form-cliente').css('display','block');
                $('#form-servicio').css('display','none');
                $('#form-peticion').css('display','none');
                $('#form-estado').css('display','none');                
            } else if('Servicio' === formulario) {
                $('#form-servicio').css('display','block');
                $('#form-tramitador').css('display','none');
                $('#form-cliente').css('display','none');
                $('#form-peticion').css('display','none');
                $('#form-estado').css('display','none');
            } else if('Peticion' === formulario) {
                $('#form-peticion').css('display','block');
                $('#form-servicio').css('display','none');
                $('#form-tramitador').css('display','none');
                $('#form-cliente').css('display','none');
                $('#form-estado').css('display','none');                
            } else if('Estado' === formulario) {
                $('#form-estado').css('display','block');
                $('#form-peticion').css('display','none');
                $('#form-servicio').css('display','none');
                $('#form-tramitador').css('display','none');
                $('#form-cliente').css('display','none');
            } else {
                $('#form-tramitador').css('display','none');
                $('#form-cliente').css('display','none');
                $('#form-servicio').css('display','none');
                $('#form-peticion').css('display','none');
                $('#form-estado').css('display','none');
            }

        });
        
        $("#save-formTramitador").on("click", function(e){
            e.preventDefault();
            
            var url = '<?= $this->url('save-tables'); ?>';
            var formName = $('#formName').val();
            $.ajax({
                type: "POST",
                url: url,
                data: $('#'+formName).serialize(),
                cache: false,
                success: function (html) {
                    $("#result").html(html);

                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#box").html(html);
                }
            });            
            
            //Response server message
            var output = '<div class="notification success"><span class="notification-icon"><i class="glyphicon glyphicon-ok" aria-hidden="true"></i></span><span class="notification-text">' + 'Se ha guardado satisfactoriamente!' + '</span></div>';
            //If success clear inputs
            $("#tramitador").val('');
            $("#backup").prop('checked',false);
            $("#save-formTramitador").addClass('disabled');

            $("#notification").html(output);
            $(".notification").delay(8000).queue(function (next) {
                $(this).addClass("scale-out");
                next();
            });
            $(".notification").on("click", function(){ 
                $(this).addClass("scale-out");
            });

        });
        
        $("#save-formCliente").on("click", function(e){
            e.preventDefault();
            
            var url = '<?= $this->url('save-tables'); ?>';
            var formName = $('#formName').val();
            $.ajax({
                type: "POST",
                url: url,
                data: $('#'+formName).serialize(),
                cache: false,
                success: function (html) {
                    $("#result").html(html);

                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#box").html(html);
                }
            });            
            
            //Response server message
            var output = '<div class="notification success"><span class="notification-icon"><i class="glyphicon glyphicon-ok" aria-hidden="true"></i></span><span class="notification-text">' + 'Se ha guardado satisfactoriamente!' + '</span></div>';
            //If success clear inputs
            $("#cliente").val('');
            $("#nif").val('');
            $("#save-formCliente").addClass('disabled');

            $("#notification").html(output);
            $(".notification").delay(8000).queue(function (next) {
                $(this).addClass("scale-out");
                next();
            });
            $(".notification").on("click", function(){ 
                $(this).addClass("scale-out");
            });

        });
        
        
        $("#save-formServicio").on("click", function(e){
            e.preventDefault();
            
            var url = '<?= $this->url('save-tables'); ?>';
            var formName = $('#formName').val();
            $.ajax({
                type: "POST",
                url: url,
                data: $('#'+formName).serialize(),
                cache: false,
                success: function (html) {
                    $("#result").html(html);

                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#box").html(html);
                }
            });            
            
            //Response server message
            var output = '<div class="notification success"><span class="notification-icon"><i class="glyphicon glyphicon-ok" aria-hidden="true"></i></span><span class="notification-text">' + 'Se ha guardado satisfactoriamente!' + '</span></div>';
            //If success clear inputs
            $("#servicio").val('');
            $("#save-formServicio").addClass('disabled');

            $("#notification").html(output);
            $(".notification").delay(8000).queue(function (next) {
                $(this).addClass("scale-out");
                next();
            });
            $(".notification").on("click", function(){ 
                $(this).addClass("scale-out");
            });

        });
        

        $("#save-formPeticion").on("click", function(e){
            e.preventDefault();
            
            var url = '<?= $this->url('save-tables'); ?>';
            var formName = $('#formName').val();
            $.ajax({
                type: "POST",
                url: url,
                data: $('#'+formName).serialize(),
                cache: false,
                success: function (html) {
                    $("#result").html(html);

                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#box").html(html);
                }
            });            
            
            //Response server message
            var output = '<div class="notification success"><span class="notification-icon"><i class="glyphicon glyphicon-ok" aria-hidden="true"></i></span><span class="notification-text">' + 'Se ha guardado satisfactoriamente!' + '</span></div>';
            //If success clear inputs
            $("#peticion").val('');
            $("#save-formPeticion").addClass('disabled');

            $("#notification").html(output);
            $(".notification").delay(8000).queue(function (next) {
                $(this).addClass("scale-out");
                next();
            });
            $(".notification").on("click", function(){ 
                $(this).addClass("scale-out");
            });

        });

        $("#save-formEstado").on("click", function(e){
            e.preventDefault();
            
            var url = '<?= $this->url('save-tables'); ?>';
            var formName = $('#formName').val();
            $.ajax({
                type: "POST",
                url: url,
                data: $('#'+formName).serialize(),
                cache: false,
                success: function (html) {
                    $("#result").html(html);

                },
                error: function (xhr, status) {
                    html = "<div class='alert alert-danger'>Error!</div>"
                    $("#box").html(html);
                }
            });            
            
            //Response server message
            var output = '<div class="notification success"><span class="notification-icon"><i class="glyphicon glyphicon-ok" aria-hidden="true"></i></span><span class="notification-text">' + 'Se ha guardado satisfactoriamente!' + '</span></div>';
            //If success clear inputs
            $("#estado").val('');
            $("#visible").val('1');
            $("#save-formEstado").addClass('disabled');

            $("#notification").html(output);
            $(".notification").delay(8000).queue(function (next) {
                $(this).addClass("scale-out");
                next();
            });
            $(".notification").on("click", function(){ 
                $(this).addClass("scale-out");
            });

        });

    });

</script>

<?php
    $form = $this->form;
//    $form->setAttribute('action', $this->url('save-tables'));
//    $form->setAttribute('id', 'formTramitador');
//    $form->setAttribute('role', 'form');
    $form->setAttribute('data-toggle', 'validator');
    $form->setAttribute('accept-charset', 'utf-8');
    #$form->setAttribute('novalidate', 'novalidate');
    $form->prepare();
?>



<fieldset class="col-md-6">
    <legend>Tablas maestras</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-12">
                <div class="form-group">
                    <label>Tablas</label>
                    <div class="form_select">
                        <select id="table-id" name="table-id" class="form-control" title="Selecciona la tabla maestra" data-header="Selecciona la tabla maestra" data-live-search="true" data-size="5">
                            <option value="Cliente">Cliente</option>
                            <option value="Estado">Estados de trámites</option>
                            <option value="Peticion">Tipo de trámites</option>
                            <option value="Tramitador">Tramitadores</option>
                            <option value="Servicio">Servicios</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</fieldset>

<input type="hidden" id="formName" name="formName" value="" />
<fieldset id="form-tramitador" class="col-md-12" style="display: none;">
    <?= $this->form()->openTag($form); ?>
    <legend>Alta de tramitadores</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-6">
                
                <div class="form-group">
                    <label for="tramitador">Tramitador</label>
                    <?= $this->formInput($form->get('tramitador')); ?>
                </div>
                
                <div class="form-group">&nbsp;</div>
                
                <div class="form-group">
                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" id="backup" value="1" name="backup" class="form-check-input">
                            ¿Es backup?
                        </label>
                    </div>
                </div>

                <input type="hidden" id="entity" name="entity" value="\Tramitador" />
                <input type="hidden" id="activo" name="activo" value="1" />

                <div class="form-group">&nbsp;</div>

                <div style="float:right;">
                    <button id="save-formTramitador" class="btn btn-primary" title="Guardar" type="submit"  ><span class="glyphicon glyphicon-saved"></span></button>
                </div>
                
            </div>
            <div class="col-lg-6">

                <div class="form-group">&nbsp;</div>

            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
    <?= $this->form()->closeTag($form); ?>
</fieldset>
<?php
    $cliente = $this->cliente;
    $cliente->setAttribute('data-toggle', 'validator');
    $cliente->setAttribute('accept-charset', 'utf-8');
    $cliente->prepare();
?>
<fieldset id="form-cliente" class="col-md-12" style="display: none;">
    <?= $this->form()->openTag($cliente); ?>
    <legend>Alta de clientes</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-6">
                
                <div class="form-group">
                    <label for="cliente">Cliente</label>
                    <?= $this->formInput($cliente->get('cliente')); ?>
                </div>
                
                <div class="form-group">
                    <label for="nif">NIF</label>
                    <?= $this->formInput($cliente->get('nif')); ?>
                </div>

                <input type="hidden" id="entity" name="entity" value="\Cliente" />
                <input type="hidden" id="activo" name="activo" value="1" />

                <div class="form-group">&nbsp;</div>

                <div style="float:right;">
                    <button id="save-formCliente" class="btn btn-primary" title="Guardar" type="submit"  ><span class="glyphicon glyphicon-saved"></span></button>
                </div>
                
            </div>
            <div class="col-lg-6">

                <div class="form-group">&nbsp;</div>

            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
    <?= $this->form()->closeTag($cliente); ?>
</fieldset>
<?php
    $servicio = $this->servicio;
    $servicio->setAttribute('data-toggle', 'validator');
    $servicio->setAttribute('accept-charset', 'utf-8');
    $servicio->prepare();
?>
<fieldset id="form-servicio" class="col-md-12" style="display: none;">
    <?= $this->form()->openTag($servicio); ?>
    <legend>Alta de servicios</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-6">
                
                <div class="form-group">
                    <label for="servicio">Servicio</label>
                    <?= $this->formInput($servicio->get('servicio')); ?>
                </div>
                
                <input type="hidden" id="entity" name="entity" value="\Servicio" />
                <input type="hidden" id="activo" name="activo" value="1" />

                <div class="form-group">&nbsp;</div>

                <div style="float:right;">
                    <button id="save-formServicio" class="btn btn-primary" title="Guardar" type="submit"  ><span class="glyphicon glyphicon-saved"></span></button>
                </div>
                
            </div>
            <div class="col-lg-6">

                <div class="form-group">&nbsp;</div>

            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
    <?= $this->form()->closeTag($servicio); ?>
</fieldset>
<?php
    $peticion = $this->peticion;
    $peticion->setAttribute('data-toggle', 'validator');
    $peticion->setAttribute('accept-charset', 'utf-8');
    $peticion->prepare();
?>
<fieldset id="form-peticion" class="col-md-12" style="display: none;">
    <?= $this->form()->openTag($peticion); ?>
    <legend>Alta de tipo de trámites</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-6">
                
                <div class="form-group">
                    <label for="peticion">Trámite</label>
                    <?= $this->formInput($peticion->get('peticion')); ?>
                </div>
                
                <input type="hidden" id="entity" name="entity" value="\Peticion" />
                <input type="hidden" id="activo" name="activo" value="1" />

                <div class="form-group">&nbsp;</div>

                <div style="float:right;">
                    <button id="save-formPeticion" class="btn btn-primary" title="Guardar" type="submit"  ><span class="glyphicon glyphicon-saved"></span></button>
                </div>
                
            </div>
            <div class="col-lg-6">

                <div class="form-group">&nbsp;</div>

            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
    <?= $this->form()->closeTag($peticion); ?>
</fieldset>
<?php
    $estado = $this->estado;
    $estado->setAttribute('data-toggle', 'validator');
    $estado->setAttribute('accept-charset', 'utf-8');
    $estado->prepare();
?>
<fieldset id="form-estado" class="col-md-12" style="display: none;">
    <?= $this->form()->openTag($estado); ?>
    <legend>Alta de estados de un trámite</legend>
    <div class="panel panel-default">
        <div class="panel-body" data-toggle="validator">
            <div class="col-lg-6">

                <div class="form-group">
                    <label for="estado">Estado</label>
                    <?= $this->formInput($estado->get('estado')); ?>
                </div>

                <div class="form-group">&nbsp;</div>

                <div class="form-group">
                    <label for="visible">Contexto</label>
                    <?= $this->formSelect($estado->get('visible')); ?>
                </div>

                <input type="hidden" id="entity" name="entity" value="\Estado" />
                <input type="hidden" id="activo" name="activo" value="1" />

                <div class="form-group">&nbsp;</div>

                <div style="float:right;">
                    <button id="save-formEstado" class="btn btn-primary" title="Guardar" type="submit"><span class="glyphicon glyphicon-saved"></span></button>
                </div>

            </div>
            <div class="col-lg-6">

                <div class="form-group">&nbsp;</div>

            </div>
            
        <div class="clearfix"></div>
        </div>
    </div>
    <?= $this->form()->closeTag($estado); ?>
</fieldset>
<div id="result"></div>