<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }
    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }
    .form-group
    {
        margin-bottom: 1px;
    }

/*    .form-control
    {
        height: 26px;
        font-size: 9px;

    }*/

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
</style>                

<style type="text/css" style="display:none">
.clock{
	/* The .clock div. Created dynamically by jQuery */
	background-color:#252525;
	height:200px;
	width:200px;
	position:relative;
	overflow:hidden;
	float:left;
       
}
.clock .rotate{
	/* There are two .rotate divs - one for each half of the background */
	position:absolute;
	width:200px;
	height:200px;
	top:0;
	left:0;
        
}
.rotate.right{
	display:none;
	z-index:11;
}
.clock .bg, .clock .front{
	width:100px;
	height:200px;
	background-color:#252525; /*252525*/
	position:absolute;
	top:0;
}
.clock .display{
	/* Holds the number of seconds, minutes or hours respectfully */
	position:absolute;
	width:200px;
	font-family:"Lucida Sans Unicode", "Lucida Grande", sans-serif;
	z-index:20;
	color:#F5F5F5;
	font-size:60px;
	text-align:center;
	top:65px;
	left:0;
	/* CSS3 text shadow: */
	text-shadow:4px 4px 5px #333333;
        
}

/* The left part of the background: */
.clock .bg.left{ left:0;}

/* Individual styles for each color: */

.red .bg.left{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat left top; }
.orange .bg.left{ background:url(<?= $this->basePath() . '/img/bg_orange.png' ;?>) no-repeat left top; }
.green .bg.left{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat left top; }
.blue .bg.left{ background:url(<?= $this->basePath() . '/img/bg_blue.png' ;?>) no-repeat left top; }



/* The right part of the background: */
.clock .bg.right{ left:100px; }

.red .bg.right{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat right top; }
.orange .bg.right{ background:url(<?= $this->basePath() . '/img/bg_orange.png' ;?>) no-repeat right top; }
.green .bg.right{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat right top; }
.blue .bg.right{ background:url(<?= $this->basePath() . '/img/bg_blue.png' ;?>) no-repeat right top; }


.clock .front.left{
	left:0;
	z-index:10;
}

</style>

<script type="text/javascript" style="display:none">
<!--

(function($){
	
	// A global array used by the functions of the plug-in:
	var gVars = {};

	// Extending the jQuery core:
	$.fn.tzineClock = function(opts){
	
		// "this" contains the elements that were selected when calling the plugin: $('elements').tzineClock();
		// If the selector returned more than one element, use the first one:
		
		var container = this.eq(0);
	
		if(!container)
		{
			try{
				console.log("Invalid selector!");
			} catch(e){}
			
			return false;
		}
		
		if(!opts) opts = {}; 
		
		var defaults = {
			/* Additional options will be added in future versions of the plugin. */
		};
		
		/* Merging the provided options with the default ones (will be used in future versions of the plugin): */
		$.each(defaults,function(k,v){
			opts[k] = opts[k] || defaults[k];
		})

		// Calling the setUp function and passing the container,
		// will be available to the setUp function as "this":
		setUp.call(container);
		
		return this;
	}
	
	function setUp()
	{
		// The colors of the dials:
		var colors = ['red', 'orange', 'blue','green'];
		
		var tmp;
		
		for(var i=0;i<4;i++)
		{
			// Creating a new element and setting the color as a class name:
			
			tmp = $('<div>').attr('class',colors[i]+' clock').html(
				'<div class="display"></div>'+
				
				'<div class="front left"></div>'+
				
				'<div class="rotate left">'+
					'<div class="bg left"></div>'+
				'</div>'+
				
				'<div class="rotate right">'+
					'<div class="bg right"></div>'+
				'</div>'
			);
			
			// Appending to the container:
			$(this).append(tmp);
			
			// Assigning some of the elements as variables for speed:
			tmp.rotateLeft = tmp.find('.rotate.left');
			tmp.rotateRight = tmp.find('.rotate.right');
			tmp.display = tmp.find('.display');
			
			// Adding the dial as a global variable. Will be available as gVars.colorName
			gVars[colors[i]] = tmp;
		}
		
		// Setting up a interval, executed every 1000 milliseconds:
		setInterval(function(){
		
			//var currentTime = new Date();
			//var h = currentTime.getHours();
			//var m = currentTime.getMinutes();
			//var s = currentTime.getSeconds();
			
                        
			/* NEW */
			var year =  '<?= $this->information['tramite']['0']['year']; ?>';
                        var month =  '<?= $this->information['tramite']['0']['month']; ?>';
                        var day =  '<?= $this->information['tramite']['0']['day']; ?>';
                        var hour =  '<?= $this->information['tramite']['0']['hour']; ?>';
                        var minut =  '<?= $this->information['tramite']['0']['minut']; ?>';
                        var second =  '<?= $this->information['tramite']['0']['second']; ?>';
                        // 2018,03,08,00,30,00
			var date_past = new Date(year,month,day,hour,minut,second);
                        //alert('DATE PASADO ' + date_past);
			var date_now = new Date();

			var seconds = Math.floor((date_now - (date_past))/1000);
			
			var minutes = Math.floor(seconds/60);
			var hours = Math.floor(minutes/60);
			var days = Math.floor(hours/24);
			
			//alert('MINUTES : ' + minutes);
			//alert('HOURS : ' + hours);
			var h = hours-(days*24);
			//var m = minutes-(days*24*60)-(hours*60);
			var m = minutes-(hours*60);
			//alert('CALCULO : ' + minutes + ' DAY : ' + days*24*60 + ' HOURS : ' + hours*60);
			//var s = seconds-(days*24*60*60)-(hours*60*60)-(minutes*60);
			var s = seconds-(minutes*60);
			//alert('	m : ' + m);
			var d = days;
			
			/* END */
			
			animation(gVars.green, s, 60);
			animation(gVars.blue, m, 60);
			animation(gVars.orange, h, 24);
			animation(gVars.red, d, 360);
		
		},1000);
	}
	
	function animation(clock, current, total)
	{
		// Calculating the current angle:
		var angle = (360/total)*(current+1);
	
		var element;
                
		if(current==0)
		{
			// Hiding the right half of the background:
			clock.rotateRight.hide();
			
			// Resetting the rotation of the left part:
			rotateElement(clock.rotateLeft,0);
		}
		
		if(angle<=180)
		{
			// The left part is rotated, and the right is currently hidden:
			element = clock.rotateLeft;
		}
		else
		{
			// The first part of the rotation has completed, so we start rotating the right part:
			clock.rotateRight.show();
			clock.rotateLeft.show();
			
			rotateElement(clock.rotateLeft,180);
			
			element = clock.rotateRight;
			angle = angle-180;
		}

		rotateElement(element,angle);
		
		// Setting the text inside of the display element, inserting a leading zero if needed:
		clock.display.html(current<10?'0'+current:current);
	}
	
	function rotateElement(element,angle)
	{
		// Rotating the element, depending on the browser:
		var rotate = 'rotate('+angle+'deg)';
		
		if(element.css('MozTransform')!=undefined)
			element.css('MozTransform',rotate);
			
		else if(element.css('WebkitTransform')!=undefined)
			element.css('WebkitTransform',rotate);
	
		// A version for internet explorer using filters, works but is a bit buggy (no surprise here):
		else if(element.css("filter")!=undefined)
		{
			var cos = Math.cos(Math.PI * 2 / 360 * angle);
			var sin = Math.sin(Math.PI * 2 / 360 * angle);
			
			element.css("filter","progid:DXImageTransform.Microsoft.Matrix(M11="+cos+",M12=-"+sin+",M21="+sin+",M22="+cos+",SizingMethod='auto expand',FilterType='nearest neighbor')");
	
			element.css("left",-Math.floor((element.width()-200)/2));
			element.css("top",-Math.floor((element.height()-200)/2));
		}
	
	}
	
})(jQuery)
//-->
</script>

<script type="text/javascript" style="display:none">
<!--
$(document).ready(function(e){
	/* This code is executed after the DOM has been completely loaded */

	$('#fancyClock').tzineClock();

        $(".btn-pref .btn").click(function () {
            $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
            // $(".tab").addClass("active"); // instead of this do the below 
            $(this).removeClass("btn-default").addClass("btn-primary");   
        });



});
//-->
</script>











<!--<script>
$(document).ready(function (e){

    $(".btn-pref .btn").click(function () {
        $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
        // $(".tab").addClass("active"); // instead of this do the below 
        $(this).removeClass("btn-default").addClass("btn-primary");   
    });
    
    });
</script>-->
<fieldset class="col-md-12">
    <legend>Seguimiento de Provisiones</legend>
    <div class="panel panel-default">
        <div class="panel-body">


<div style="padding: 4px;" class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab" style="width:100%;">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
            <div class="hidden-xs">&nbsp;&nbsp;&nbsp;Trámite&nbsp;&nbsp;&nbsp;</div>
            <div class="hidden-xs">&nbsp;</div>
        </button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab" style="width:100%;">
            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
            <div class="hidden-xs">&nbsp;&nbsp;&nbsp;&nbsp;SLA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
            <div class="hidden-xs">&nbsp;</div>
        </button>
    </div>
</div>
<div class="tab-content" style="margin: 2px; padding: 2px;">
    <div class="tab-pane fade in active" id="tab1">
        
                    <div class="col-lg-4">    

                            <div class="form-group">
                                <label for="exampleSelect1">Entidad</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>Ajuntament de Baga</option>
                                    <option>Ajuntament de El Brull</option>
                                    <option>Ajuntament de Calonge de Segarra</option>
                                    <option>Diputacion de Barcelona</option>
                                    <option>Serveis Municipal de Montseny S.L.</option>
                                    <option>Xarxa Audiovisual Local</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">NIF</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Fecha de Solicitud</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                        
                            <div class="form-group">
                                <label for="exampleInputEmail1">Solicitante</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                        
                            <div class="form-group">
                                <label for="exampleInputEmail1">Adm/Tel/Ext</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">MIDAS</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                        
                            <div class="form-group">
                                <label for="exampleSelect1">Sede</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>Ajuntament de Baga</option>
                                    <option>Ajuntament de El Brull</option>
                                    <option>Ajuntament de Calonge de Segarra</option>
                                    <option>Diputacion de Barcelona</option>
                                    <option>Serveis Municipal de Montseny S.L.</option>
                                    <option>Xarxa Audiovisual Local</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Lote</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>Lote 2</option>
                                    <option>Lote 3 </option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleSelect1">Servicio</label>
                                <select class="form-control" id="exampleSelect1">
                                    <option>Macrolan</option>
                                    <option>DataInternet</option>
                                </select>
                            </div>

                    </div>    
                    
                    <div class="col-lg-4">    

                        <div class="form-group">
                            <label for="exampleSelect1">Tipo de Petición</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Alta</option>
                                <option>Baja</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleSelect1">Tramitador</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>Edgar</option>
                                <option>Marta</option>
                                <option>Oscar</option>
                            </select>
                        </div>
                    
                        <div class="form-group">
                                <label for="exampleInputEmail1">ODIN VOZ</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>
                        
                        <div class="form-group">
                                <label for="exampleInputEmail1">BJ</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>
                        
                        <div class="form-group">
                                <label for="exampleInputEmail1">ODIN DATOS</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>
                        
                        <div class="form-group">
                                <label for="exampleInputEmail1">SG</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>
                        
                        <div class="form-group">
                                <label for="exampleInputEmail1">Atlas</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>

                        <div class="form-group">
                                <label for="exampleInputEmail1">Visord</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>
                        
                        <div class="form-group">
                            <label for="exampleSelect1">Estado</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>En curso</option>
                                <option>Coordinada</option>
                                <option>Incidencia</option>
                            </select>
                        </div>
                        
                    </div>    
        
                    <div class="col-lg-4">    
                        <div class="form-group">
                            <label for="exampleTextarea">Observación</label>
                            <textarea class="form-control input-sm" rows="4"></textarea>
                        </div>                        

                       

                    </div>    
        
        
        
    </div>
    <div class="tab-pane fade in" id="tab2">
        <div id="fancyClock"></div>
    </div>
    
    <div class="clearfix"></div>
</div>
            
</div>
</div>
</fieldset>    
            