<style>
    .btn-pref .btn {
        -webkit-border-radius:0 !important;
    }
    fieldset 
    {
        border: 1px solid #ddd !important;
        margin: 0;
        xmin-width: 0;
        padding: 4px;       
        position: relative;
        border-radius:4px;
        background-color:#f5f5f5;
        padding-left:10px!important;
    }	
    legend
    {
        font-size:14px;
        font-weight:bold;
        margin-bottom: 0px; 
        width: 35%; 
        border: 1px solid #ddd;
        border-radius: 4px; 
        padding: 2px 2px 2px 4px; 
        background-color: #ffffff;
    }
    .form-group
    {
        margin-bottom: 1px;
    }

/*    .form-control
    {
        height: 26px;
        font-size: 9px;

    }*/

    .panel
    {
        margin-bottom: 2px;
    }

    .tab-content
    {
        padding: 0px;
    }

    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td
    {
        padding: 4px;
    }
    
    /* Custom */
    .custom-fieldset
    {
        background-color:#ffffff;
    }
    .custom-legend
    {
        width: 60%;
        font-size: 12px;
        border: 0px solid #ddd;
    }
    .custom-label
    {
        font-size: 12px;
    }
    .custom-radio
    {
        font-size: 10px;
    }
    
    .table-hover tbody tr:hover td {
        background: #FFCCCC;
        
    }
    .table-hover tbody tr:hover td span {
        
        color: black;
    }
    
    
</style>                

<style type="text/css" style="display:none">
.clock{
	/* The .clock div. Created dynamically by jQuery */
	background-color:#252525;
	height:200px;
	width:200px;
	position:relative;
	overflow:hidden;
	float:left;
       
}
.clock .rotate{
	/* There are two .rotate divs - one for each half of the background */
	position:absolute;
	width:200px;
	height:200px;
	top:0;
	left:0;
        
}
.rotate.right{
	display:none;
	z-index:11;
}
.clock .bg, .clock .front{
	width:100px;
	height:200px;
	background-color:#252525; /*252525*/
	position:absolute;
	top:0;
}
.clock .display{
	/* Holds the number of seconds, minutes or hours respectfully */
	position:absolute;
	width:200px;
	font-family:"Lucida Sans Unicode", "Lucida Grande", sans-serif;
	z-index:20;
	color:#F5F5F5;
	font-size:60px;
	text-align:center;
	top:65px;
	left:0;
	/* CSS3 text shadow: */
	text-shadow:4px 4px 5px #333333;
        
}

/* The left part of the background: */
.clock .bg.left{ left:0;}

/* Individual styles for each color: */

.red .bg.left{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat left top; }
.orange .bg.left{ background:url(<?= $this->basePath() . '/img/bg_orange.png' ;?>) no-repeat left top; }
.green .bg.left{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat left top; }
.blue .bg.left{ background:url(<?= $this->basePath() . '/img/bg_blue.png' ;?>) no-repeat left top; }



/* The right part of the background: */
.clock .bg.right{ left:100px; }

.red .bg.right{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat right top; }
.orange .bg.right{ background:url(<?= $this->basePath() . '/img/bg_orange.png' ;?>) no-repeat right top; }
.green .bg.right{ background:url(<?= $this->basePath() . '/img/bg_green.png' ;?>) no-repeat right top; }
.blue .bg.right{ background:url(<?= $this->basePath() . '/img/bg_blue.png' ;?>) no-repeat right top; }


.clock .front.left{
	left:0;
	z-index:10;
}

</style>

<script type="text/javascript" style="display:none">
<!--

(function($){
	
	// A global array used by the functions of the plug-in:
	var gVars = {};

	// Extending the jQuery core:
	$.fn.tzineClock = function(opts){
	
		// "this" contains the elements that were selected when calling the plugin: $('elements').tzineClock();
		// If the selector returned more than one element, use the first one:
		
		var container = this.eq(0);
	
		if(!container)
		{
			try{
				console.log("Invalid selector!");
			} catch(e){}
			
			return false;
		}
		
		if(!opts) opts = {}; 
		
		var defaults = {
			/* Additional options will be added in future versions of the plugin. */
		};
		
		/* Merging the provided options with the default ones (will be used in future versions of the plugin): */
		$.each(defaults,function(k,v){
			opts[k] = opts[k] || defaults[k];
		})

		// Calling the setUp function and passing the container,
		// will be available to the setUp function as "this":
		setUp.call(container);
		
		return this;
	}
	
	function setUp()
	{
		// The colors of the dials:
		var colors = ['red', 'orange', 'blue','green'];
		
		var tmp;
		
		for(var i=0;i<4;i++)
		{
			// Creating a new element and setting the color as a class name:
			
			tmp = $('<div>').attr('class',colors[i]+' clock').html(
				'<div class="display"></div>'+
				
				'<div class="front left"></div>'+
				
				'<div class="rotate left">'+
					'<div class="bg left"></div>'+
				'</div>'+
				
				'<div class="rotate right">'+
					'<div class="bg right"></div>'+
				'</div>'
			);
			
			// Appending to the container:
			$(this).append(tmp);
			
			// Assigning some of the elements as variables for speed:
			tmp.rotateLeft = tmp.find('.rotate.left');
			tmp.rotateRight = tmp.find('.rotate.right');
			tmp.display = tmp.find('.display');
			
			// Adding the dial as a global variable. Will be available as gVars.colorName
			gVars[colors[i]] = tmp;
		}
		
		// Setting up a interval, executed every 1000 milliseconds:
		setInterval(function(){
		
			//var currentTime = new Date();
			//var h = currentTime.getHours();
			//var m = currentTime.getMinutes();
			//var s = currentTime.getSeconds();
			

                    /* NEW */
			var year =  '<?= $this->information['tramite']['0']['inicioSplit']['year']; ?>';
                        var month =  '<?= $this->information['tramite']['0']['inicioSplit']['month']; ?>';
                        var day =  '<?= $this->information['tramite']['0']['inicioSplit']['day']; ?>';
                        var hour =  '<?= $this->information['tramite']['0']['inicioSplit']['hour']; ?>';
                        var minut =  '<?= $this->information['tramite']['0']['inicioSplit']['minut']; ?>';
                        var second =  '<?= $this->information['tramite']['0']['inicioSplit']['second']; ?>';
			var date_past = new Date(year,month,day,hour,minut,second);
                        
                        var date_process;
                        var finish = false;
                        <?php if(isset($this->information['tramite']['0']['finSplit'])) : ?>
                            var year2 =  '<?= $this->information['tramite']['0']['finSplit']['year']; ?>';
                            var month2 =  '<?= $this->information['tramite']['0']['finSplit']['month']; ?>';
                            var day2 =  '<?= $this->information['tramite']['0']['finSplit']['day']; ?>';
                            var hour2 =  '<?= $this->information['tramite']['0']['finSplit']['hour']; ?>';
                            var minut2 =  '<?= $this->information['tramite']['0']['finSplit']['minut']; ?>';
                            var second2 =  '<?= $this->information['tramite']['0']['finSplit']['second']; ?>';
                            date_process = new Date(year2,month2,day2,hour2,minut2,second2);    
                            finish = true;
                        <?php elseif(isset($this->information['tramite']['0']['inicioParadaSplit'])) : ?>
                            var year2 =  '<?= $this->information['tramite']['0']['inicioParadaSplit']['year']; ?>';
                            var month2 =  '<?= $this->information['tramite']['0']['inicioParadaSplit']['month']; ?>';
                            var day2 =  '<?= $this->information['tramite']['0']['inicioParadaSplit']['day']; ?>';
                            var hour2 =  '<?= $this->information['tramite']['0']['inicioParadaSplit']['hour']; ?>';
                            var minut2 =  '<?= $this->information['tramite']['0']['inicioParadaSplit']['minut']; ?>';
                            var second2 =  '<?= $this->information['tramite']['0']['inicioParadaSplit']['second']; ?>';
                            date_process = new Date(year2,month2,day2,hour2,minut2,second2);    
                        <?php else : ?>
                             date_process = new Date();
                        <?php endif ?> ;

                        // 1st REAL WATCH    
                        var seconds = Math.floor((date_process - (date_past))/1000);
			var minutes = Math.floor(seconds/60);
			var hours = Math.floor(minutes/60);
			var days = Math.floor(hours/24);
			var h = hours-(days*24);
			var m = minutes-(hours*60);
			var s = seconds-(minutes*60);
			var d = days;
			
			/* END */
			
			animation(gVars.green, s, 60);
			animation(gVars.blue, m, 60);
			animation(gVars.orange, h, 24);
			animation(gVars.red, d, 360);
                        
                        //2nd Timelife all
                        var timelifeAll;
                        if(finish) {
                            timelifeAll = date_process;
                        } else {
                            timelifeAll = new Date();
                        } 
                        var secondsAll = Math.floor((timelifeAll - (date_past))/1000);
			var minutesAll = Math.floor(secondsAll/60);
			var hoursAll = Math.floor(minutesAll/60);
			var daysAll = Math.floor(hoursAll/24);
			var hAll = hoursAll-(daysAll*24);
			var mAll = minutesAll-(hoursAll*60);
			var sAll = secondsAll-(minutesAll*60);
			var dAll = daysAll;

                        $("#days").text(dAll);
                        $("#hours").text(hAll);
                        $("#minutes").text(mAll);
                        $("#seconds").text(sAll);
                        
                        //3th Stop watch in process
                        var currentDate = new Date();
                        var secondsStop = Math.floor((currentDate - (date_process))/1000);
			var minutesStop = Math.floor(secondsStop/60);
			var hoursStop = Math.floor(minutesStop/60);
			var daysStop = Math.floor(hoursStop/24);
			var hStop = hoursStop-(daysStop*24);
			var mStop = minutesStop-(hoursStop*60);
			var sStop = secondsStop-(minutesStop*60);
			var dStop = daysStop;

                        if(sStop%2===0) {
                            $("#secondsstop").css("color","red");
                            $("#minutesstop").css("color","red");
                            $("#hoursstop").css("color","red");
                            $("#daysstop").css("color","red");
                        } else {
                            $("#secondsstop").css("color","#FA5858");
                            $("#minutesstop").css("color","#FA5858");
                            $("#hoursstop").css("color","#FA5858");
                            $("#daysstop").css("color","#FA5858");
                        }
                            
                        $("#daysstop").text(dStop);
                        $("#hoursstop").text(hStop);
                        $("#minutesstop").text(mStop);
                        $("#secondsstop").text(sStop);
                        
                        // To DDBB
                        
                        var mthp = parseInt(currentDate.getMonth()) + 1;
                        mthp = mthp<10?'0'+mthp:mthp;
                        var dp= currentDate.getDate()<10?'0'+currentDate.getDate():currentDate.getDate();
                        var hp= currentDate.getHours()<10?'0'+currentDate.getHours():currentDate.getHours();
                        var mp= currentDate.getMinutes()<10?'0'+currentDate.getMinutes():currentDate.getMinutes();
                        var sp= currentDate.getSeconds()<10?'0'+currentDate.getSeconds():currentDate.getSeconds();
                        
                        var dformat = currentDate.getFullYear() + '-' + mthp + '-' + dp + ' ' + hp + ':' + mp + ':' + sp;

                        $("#datestop").text(dformat);            
                                    
                        $("#dateprocess").val(dformat);
                        $("#dayprocess").val(dStop);
                        $("#hourprocess").val(hStop);
                        $("#minuteprocess").val(mStop);
                        $("#secondprocess").val(sStop);
                        
                        // ADD Total segunds
                        var totalAcumulado;
                        if(finish) {
                        totalAcumulado = parseInt(<?= $this->information['tramite']['0']['total_s'] ?>);
                        } else {
                            totalAcumulado = parseInt(secondsStop) + parseInt(<?= $this->information['tramite']['0']['total_s'] ?>);
                        }
                        $("#totalsegunds").val(secondsStop);
                        $("#totalsegundsacumulado").val(totalAcumulado);
                        
                        
                        //4th Acumulado Stop process
                     
			var minutesAcumulado = Math.floor(totalAcumulado/60);
			var hoursAcumulado = Math.floor(minutesAcumulado/60);
			var daysAcumulado = Math.floor(hoursAcumulado/24);
			var hAcumulado = hoursAcumulado-(daysAcumulado*24);
			var mAcumulado = minutesAcumulado-(hoursAcumulado*60);
			var sAcumulado = totalAcumulado-(minutesAcumulado*60);
			var dAcumulado = daysAcumulado;
                        
                                
                        $("#daysacumulado").text(dAcumulado);
                        $("#hoursacumulado").text(hAcumulado);
                        $("#minutesacumulado").text(mAcumulado);
                        $("#secondsacumulado").text(sAcumulado);
                        
                        
                        // 5th Real Time in process
                        var totalReal = parseInt(secondsAll) - parseInt(totalAcumulado);

			var minutesReal = Math.floor(totalReal/60);
			var hoursReal = Math.floor(minutesReal/60);
			var daysReal = Math.floor(hoursReal/24);
			var hReal = hoursReal-(daysReal*24);
			var mReal = minutesReal-(hoursReal*60);
			var sReal = totalReal-(minutesReal*60);
			var dReal = daysReal;
                        
                                
                        $("#daysreal").text(dReal);
                        $("#hoursreal").text(hReal);
                        $("#minutereal").text(mReal);
                        $("#secondsreal").text(sReal);

                        
                        
		},1000);
	}
	
	function animation(clock, current, total)
	{
		// Calculating the current angle:
		var angle = (360/total)*(current+1);
	
		var element;
                
		if(current==0)
		{
			// Hiding the right half of the background:
			clock.rotateRight.hide();
			
			// Resetting the rotation of the left part:
			rotateElement(clock.rotateLeft,0);
		}
		
		if(angle<=180)
		{
			// The left part is rotated, and the right is currently hidden:
			element = clock.rotateLeft;
		}
		else
		{
			// The first part of the rotation has completed, so we start rotating the right part:
			clock.rotateRight.show();
			clock.rotateLeft.show();
			
			rotateElement(clock.rotateLeft,180);
			
			element = clock.rotateRight;
			angle = angle-180;
		}

		rotateElement(element,angle);
		
		// Setting the text inside of the display element, inserting a leading zero if needed:
		clock.display.html(current<10?'0'+current:current);
	}
	
	function rotateElement(element,angle)
	{
		// Rotating the element, depending on the browser:
		var rotate = 'rotate('+angle+'deg)';
		
		if(element.css('MozTransform')!=undefined)
			element.css('MozTransform',rotate);
			
		else if(element.css('WebkitTransform')!=undefined)
			element.css('WebkitTransform',rotate);
	
		// A version for internet explorer using filters, works but is a bit buggy (no surprise here):
		else if(element.css("filter")!=undefined)
		{
			var cos = Math.cos(Math.PI * 2 / 360 * angle);
			var sin = Math.sin(Math.PI * 2 / 360 * angle);
			
			element.css("filter","progid:DXImageTransform.Microsoft.Matrix(M11="+cos+",M12=-"+sin+",M21="+sin+",M22="+cos+",SizingMethod='auto expand',FilterType='nearest neighbor')");
	
			element.css("left",-Math.floor((element.width()-200)/2));
			element.css("top",-Math.floor((element.height()-200)/2));
		}
	
	}
	
})(jQuery)
//-->
</script>

<script type="text/javascript" style="display:none">
<!--
$(document).ready(function(e){
	/* This code is executed after the DOM has been completely loaded */

	$('#fancyClock').tzineClock();

        $(".btn-pref .btn").click(function () {
            $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
            // $(".tab").addClass("active"); // instead of this do the below 
            $(this).removeClass("btn-default").addClass("btn-primary");   
        });

        $('#stopWatch').on('show.bs.modal',function(e){
            //var id = $(e.relatedTarget).data().id;
        })

        $('#playWatch').on('show.bs.modal',function(e){
            //var id = $(e.relatedTarget).data().id;
        })
        
        $('#comments').on('show.bs.modal',function(e){
            //var id = $(e.relatedTarget).data().id;
        })

        $('#supplyDelete').on('show.bs.modal',function(e){
            //var id = $(e.relatedTarget).data().id;
        })

        $('#supplyRemove').on('show.bs.modal',function(e){
            //var id = $(e.relatedTarget).data().id;
        })

        $('#supplyReopen').on('show.bs.modal',function(e){
            //var id = $(e.relatedTarget).data().id;
        })


        <?php if($this->information['tramite']['0']['visible'] == 2) : ?>
            $('.supply-submit').addClass('disabled');
            $('.supply-finish').addClass('disabled');
            $('.supply-remove').addClass('disabled');
            $('.supply-delete').addClass('disabled');
            $('.comments').addClass('disabled');                
        <?php endIf; ?>        



});

function watchStopping() {
    $('#stopWatch').modal('hide');
    var url = '<?= $this->url('watch-stopping'); ?>';
    var id = '<?= $this->information['tramite']['0']['id']; ?>';
    var parada = '<?= $this->information['tramite']['0']['paradaId']; ?>';
    var motivo = $('#motivo').val();
    
    var data = {id: id, parada: parada, motivo: motivo};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
            location.href = "<?= $this->url('supply'); ?>"  + "/" + id;
//             $("#watch-stopping").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });
    
}

function restartWatch() {

    $('#playWatch').modal('hide');
    var url = '<?= $this->url('restart-watch'); ?>';
    var id = '<?= $this->information['tramite']['0']['id']; ?>';
    var parada = '<?= $this->information['tramite']['0']['paradaId']; ?>';
    var fin = $('#dateprocess').val();
    var d = $('#dayprocess').val();
    var h = $('#hourprocess').val();
    var m = $('#minuteprocess').val();
    var s = $('#secondprocess').val();
    var totals = $('#totalsegunds').val();
    var tsacumulado = $('#totalsegundsacumulado').val();
    var data = {id: id, parada: parada, fin: fin, d: d, h: h, m: m, s: s, totals: totals, tsacumulado: tsacumulado};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
                location.href = "<?= $this->url('supply'); ?>"  + "/" + id;
//             $("#watch-stopping").html(html);
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });


}


function supplyFinish() {

    $('#supplyFinish').modal('hide');
    var url = '<?= $this->url('supply-finish'); ?>';
    var id = '<?= $this->information['tramite']['0']['id']; ?>';
    var finishComment = $('#finish-comment').val();
    var comentarista = $('#comentaristaf').val();
    var data = {id: id, finishComment: finishComment, comentarista:comentarista};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
                location.href = "<?= $this->url('supply'); ?>"  + "/" + id + "/2";
                
//             $("#ajax-comments").html(html);
//             $('.supply-submit').addClass('disabled');
//             $('.supply-finish').addClass('disabled');
//             $('.supply-remove').addClass('disabled');
//             $('.supply-delete').addClass('disabled');
//             $('.comments').addClass('disabled');
//             $('#favorites').addClass('disabled');
             
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });

}

function supplyRemove() {

    $('#supplyRemove').modal('hide');
    var url = '<?= $this->url('supply-remove'); ?>';
    var id = '<?= $this->information['tramite']['0']['id']; ?>';
    var removeComment = $('#remove-comment').val();
    var comentarista = $('#comentaristaa').val();
    var data = {id: id, removeComment: removeComment, comentarista:comentarista };
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
                  location.href = "<?= $this->url('supply'); ?>"  + "/" + id + "/2";  
//             $("#ajax-comments").html(html);
//             $('.supply-submit').addClass('disabled');
//             $('.supply-finish').addClass('disabled');
//             $('.supply-remove').addClass('disabled');
//             $('.supply-delete').addClass('disabled');
//             $('.comments').addClass('disabled');
//             $('#favorites').addClass('disabled');
             
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });

}

function supplyDelete() {

    $('#supplyDelete').modal('hide');
    var url = '<?= $this->url('supply-delete'); ?>';
    var id = '<?= $this->information['tramite']['0']['id']; ?>';
    var deleteComment = $('#delete-comment').val();
    var comentarista = $('#comentaristad').val();
    var data = {id: id, deleteComment: deleteComment, comentarista:comentarista};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
             $("#ajax-comments").html(html);
             $('.supply-submit').addClass('disabled');
             $('.supply-finish').addClass('disabled');
             $('.supply-remove').addClass('disabled');
             $('.supply-delete').addClass('disabled');
             $('.comments').addClass('disabled');
             $('#favorites').addClass('disabled');
             
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });

}


function addComment() {

    $('#comments').modal('hide');
    var url = '<?= $this->url('add-comment'); ?>';
    var id = '<?= $this->information['tramite']['0']['id']; ?>';
    var addComment = $('#add-comment').val();
    var comentarista = $('#comentarista').val();
    
    var data = {id: id, addComment: addComment, comentarista: comentarista};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//                document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/' ;
            location.href = "<?= $this->url('supply'); ?>"  + "/" + id;
//        $("#ajax-comments").html(html);
             
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });

}

function supplyReopen () {

    $('#supplyReopen').modal('hide');
    var url = '<?= $this->url('supply-reopen'); ?>';
    var id = '<?= $this->information['tramite']['0']['id']; ?>';
    var reopenComment = $('#reopen-comment').val();
    var comentarista = $('#comentaristar').val();
    var data = {id: id, reopenComment: reopenComment, comentarista:comentarista};
    
    $.ajax({
        type: "POST",
        url: url,
        data: data,
        cache: false,
        success: function (html) {
//         document.location.href = baseUrl + '/hr/salaryadvance-mng/download-csv/';
           location.href = "<?= $this->url('supply'); ?>"  + "/" + id;
//         $("#ajax-comments").html(html);
             
        },
        error: function (xhr, status) {
            html = "<div class='alert alert-danger'>Error!</div>"
            $("#result").html(html);
        }
    });


}





//-->
</script>











<!--<script>
$(document).ready(function (e){

    $(".btn-pref .btn").click(function () {
        $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
        // $(".tab").addClass("active"); // instead of this do the below 
        $(this).removeClass("btn-default").addClass("btn-primary");   
    });
    
    });
</script>-->
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('update-supply'));
    $form->setAttribute('id', 'supply');
    $form->setAttribute('role', 'form');
    //$form->setAttribute('data-toggle', 'validator');
    $form->setAttribute('accept-charset', 'utf-8');
    $form->setAttribute('novalidate', 'novalidate');
    $form->prepare();
?>



 <?= $this->form()->openTag($form); ?>
<fieldset class="col-md-12">
    <legend>Seguimiento de Provisiones</legend>
    <div class="panel panel-default">
        <div class="panel-body">


<div style="padding: 4px;" class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab" style="width:100%;">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
            <div class="hidden-xs">&nbsp;&nbsp;&nbsp;Trámite&nbsp;&nbsp;&nbsp;</div>
            <div class="hidden-xs">&nbsp;</div>
        </button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab" style="width:100%;">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
            <div class="hidden-xs">&nbsp;&nbsp;&nbsp;&nbsp;SLA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
            <div class="hidden-xs">&nbsp;</div>
        </button>
    </div>
</div>
<div class="tab-content" style="margin: 2px; padding: 2px;">
    <div class="tab-pane fade in active" id="tab1">
        <?php if(isset($this->information['tramite']['0'])) : ?>
                    <div class="col-lg-4">    

                            <div class="form-group">
                                <label for="entidad">Entidad</label>
                                <?php 
                                    $form->get('cliente')->setValue($this->information['tramite']['0']['clienteId']);
                                    $form->get('cliente')->setAttribute('disabled','true');
                                ?>
                                <?= $this->formSelect($form->get('cliente')); ?>                                
                            </div>

                            <div class="form-group">
                                <label for="nif">NIF</label>
                                <input type="text" class="form-control" id="nif" name="nif" aria-describedby="nifHelp" readonly="true" value="<?= $this->information['tramite']['0']['nif']; ?>">
                            </div>

                            <div class="form-group">
                                <label for="inicio">Fecha de Solicitud</label>
                                <?php
                                    $form->get('inicio')->setValue($information['tramite']['0']['inicio']);
                                ?>
                                <?= $this->formInput($form->get('inicio')); ?>
                            </div>
                        
                            <div class="form-group">
                                <label for="solicitante">Solicitante</label>
                                <?php
                                    $form->get('solicitante')->setValue($information['tramite']['0']['solicitante']);
                                    $form->get('solicitante')->setAttribute('readonly','true');
                                ?>
                                <?= $this->formInput($form->get('solicitante')); ?>
                            </div>

                            <div class="form-group">
                                <label for="asunto">Asunto</label>
                                <?php
                                    $form->get('asunto')->setValue($information['tramite']['0']['asunto']);
                                    $form->get('asunto')->setAttribute('readonly','true');
                                ?>
                                <?= $this->formInput($form->get('asunto')); ?>
                            </div>

                            <div class="form-group">
                                <label for="sede">Sede</label>
                                <?php
                                    $form->get('sede')->setValue($this->information['tramite']['0']['sedeId']);
                                    //$form->get('sede')->setAttribute('disabled','true');
                                ?>
                                <?= $this->formSelect($form->get('sede')); ?>                                
                            </div>
                        
                            <div class="form-group">
                                <label for="linea">Adm/Tel/Ext</label>
                                <?php
                                    $form->get('linea')->setValue($information['tramite']['0']['linea']);
                                    //$form->get('linea')->setAttribute('readonly','readonly');
                                ?>
                                <?= $this->formInput($form->get('linea')); ?>
                            </div>

                            <div class="form-group">
                                <label for="midas">Midas</label>
                                <?php
                                    $form->get('midas')->setValue($information['tramite']['0']['midas']);
                                    //$form->get('midas')->setAttribute('readonly','true');
                                ?>
                                <?= $this->formInput($form->get('midas')); ?>
                            </div>
                        

                            <div class="form-group">
                                <label for="lote">Lote</label>
                                <?php
                                    $form->get('lote')->setValue($this->information['tramite']['0']['loteId']);
                                    $form->get('lote')->setAttribute('disabled','true');
                                ?>
                                <?= $this->formSelect($form->get('lote')); ?>                                
                            </div>

                    </div>    
                    
                    <div class="col-lg-4">
                        
                            <div class="form-group">
                                <label for="servicio">Servicio</label>
                                <?php
                                    $form->get('servicio')->setValue($this->information['tramite']['0']['servicioId']);
                                    $form->get('servicio')->setAttribute('disabled','true');
                                ?>
                                <?= $this->formSelect($form->get('servicio')); ?>                                
                            </div>
                        
                        <div class="form-group">
                            <label for="peticion">Tipo de Petición</label>
                            <?php
                                $form->get('peticion')->setValue($this->information['tramite']['0']['servicioId']);
                                $form->get('peticion')->setAttribute('disabled','true');
                            ?>
                            <?= $this->formSelect($form->get('peticion')); ?>
                        </div>

                        <div class="form-group">
                            <label for="tramitador">Tramitador</label>
                            <?php
                                $form->get('tramitador')->setValue($this->information['tramite']['0']['tramitadorId']);
                                $form->get('tramitador')->setAttribute('disabled','true');
                            ?>
                            <?= $this->formSelect($form->get('tramitador')); ?>
                        </div>
                    
                        <div class="form-group">
                            <label for="odinvoz">Odin Voz</label>
                            <?php
                                $form->get('odinvoz')->setValue($information['tramite']['0']['odin_voz']);
                            ?>
                            <?= $this->formInput($form->get('odinvoz')); ?>                                
                        </div>
                        
                        <div class="form-group">
                            <label for="bj">BJ</label>
                            <?php
                                $form->get('bj')->setValue($information['tramite']['0']['bj']);
                            ?>
                            <?= $this->formInput($form->get('bj')); ?>
                        </div>
                        
                        <div class="form-group">
                            <label for="odindatos">Odin Datos</label>
                            <?php
                                $form->get('odindatos')->setValue($information['tramite']['0']['odin_datos']);
                            ?>
                            <?= $this->formInput($form->get('odindatos')); ?>
                        </div>

                        <div class="form-group">
                            <label for="sg">SG</label>
                            <?php
                                $form->get('sg')->setValue($information['tramite']['0']['sgc']);
                            ?>
                            <?= $this->formInput($form->get('sg')); ?>

                        </div>
                        
                        <div class="form-group">
                            <label for="atlas">Atlas</label>
                            <?php
                                $form->get('atlas')->setValue($information['tramite']['0']['atlas']);
                            ?>
                            <?= $this->formInput($form->get('atlas')); ?>
                        </div>

                        <div class="form-group">
                            <label for="visord">Visord</label>
                            <?php
                                $form->get('visord')->setValue($information['tramite']['0']['visord']);
                            ?>
                            <?= $this->formInput($form->get('visord')); ?>
                        </div>

                    </div>    

                    <div class="col-lg-4">
                        
                        <div class="form-group">
                            <label for="estado">Estado</label>
                            <?php $form->get('estado')->setValue($this->information['tramite']['0']['estadoId']) ?>
                            <?= $this->formSelect($form->get('estado')); ?>                        
                        </div>
                        
                        <div class="form-group">
                            <label for="descripcion">Descripción</label>
                             <?php 
                                $form->get('descripcion')->setValue($this->information['tramite']['0']['descripcion']);
                                #$form->get('observacion')->setAttribute('rows', 1);
                                $form->get('descripcion')->setAttribute('disabled','true');
                            ?>
                            <?= $this->formTextarea($form->get('descripcion')); ?>
                        </div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div class="form-group">&nbsp;</div>
                        <div style="float:right;">
                            <button class="btn btn-primary supply-submit" title="Guardar cambios" type="submit"><span class="glyphicon glyphicon-edit"></span></button>
                            <button class="btn btn-primary supply-finish" title="Finalizar" type="button" data-toggle="modal" data-target="#supplyFinish"><span class="glyphicon glyphicon-ok"></span></button>
                            <button class="btn btn-primary supply-remove" title="Anular" type="button" data-toggle="modal" data-target="#supplyRemove"><span class="glyphicon glyphicon-remove"></span></button>
                            <button class="btn btn-primary supply-delete" title="Eliminar el trámite" type="button" data-toggle="modal" data-target="#supplyDelete"><span class="glyphicon glyphicon-trash"></span></button>
                            <button class="btn btn-primary comments" title="Añadir comentarios" type="button" data-toggle="modal" data-target="#comments"><span class="glyphicon glyphicon-comment"></span></button>
                            <?php if($this->information['tramite']['0']['visible'] == 2) : ?>
                            <button class="btn btn-primary supply-reopen" title="Re-abrir" type="button" data-toggle="modal" data-target="#supplyReopen"><span class="glyphicon glyphicon-folder-open"></span></button>
                            <a class="btn btn-primary btn-primary retornar-bandeja" href="<?= $this->url('close-supply-tracing'); ?>" role="button" title="Retornar a la bandeja de trámites cerrados">
                                <i class="glyphicon glyphicon-arrow-left"></i>
                            </a>
                            <?php else : ?>
                            <a class="btn btn-primary btn-primary retornar-bandeja" href="<?= $this->url('open-supply-tracing'); ?>" role="button" title="Retornar a la bandeja de trámites abiertos">
                                <i class="glyphicon glyphicon-arrow-left"></i>
                            </a>
                            <?php endif; ?>
                        </div>
                    </div>
                    <input type="hidden" id="supplyId" name="supplyId" value="<?= $this->information['tramite']['0']['id'] ?>">
        
                    <div class="clearfix"></div>
        
                    <?php if(count($this->information['comentarios'])>0) : ?>     
                        <?php foreach($this->information['comentarios'] as $item ) : ?>
                        <div style="height: 20px;">
                        </div>
                        <fieldset class="col-md-12">
                            <legend><span class="glyphicon glyphicon-comment"></span><span><?= ' ' . $item['tramitador'];?></span><span style='float: right;'>&nbsp;<?= $item['created'];?><span></legend>
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <?= $item['comentario']; ?>
                                </div>
                            </div>
                        </fieldset>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <div id="ajax-comments"></div>

        <?php endif; ?>            
    
    </div>
    <div class="tab-pane fade in" id="tab2">
        <?php if(isset($this->information['tramite']['0'])) : ?>
        <div id='watch-stopping'>
        <div id="fancyClock"></div>
        <div style="padding: 4px; margin-left: 4px; float: left;">
            <!--<button type="button" class="btn btn-primary btn-lg" title="Pause"><span class="glyphicon glyphicon-pause"></span></button>-->
        <?php if(empty($this->information['tramite']['0']['fin'])) : ?>    
            <?php if(isset($this->information['tramite']['0']['inicioParadaSplit'])) : ?>
            <button type="button" class="btn btn-primary btn-lg" title="Reanudar la tramitación" data-toggle="modal" data-target="#playWatch" style="width:200%;">
                <span class="glyphicon glyphicon-play"></span>
            </button>
            <?php else : ?>
            <button type="button" class="btn btn-primary btn-lg" title="Parar la tramitación" data-toggle="modal" data-id="<?= $this->information['tramite']['0']['id']; ?>" data-paradaid="<?= $this->information['tramite']['0']['paradaId']; ?>" data-target="#stopWatch" style=" width:200%;">
                <span class="glyphicon glyphicon-stop"></span>
            </button>
            <?php endif ;?>
        <?php endif ;?>    
        </div>
        <div class="clearfix"></div>
        <div style="border: 1px solid #cdcdcd;">
            <table id="grid-circuitos" class="table table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th style="width:4%;">#</th>
                        <th style="width:14%;">Descripción</th>
                        <th style="width:16%;">Inicio</th>
                        <th style="width:16%;">Fin</th>
                        <th style="width:5%;">Días</th>
                        <th style="width:5%;">H</th>
                        <th style="width:5%;">m</th>
                        <th style="width:5%;">s</th>
                        <th style="width:30%;">Motivo</th>
                    </tr>
                </thead>
                <tbody style="font-size: 11px;">
                    <tr>
                        <td>1</td>
                        <td>Trámite de Provisión</td>
                        <td><?= $this->information['tramite']['0']['inicio']; ?></td>
                        <td><?= $this->information['tramite']['0']['fin']; ?></td>
                        <td><span id='days'></span></td>
                        <td><span id='hours'></span></td>
                        <td><span id='minutes'></span></td>
                        <td><span id='seconds'></span></td>
                        <td></td>
                    </tr>
                    <?php $contador = 2;
                    foreach($this->information['parada'] as $item) : ?>
                    <?php if(!empty($item['inicio']) && empty($item['fin'])) : ?>
                    <tr style="font-weight: bold; color: red;">
                            <td><?= $contador; ?></td>
                            <td>Parada <?= $contador-1; ?></td>
                            <td><?= $item['inicio']; ?></td>
                            <td><span id='datestop'></span></td>
                            <td><span id='daysstop'></span></td>
                            <td><span id='hoursstop'></span></td>
                            <td><span id='minutesstop'></span></td>
                            <td><span id='secondsstop'></span></td>
                            <td><?= $item['motivo']; ?></td>
                        </tr>
                    <?php elseif(!empty($item['inicio']) && !empty($item['fin'])) : ?>
                        <tr>
                            <td><?= $contador; ?></td>
                            <td>Parada <?= $contador-1; ?></td>
                            <td><?= $item['inicio']; ?></td>
                            <td><?= $item['fin']; ?></td>
                            <td><?= $item['days']; ?></td>
                            <td><?= $item['hours']; ?></td>
                            <td><?= $item['minutes']; ?></td>
                            <td><?= $item['seconds']; ?></td>
                            <td><?= $item['motivo']; ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php $contador++;
                    endforeach;
                    ?>
                    <?php if((int)$this->information['tramite']['0']['total_s']>0 || isset($this->information['tramite']['0']['inicioParadaSplit'])) : ?>
                    <tr style="background-color: #3276b1;">
                        <td colspan="4" style="text-align: center; color: white; font-weight: bold;"><span>TOTAL TIEMPO PARADO</span></td>
                        <td style="color: white; font-weight: bold;"><span id='daysacumulado'></span></td>
                        <td style="color: white; font-weight: bold;"><span id='hoursacumulado'></span></td>
                        <td style="color: white; font-weight: bold;"><span id='minutesacumulado'></span></td>
                        <td style="color: white; font-weight: bold;"><span id='secondsacumulado'></span></td>
                        <td></td>
                    </tr>
                    <?php endif; ?>
                    <tr style="background-color: green;">
                        <td colspan="4" style="text-align: center; color: white; font-weight: bold;"><span>TIEMPO REAL</span></td>
                        <td style="color: white; font-weight: bold;"><span id='daysreal'></span></td>
                        <td style="color: white; font-weight: bold;"><span id='hoursreal'></span></td>
                        <td style="color: white; font-weight: bold;"><span id='minutereal'></span></td>
                        <td style="color: white; font-weight: bold;"><span id='secondsreal'></span></td>
                        <td></td>
                    </tr>
                </tbody>     
            </table>
        </div>
        </div>
         <?php endif; ?>
    </div>
    <input type="hidden" id="dayprocess" name="dayprocess" value="">
    <input type="hidden" id="hourprocess" name="hourprocess" value="">
    <input type="hidden" id="minuteprocess" name="minuteprocess" value="">
    <input type="hidden" id="secondprocess" name="secondprocess" value="">
    <input type="hidden" id="dateprocess" name="dateprocess" value="">
    <input type="hidden" id="totalsegunds" name="totalsegunds" value="">
    <input type="hidden" id="totalsegundsacumulado" name="totalsegundsacumulado" value="">
    
    <div class="clearfix"></div>
</div>
            
</div>
</div>
</fieldset>
<?= $this->form()->closeTag($form); ?>

<!-- Modal Watch stopping  -->
<div class="modal fade" id="stopWatch" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Watch stopping</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de detener el reloj?</p>
                <textarea id="motivo" name="motivo" rows="3" style="width: 100%;" placeholder="Ingrese el motivo ..."></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="watchStopping();" >Detener</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Watch play  -->
<div class="modal fade" id="playWatch" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Restart watch</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de reanudar el reloj?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="restartWatch();" >Reanudar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Comments  -->
<div class="modal fade" id="comments" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Comentario</h4>
            </div>
            <div class="modal-body">
<!--            <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de reanudar el reloj?</p>-->
                <div class="form-group">
                    <label for="tramitador">Tramitador</label>
                    <?= $this->formSelect($form->get('comentarista')); ?>
                </div>
                <div class="form-group">
                    <textarea id="add-comment" name="add-comment" rows="3" style="width: 100%;" placeholder="Ingrese el comentario ..."></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="addComment();" >Comentar</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal Supply Delete   -->
<div class="modal fade" id="supplyDelete" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de eliminar el trámite?</p>
                <div class="form-group">
                    <label for="tramitadorf">Tramitador</label>
                    <?= $this->formSelect($form->get('comentaristad')); ?>
                </div>
                <div class="form-group">
                    <textarea id="delete-comment" name="delete-comment" rows="3" style="width: 100%;" placeholder="Ingrese el comentario ..."></textarea>
                </div>    
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="supplyDelete();" >Eliminar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Supply Remove   -->
<div class="modal fade" id="supplyRemove" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Anular</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de anular el trámite?</p>
                <div class="form-group">
                    <label for="tramitadorf">Tramitador</label>
                    <?= $this->formSelect($form->get('comentaristaa')); ?>
                </div>
                <div class="form-group">
                    <textarea id="remove-comment" name="remove-comment" rows="3" style="width: 100%;" placeholder="Ingrese el comentario ..."></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="supplyRemove();" >Anular</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Supply Finish   -->
<div class="modal fade" id="supplyFinish" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Finalizar</h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold; margin-top: 20px;">¿Esta seguro de finalizar el trámite?.</p>
                <div class="form-group">
                    <label for="tramitadorf">Tramitador</label>
                    <?= $this->formSelect($form->get('comentaristaf')); ?>
                </div>
                <div class="form-group">
                    <textarea id="finish-comment" name="finish-comment" rows="3" style="width: 100%;" placeholder="Ingrese el comentario ..."></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="supplyFinish();" >Finalizar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Supply Reopen   -->
<div class="modal fade" id="supplyReopen" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"> Reabrir </h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold; margin-top: 20px;">¿Está seguro de reabrir el trámite?.</p>
                <div class="form-group">
                    <label for="tramitadorr">Tramitador</label>
                    <?= $this->formSelect($form->get('comentaristar')); ?>
                </div>
                <div class="form-group">
                    <textarea id="reopen-comment" name="finish-comment" rows="3" style="width: 100%;" placeholder="Ingrese el comentario ..."></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="float: left;">Cancelar</button>
                <button type="button" class="btn btn-danger" style="float: left;" onclick="supplyReopen();" > Reabrir </button>
            </div>
        </div>
    </div>
</div>
